### ISSUE TITLE
LetsEncrypt acme.sh: Allow pass in parameters

### ISSUE THREAD

**Issue by pquerner** [Froxlor/Froxlor#1009]
**Is your feature request related to a problem? Please describe.**
My DNS can use the API feature of acme.sh so I can verify the domain via DNS TXT record.
But in order for that to work, I need to pass in parameters into acme.sh call, like so:
acme.sh [... other params] `--dns dns_inwx`

**Describe the solution you'd like**
Allow for a field (maybe 2, 1 for is_active 1 for the actual params?) to have the parameters applied to the acme.sh call.

**Describe alternatives you've considered**
I tried to mis-use the field "Path to acme.sh", but its value is verified with a `file_exists`, so it wouldnt work of course.

**Comment by d00p** [comment]
possible to do, yes

**Comment by d00p** [comment]
Well what you could try is writing a wrapper for `/root/.acme.sh/acme.sh` and add your parameter there and specify the wrapper-script as "path to acme.sh"

**Comment by pquerner** [comment]
True, I could do that! Thanks.

**Comment by pquerner** [comment]
Do you happen to know how I could wrap the script?

**Comment by d00p** [comment]
> Do you happen to know how I could wrap the script?

something like this: 

```bash
#!/bin/bash

CUSTOM_PARAMS="--something"

/root/.acme.sh/acme.sh "$@ $CUSTOM_PARAMS"
```
