### ISSUE TITLE
Feature Request: Cronjob for Cleaning PHP session files

### ISSUE THREAD

**Issue by Af0x** [Froxlor/Froxlor#1011]
Hello,

I want to request the implementation of a cronjob for cleaning PHP session files.

Regards,

Af0x

**Comment by d00p** [comment]
? I literally told you on the forum that there is a file for that: https://github.com/Froxlor/Froxlor/blob/master/install/scripts/php-sessionclean.php

**Comment by d00p** [comment]
fixed in 84f5de42a90108684734512fd7bf9f85a90046ed
