### ISSUE TITLE
Unattended installation

### ISSUE THREAD

**Issue by Kapsonfire-DE** [Froxlor/Froxlor#1015]
Is there a way to complete installation from cli

I wan't to automatically install/configure my servers with saltstack.
Is there a way to create all config files, the upgrade process and installation from cli

php /var/www/froxlor/scripts/installation.php --configFile=/etc/froxlor/config.json

and in the config json are the paramaters needed for installation like mysql root password and so on?

**Comment by d00p** [comment]
The config-services.php script can do most of that. Even read in previously/ externally exported settings from another install and apply them prior to configure the services.

For the parts beforehand (basic installation) you would need to download, extract, create a database and corresponding users, fill the database with install/froxlor.sql and some manual SQL Inserts and updates to have the admin user and lastly create the lib/userdata.inc.php file with the MySQL credentials.... that's more or less what we do with ansible

**Comment by d00p** [comment]
Maybe you want to try https://github.com/Froxlor/Froxlor-Installer

**Comment by Kapsonfire-DE** [comment]
Looks good, but need some changes, like I want to use debian apt to maintain version and so on. But a good start to get inspiration how to do it.

**Comment by d00p** [comment]
> Looks good, but need some changes, like I want to use debian apt to maintain version and so on.

Well you can of course also add our repository and `apt install froxlor` instead of downloading and extracting the archive :)

**Comment by Kapsonfire-DE** [comment]
In the userdata.inc.php is the $sql_root really needed or just for installation and i can drop it after installation?

**Comment by Kapsonfire-DE** [comment]
ah yes ofc... should have known that

**Comment by d00p** [comment]
only `-y` is not sufficient, we will add `DEBIAN_FRONTEND=noninteractive apt-get -yq install` as default apt-get install command so no user-interaction is needed

**Comment by Kapsonfire-DE** [comment]
Yes, or use DEBCONF UTIL 

`echo "postfix postfix/mailname string example.com" | debconf-set-selections`
https://serverfault.com/questions/143968/automate-the-installation-of-postfix-on-ubuntu

**Comment by Kapsonfire-DE** [comment]
Hi, thanks for support and I got it in a working state. Finally...
After a update, the admin needs to login and execute the "update scripts"

Is there already a mechanism to do this from CLI?

**Comment by d00p** [comment]
kindof yes, you can create a custom script, the key element is the defining of *_CRON_UPDATE* prior to including the updatesql.php file

```php
<?php

[...includes etc...]

define('_CRON_UPDATE', 1);
include_once \Froxlor\Froxlor::getInstallDir() . '/install/updatesql.php';
```

**Comment by Kapsonfire-DE** [comment]
I guess requiring lib/init.php is enough as include before?
Shall I make a PR to Froxlor when its done, so other people can use it as well?

**Comment by d00p** [comment]
no you don't need lib/init.php, most likely just `include_once \Froxlor\Froxlor::getInstallDir() . '/lib/tables.inc.php';`

Of course you can always create a PR when it fits i will merge it gladly :)

**Comment by Kapsonfire-DE** [comment]
But i cant use Froxlor::getInstallDir() for this when its not included before.

**Comment by d00p** [comment]
lib/init.php is for web/ui - as it will send headers etc. if you need to use froxlor-classes, well, it's composer-based, you just need ` /vendor/autoload.php`

**Comment by Kapsonfire-DE** [comment]
Yep basically thats all needed:
```php
<?php
require __DIR__.'/../vendor/autoload.php';
require \Froxlor\Froxlor::getInstallDir() . '/lib/tables.inc.php';
define('_CRON_UPDATE', 1);
include_once \Froxlor\Froxlor::getInstallDir() . '/install/updatesql.php';
```

Ofc. the updateScript returns html source as response - I could buffer and strip out the html tags

**Comment by d00p** [comment]
Yes, something like that:

```php
<?php
require __DIR__.'/../vendor/autoload.php';
require \Froxlor\Froxlor::getInstallDir() . '/lib/tables.inc.php';
function cleanUpdateOutput($buffer) {
	return strip_tags(preg_replace("/<br\W*?\/>/", "\n", $buffer));
}
define('_CRON_UPDATE', 1);
ob_start('cleanUpdateOutput');
include_once \Froxlor\Froxlor::getInstallDir() . '/install/updatesql.php';
ob_end_flush();
```
