### ISSUE TITLE
Fatal error in autoload.php

### ISSUE THREAD

**Issue by rundekugel** [Froxlor/Froxlor#1016]
executing:
```
php /var/www/froxlor/froxlor/install/scripts/config-services.php --froxlor-dir=/var/www/froxlor/froxlor/ --create
PHP Warning:  require(/var/www/froxlor/froxlor/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/froxlor/froxlor/install/scripts/config-services.php on line 24
PHP Fatal error:  require(): Failed opening required '/var/www/froxlor/froxlor/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/froxlor/froxlor/install/scripts/config-services.php on line 24

```
And on http://ip/froxlor: "Whoops! It seems you are missing some required files."

**System information**
* Froxlor version: $version/11533c2d752858
* Web server: nginx
* DNS server: -
* POP/IMAP server: -
* SMTP server: -
* FTP server:-
* OS/Version: Debian11

**To Reproduce**
1. php froxlor-install.phar --skip-download --git
2. execute config script
3. See error

**Logfiles**
I'll reproduce it for you and add all you want

**Additional context**
You may also log into the server, as I'll do it from scratch

**Comment by d00p** [comment]
Git requires "composer install" as stated in the docs (https://docs.froxlor.org/general/installation/source.html).

**Comment by d00p** [comment]
as you are using the Froxlor-Installer,this might be fixed in https://github.com/Froxlor/Froxlor-Installer/commit/cae08138c7736c479d1e8a5c53ffb0e8738bd4a6

**Comment by rundekugel** [comment]
> Git requires "composer install" as stated in the docs (https://docs.froxlor.org/general/installation/source.html).

`apt install composer`
now it runs
thanks for help
