### ISSUE TITLE
no eventlistener on 'historyback' links on several error messages - js files not added

### ISSUE THREAD

**Issue by peterdd** [Froxlor/Froxlor#1017]
**Describe the bug**
When trying as customer1 to add a database on https://demo.froxlor.org and there is an error, the error message contains a "Go back" link, but as there this is no direct link and the main.js is not added to the html head section that would add a javascript click event listener there happens nothing when clicking on it, see screenshot.

**System information**
https://demo.froxlor.org
(on 2022-04-06)

**To Reproduce**
login as customer1/customer1 on https://demo.froxlor.org
Go to database section and try create a new database, fill the form and submit.

**Expected behavior**
Well, the database should be created ;-)
And if there is an error the "Go back" link should work.

![froxlor_historyback_error](https://user-images.githubusercontent.com/1839154/162074100-60949803-ff36-459a-8397-b45e2650759b.png)

**Comment by d00p** [comment]
Adding databases in the demo is restricted on purpose and is also slightly patched for various reasons.

**Comment by d00p** [comment]
Even though, the patch for preventing adding databases to the demo server for real was faulty, so, thanks for the hint :)
