### ISSUE TITLE
adding css text_align_left.png is useless

### ISSUE THREAD

**Issue by peterdd** [Froxlor/Froxlor#1018]
**Describe the bug**
CSS rule 

```css
input {
  background: #fff url(../img/icons/text_align_left.png) no-repeat 5px 4px;
...
}
```

is useless.

If users need to learn that this icon in Froxlor means 'That is a form input' then the form UI design idea is bad. As I never used Froxlor before I really wondered why there is such 'left align the text'-icon there. (as in word processing apps)

Instead please use HTML5 placeholder, required, pattern attributes to improve form usability where applicable.

**System information**
https://demo.froxlor.org
(on 2022-04-06)

**To Reproduce**
login in on froxlor and browse to a form with input fields.

**Expected behavior**
Just normal input fields, maybe with some visible helpers like placeholder, required, and client side form validation for quick fixing before a maybe frustrating invalid form is sended that is rejected later by server side validation.

**Comment by d00p** [comment]
It's just the design. If you don't like it, either create your own or wait for 0.11
