### ISSUE TITLE
add click event handler for adding demo login data

### ISSUE THREAD

**Issue by peterdd** [Froxlor/Froxlor#1019]
**Is your feature request related to a problem? Please describe.**
The https://demo.froxlor.org requires to copy-paste or type the 3 different account logins into the form. This is a bit annoying as there is all required information yet on the login page.

**Describe the solution you'd like**
It could be improved by just adding very simple click handlers to admin, reseller1, customer1 that inserts loginname and password into the actual login form.

Similiar approach as inspiration example is on https://dev.modified-shop.org/ 

```js
document.getElementById('loginname').value = 'admin';
document.getElementById('password').value = 'admin';
```

Similiar approach as inspiration example is on https://dev.modified-shop.org/

**Comment by d00p** [comment]
Not a froxlor bug, this is demo specific.

Also, i don't see a "similar approach" on the given URL

**Comment by peterdd** [comment]
![demomodshop](https://user-images.githubusercontent.com/1839154/162192553-1ee1f949-a7ef-4eee-9740-3398ff12710b.png)

Sure, it demo specific, but where should it reported then? :-)

Similiar is the froxlor generated password suggestions could also feature such a click handler that puts their value it into the real form.
![froxlor_createcustomer_password_suggestion](https://user-images.githubusercontent.com/1839154/162192872-76b6aba2-6987-440a-97fd-139d016e25b2.png)

**Comment by peterdd** [comment]
And I chose 'Feature', not 'Bug'. ;-)

**Comment by d00p** [comment]
> Sure, it demo specific, but where should it reported then? :-)

Forum, Discord, E-mail...this is the issue tracker for the applications code. It's very confusing for others when feature-requests/enhancements/changes to things outside the application itself are posted here

**Comment by envoyr** [comment]
Issue is closed, due to the current relevance, as this only affects the demo.
