### ISSUE TITLE
helper scripts broken

### ISSUE THREAD

**Issue by Kapsonfire-DE** [Froxlor/Froxlor#1020]
The debian repo isnt updated:
https://github.com/Froxlor/Froxlor/commit/11533c2d7528586af4468ecade74f74a6368d36e

The commit is missing and makes the config services php broken

**Comment by d00p** [comment]
It's not related to the debian repo, yes we know. There will be a bugfix release next week.

**Comment by d00p** [comment]
Closed with release of tag https://github.com/Froxlor/Froxlor/commit/4546c00adb12dec79abf15f830b761834beead55
