### ISSUE TITLE
php-sessionclean.php called as shellscript

### ISSUE THREAD

**Issue by hknet** [Froxlor/Froxlor#1023]
**Describe the bug**
php /var/www/froxlor/scripts/froxlor_master_cronjob.php --force
creates (also) /etc/cron.d/froxlor and puts in these lines:
# Look for and purge old sessions every 30 minutes
09,39 * * * * root /var/www/froxlor/scripts/php-sessionclean.php --froxlor-dir='/var/www/froxlor/' 1> /dev/null

ending up this script being called as shell script by the cron scheduler.

correct cron-entry should be:
# Look for and purge old sessions every 30 minutes
09,39 * * * * root /usr/bin/nice -n 5 /usr/bin/php -q /var/www/froxlor/scripts/php-sessionclean.php --froxlor-dir='/var/www/froxlor/' 1> /dev/null

**System information**
* Froxlor version: 0.10.34-1
* Web server: apache2
* OS/Version: Ubuntu 20.04

**To Reproduce**
1. call php /var/www/froxlor/scripts/froxlor_master_cronjob.php --force
2. look into /etc/cron.d/froxlor

**Expected behavior**
file /etc/cron.d/froxlor should have a php-call for the sessionclean.php script

**Comment by d00p** [comment]
no it does not need to have it as it has the shebang at the beginning `#!/usr/bin/php` and it should have the executable flag set so it can be run without prefixing php, see:

```bash
d00p $ ./scripts/php-sessionclean.php 

Help / command line parameters:

--froxlor-dir		path to froxlor installation
			Example: --froxlor-dir=/var/www/froxlor/

--max-lifetime		The number of seconds after which data will be seen as 'garbage' and potentially cleaned up. Defaults to '1440'
			Example: --max-lifetime=2000

--help			show help screen (this)

-h			same as --help
```

**Comment by hknet** [comment]
this way one has to rely on the systemphp-cli-setup, while froxlor-cron-settings are not honored, also obviously there are systems that do not have the correct shebang-setup in place...

**Comment by d00p** [comment]
Still fixed already: https://github.com/Froxlor/Froxlor/commit/652a998188241acdb5ba7aa1c8557d07a5396f0d
