### ISSUE TITLE
CSS error when installing Froxlor

### ISSUE THREAD

**Issue by net44** [Froxlor/Froxlor#1034]
For several years, when installing Froxlor, on the page where you enter database data, etc, there is always a horizontal scroll line (css error) at the bottom. 
See the screenshot from Froxlor forum:  https://forum.froxlor.org/uploads/monthly_2022_05/330589634_Screenshotfrom2022-05-2603-30-30.png.f71d1385335ff8b3310768fa4586282b.png (at the bottom)
Please fix it by the way. Thanks

**Comment by d00p** [comment]
Installer has completely been reworked and redesigned (as froxlor itself) for the next major version
