### ISSUE TITLE
IDN domains

### ISSUE THREAD

**Issue by dampelz** [Froxlor/Froxlor#1037]
**Describe the bug**
Hi, i can't create idn domain.

Without punycode **тини-панель.рф** - Error NAMEPREP: Prohibited input U+00000082

With punycode convertion **xn----8sbpjavjdqz3j.xn--p1ai**  Error
You must not specify punycode (IDNA). The domain will automatically be converted

How to create idn domain ?

**System information**
* Froxlor version: 0.10.35.1-1 (DB: 202112310)
* Web server: nginx
* DNS server: Bind
* POP/IMAP server: Courier/Dovecot
* SMTP server: postfix/exim
* FTP server: proftpd
* OS/Version: Ubuntu 20.04

**To Reproduce**
1. Try to create domain тини-панель.рф
2. Or try to create with punycode xn----8sbpjavjdqz3j.xn--p1ai
3. See errors
Error NAMEPREP: Prohibited input U+00000082
or
You must not specify punycode (IDNA). The domain will automatically be converted

**Comment by d00p** [comment]
Works perfectly fine when adding "тини-панель.рф" on our demo. Be sure that you do not have any other special (control) characters in the string

**Comment by dampelz** [comment]
Maybe problem with locales on Ubuntu 20 ?

**Comment by d00p** [comment]
I'm not aware that the idea library does anything with locales

**Comment by d00p** [comment]
According to your error message, the problem is the character U+00000082 which if I'm not mistaken ist most definitely a control character

**Comment by dampelz** [comment]
I reconfigured the locales and the domain was added
`dpkg-reconfigure locales`

Thank you for your help
