### ISSUE TITLE
ubuntu unattended upgrades need distro_codenames

### ISSUE THREAD

**Issue by hknet** [Froxlor/Froxlor#1040]
currently ubuntu packages are delivered usgin stable/oldstable as their distrocodenames.

in order to have unattended-upgrades working properly with distro_codename macros it would be helpful to have proper distronames used like focal, bionic, etc.

thx!

**Comment by d00p** [comment]
![Screenshot_20220702-074207](https://user-images.githubusercontent.com/1757229/176988206-e4edc068-aa70-444d-9a60-93bc01ce2b06.png)
More context/error message please

**Comment by hknet** [comment]
basically now with the new 0.37 release (thanks!) we can see that:
the corresponding apt file from deb.froxlor.org/ubuntu gets this one in the filesystem:
/var/lib/apt/lists/deb.froxlor.org_ubuntu_dists_focal_InRelease
there one can read the content:

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Origin: froxlor.org
Label: Froxlor Repository
Suite: oldstable
Codename: focal
...
---------------------------------

the issue here is now that using the Allowed-Origins in unattended-upgrades like:
"froxlor.org:${distro_codename}";
or "froxlor.org:stable";
does obviously not work. because the Suite is defined as oldstable

therefore on the latest and greates ubuntu one has to use "froxlor.org:oldstable"; as origin and this seems very odd :)

also it would be nice to have it named focal for the current release as this allows for the origin-config to be more consistent.

thx!

**Comment by d00p** [comment]
well "focal" isnt the "latest and greatest" as you say...current stable LTS is 22.04, which is "jammy", hence, oldstable is perfectly correct for focal

> also it would be nice to have it named focal for the current release as this allows for the origin-config to be more consistent.

have what exactly named "focal"? Three is a focal folder, which is symlinked by its current suite (oldstable). If you want to be totally sure you stay on the same release, just use the codename instead of the suite

**Comment by d00p** [comment]
no feedback
