### ISSUE TITLE
Ubuntu install instructions is broken on 22.04

### ISSUE THREAD

**Issue by divinity76** [Froxlor/Froxlor#1041]
i suspect the issue is that the deb.froxlor.org/ubuntu repo has not been updated with Ubuntu 22.04 packages yet (given that 22.04 was released 73 days ago, less than 3 months old), anyhow:
following the instructions on https://docs.froxlor.org/general/installation/aptpackage.html  for Ubuntu apt installations ends with a 404 error followed by an `E: Unable to locate package froxlor` error:
```
$ apt update;apt full-upgrade;
Hit:1 http://no.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://no.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://no.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://no.archive.ubuntu.com/ubuntu jammy-security InRelease
Ign:5 https://deb.froxlor.org/ubuntu jammy InRelease
Err:6 https://deb.froxlor.org/ubuntu jammy Release
  404  Not Found [IP: 185.123.52.110 443]
Reading package lists... Done
E: The repository 'https://deb.froxlor.org/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
$ apt install froxlor
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package froxlor
```

**Comment by d00p** [comment]
Yes, it's because we do not yet include packages for jammy. Will follow for the next release

**Comment by divinity76** [comment]
gotcha, next release ETA?

**Comment by d00p** [comment]
Always 1st Friday of the month

**Comment by divinity76** [comment]
gotcha, unsure if i should close this issue now or wait until friday?

**Comment by d00p** [comment]
I'll close it with the commit later

**Comment by Digioso** [comment]
Hi!

Has this issue really been solved? I just tried instaling it on Ubuntu 22.04 and got the same error message as [divinity76](https://github.com/divinity76).

**Comment by d00p** [comment]
Well it's there: https://deb.froxlor.org/ubuntu/dists/jammy/ - what can I say

**Comment by divinity76** [comment]
@Digioso 
(Disclaimer: I'm now a HestiaCP security team member, but i wasn't when I filed this issue.) Fwiw i run HestiaCP on my 22.04 server, it does most of the same stuff Froxlor does. And i don't have a spare 22.04 server to do a Froxlor test install on

**Comment by Digioso** [comment]
@divinity76  Thanks! I'll have a look.

I just retried it on a completely fresh Ubuntu 22.04.

Same result.

`root@digioso:~# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
root@digioso:~# apt-get -y install apt-transport-https lsb-release ca-certificates curl
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
lsb-release is already the newest version (11.1.0ubuntu4).
lsb-release set to manually installed.
ca-certificates is already the newest version (20211016ubuntu0.22.04.1).
ca-certificates set to manually installed.
curl is already the newest version (7.81.0-1ubuntu1.6).
curl set to manually installed.
The following NEW packages will be installed:
  apt-transport-https
0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 1506 B of archives.
After this operation, 169 kB of additional disk space will be used.
Get:1 http://eu-frankfurt-1-ad-1.clouds.ports.ubuntu.com/ubuntu-ports jammy-updates/universe arm64 apt-transport-https all 2.4.8 [1506 B]
Fetched 1506 B in 0s (42.6 kB/s)
Selecting previously unselected package apt-transport-https.
(Reading database ... 65856 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_2.4.8_all.deb ...
Unpacking apt-transport-https (2.4.8) ...
Setting up apt-transport-https (2.4.8) ...
Scanning processes...
Scanning candidates...
Scanning linux images...

Running kernel seems to be up-to-date.

Restarting services...
 /etc/needrestart/restart.d/dbus.service
 systemctl restart networkd-dispatcher.service unattended-upgrades.service

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
root@digioso:~# curl -sSLo /usr/share/keyrings/deb.froxlor.org-froxlor.gpg https://deb.froxlor.org/froxlor.gpg
root@digioso:~# sh -c 'echo "deb [signed-by=/usr/share/keyrings/deb.froxlor.org-froxlor.gpg] https://deb.froxlor.org/debian $(lsb_release -sc) main" > /etc/apt/sources.list.d/froxlor.list'
root@digioso:~# apt-get update && apt-get upgrade
Hit:1 http://eu-frankfurt-1-ad-1.clouds.ports.ubuntu.com/ubuntu-ports jammy InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports jammy-security InRelease
Hit:3 http://eu-frankfurt-1-ad-1.clouds.ports.ubuntu.com/ubuntu-ports jammy-updates InRelease
Hit:4 http://eu-frankfurt-1-ad-1.clouds.ports.ubuntu.com/ubuntu-ports jammy-backports InRelease
Ign:5 https://deb.froxlor.org/debian jammy InRelease
Err:6 https://deb.froxlor.org/debian jammy Release
  404  Not Found [IP: 185.123.52.110 443]
Reading package lists... Done
E: The repository 'https://deb.froxlor.org/debian jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@digioso:~#`

**Comment by dtugend** [comment]
You must select Ubuntu here, not Debian:
![image](https://user-images.githubusercontent.com/3610128/210359377-2074079d-7bda-422b-bd55-68c9d71b237a.png)

**Comment by envoyr** [comment]
Exact, this can't work since you have selected the Debian repo :)

You have to change your `/etc/apt/sources.list.d/froxlor.list` from
```
sh -c 'echo "deb [signed-by=/usr/share/keyrings/deb.froxlor.org-froxlor.gpg] https://deb.froxlor.org/debian $(lsb_release -sc) main" > /etc/apt/sources.list.d/froxlor.list'
```
to
```
sh -c 'echo "deb [signed-by=/usr/share/keyrings/deb.froxlor.org-froxlor.gpg] https://deb.froxlor.org/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/froxlor.list'
```

notice the `https://deb.froxlor.org/debian` to `https://deb.froxlor.org/ubuntu` change.

**Comment by Digioso** [comment]
Ah, that explains it.
Then I suggest updating your documentaion as well: https://docs.froxlor.org/latest/general/installation/apt-package.html

This is what I followed and it says to use it for Debian AND Ubuntu.

**Comment by d00p** [comment]
okay, the distro select shown in https://github.com/Froxlor/Froxlor/issues/1041#issuecomment-1369724919 seems to be too "hidden", we'll adjust the documentation
