### ISSUE TITLE
Dovecot LDA mail_plugins

### ISSUE THREAD

**Issue by itcbweb** [Froxlor/Froxlor#1042]
in dovecot configuration: /bin/nano /etc/dovecot/conf.d/15-lda.conf

this is wrong:
protocol lda {
    #mail_plugins = $mail_plugins
}`

right is:
protocol lda {
  **mail_plugins = $mail_plugins quota sieve**
}

**Comment by d00p** [comment]
sieve is not enabled by default.
And please be more specific on why the current templates are "wrong" in your opinion.
What does not work? Do you get any error messages?

**Comment by itcbweb** [comment]
Hi,
Sieve in old version of Froxlor is enabled.
Its logical to be enabled by default because installed in

apt-get install dovecot-imapd dovecot-pop3d dovecot-mysql dovecot-managesieved dovecot-sieve

and set config files for sieve.

/bin/nano /etc/dovecot/conf.d/20-managesieve.conf
/bin/nano /etc/dovecot/conf.d/90-sieve.conf

in old version of Debian:



in new version of Debian – not:




Ivan
