### ISSUE TITLE
acme.sh not renewing LE certificates

### ISSUE THREAD

**Issue by makuser** [Froxlor/Froxlor#1043]
**As a rule of thumb: before reporting an issue**
* see if it hasn't been [reported](https://github.com/Froxlor/froxlor/issues) (and possibly already been [fixed](https://github.com/Froxlor/froxlor/issues?utf8=✓&q=is:issue%20is:closed)) first
* try with the git master

**Describe the bug**
expired certificates are not renewed

**System information**
* Froxlor version: 0.10.36/a2342ad1d2450030bb1738476c7a3edd6023a9ac
* Web server: apache2
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: none
* OS/Version: Debian GNU/Linux 11 (bullseye)

**To Reproduce**

**Expected behavior**
LE certificates should be renewed before they expire

**Logfiles**
If applicable, add log-entries to help explain your problem.

**Additional context**
Disabling LE for the domain, waiting for the cronjob to delete the certificate from acme.sh and only afterwards re-enabling LE for the domain will renew the certificate. I do not know if it will automatically renew it next time they expire though. Disabling and re-enabling LE without waiting for a cronjob in between, will not renew it.

Expired certs are properly recognized in the certificate dashboard (/admin_domains.php?page=sslcertificates) and in froxlor database, but for some reason acme.sh does nothing to renew them when invoked via froxlor.

I'm now not sure whether I should try to invoke acme.sh manually, and especially using which parameters, so that I do not worsen the situation.

**Comment by makuser** [comment]
I figured running `acme.sh --list` would probably be fine, so I ran it and it displayed a list of certificates acme.sh is aware of.
To my surprise, it displayed some of the certificates with ZeroSSL.com as issuer, a CA which I've never used and not plan on using anytime soon. Froxlor has always been set to LE (live), never any other option in the ssl settings.
So I took one of the listed domain certs and actually looked at them using `openssl x509 -text -in /root/.acme.sh/domain.tld/domain.tld.cer`.
It was not issued by ZeroSSL, but by LE.
Viewing the config file though, will show this content (I replaced details):
```ini
Le_Keylength='4096'
Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/$123/$456'
Le_Domain='domain.tld'
Le_Alt='www.domain.tld'
Le_Webroot='/var/www/froxlor'
Le_PreHook=''
Le_PostHook=''
Le_RenewHook=''
Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/$123/$456'
Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/$certhash'
Le_CertCreateTime='1647298898'
Le_CertCreateTimeStr='Mon 14 Mar 2022 11:01:38 PM UTC'
Le_ForceNewDomainKey='1'
Le_NextRenewTimeStr='Fri 13 May 2022 11:01:38 PM UTC'
Le_NextRenewTime='1652396498'
Le_API='https://acme.zerossl.com/v2/DV90'
```

Why has the Le_API parameter been set to zerossl? Has there been any change in acme.sh or froxlor that might explain it?

How can we catch it? Froxlor still displays LE as issuer in the cert dashboard.

**Comment by makuser** [comment]
/root/.acme.sh/account.conf
```bash

AUTO_UPGRADE='0'
USER_PATH='/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin'
UPGRADE_HASH='e3cd96bf19caed7282f5eab817d1e324574b9107'
DEFAULT_ACME_SERVER='https://acme-v02.api.letsencrypt.org/directory'
```

`DEFAULT_ACME_SERVER` looks fine to me,

https://github.com/acmesh-official/acme.sh/blob/e3cd96bf19caed7282f5eab817d1e324574b9107/acme.sh#L38 is probably very bad if froxlor updates acme.sh to 3.0.0+ before the `DEFAULT_ACME_SERVER` parameter had been set. I don't know since when that parameter had been set, so I am just guessing.

This all probably happened when acme.sh devs did this: https://github.com/acmesh-official/acme.sh/wiki/Change-default-CA-to-ZeroSSL, but then their line "any pre-existing certs will still be renewed automatically against the current CA." is either BS or a bug, can't tell because I haven't looked at the code.

I'm wondering why 1. noone else here seems to be affected and 2. why only some of my domains are switched to Zero.

**Comment by d00p** [comment]
> Why has the Le_API parameter been set to zerossl? Has there been any change in acme.sh or froxlor that might explain it?

Nothing froxlor does, we issue the certificates with `-server letsencrypt` (if set) so absolutely no idea where zerossl comes from from our side

**Comment by d00p** [comment]
> I'm wondering why 1. noone else here seems to be affected 

I could guess because froxlor checks for acme.sh upgrades on its cron run, and from what I've seen it always upgrades to current master/main from git. But froxlor just does what the docs say: https://github.com/acmesh-official/acme.sh#14-how-to-upgrade-acmesh

> 2. why only some of my domains are switched to Zero.

That i also did not figure out yet. FirstI thought it was a specific time where these certificates where issued but there were other domains in the same time-period not being set to ZeroSSL

**Comment by snoopotic** [comment]
I had this issue few years ago, too and also an issue open (could not find yet)
The fix is, you need to delete the certs from froxlor webinterface and after next runs, certs get renewed.
I hat this few weeks ago again. Maybe ACME or LE changed something that needed this special renew.

**Comment by d00p** [comment]
acme.sh bug, see https://github.com/acmesh-official/acme.sh/issues/4069
