### ISSUE TITLE
Fehler beim Editieren von Domaineinstellungen

### ISSUE THREAD

**Issue by stdaube** [Froxlor/Froxlor#1044]
Beim Aufruf der Domaineinstellungen bekomme ich eine weiße Seite

Im PHP-Fehlerlog stehen folgende Informationen:

mod_fcgid: stderr: PHP Fatal error:  Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(/home/web1/abcd/efgh): failed to open dir: Permission denied in /var/www/froxlor/lib/Froxlor/FileDir.php:505, referer: froxlor/customer_domains.php?page=domains&s=3d2bd7ceec6d8b1b99fe02d456aa19a9
mod_fcgid: stderr: Stack trace:, referer: froxlor/customer_domains.php?page=domains&s=3d2bd7ceec6d8b1b99fe02d456aa19a9
mod_fcgid: stderr: #0 [internal function]: RecursiveDirectoryIterator->__construct('/home/web1/abcd/efgh', 4096), referer: froxlor/customer_domains.php?page=domains&s=3d2bd7ceec6d8b1b99fe02d456aa19a9
mod_fcgid: stderr: #1 [internal function]: RecursiveDirectoryIterator->getChildren(), referer: froxlor/customer_domains.php?page=domains&s=3d2bd7ceec6d8b1b99fe02d456aa19a9
mod_fcgid: stderr: #2 /var/www/froxlor/lib/Froxlor/FileDir.php(505): RecursiveCallbackFilterIterator->getChildren(), referer: froxlor/customer_domains.php?page=domains&s=3d2bd7ceec6d8b1b99fe02d456aa19a9
mod_fcgid: stderr: #3 /var/www/froxlor/lib/Froxlor/FileDir.php(407): Froxlor\\FileDir::findDirs('/home/web1/abcd/efgh', '1187', '1187'), referer: froxlor/customer_domains.php?page=domains&s=3d2bd7ceec6d8b1b99fe02d456aa19a9
mod_fcgid: stderr: #4 /var/www/froxlor/customer_domains.php(301): Froxlor\\FileDir::makePathfield('/home/web1/abcd/efgh', '1187', '1187', '/html/c49/web/'), referer: froxlor/customer_domains.php?page=domains&s=3d2bd7ceec6d8b1b99fe02d456aa19a9
mod_fcgid: stderr: #5 {main}, referer: froxlor/customer_domains.php?page=domains&s=3d2bd7ceec6d8b1b99fe02d456aa19a9
mod_fcgid: stderr:   thrown in /var/www/froxlor/lib/Froxlor/FileDir.php on line 505, referer: froxlor/customer_domains.php?page=domains&s=3d2bd7ceec6d8b1b99fe02d456aa19a9

/home/web1/abcd/efgh hat chmod 700 und web1:web1 als Benutzer

**Comment by stdaube** [comment]
Ist im Prinzip richtig, trotzdem sollte der Fehler abgefangen und das Verzeichnis ignoriert werden.
Leider habe ich keine Einfluß darauf welche chmods der Benutzer setzt.

**Comment by stdaube** [comment]
Bekomme mit dem Update jetzt nur / angeboten.

**Comment by d00p** [comment]
Can you verify that the following patch resolves the issue?

```diff
diff --git a/lib/Froxlor/FileDir.php b/lib/Froxlor/FileDir.php
index 8291d59a..d258835d 100644
--- a/lib/Froxlor/FileDir.php
+++ b/lib/Froxlor/FileDir.php
@@ -491,7 +491,7 @@ class FileDir
                                        new \RecursiveDirectoryIterator($path, \RecursiveDirectoryIterator::SKIP_DOTS),
                                        $filter
                                ),
-                               \RecursiveIteratorIterator::LEAVES_ONLY,
+                               \RecursiveIteratorIterator::SELF_FIRST,
                                \RecursiveIteratorIterator::CATCH_GET_CHILD
                        );
                        // we can limit the recursion-depth, but will it be helpful or
```

**Comment by stdaube** [comment]
Ja, nun funktioniert es.
