### ISSUE TITLE
DbManager correctMysqlUsers does not support mysql pluggable authentication correctly

### ISSUE THREAD

**Issue by eis-os** [Froxlor/Froxlor#1045]
DbManager correctMysqlUsers with the mysql 8.0 default caching_sha2_password authentication:

SQL Error:
SQLSTATE[HY000]: General error: 1827 The password hash doesn't have the expected format.

DbManagerSQL->getAllSqlUsers(false) won't return the plugin authentication typ.
DbManagerSQL->grantPrivilegesTo is missing a way to provide the authentication scheme, when passing p_encrypted = true

**System information**
* Froxlor version: 57ae625d38f415a0fa310d933209e260953f30f5
* Web server: apache2
* mysql server: mysqld  Ver 8.0.29-0ubuntu0.22.04.2 
* OS/Version: ubuntu 22.04

**To Reproduce**
1. Create a sql user 
2. Check if at least one mysql user has caching_sha2_password in mysql.users
3. Try to alter settings mysql_access_host or server ip (triggering correctMysqlUsers)

**Expected behavior**
DbManagerSQL->getAllSqlUsers(false)  should return authentication plugin typ
DbManagerSQL->grantPrivilegesTo for encrypted password needs a way to pass authentication plugin setting

correctMysqlUsers modified to pass authentication plugin typ

**Comment by d00p** [comment]
referencing [cfda35a](https://github.com/Froxlor/Froxlor/commit/cfda35a36b13b57cf48cfc717dfab373d4016ab1)
