### ISSUE TITLE
Domain Update Command

### ISSUE THREAD

**Issue by fHpro0** [Froxlor/Froxlor#1047]
**The Problem**
The command `Domains.update` gives no respone and print nothing into the logs. 
The only error i get is in the PHP-Logfiles and this is the error:
```log
[Tue Jul 19 15:49:29.049919 2022] [php7:error] [pid 346328] [client X.X.X.X:X] PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /var/www/froxlor/lib/Froxlor/Api/Commands/Domains.php:1329\nStack trace:\n#0 /var/www/froxlor/api.php(50): Froxlor\\Api\\Commands\\Domains->update()\n#1 {main}\n  thrown in /var/www/froxlor/lib/Froxlor/Api/Commands/Domains.php on line 1329
```
It seems like, the error comes from this [code part](https://github.com/Froxlor/Froxlor/blob/master/lib/Froxlor/Api/Commands/Domains.php#L1329).

**System information**
* Froxlor version: newest
* Web server: apache2
* PHP 7.4.30

**To Reproduce**
1. Set up PHP 7.4.30
2. Call command `Domains.update`

**Comment by d00p** [comment]
Seems like you are invoking the API directly, please keep in mind that the `ssl_ipandport` parameter is an `array`, not a `string`, see https://docs.froxlor.org/apiguide/commands/0.10.36/domains.html#domainsupdate

**Comment by fHpro0** [comment]
It seems like that `ssl_ipandport` musst be set 🥴
this key should be optional, i didn´t send it before so it should take the current set value of this domain

> Seems like you are invoking the API directly, please keep in mind that the `ssl_ipandport` parameter is an `array`, not a `string`, see https://docs.froxlor.org/apiguide/commands/0.10.36/domains.html#domainsupdate

**Comment by d00p** [comment]
no it must not be set, quote:

```
optional, list of ssl-enabled ip/port id’s to assign to this domain, if left empty, the current set value is being used, to remove all ssl ips use $remove_ssl_ipandport
```

**Comment by d00p** [comment]
Why don't you show us the code / parameters you are using to call the method? Would be very helpful

**Comment by fHpro0** [comment]
> if you've defined it and it POSTs the field with an empty value, that of course you will get the error (as the api thinks you want to update to `empty`). You have to leave the parameters out you dont want to touch when updating

there is no empty value, its just not defined
i am just sending this key with an empty array now 😌

**Comment by d00p** [comment]
and there's your problem, as said, don't pass the field if you don't want to update it

**Comment by d00p** [comment]
> i know it should be optional, but it seems like its required to work correct. my api call wont give anything back until i set `ssl_ipandport`

check server-logs...there must be _something_

**Comment by d00p** [comment]
Well there are quite a few UnitTests that say it works if not passed in the parameters list, see https://github.com/Froxlor/Froxlor/blob/master/tests/Domains/DomainsTest.php

Why don't you join us on our discord server, it's much easier to discuss there

**Comment by fHpro0** [comment]
simple explanation
`ssl_ipandport` field not defined => Error in PHP-Filelog and no api response
`ssl_ipandport` field defined, even if it is just an empty array => `Domain.update` command is working and gives an api response

This must be fixed 😅

**Comment by d00p** [comment]
If the parameter is **not** passed:

-> https://github.com/Froxlor/Froxlor/blob/master/lib/Froxlor/Api/Commands/Domains.php#L1040
the variable for the parameter gets a `null` assigned, meaning, empty.
-> if empty, set the current ip-ids, https://github.com/Froxlor/Froxlor/blob/master/lib/Froxlor/Api/Commands/Domains.php#L1326

as said: works fine here, please test with cURL or double check your code

**Comment by fHpro0** [comment]
> If the parameter is **not** passed:
> 
> -> https://github.com/Froxlor/Froxlor/blob/master/lib/Froxlor/Api/Commands/Domains.php#L1040 the variable for the parameter gets a `null` assigned, meaning, empty. -> if empty, set the current ip-ids, https://github.com/Froxlor/Froxlor/blob/master/lib/Froxlor/Api/Commands/Domains.php#L1326
> 
> as said: works fine here, please test with cURL or double check your code

it was my fault, i missed in my struct one thing 🤦‍♂️ 
but interesting that the `Domains.update` command struggled with this and couldn´t handle it. Any api response would be helpful 😅 

but thanks for your help 😌

**Comment by florivdg** [comment]
I think there still is an issue with the Froxlor API. It checks if the parameter is empty **or** not an array and null:

```php
(empty($p_ssl_ipandports) || (! is_array($p_ssl_ipandports) && is_null($p_ssl_ipandports)))
```

If so it uses the empty index operator:

```php
$p_ssl_ipandports[] = $ip['id'];
```

Which causes an error since PHP 7.1.0 when used on a string (see [php.net](https://www.php.net/manual/en/language.types.array.php#language.types.array.syntax.modifying)).

So I think the API should protect itself better by stricter type checking. Since you can make it throw an `Fatal Error` when passing just an empty string (`ssl_ipandport = ""`). At best it should ignore string values when using the empty index operator.

**Comment by d00p** [comment]
Empty string is handled by `empty()`. I think JSON makes an empty array out of it, need to validate that though

**Comment by florivdg** [comment]
> I think JSON makes an empty array out of it, need to validate that though

Wherever the error comes from... Just as a reference this curl request comes back with status 500:

```sh
curl -v "https://your-froxlor.api/api.php" \
     -H 'Content-Type: application/json' \
     -d $'{
  "body": {
    "command": "Domains.update",
    "params": {
      "id": 1,
      "ssl_ipandport": ""
    }
  },
  "header": {
    "secret": "secret",
    "apikey": "apikey"
  }
}'
```

When changed to `"ssl_ipandport": []` it goes through fine.
