### ISSUE TITLE
MySQL error during migration from 0.10.38.3 to 2.0.1

### ISSUE THREAD

**Issue by cngJo** [Froxlor/Froxlor#1061]
**As a rule of thumb: before reporting an issue**
* see if it hasn't been [reported](https://github.com/Froxlor/froxlor/issues) (and possibly already been [fixed](https://github.com/Froxlor/froxlor/issues?utf8=✓&q=is:issue%20is:closed)) first
* try with the git master

**Describe the bug**
I wanted to update my froxlor installation form the latest 0.10 to the newest 2 Version.
After following the manual update guide from the documentation and proceeding in the Web Interface to complete the Update I get an (reproducible) error message regarding a `Syntax error or access violation` from MySQL.

The complete error message is:
```text
SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'allowed_mysqlserver' can't have a default value
``` 

This seems to be an issue with my MySQL 5.7 installation, which does not support default values for e.G. the `TEXT` type. That was added with MySQL 8.

I've done a bit of research and found that the line causing this error probably is: https://github.com/Froxlor/Froxlor/blob/d69a7eeb0782e911e7cd6e90fccadc8532333baa/install/updates/froxlor/update_2.x.inc.php#L70

I've also looked at the CI Workflows which seem to test against MySQL 5.7 and are green.
But they use a MySQL dump generated from `install/froxlor.sql.php` which does not include a default value for the affected column. 
https://github.com/Froxlor/Froxlor/blob/d69a7eeb0782e911e7cd6e90fccadc8532333baa/install/froxlor.sql.php#L225

I haven't found and documentation about supported MySQL versions, apart from 
> For a manual installation, you need to have a recent webserver (apache2 or nginx) with PHP and MySQL/MariaDB-server running

in the [docs for manual installation](https://docs.froxlor.org/latest/general/installation/tarball.html)

This seems related to this commit (46c696811dc458c7ae07f77d13b549c8fd88a01f) which changes the mentioned columns from `varchar(500)` to `TEXT`.

From what I understand, the commit was about the column being too short in the past, would it maybe be an option to increase the `varchar` size more, instead of changing it to `TEXT` to keep compatibility with MySQL 5.7 or not specifying a default value in the database but in the PHP-Code somewhere?

Thank you!

**System information**
* Froxlor version: 2.0.1
* Web server: apache2
* DNS server: Bind/PowerDNS (standalone)/PowerDNS (Bind-backend)
* POP/IMAP server: Courier/Dovecot
* SMTP server: postfix/exim
* FTP server: proftpd/pureftpd
* OS/Version: Ubuntu 18.04

**To Reproduce**
1. Follow manual update in the documentation
2. "Proceed" the update in the Web Installer
3. Error message: `SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'allowed_mysqlserver' can't have a default value`

**Expected behavior**
No errors during the upgrade from 0.10 to 2, or documentation that MySQL 5.7 is no longer supported 😉

**Logfiles**
If applicable, add log-entries to help explain your problem.

**Additional context**

**Comment by d00p** [comment]
will be fixed in 2.0.2 later this day, thanks. I sadly forgot to adjust two queries

**Comment by cngJo** [comment]
no problem, thank you for the quick response and fix!

**Comment by d00p** [comment]
fixed in https://github.com/Froxlor/Froxlor/commit/7ce7123756639c710ab9f8af18616b6747444ffb

**Comment by cngJo** [comment]
Thank you, did the Upgrade to 2.0.2 and everything worked fine 🎉
