### ISSUE TITLE
Tabellengruppierung E-Mail-Adressen

### ISSUE THREAD

**Issue by TillMenke** [Froxlor/Froxlor#1066]
Seit Version 2.0 werden E-Mail-Adressen nicht mehr nach (Sub-)Domain sortiert angegeben. Dies ist sehr unübersichtlich. Es wäre schön, wieder zur alten Ansicht zurückzukehren (bzw. zurückkehren zu können)

**Comment by d00p** [comment]
Wir würden hier bei mehr als einer maildomain eine domain-übersicht davorschalten - wäre zwar ein klick mehr um zu den adressen zu gelangen und dann auch explizit nur die der gewählten domain, sollte aber die übersicht steigern

**Comment by d00p** [comment]
Added for next release (2.0.11)
