### ISSUE TITLE
Bug: Emaildomain-Eigenschaft einer Subdomain wird zurückgesetzt

### ISSUE THREAD

**Issue by TillMenke** [Froxlor/Froxlor#1067]
**Describe the bug**
Die Emaildomain-Eigenschaft einer Subdomain wird zurückgesetzt, wenn die Subdomain bearbeitet wird.

**System information**
* Froxlor version: 2.0.5, aber auch frühere Versionen (0.x)
* Web server: apache2
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd

**To Reproduce**
1. Go to 'Domains->Übersicht Domains' im Kundenbackend
2. Click on 'Bearbeiten' bei einer Subdomain
3. Click on 'Speichern'
4. Die Eigenschaft "Emaildomain" ist zurückgesetzt, eingerichtete E-Mail-Adressen werden ohne Rückfrage gelöscht

**Expected behavior**
Die Eigenschaft "Emaildomain" sowie die Adressen bleiben erhalten

**Comment by d00p** [comment]
Hier wäre wichtig zu wissen, wie die Einstellung der zugehörigen "Elterndomain" für `Subdomains als E-Mail-Domains erlauben` lautet
