### ISSUE TITLE
Ubuntu 18LTS apt update fails on froxlor_2.0.5-1

### ISSUE THREAD

**Issue by hknet** [Froxlor/Froxlor#1068]
Ubuntu 18LTS apt update fails on froxlor_2.0.5-1 like this...

Moving older froxlor installation to new default location
mv: cannot move '/var/www/froxlor' to '/var/www/html/froxlor': Directory not empty
dpkg: error processing archive /var/cache/apt/archives/froxlor_2.0.5-1_all.deb (--unpack):
 new froxlor package pre-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 /var/cache/apt/archives/froxlor_2.0.5-1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**System information**
* Froxlor version: 0.10.38.3-1
* Web server: apache2
* DNS server: none
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Unbuntu 18.0.4.6 LTS

**To Reproduce**
apt update

**Expected behavior**
should not try to move itself to some place without consent.

**Additional context**
this breaks basically any unattended-upgrades as this behavior is quite unexpected.

**Comment by d00p** [comment]
Changing the documentroot to debian/ubuntu default was requested a lot. By moving the files we wanted to ensure that also updaters can use the apt-package. If there is any better solution for this, i'm happy to hear and implement it
