### ISSUE TITLE
Please restore 1.X Debian packages

### ISSUE THREAD

**Issue by chrschn** [Froxlor/Froxlor#1070]
Congrats on hitting the 2.0 milestone!

I still run an old Debian Buster server with Froxlor, which auto-updated to 2.0.6 over night. Now the installation is broken because the system is missing PHP >= 7.4, which is not explicitly encoded in the package information (maybe it should be). 

While I certainly need to upgrade Debian on that server, that's not an ad-hoc process, so I would like to restore the system to a functional state in the meanwhile. Unfortunately, the 1.X packages disappeared from https://deb.froxlor.org/debian/, so I cannot downgrade the package to fix it. It's also gone from `/var/cache/apt/archives/` on the server.

Could you please restore the 1.X packages in https://deb.froxlor.org/debian/ for folks with a similar problem like me?

In addition, it would be great if the 2.X packages could explicitly depend on PHP >= 7.4, which would avoid running into this situation in the first place.

**Comment by d00p** [comment]
The apt package should depend on php7.4+ (`php (>= 1:7.4)` in debian/control file)

And as we are just not able to continue supporting 0.10.x packages we won't re-add those to the repository.

In addition, debian 10 is EOL, an upgrade should be considered. Alternatively, install php-7.4 from e.g. sury repository, see https://packages.sury.org/php/

**Comment by chrschn** [comment]
> The apt package should depend on php7.4+ (`php (>= 1:7.4)` in debian/control file)

I can see that Froxlor 2.0.5 depends on `php (>= 1:7.4) | php-cgi (>= 1:7.4) | php-fpm (>= 1:7.4)`, yet `cron-apt` happily installed it on my server with PHP 7.3. The exact version is `2:7.3+69`. Maybe the leading 2 causes the dependency to be satisfied?

> And as we are just not able to continue supporting 0.10.x packages we won't re-add those to the repository.

I'm not asking for continued support of the old version. All I'm suggesting is to restore the packages that have been available until last night to help ppl like me with the upgrade process. From the dependency quirks above I understand that you tried your best not to break existing installations, yet it happened.

> In addition, debian 10 is EOL, an upgrade should be considered. Alternatively, install php-7.4 from e.g. sury repository, see https://packages.sury.org/php/

As I wrote above, I know that Buster is EoL and that I need to upgrade the server. I was just hoping for an intermediate resolution before I can take the time to do so properly and safely.

**Comment by d00p** [comment]
we'll discuss possibilities to add 0.10.x package to the repository in a `oldstable` component instead of `main`, so you'd still have to adjust the repository-url

**Comment by chrschn** [comment]
That would be a great option, thanks for considering it!

**Comment by a-germain** [comment]
> I can see that Froxlor 2.0.5 depends on `php (>= 1:7.4) | php-cgi (>= 1:7.4) | php-fpm (>= 1:7.4)`, yet `cron-apt` happily installed it on my server with PHP 7.3. The exact version is `2:7.3+69`. Maybe the leading 2 causes the dependency to be satisfied?

I can attest of the same problem, so that's two of us if that makes you feel better! It completely broke my froxlor installation. 

The number before the colon is called the epoch. And yes, that's indeed what caused the issue, "2:" being considered higher than "1:", whatever comes next (which is the upstream version).

@d00p, would you consider changing the dependency of the froxlor package so that it requires epoch 2 instead? As that is what Debian currently provides. That way, it (as expected) would at least refuse to install on old systems.

- https://packages.debian.org/bullseye/php
- https://packages.debian.org/bullseye/php-fpm
- etc.

Cheers,

**Comment by d00p** [comment]
Yes we did adjust that yesterday and tested on all different distros. New build will be generated today

**Comment by chrschn** [comment]
Has there been any decision made on this issue?

**Comment by d00p** [comment]
The explicit checks for php7.4 are in the package of 2.0, but there won't be any 0.10.x packages in the repository. You can always find old files on https://files.froxlor.org/releases/

**Comment by chrschn** [comment]
Well, that's sad to hear as the source packages won't helping my situation. I was hoping just restoring the 1.X Debian packages is virtually no extra work and has no additional support constraint since the dist configuration already selects the latest 2.X release for supported distributions.

But thanks anyway.
