### ISSUE TITLE
web update missing Sparkle/install/update.html.twig

### ISSUE THREAD

**Issue by hknet** [Froxlor/Froxlor#1071]
after the apt upgrade was successfull the update via gui fails:

Template error
Unable to find template "Sparkle/install/update.html.twig" (looked into: /var/www/html/froxlor//templates).

#0 /var/www/html/froxlor/vendor/twig/twig/src/Loader/FilesystemLoader.php(131): Twig\Loader\FilesystemLoader->findTemplate()
#1 /var/www/html/froxlor/vendor/twig/twig/src/Environment.php(261): Twig\Loader\FilesystemLoader->getCacheKey()
#2 /var/www/html/froxlor/vendor/twig/twig/src/Environment.php(309): Twig\Environment->getTemplateClass()
#3 /var/www/html/froxlor/vendor/twig/twig/src/Environment.php(277): Twig\Environment->load()
#4 /var/www/html/froxlor/lib/Froxlor/UI/Panel/UI.php(301): Twig\Environment->render()
#5 /var/www/html/froxlor/lib/Froxlor/UI/Panel/UI.php(253): Froxlor\UI\Panel\UI::twigOutputBuffer()
#6 /var/www/html/froxlor/admin_updates.php(60): Froxlor\UI\Panel\UI::view()
#7 {main}

**System information**
* Froxlor version: 2.0.6-1
* Web server: apache2
* DNS server: none
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Ubuntu 18.04.6 LTS

**To Reproduce**
Start web-based update -> results in error above

**Expected behavior**
update via web should work...

**Comment by hknet** [comment]
sidenote: aber logging in again it _seems_ the update has worked anyhow, yet there is no way to be sure everything went fine.

**Comment by d00p** [comment]
Upgrade from a 0.10.x version or another 2.0.x?

**Comment by T-Qualizer** [comment]
I got exactly the same error here, using Debian Bullseye. 

I'm regularly upgrading Froxlor with the package manager.
The error occurred direct after the Page where I could make some choices, like view-options and the Linux-distribution.

Something may have broken during the upgrade with apt, at the following point, but I think that the installation script just continued and has nothing to do with the missing template:

> Preparing to unpack .../froxlor_2.0.6-1_all.deb ...
> Moving older froxlor installation to new default location
> PHP Notice:  Undefined index: dkim_id in /var/www/html/froxlor/lib/Froxlor/Dns/Dns.php on line 164
> PHP Notice:  Undefined index: dkim_id in /var/www/html/froxlor/lib/Froxlor/Dns/Dns.php on line 321
> sh: 1: /etc/init.d/bind9: not found
> [error] Error while running \`/etc/init.d/bind9 reload\`: exit code (127) - please check your system logs
> `Unpacking froxlor (2.0.6-1) over (0.10.38.3-1) ...`
> Setting up php7.4-gmp (7.4.33-1+deb11u1) ...
> 
> Creating config file /etc/php/7.4/mods-available/gmp.ini with new version
> Setting up froxlor (2.0.6-1) ...
> The froxlor package has been updated, please log in via webinterface to finish update.
> Setting up php-gmp (2:7.4+76) ...
> Processing triggers for php7.4-fpm (7.4.33-1+deb11u1) ...
> NOTICE: Not enabling PHP 7.4 FPM by default.
> NOTICE: To enable PHP 7.4 FPM in Apache2 do:
> NOTICE: a2enmod proxy_fcgi setenvif
> NOTICE: a2enconf php7.4-fpm
> NOTICE: You are seeing this message because you have apache2 package installed.

This may be also helpful:
> \# systemctl status bind9
> ● named.service - BIND Domain Name Server
>      Loaded: loaded (/lib/systemd/system/named.service; enabled; vendor preset: enabled)
>      Active: failed (Result: exit-code) since Tue 2022-12-27 12:10:43 CET; 2 weeks 0 days ago
>        Docs: man:named(8)
>     Process: 998 ExecStart=/usr/sbin/named -f $OPTIONS (code=exited, status=1/FAILURE)
>    Main PID: 998 (code=exited, status=1/FAILURE)
>         CPU: 25ms
> 
> Dec 27 12:10:43 www.example.com systemd[1]: named.service: Scheduled restart job, restart counter is at 5.
> Dec 27 12:10:43 www.example.com systemd[1]: Stopped BIND Domain Name Server.
> Dec 27 12:10:43 www.example.com systemd[1]: named.service: Start request repeated too quickly.
> Dec 27 12:10:43 www.example.com systemd[1]: named.service: Failed with result 'exit-code'.
> Dec 27 12:10:43 www.example.com systemd[1]: Failed to start BIND Domain Name Server.

**Comment by d00p** [comment]
Upgrade looks fine, the "errors" are from the cronjob call we need to trigger after moving froxlor to the new location to have correct vhosts for you to be able to open froxlor and update the database.

We are still investigating this issue but so far have tested a lot of updates and never ran into this

**Comment by hknet** [comment]
Well, we got the issue on several hosts (Debian v10, different Ubuntus).
some froxlor-cronfiles were not changed still trying to find their scripts in /var/www/froxlor.
Probably an issue with systems using update-alternatives to set php to use eg. 7.2, as I believe the systemcall is not properly set to use the compatible version.
But it’s quite hard to track what happened during an unattened-upgrade-job.

**Comment by d00p** [comment]
check `scripts/froxlor_master_cronjob.php` if still exists, it calls the new cronjob which has `#!/usr/bin/env php` set - could indeed be an issue if php-cli is set to 7.2

**Comment by T-Qualizer** [comment]
The installation ended immediately after the 'choices' screen. where the red marked error message popped up like described by hknet. There were no Database integrity checks and so on, like I used to see on Froxlor upgrades before.

**Comment by d00p** [comment]
@T-Qualizer installation is 2 steps, 1) extract/install new files and 2) update database. The error for your occurs on the second.

We were not yet abel to reproduce this sadly

**Comment by T-Qualizer** [comment]
The update database step, came usually on logging in into Froxlor after the upgrade from the package manager, but this time I didn't see it.

By the way, this is what I've tried now:

> \# ls -la /var/www/html/froxlor/scripts
> total 20K
> drwxr-xr-x  2 froxlorlocal froxlorlocal 4.0K Jan 10 13:20 .
> drwxr-xr-x 18 froxlorlocal froxlorlocal  12K Jan 10 11:51 ..
> -rw-r--r--  1 froxlorlocal froxlorlocal    0 Dec  2 16:21 index.html
> -rwxr-xr-x  1 froxlorlocal froxlorlocal  903 Dec  2 16:21 php-sessionclean.php

**Comment by d00p** [comment]
`scripts/php-sessionclean.php` will be removed after the web-update process, look fine this way

**Comment by T-Qualizer** [comment]
the web-update process ended with the template error page:

>Template error
>
> Unable to find template "Sparkle/install/update.html.twig" (looked into: /var/www/html/froxlor//templates).
> 
> \#0 /var/www/html/froxlor/vendor/twig/twig/src/Loader/FilesystemLoader.php(131): Twig\Loader\FilesystemLoader->findTemplate()
> \#1 /var/www/html/froxlor/vendor/twig/twig/src/Environment.php(261): Twig\Loader\FilesystemLoader->getCacheKey()
> \#2 /var/www/html/froxlor/vendor/twig/twig/src/Environment.php(309): Twig\Environment->getTemplateClass()
> \#3 /var/www/html/froxlor/vendor/twig/twig/src/Environment.php(277): Twig\Environment->load()
> \#4 /var/www/html/froxlor/lib/Froxlor/UI/Panel/UI.php(301): Twig\Environment->render()
> \#5 /var/www/html/froxlor/lib/Froxlor/UI/Panel/UI.php(253): Froxlor\UI\Panel\UI::twigOutputBuffer()
> \#6 /var/www/html/froxlor/admin_updates.php(60): Froxlor\UI\Panel\UI::view()
> \#7 {main}

Please note the double "//" at "(looked into: /var/www/html/froxlor//templates)".

**Comment by d00p** [comment]
Double // is not the issue, there is no theme "Sparkle" anymore but this should not occur as we fallback to the current one for updates - as said we've tested that multiple times - we're trying to figure out how this is possible

**Comment by T-Qualizer** [comment]
On the first everything looks running fine, I see a new Froxlor Interface, hosts are online, etc., but I feel at my guts, that something is wrong, "php-sessionclean.php" is still there. Is there a way to check the database integrity and how far the update has been finished or where it broke?

**Comment by d00p** [comment]
you are "just" missing the update-procedure which updates the database and adjusts existing entries accordingly and removes old files - it would be very helpful if you could join our Discord and we could check on your server directly to hopefully find where this originates

**Comment by d00p** [comment]
hm, but the error message occurs **after** the `$_POST` action ... so the updates should be done and you should be able to login and use froxlor normally - is this not the case?

**Comment by T-Qualizer** [comment]
Yes, the panel seems to work fine, but the old files are not removed and I didn't notice any database upgrade, like I've seen usual on updating froxlor.

I've joined discord.froxlor now...

**Comment by d00p** [comment]
We've found the cause. Looks like this occurs when the froxlor-vhost is not allowed to run `exec()` in its php-settings (which it does by default) which then leads to the updater not being able to automatically remove old files (including the old theme Sparkle/) and we only checked for the folder to exist - a fix will soon be available
