### ISSUE TITLE
updating 0.10 to 2.0.7 - sinks on debian v10

### ISSUE THREAD

**Issue by hknet** [Froxlor/Froxlor#1072]
**Describe the bug**
During installing v2.0.7 using apt there was virtually no problem, but changing the paths from /var/www to /var/www/html did not propagate to apache-configs, as a result php8.1-fpm for the froxlor vhost broke.
Quick-Fix-Idea: enable php8.1 apache-module and do the web-update-process, but after choosing Debian V10 and going for the database-update things break:

Uncaught exception
0 fwrite(): Argument #1 ($stream) must be of type resource, bool given

#0 /var/www/html/froxlor/lib/Froxlor/Database/Database.php(198): fwrite()
#1 /var/www/html/froxlor/lib/Froxlor/Database/Database.php(594): Froxlor\Database\Database::showerror()
#2 /var/www/html/froxlor/install/updates/froxlor/update_2.x.inc.php(68): Froxlor\Database\Database::__callStatic()
#3 /var/www/html/froxlor/install/updatesql.php(56): include_once('...')
#4 /var/www/html/froxlor/admin_updates.php(53): include_once('...')
#5 {main}

of course /var/www/html is owned by the froxlorlocal-user.

a cli-update-option would be dearly needed as this is getting messy.

**System information**
* Froxlor version: 2.0.7-1
* Web server: apache2
* DNS server: none
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian v10

**To Reproduce**
failed fpm-config - try to fix by using apache-mod-php, after the above error try to give ownership to the www-data user, resulting in:

Uncaught exception
0 Class "Database" not found

#0 /var/www/html/froxlor/admin_index.php(303): require_once()
#1 {main}

**Expected behavior**
not having apt-updates break all things.

**Comment by hknet** [comment]
moving back everything to fpm.
web-update fails:

A database error occurred
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

when trying to report this error using the button presented - ending up here:

Uncaught exception
0 Class "Database" not found

#0 /var/www/html/froxlor/admin_index.php(303): require_once()
#1 {main}

**Comment by hknet** [comment]
This system had MariaDB v10.1 packaged for historing mysql-customizations.
After going for MariaDB v10.3 things seem to get working.

**Comment by d00p** [comment]
> a cli-update-option would be dearly needed as this is getting messy.

https://docs.froxlor.org/latest/admin-guide/cli-scripts/#update

**Comment by hknet** [comment]
the cli update reported being the latest release, I have yet to find a way to do the database-updates this way I guess, as this seems only possible using the web-update-process afterwards.

**Comment by d00p** [comment]
Happens if non-default php.ini for froxlor is used and the commands are not being run automatically due to missing exec() permissions - a compatible Cron is being created within the update after the removing of old files but obviously deleted if run manually after the update.

We'll look into it.
