### ISSUE TITLE
Permissions changing on every master-cronjob

### ISSUE THREAD

**Issue by md127** [Froxlor/Froxlor#1074]
Hello guys,

the master-cronjob changes user and group of /var/www/froxlor to "**www-data**" on every run. 
If I want to use the auto-update function, I have to set both to "**froxlorlocal**" via 
`chown -R froxlorlocal:froxlorlocal /var/www/froxlor`
or disable the cronjob, which is certainly not the best solution.

In addition: In version **2.0.7**, Froxlor also states "userdata.inc.php not readable." The login page is replaced by the error message and it is only possible to log back in after doing 
`chown -R froxlorlocal:froxlorlocal /var/www/froxlor`
once more, only to be presented the same message a minute later, after the cronjob ran. (I have mine set to 1min)

In **2.0.6**, at least the panel works flawlessly. No login or navigation problems there.

**System information**
* Froxlor version: 2.0.6
* Web server: Apache2
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian 11 x64, Kernel 6.1
* MariaDB: 10.11
* FastCGI enabled

**Expected behavior**
User and group of /var/www/froxlor stay - once set to froxlorlocal - the same and do not get changed by the cronjob

I had this issue with older versions (0.9.X) as well. 

Any hints?

Regards,
Michael

**Comment by d00p** [comment]
The local user and group are a setting in "Froxlor vhost setting"

**Comment by PhilWaldmann** [comment]
I've the same problem.
Fresh installation and after a few minutes unable to use the web UI, because of the mentioned warning about the file owner.
In order to fix it, I'll need to quickly change the user/group from froxlorlocal to www-data in the web UI vhost settings.

**Comment by d00p** [comment]
Can you validate the local user/group settings in "Froxlor vhost" after installation?

**Comment by PhilWaldmann** [comment]
I haven't found a way to change these settings via CLI (maybe via `froxlor:api-call`?)
But in the web UI it's set to `froxlorlocal`. And the user permissions for all files unter /var/www/html/froxlor is `froxlorlocal:froxlorlocal`.
So instead of the login screen I'll get "The configuration file lib/userdata.inc.php cannot be read from the webserver."

I'm nginx and php-fpm. I guess there is something wrong with the auto config of php-fpm.
If you think so too, I'll dig deeper and check the applied config

**Comment by d00p** [comment]
`froxlorlocal` would be correct though if this is a default installation using php-fpm. I think it's somehow related to your issue #1092 - maybe best discuss this on Discord to not mixup things here

**Comment by PhilWaldmann** [comment]
uninstalling apache2 first did the trick.
Because apache2 has the default www-data setup which causes the problems.
