### ISSUE TITLE
froxlor 2.0.7 update manually removing files clashes with cron-job

### ISSUE THREAD

**Issue by hknet** [Froxlor/Froxlor#1076]
**Describe the bug**
After an apt upgrade the web-update-process orders to remove files manually, including:
rm -rf '/var/www/html/froxlor/scripts'
yet the cronjob in /etc/cron.d/froxlor still calls /var/www/html/froxlor/scripts/froxlor_master_cronjob.php
which results in the cron job not being updated anymore...

**System information**
* Froxlor version: 2.0.7
* Web server: apache2
* DNS server: none
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: debian v10

**To Reproduce**
update from 0.10 to 2.0.7 via apt updates

**Expected behavior**
probably adding another command to be executed manually to install the cron-jobs correctly.

**Comment by d00p** [comment]
Happens if non-default php.ini for froxlor is used and the commands are not being run automatically due to missing exec() permissions - a compatible Cron is being created within the update after the removing of old files but obviously deleted if run manually after the update.

We'll look into it.
