### ISSUE TITLE
Multi Server Setup

### ISSUE THREAD

**Issue by ghost** [Froxlor/Froxlor#1079]
**Is your feature request related to a problem? Please describe.**
Actually its only possible to habe 1 Server with all Services which can on a high usage reach process Limits which is not recommended to setup to much higher than 2000 processes.

**Describe the solution you'd like**
The possibility to a Multi Server Setup Like:
- App Server for Webserver & PHP
- Database Server for MySQL 5.6/8/MariaDB10.5/10.6
- Mail Server Including Dovecot, Postfix, Webmail and autoconfig to Work with Mail Clients like Outlook and Thunderbird
- Cache Server for Redis Instances and memcache
- Primary DNS Server
- Secondary DNS Server
- Management Server for Admin/Reseller Web Interface (especially to secure Reseller/Admin Login to be only available via VPN or company network

**Describe alternatives you've considered**
Actually i did not use froxlor, cause the maintenance is more hard when there is no service-related Multi Server setup

**Additional context**
It wouldnt have high prio. Just a nice to have and a USP to Plesk or CPanel cause their Multi-Server Setups are .... not that what most shared hoster would like to use.

P.S. im working in the managed hosting business and know how our customers with more than a tiny blog or website like these setups.

**Comment by d00p** [comment]
Using shared storage for froxlor generated configs and managed directories, this can more or less be achieved

**Comment by GeeksBase** [comment]
Can you explain more in Detail what you mean?

**Comment by d00p** [comment]
Join our discord, I'm glad to discuss there
