### ISSUE TITLE
Ticket System Including "staff" accounts

### ISSUE THREAD

**Issue by ghost** [Froxlor/Froxlor#1080]
**Is your feature request related to a problem? Please describe.**
Some customers would like to write tickets to different departures like technical support, General iniquiries etc. without writing an extra mail for it. Further support operators need to answer emails or use a 3rd party ticket system.

**Describe the solution you'd like**
- customers can write tickets to Resellers Departments, which can get setup by resellers.
- resellers can write tickets to admin (hoster Departments), which can get setup by admins
- customer tickets can get assigned to a resellers staff Account
- Reseller Tickets can get assigned to a hosters staff Account
- resellers and admins can setup staff accounts and set detailed permissions what they can do.
- customers/resellersladmins can see a list of their Tickets and Filter them by Status
- Ticket System can individually enabled/disabled for customers/resellers
- the priority can only set by the receivers site
- when a Ticket gets closed, the customer/Reseller can rate it with stars 1-5 and add a optional Note
- resellers/admins can see a general statistic about their received ratings and ticket system kpi's

**Describe alternatives you've considered**
Using third party ticket system

**Additional context**
I think thats a really nice to have feature.

**Comment by d00p** [comment]
There are so many open-source ticket-system applications, this is not froxlor's main purpose
