### ISSUE TITLE
froxlor 2.0.8-1 assumes ACME path at /var/www/froxlor

### ISSUE THREAD

**Issue by hknet** [Froxlor/Froxlor#1081]
**Describe the bug**
after the apt update to v2.0.8 the web-based-updater-follow-up asks for the ACME challenge docroot.
it is pre-filled with /var/www/froxlor (which is possibly wrong if follwoing v2 updates the path for froxlor has been changed to /var/www/html/froxlor already)
yet we find little explanation on this value - should it correspond with the webservers-settings (probably) for the .acme-path or should it alle be moved to the new froxlor path as the old one is usually empty/non-existent...

**System information**
* Froxlor version: 2.0.8
* Web server: apache2
* DNS server: none
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian v11

**To Reproduce**
apt update from 2.0.7 to 2.0.8 - web-based updater presents this path option, yet gives virtually no hint on how to solve this question.

**Expected behavior**
a more concise explanation on those settings, one can only assume to change this if one knows about the new directory-structure as well as other updates needed (new apache alias config-path or similar).
happily when one answers the first answer correct one gets told to enter the new config for the webserver.

**Comment by d00p** [comment]
Has been addressed with https://github.com/Froxlor/Froxlor/commit/41de161555a2546fdfb471c5f5f5c2c314133410
