### ISSUE TITLE
Disable "Documentation" in navigation 

### ISSUE THREAD

**Issue by JB1985** [Froxlor/Froxlor#1083]
It would be great if it is possible to deactivate or switch off the "Documentation" navigation menu.

![image](https://user-images.githubusercontent.com/9932751/212891450-ea5241b9-7994-42f9-99a2-1a5b16dfa579.png)

**Comment by d00p** [comment]
Possible to hide it for customers in panel-settings using "customer-hide-options", see c56bc651b9a784ccb48e568bba7538435b3295ed

**Comment by JB1985** [comment]
Yes, why not!
