### ISSUE TITLE
Le_Webroot for acme.sh needs updates vor froxlor v2

### ISSUE THREAD

**Issue by hknet** [Froxlor/Froxlor#1084]
some acme.sh config files still have the parameter:
Le_Webroot='/var/www/froxlor'

which is broken as of froxlor v2, new cert issues for those hostnames/domains fail obviously for http-verification.

this obviously needs an update.

hopefully specific prehook and posthook scripts won't be kicked.

**System information**
* Froxlor version: 2.0.8-1
* Web server: apache2
* DNS server: none
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian v11

**To Reproduce**
update froxlor wait for letsencrypt-renewals and see them fail.

**Expected behavior**
Webroot parameter for existing acme config-files should be updated.

**Comment by d00p** [comment]
Did you run the `bin/froxlor-cli froxlor:validate-acme-webroot ` command (git version)

**Comment by hknet** [comment]
nope, didn't even know about this option, yet I'd expect the update to do this at least once to fix things - or tell the admin to do this after being told to fixup the acme-webroot.

**Comment by d00p** [comment]
I appreciate your feedback but sorry we don't seem to meet all you _expectations_, this is still an open-source project done in spare-time.

Also, as the acme-challenge path is configurable, we cannot blindly run this script on update (not even if we wanted to, it requires root privileges, so let's assume you mean the debian package postinst:) to avoid overwriting custom-set values.

A note to inform about runnig this command if the value changed can surely be added but makes only sense in the update-procedure between 2.0.7 and 2.0.8 where we ask for this value. So, this will only affect updaters coming from 2.0.8 anyway

**Comment by hknet** [comment]
in fact I was more hopeing for the web-update-part as this would probably help others to get this also right.
