### ISSUE TITLE
RFC: Will Froxlor use semantic versioning for future releases?

### ISSUE THREAD

**Issue by LordSimal** [Froxlor/Froxlor#1085]
Even though the 2.0.8 release seems quite solid since there are no problems till now we were quite shocked after performing usual server updates and suddenly Froxlor jumped from 0.10.38.3 to 2.0.8

Ususally https://semver.org/ is a pretty solid way of versioning software and communicating with users if those updates contain
- major changes (user attention is needed)
- minor changes/new features but still backwards compatible (user attention is recommended)
- patch changes for e.g. bugfixes or security fixes (no user attention is required)

This issue should just be a little discussion on how future releases could be handled.

Was there a specific reason why it wasn't just a simple 1.0.0 release? I am just curious.

**Comment by d00p** [comment]
it's not 1.0.0 because there used to be a codebase back a few years that would've been froxlor-1.0.0 but has been banonded for several reasons, most likely man-power/spare time.

Imagine this being almost like why there is no php6 :)

**Comment by LordSimal** [comment]
Thanks for your quick answer 👍🏻
