### ISSUE TITLE
froxlor:cron 'letsencrpt' generates php warning undefined property Net_DNS2_RR_CNAME::$address

### ISSUE THREAD

**Issue by hknet** [Froxlor/Froxlor#1089]
during a manual call for a new cert to be generated:
/var/www/html/froxlor/bin/froxlor-cli froxlor:cron 'letsencrypt' generates two warnings:

PHP Warning:  Undefined property: Net_DNS2_RR_CNAME::$address in /var/www/html/froxlor/lib/Froxlor/PhpHelper.php on line 266
PHP Warning:  Undefined property: Net_DNS2_RR_CNAME::$address in /var/www/html/froxlor/lib/Froxlor/PhpHelper.php on line 277

**System information**
* Froxlor version: 2.0.9-1
* Web server: apache2
* DNS server: none
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian v10 (buster)

**To Reproduce**
1. create new domain using letsencrypt
2. manuall call the cron-job letsencrypt
3. reports the above warnings

**Expected behavior**
possibly avoid using an undefined property

**Comment by d00p** [comment]
Is there a CNAME record specified for the domain you were testing?

**Comment by hknet** [comment]
yep, the domain-record points to an A record, the www-host-record points in turn via cname to the hostname of the froxlor-host.
