### ISSUE TITLE
after disabling LetsEncrypt for a domain - also remove it from acme.sh backend

### ISSUE THREAD

**Issue by hknet** [Froxlor/Froxlor#1091]
after disabling letsencrypt or removing a domain from froxlor there is a backend-content within acme.sh that is not removed and this way acme trys to renew certificates (and fails).

when removing a letsencrypt enabled domain or simply when disabling letsencrypt with a domain issue a system-call like "acme.sh --remove -d domain" and this should be handled by acme.

**Comment by d00p** [comment]
froxlor inserts the task `DELETE_DOMAIN_SSL` if let's encrypt has been disabled which is processed by the cronjob and calls this function: https://github.com/Froxlor/Froxlor/blob/main/lib/Froxlor/Domain/Domain.php#L354

**Comment by hknet** [comment]
might it be this task is not inserted if the domain is simply deleted?
(otherwise I got no explanation for those old datapoints in the acme-backend)

**Comment by d00p** [comment]
it is also inserted when the domain gets deleted: https://github.com/Froxlor/Froxlor/blob/main/lib/Froxlor/Api/Commands/Domains.php#L2147

**Comment by d00p** [comment]
Just tested, works as intended
