### ISSUE TITLE
Unattended Installation infinite loop

### ISSUE THREAD

**Issue by PhilWaldmann** [Froxlor/Froxlor#1092]
**Describe the bug**
Installing froxlor via CLI `bin/froxlor-cli froxlor:install -n /path/to/config.json` will result in an infinite loop if any config parameter is invalid. 
E.g. if a non existing `httpuser` is set, or the `servername` contains underscores.

**System information**
* Froxlor version: 2.0.9-1
* Web server: nginx
* DNS server: None
* POP/IMAP server: None
* SMTP server: None
* FTP server: proftpd
* OS/Version: Ubuntu 20.04
 
**To Reproduce**
1. Install froxler via apt
2. Start the installation via `bin/froxlor-cli froxlor:install -n /path/to/config.json` and provide a faulty config

**Expected behavior**
Install process should return the error and stop

**Additional context**
Tried this via ansible and the whole server got unresponsive because if the infinite loop/retries...

**Comment by d00p** [comment]
Could you provide the used config.json please

**Comment by PhilWaldmann** [comment]
sure

```json
{
  "mysql_host": "localhost",
  "mysql_ssl_ca_file": "",
  "mysql_ssl_verify_server_certificate": "0",
  "mysql_root_user": "root",
  "mysql_root_pass": "{{ db_root_password }}",
  "mysql_unprivileged_user": "{{ db_username }}",
  "mysql_unprivileged_pass": "{{ db_password }}",
  "mysql_database": "{{ db_name }}",
  "mysql_force_create": "0",
  "admin_name": "Administrator",
  "admin_user": "{{ froxlor_username }}",
  "admin_pass": "{{ froxlor_password }}",
  "admin_pass_confirm": "{{ froxlor_password }}",
  "admin_email": "{{ froxlor_email }}",
  "distribution": "focal",
  "serveripv4": "{{ ec2_public_ip }}",
  "serveripv6": "",
  "servername": "{{ id }}",
  "use_ssl": "1",
  "webserver": "nginx",
  "webserver_backend": "php-fpm",
  "httpuser": "froxlorlocal",
  "httpgroup": "froxlorlocal",
  "activate_newsfeed": "0",
  "target_servername": "{{ id }}"
}
```

Here is the log messages which get repeated infinitely:
```
Details about your server
-------------------------

 Setting field 'distribution' to value 'focal'
 Setting field 'serveripv4' to value '3.126.173.122'
 Setting field 'serveripv6' to value ''
 Setting field 'servername' to value 'shared.digitalbits.at'
 Setting field 'use_ssl' to value '1'
 Setting field 'webserver' to value 'nginx'
 Setting field 'webserver_backend' to value 'php-fpm'
 Setting field 'httpuser' to value 'froxlorlocal'
 Setting field 'httpgroup' to value 'froxlorlocal'
 Setting field 'activate_newsfeed' to value '0'

                                                                                                                        
 [ERROR] Given webserver-user does not seem to exist on the system                                                                                                                           
```

**Comment by PhilWaldmann** [comment]
I've no changed the `httpuser` and `httpgroup` back to `www-data`, which produces another problem. See #1074

**Comment by d00p** [comment]
you've chosen to use php-fpm - why would you want that to be set to www-data? Makes no sense.

I'll check the installer, a check for the user does not seem right as for php-fpm, the local user will be generated by froxlor

**Comment by d00p** [comment]
So okay, first thing, I mixed up things, the `httpuser`and `httpgroup` really does need to be the webserver-user (as it will be added as group member to the users when using php-fpm).
As said in #1074 - better discuss and try to find cause via Discord
