### ISSUE TITLE
DKIM with RSPAMD and without DNS

### ISSUE THREAD

**Issue by nched** [froxlor/Froxlor#1093]
**Is your feature request related to a problem? Please describe.**
There are several requests for a proper DKIM implementation. In nearly all cases it boils down to a combination of DKIM & DNS and since DNS is not used widely enough DKIM implementation is considered low priority. 

**Describe the solution you'd like**
DKIM signed mails are now more or less required by bigger e-mail providers like Google, Yahoo etc to pass their spam tests. I run several tests with different Google accounts and Mail-tester.com. While I scored a high score without DKIM at mail-tester.com - Google still put the mails in the spam folder. As soon as the mail was DKIM signed Google put it into the inbox. 

I run Froxlor with web- and mail server but without DNS. DNS is managed external. I already have rspamd running. 
What I propose is the following:

1. Let Froxlor produce a pair of keys for domains with DKIM setting ticked. 
2. Create the keys in a way that they are readable by rspamd -> the key files containing the domain name. 
3. Template for rspamd.
4. Make the public key viewable through the Froxler interface. 
5. If DNS server is used and the DKIM setting per domain is ticked then write the DNS configuration. 

**Describe alternatives you've considered**
Point 5 is a different use case and optional. Point 4 would be nice to have - as well as point 3. Point 1 & 2 are essential. 

**Additional context**

**Comment by nched** [comment]
agreed. And I highly appreciate what you guys are doing, especially you d00p! No time pressure. I can sponsor some beers. ;-)

**Comment by Neustradamus** [comment]
To follow this important ticket.

**Comment by d00p** [comment]
started implementation with b15f99b1e1625ac83512c5f44ad0a6514e630879 (future version 2.2)

**Comment by d00p** [comment]
It's implemented that way as antispam-feature in v2.2
