### ISSUE TITLE
Google Safe Browsing hat kürzlich Phishingaktivitäten auf xxx.de festgestellt. 

### ISSUE THREAD

**Issue by drexlma** [Froxlor/Froxlor#1102]
Nach dem Upgrade auf die Version 2 bekomme ich sowohl aufm Handy als auch aufm Desktop Chrome eine Warnung.
![5BDDBA78-04A5-412B-9F36-9FFD0DEC6198](https://user-images.githubusercontent.com/7121202/221395551-2222313b-aff5-4fd3-bb88-3682d8b636a3.jpeg)

Downgrade ich, kommt keine Meldung.

Reproduzieren:
1. Login in Froxlor
2. Seite aufrufen admin_customers.php?page=customers
3. Auf einen Kunden klicken damit man sich mit ihm einloggt

**Comment by d00p** [comment]
Wie hast du froxlor bezogen (tarball, debian paket, etc.)? Wie wurde das update durchgeführt? Sofern es reproduzierbar nenne mir doch bitte (auch gern via DM) die domain damit ich prüfen kann was zu dieser Meldung führen soll

**Comment by drexlma** [comment]
Vorab hier:
Tarball ist die original installation. Danach per Web-auto-Update.

ich teste es die tage bei anderen Kunden von mir noch. 

Hab ein Request schon an google gestellt.

**Comment by bhueske** [comment]
Das gleiche habe ich auch bei einer meiner Installationen. Installiert wurde es per Tarball noch als Version 0.10 und dann immer per Web-Updater geupdated.

**Comment by d00p** [comment]
Wir konnten bisher leider nicht feststellen, was genau im Code einen phishing-verdacht verursachen sollte

**Comment by d00p** [comment]
Ggfls behoben durch Anpassungen beim Setzen des Cookies, siehe https://github.com/Froxlor/Froxlor/commit/c56e0b9daca3a0c27b148516b5c60bcdb4a95c65#diff-c2296ae20a75ceef36611d6532b747ef1e788a4996856152f5800f4a021bb762 da wir vermuten, dass u.U. das Setzen von `$_SERVER['HTTP_HOST']` hier problematisch gewesen sein könnte

**Comment by drexlma** [comment]
ok irgend was stört google trotzdem
<img width="1232" alt="Bildschirmfoto 2023-06-04 um 20 40 12" src="https://github.com/Froxlor/Froxlor/assets/7121202/9019ef35-7cc2-4f5d-9338-03ba241c70b3">
das ist echt kritisch weil die Hauptdomain nun auch gesperrt ist...

**Comment by d00p** [comment]
Hast du mehrere froxlor instanzen auf verschiedenen subdomains der hauptdomain liegen?

**Comment by drexlma** [comment]
super ... sehr sehr ärgerlich

**Comment by drexlma** [comment]
> Hast du mehrere froxlor instanzen auf verschiedenen subdomains der hauptdomain liegen?

nur auf einer.

**Comment by drexlma** [comment]
bzw. hab mehere Server aber für diesen server mit dieser domain gibts nur eine Instanz mit der sv1 als subdomain

**Comment by d00p** [comment]
ja wie gesagt, wir bekommen leider keinerlei detail infos von google noch sonst woher, wir wissen leider auch nicht was google hier als "social engineering content" einstuft - es ist uns ein rätsel

**Comment by d00p** [comment]
@drexlma die false positives bekommen wohl auch mehr leute: https://support.google.com/webmasters/thread/207009639?hl=de&sjid=10802434342134259044-EU

**Comment by drexlma** [comment]
shit. aber mit v1 gabs nie probleme, erst mit v2. 
also ich hab mich eingeloggt, bin auf kunden, hab auf den Kundennamen geklickt um mich mit ihm einzuloggen, hab die mail adressen angeschaut. 
und dann war ich gesperrt, irgend was dabei. Davor war ich Wochen nicht drin, und mein browser hat das automatisiert an google gemeldet.

**Comment by d00p** [comment]
> shit. aber mit v1 gabs nie probleme, erst mit v2.

ist mir bewusst - wir wissen dennoch nicht wo google hier "social engineering inhalte" erkennt - wenn du nen tipp hast, gern

Was der Chrome browser da ggfls alles "local" macht und meldet weiss ich nicht - google kann jedenfalls sonst nicht einfach bereiche indizieren, die login geschützt sind

**Comment by d00p** [comment]
Wir haben aktuell noch die "hidden" fields für das redirecten zur letzten seite bei session timeout...das könnte google möglicherweise noch stören, wir schauen mal das wir da noch was dran machen, dass der login so leicht und sauber wie möglicht ist, im schlimmsten fall halt auf kosten irgendwelcher redirects nach logout - das ist nicht das schlimmste

**Comment by drexlma** [comment]
ja muss mein browser gewesen sein. ja google loggt sich definitv nicht ein. 

ist das n change zu v1 mit dem hidden-field? mit v1 war das ja nie n thema. außer google hat das selbst was an der detection angepasst.

**Comment by d00p** [comment]
nö, das war auch in 0.9 und 0.10 schon so  - aber was anderes fällt uns einfach wirklich nicht mehr ein was es noch sein könnte...chrome entwickelt das ja auch weiter und ggfls werden halt sachen jetzt anders eingeschätzt oder was auch immer als noch vor 2-3 jahren

**Comment by drexlma** [comment]
hm wobei ich das problem am Feb 26 ja nur mit v2 hatte, mit v1 nicht.  hm.

**Comment by d00p** [comment]
ja, ist uns bewusst - ich kann aber google leider nicht in die karten schauen. Ich habe doch jetzt gesagt das wir was tun, also bring doch nich zum 3. mal "aber mit v1 gings" - das ist uns klar

**Comment by dtugend** [comment]
@drexlma Klingt eher so als ob sich jemand an Goolge als an Froxlor wenden muss - vielleicht auch ein GDPR fall, aber praktisch hat Google ja Supportpersonal abgebaut - ka  :-(

**Comment by drexlma** [comment]
<img width="709" alt="image" src="https://github.com/Froxlor/Froxlor/assets/7121202/a09aa409-ade7-415f-94e1-c039a6734081">
leider wieder, diesmal bei einem anderen Kunden, mit der aktuellen Version.

**Comment by dtugend** [comment]
Da Froxlor nicht auf der selben domain sondern ggf. (wenn überhaupt) nur selben IP läuft, könnte das ggf. was mit NGINX setup zu tun haben vielleicht?
Weil wir hatten das Problem mit Froxlor 2 zum Glück noch nie, verwenden aber kein NGINX, sondern nur Apache2?

**Comment by d00p** [comment]
passiert auch mit apache - kann hier nur leider keine neueren erkenntnisse geben. Wir wissen schlichtweg nicht woher es kommen soll. Wenn jemand mehr info hat, gerne melden

**Comment by drexlma** [comment]
Ich schau mal ob ich bei allen drei fällen bei uns etwas durch Korrelation der Access Logs was rausfinden kann.

**Comment by dtugend** [comment]
Falls möglich schau auch bitte in die Error logs (z.B. nach Zertifikatsfehler oder so).
(Sorry, dass ich schon wieder nerve, ich habe Angst, dass das problem bei uns auch irgendwann auftritt.)

**Comment by d00p** [comment]
Nächster Versuch das zu fixen: https://github.com/Froxlor/Froxlor/commit/2d30394150ff93c03d3326dcff486084c98b4c79 (kommt mit 2.0.22)
