### ISSUE TITLE
Max. Character Length of UNIX Sockets

### ISSUE THREAD

**Issue by 3lding** [Froxlor/Froxlor#1108]
**Describe the bug**
We've some customers where the domain names are really long combined with the customer name. This results to that the absolute fpm socket paths are too long (see [this link](https://unix.stackexchange.com/questions/367008/why-is-socket-path-length-limited-to-a-hundred-chars)) and reach the max character limit for absolute socket paths. This also results to that the webserver is unable to connect to the socket defined in its configuration file because the file does not exist because of an incomplete name.

For example:

- Customer name: i-have-an-really-long-customer-name
- Domain: my-really-long-domain-name-is-too-long.com
- Resulting file (created by php fpm): /var/lib/apache2/fastcgo/1-i-have-an-really-long-customer-name-my-really-long-domain-name-is-too-long.com-p (the rest will be cut by the system itself because of the maximum character length)

**System information**
* Froxlor version: 2.0.12
* Web server: apache2
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian 11 (bullseye)

**To Reproduce**
1. Go to customers 
2. Create a customer with a very long name
3. Create a domain with a very long name
4. Use PHP FPM
5. Run the Froxlor Cron for creating the FPM socket
6. Check resulting file

**Expected behavior**
Set a max. character length within `/var/www/html/lib/Froxlor/Cron/Http/Php/Fpm.php` => `Line 346` for the socket files which should be created by e.g. PHP FPM so that the webserver is able to connect to its defined socket path again.

**Comment by d00p** [comment]
Can you test the patch shown below whether this fixes the issue?

```diff
diff --git a/lib/Froxlor/Cron/Http/Php/Fpm.php b/lib/Froxlor/Cron/Http/Php/Fpm.php
index 96721cb1..81505daa 100644
--- a/lib/Froxlor/Cron/Http/Php/Fpm.php
+++ b/lib/Froxlor/Cron/Http/Php/Fpm.php
@@ -342,8 +342,17 @@ pm.max_children = 1
        public function getSocketFile($createifnotexists = true)
        {
                $socketdir = FileDir::makeCorrectDir(Settings::Get('phpfpm.fastcgi_ipcdir'));
-               // add fpm-config-id to filename so it's unique for the fpm-daemon and doesn't interfere with running configs when reuilding
-               $socket = strtolower(FileDir::makeCorrectFile($socketdir . '/' . $this->domain['fpm_config_id'] . '-' . $this->domain['loginname'] . '-' . $this->domain['domain'] . '-php-fpm.socket'));
+               // add fpm-config-id to filename, so it's unique for the fpm-daemon and doesn't interfere with running configs when reuilding
+               $socket_filename = $this->domain['fpm_config_id'] . '-' . $this->domain['loginname'] . '-' . $this->domain['domain'] . '-php-fpm.socket';
+               if (strlen($socket_filename) > 100) {
+                       // respect the unix socket-length limitation
+                       $socket_filename = $this->domain['fpm_config_id'] . '-' . $this->domain['loginname'] . '-' . $this->domain['id'] . '-php-fpm.socket';
+                       if (strlen($socket_filename) > 100) {
+                               // even a long loginname it seems
+                               $socket_filename = $this->domain['fpm_config_id'] . '-' . $this->domain['guid'] . '-' . $this->domain['id'] . '-php-fpm.socket';
+                       }
+               }
+               $socket = strtolower(FileDir::makeCorrectFile($socketdir . '/' . $socket_filename));
 
                if (!is_dir($socketdir) && $createifnotexists) {
                        FileDir::safe_exec('mkdir -p ' . escapeshellarg($socketdir));
```

**Comment by 3lding** [comment]
> Can you test the patch shown below whether this fixes the issue?
> 
> ```diff
> diff --git a/lib/Froxlor/Cron/Http/Php/Fpm.php b/lib/Froxlor/Cron/Http/Php/Fpm.php
> index 96721cb1..81505daa 100644
> --- a/lib/Froxlor/Cron/Http/Php/Fpm.php
> +++ b/lib/Froxlor/Cron/Http/Php/Fpm.php
> @@ -342,8 +342,17 @@ pm.max_children = 1
>         public function getSocketFile($createifnotexists = true)
>         {
>                 $socketdir = FileDir::makeCorrectDir(Settings::Get('phpfpm.fastcgi_ipcdir'));
> -               // add fpm-config-id to filename so it's unique for the fpm-daemon and doesn't interfere with running configs when reuilding
> -               $socket = strtolower(FileDir::makeCorrectFile($socketdir . '/' . $this->domain['fpm_config_id'] . '-' . $this->domain['loginname'] . '-' . $this->domain['domain'] . '-php-fpm.socket'));
> +               // add fpm-config-id to filename, so it's unique for the fpm-daemon and doesn't interfere with running configs when reuilding
> +               $socket_filename = $this->domain['fpm_config_id'] . '-' . $this->domain['loginname'] . '-' . $this->domain['domain'] . '-php-fpm.socket';
> +               if (strlen($socket_filename) > 100) {
> +                       // respect the unix socket-length limitation
> +                       $socket_filename = $this->domain['fpm_config_id'] . '-' . $this->domain['loginname'] . '-' . $this->domain['id'] . '-php-fpm.socket';
> +                       if (strlen($socket_filename) > 100) {
> +                               // even a long loginname it seems
> +                               $socket_filename = $this->domain['fpm_config_id'] . '-' . $this->domain['guid'] . '-' . $this->domain['id'] . '-php-fpm.socket';
> +                       }
> +               }
> +               $socket = strtolower(FileDir::makeCorrectFile($socketdir . '/' . $socket_filename));
>  
>                 if (!is_dir($socketdir) && $createifnotexists) {
>                         FileDir::safe_exec('mkdir -p ' . escapeshellarg($socketdir));
> ```

@d00p nearly perfect. There is just one thing missing. Here's my small modification so that the fix works:

 ```diff
diff --git a/lib/Froxlor/Cron/Http/Php/Fpm.php b/lib/Froxlor/Cron/Http/Php/Fpm.php
index 96721cb1..81505daa 100644
--- a/lib/Froxlor/Cron/Http/Php/Fpm.php
+++ b/lib/Froxlor/Cron/Http/Php/Fpm.php
@@ -342,8 +342,17 @@ pm.max_children = 1
        public function getSocketFile($createifnotexists = true)
        {
                $socketdir = FileDir::makeCorrectDir(Settings::Get('phpfpm.fastcgi_ipcdir'));
-               // add fpm-config-id to filename so it's unique for the fpm-daemon and doesn't interfere with running configs when reuilding
-               $socket = strtolower(FileDir::makeCorrectFile($socketdir . '/' . $this->domain['fpm_config_id'] . '-' . $this->domain['loginname'] . '-' . $this->domain['domain'] . '-php-fpm.socket'));
+               // add fpm-config-id to filename, so it's unique for the fpm-daemon and doesn't interfere with running configs when rebuilding
+               $socket_filename = $socketdir . '/' . $this->domain['fpm_config_id'] . '-' . $this->domain['loginname'] . '-' . $this->domain['domain'] . '-php-fpm.socket';
+               if (strlen($socket_filename) > 100) {
+                       // respect the unix socket-length limitation
+                       $socket_filename = $socketdir . '/' . $this->domain['fpm_config_id'] . '-' . $this->domain['loginname'] . '-' . $this->domain['id'] . '-php-fpm.socket';
+                       if (strlen($socket_filename) > 100) {
+                               // even a long loginname it seems
+                               $socket_filename = $socketdir . '/' . $this->domain['fpm_config_id'] . '-' . $this->domain['guid'] . '-' . $this->domain['id'] . '-php-fpm.socket';
+                       }
+               }
+               $socket = strtolower(FileDir::makeCorrectFile($socket_filename));
 
                if (!is_dir($socketdir) && $createifnotexists) {
                        FileDir::safe_exec('mkdir -p ' . escapeshellarg($socketdir));
```

**Comment by d00p** [comment]
Oh the limit is for the complete path? I thought it's about the filename

**Comment by 3lding** [comment]
Yes the limit is for the absolute file path
