### ISSUE TITLE
Renew SSL certificate for Froxlor Vhost

### ISSUE THREAD

**Issue by sorinpohontu** [Froxlor/Froxlor#1115]
# Summary

SSL Certificate for Froxlor VirtualHost is not renewed when `Domain aliases for froxlor vhost` is updated

# System information

* Froxlor version: 2.0.13
* Web server: apache2
* DNS server: none
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian 11

# Steps to reproduce

1. Settings > Froxlor VirtualHost settings: Modify `Domain aliases for froxlor vhost`

# Expected behavior

1. SSL certificate for Froxlor VirtualHost should be updated / renewed on next cronjob run
2. `froxloraliases` is processed in `lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php` and should add one or more `SAN entry`

# Actual behavior

1. SSL certificate for Froxlor VirtualHost it's not updated until it expires
3. Running `/usr/bin/php /var/www/html/froxlor/bin/froxlor-cli froxlor:cron letsencrypt --force --debug` has no effect on `domainid = 0`

**Comment by d00p** [comment]
Would it be possible for you to test the following patch whether it fixes the issue?

```diff
diff --git a/actions/admin/settings/122.froxlorvhost.php b/actions/admin/settings/122.froxlorvhost.php
index a361dc42..49963bcc 100644
--- a/actions/admin/settings/122.froxlorvhost.php
+++ b/actions/admin/settings/122.froxlorvhost.php
@@ -53,7 +53,7 @@ return [
                                        'string_regexp' => '/^(([a-z0-9\-\._]+, ?)*[a-z0-9\-\._]+)?$/i',
                                        'string_emptyallowed' => true,
                                        'default' => '',
-                                       'save_method' => 'storeSettingField',
+                                       'save_method' => 'storeSettingClearCertificates',
                                        'advanced_mode' => true
                                ],
                                /**
diff --git a/lib/Froxlor/Settings/Store.php b/lib/Froxlor/Settings/Store.php
index 8c949d79..e2e1f735 100644
--- a/lib/Froxlor/Settings/Store.php
+++ b/lib/Froxlor/Settings/Store.php
@@ -46,7 +46,16 @@ class Store
        {
                $returnvalue = self::storeSettingField($fieldname, $fielddata, $newfieldvalue);
 
-               if ($returnvalue !== false && is_array($fielddata) && isset($fielddata['settinggroup']) && $fielddata['settinggroup'] == 'system' && isset($fielddata['varname']) && $fielddata['varname'] == 'le_froxlor_enabled' && $newfieldvalue == '0') {
+               if ($returnvalue !== false
+                       && is_array($fielddata)
+                       && isset($fielddata['settinggroup'])
+                       && $fielddata['settinggroup'] == 'system'
+                       && isset($fielddata['varname'])
+                       && (
+                               ($fielddata['varname'] == 'le_froxlor_enabled' && $newfieldvalue == '0')
+                               || ($fielddata['varname'] == 'froxloraliases' && $newfieldvalue != $fielddata['value'])
+                       )
+               ) {
                        Database::query("
                                DELETE FROM `" . TABLE_PANEL_DOMAIN_SSL_SETTINGS . "` WHERE `domainid` = '0'
                        ");
```

**Comment by sorinpohontu** [comment]
Hello. Saving the settings is deleting the record from `domain_ssl_settings`, but cron doesn't t recreate the certificate.

`/usr/bin/php /var/www/html/froxlor/bin/froxlor-cli froxlor:cron letsencrypt --debug`

`Running "letsencrypt" job (debug)
[information] Checking for LetsEncrypt client upgrades before renewing certificates:
[Tue 21 Mar 2023 12:43:57 PM EET] Already uptodate!
[Tue 21 Mar 2023 12:43:57 PM EET] Upgrade success!
[Tue 21 Mar 2023 12:43:57 PM EET] Installing cron job
6 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
[Tue 21 Mar 2023 12:43:57 PM EET] Changed default CA to: https://acme-v02.api.letsencrypt.org/directory
[information] No new certificates or certificate updates found
[notice] Checking system's last guid`

**Comment by d00p** [comment]
okay thanks, I'll dig deeper :)
