### ISSUE TITLE
Sorting SSL certificates by issuer

### ISSUE THREAD

**Issue by datenfalke** [Froxlor/Froxlor#1116]
Sorting the SSL certificate list by column Issuer results in Uncaught exception

500 SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c.issuer' in 'order clause'

**System information**
* Froxlor version: 2.0.13

**To Reproduce**
1. Login as admin or as user
2. Go to Ressourcesn-> SSL-Zertifikate
3. Click one icon for sorting by issuer

**Additional context**
Tested on 5 different installation - all of them have been updated from version 0.10 some time ago.

**Comment by d00p** [comment]
Same "issue" as for `valid_from` and `valid_until` as these are all read from the certificate data directly they cannot be searched for or sorted

**Comment by d00p** [comment]
Yes we are currently talking about storing these "meta data" information to the table so they will be sortable/searchable
