### ISSUE TITLE
froxlor-2.0.15 database update missing results in errors reported by cron-jobs.

### ISSUE THREAD

**Issue by hknet** [Froxlor/Froxlor#1122]
after updating to froxlor-2.0.15 (using unattended-upgrades) lots of errors are reported (for hours resulting in 1k mails):

froxlor[7854]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'domssl.validfromdate' in 'field list'
froxlor[7854]: --- DEBUG: #0 [internal function]: PDO->query() #1 /var/www/html/froxlor/lib/Froxlor/Database/Database.php(597): call_user_func_array() #2 /var/www/html/froxlor/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php(311): Froxlor\Database\Database::__callStatic() #3 /var/www/html/froxlor/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php(81): Froxlor\Cron\Http\LetsEncrypt\AcmeSh::issueDomains() #4 /var/www/html/froxlor/lib/Froxlor/Cli/MasterCron.php(134): Froxlor\Cron\Http\LetsEncrypt\AcmeSh::run() #5 /var/www/html/froxlor/vendor/symfony/console/Command/Command.php(298): Froxlor\Cli\MasterCron->execute() #6 /var/www/html/froxlor/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run() #7 /var/www/html/froxlor/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand() #8 /var/www/html/froxlor/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun() #9 /var/www/html/froxlor/b
 in/froxlor-cli(64): Symfony\Component\Console\Application->run() #10 {main}

please add error-handling especially for upgrade-situations.

thx.

**Comment by d00p** [comment]
well froxlor (for years) always requires a login after update to process the database updates (if any).

**Comment by d00p** [comment]
You can of course do the update using `bin/froxlor-cli froxlor:update` with the `--yes-to-all` flag but it is intentionally not done via postinst in the apt package automatically

**Comment by d00p** [comment]
Do you have the setting "system.cron_allowautoupdate" activcated?

**Comment by hknet** [comment]
Hi
Agreed on the situation that a manual update via webfrontend is always required.
Yet it probably should not report db-errors due to the manual intervention missing every five minutes ;)
And no system.cron_allowautoupdate is not activated – in order to have a manual look at the process – just in case.

Also thank you for the –yes-to-all idea for the cli, which in the end would either need a unattended script or someone doing the manual update.
Yet via ssh this should work a lot faster than logging into all froxlor-systems using the web-frontend. Thx!

Kindest Regards
hk

**Comment by d00p** [comment]
> Yet via ssh this should work a lot faster than logging into all froxlor-systems using the web-frontend. Thx!

It's mainly for use with e.g. ansible automation etc. but sure, can also be run manually

So, found an issue, that the cron runs even with updates available - but even with the fix, you would receive emails telling you `It seems that the froxlor files have been updated. Please login and finish the update procedure.` - but it's more correct

**Comment by hknet** [comment]
Tried this:
/var/www/html/froxlor/bin/froxlor-cli froxlor:update --yes-to-all
It seems that the froxlor files have been updated. Please login and finish the update procedure.


But the cli does not update the database it seems and we need a web-frontend-login.

Thx
hk

**Comment by d00p** [comment]
its meant for the WHOLE update process (download, extract, update db), we might be able to enhance the updater-cli script to run only the db updates with a specific parameter
