### ISSUE TITLE
Cannot allow customer to use MySQL server if allowed_mysqlserver field is empty

### ISSUE THREAD

**Issue by lukasbableck** [Froxlor/Froxlor#1123]
**Describe the bug**
On a fresh installation allowed_mysqlserver is empty ('') for a new customer. If an update from some version earlier than 2.0.7 is performed this problem is fixed by the updater but not on a fresh installation of Froxlor 2.0.7 or higher.
If I want to enable "Allow use of this server to all currently existing customers" in the MySQL Server settings after creating the customer, it will fail with the following error message.
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/42083846/232729755-a9223d3e-7b93-4885-b8b0-49c6c14ed0c4.png">

**System information**
* Froxlor version: 2.0.15
* Web server: nginx
* FTP server: proftpd
* OS/Version: Debian 11

**To Reproduce**
1. Install Froxlor on a fresh system
2. Create customer
3. Enable "Allow use of this server to all currently existing customers" in MySQL Server settings

**Expected behavior**
It should add the server to allowed_mysqlserver just like it does if the field is not empty.

**Additional context**
Possible fixes:
Set allowed_mysqlserver nullable to have a default value of null which is already handled correctly 

or
 
/lib/Froxlor/Api/Commands/MysqlServer.php(520): $allowed_mysqls = json_decode(($customer['allowed_mysqlserver'] ?? '[]'), true) ?? [];
Probably also needs to be changed in other places.

**Comment by d00p** [comment]
Can you validate that the following patch solves the issue?

```diff
diff --git a/lib/Froxlor/Api/Commands/MysqlServer.php b/lib/Froxlor/Api/Commands/MysqlServer.php
index f44b45d1..c1fbbea2 100644
--- a/lib/Froxlor/Api/Commands/MysqlServer.php
+++ b/lib/Froxlor/Api/Commands/MysqlServer.php
@@ -516,7 +516,7 @@ class MysqlServer extends ApiCommand implements ResourceEntity
                        `allowed_mysqlserver` = :am WHERE `customerid` = :cid
                ");
                while ($customer = $sel_stmt->fetch(PDO::FETCH_ASSOC)) {
-                       $allowed_mysqls = json_decode(($customer['allowed_mysqlserver'] ?? '[]'), true);
+                       $allowed_mysqls = json_decode(($customer['allowed_mysqlserver'] ?: '[]'), true);
                        if (!in_array($dbserver, $allowed_mysqls)) {
                                $allowed_mysqls[] = $dbserver;
                                $allowed_mysqls = json_encode($allowed_mysqls);
```

**Comment by lukasbableck** [comment]
Yes, it does.
