### ISSUE TITLE
WebInstaller - improve 'Finish setup' tap

### ISSUE THREAD

**Issue by shoulders** [Froxlor/Froxlor#1128]
**Is your feature request related to a problem? Please describe.**
While completing the webinstaller section, on the `Finish setup` tab there is a message and it is not very obvious.

`Run the following command as root-user in your shell on this server:`

![one-last-step](https://user-images.githubusercontent.com/319997/233776446-d26cbbd2-e2ad-44c9-bdec-5ff8eb74e57c.jpg)

**Describe the solution you'd like**
* Can you move the message out of the grey box into the text section above and maybe put in red.
* Can you improve the text of the message to `Run the following command as the root user in the server's shell/terminal:`
  * I made the text read better, to me anyway
  * I removed the `-` from `root-user` as there is only a user called `root`. Some people might try and login with `root-user`.

**Describe alternatives you've considered**
n/a

**Additional context**
I am a windows person and a linux newbie. I can follow commands but sometimes things that are obvious for a Linux persons is not for me.

**Froxlor**
Version: 2.0.15-1
Database version: 202303150
Channel: stable

**Comment by d00p** [comment]
@shoulders nice that you put so much work into this, bit instead of opening one issue after the other, why not just join us on discord and discuss all your ideas
