### ISSUE TITLE
Add 'Run Me' button to crons

### ISSUE THREAD

**Issue by shoulders** [Froxlor/Froxlor#1129]
**Is your feature request related to a problem? Please describe.**
Ability to run a cron task manually by clicking a button

**Describe the solution you'd like**
Add a run now button to the cron page

![cron-job-button](https://user-images.githubusercontent.com/319997/233800228-5ab521aa-53cf-4ab1-a2fe-8670787eb698.jpg)

**Describe alternatives you've considered**
n/a

**Additional context**
Occasional you might need to run a cron manually. Admins and/or users might setup crons that are not automatic or are disabled and they like to run them manually such as updating Magentos product cache.

**Comment by d00p** [comment]
Crons need to be run as root, a "run me" would not work
