### ISSUE TITLE
ZeroSSL hostname cert generation fails, because it needs to different domains for domain and alt-domain

### ISSUE THREAD

**Issue by Linutux** [froxlor/Froxlor#1131]
# Summary

I switched from LetsEncrypt to ZeroSSL. Suddenly acme.sh could not renew my hostname cert, because of two matching domains in /root/acme.sh/web1.example.de/web1.example.de.conf: 

```
Le_Domain='web1.example.de'
Le_Alt='web1.example.de'
```

--

When you try to manually issue "/root/acme.sh/acme.sh --renew --domain web1.example.de --force", you get
`Create new order error. Le_OrderFinalize not found. {"type":"urn:ietf:params:acme:error:rejectedIdentifier","status":400,"detail":"One or more identifiers are duplicated"}`

# Solution
Change 
```
Le_Domain='web1.example.de'
Le_Alt='web1.example.de'
````

to 

```
Le_Domain='web1.example.de'
Le_Alt='www.web1.example.de'
````

in /root/acme.sh/web1.example.de/web1.example.de.conf

Also add the corresponding DNS entry fpr www.web1.example.de

**Comment by d00p** [comment]
I guess someone entered the same domain in the "domain aliases for froxlor vhost" setting
