### ISSUE TITLE
API call EmailAccounts.add doesnt work without optional argument email_quota

### ISSUE THREAD

**Issue by RickStinson** [Froxlor/Froxlor#1132]
When adding a Email Account without using the argument "email_quota", adding the mailaccount fails with "Sie versuchen "0" MB Kontingent zu zuweisen, haben aber nicht genug übrig.".

**System information**
* Froxlor version: 2.0.15-1
* Web server: apache2
* POP/IMAP server: Dovecot
* SMTP server: postfix
* OS/Version: Ubuntu 22.04 LTS
* PHP-FPM 8.2

**Reproduce:**
1.) Add an E-Mail Address via API ("Emails.add")
2.) Add an E-Mail Account via API:

`$data = [
        'loginname' => 'customerlogin',
        'emailaddr' => 'user@domain.tld',
        'email_password' => 'password',
        'sendinfomail' => 0 . uniqid()
];
$response = $fapi->request('EmailAccounts.add', $data)`

3.) Response:
`array(1) {
  ["message"]=>
  string(75) "Sie versuchen "0" MB Kontingent zu zuweisen, haben aber nicht genug übrig."
}`

Doing the same with "email_quota" works:
`$data = [
        'loginname' => 'customerlogin',
        'emailaddr' => 'user@domain.tld',
        'email_password' => 'password',
        'email_quota' => '5000',
        'sendinfomail' => 0 . uniqid()
];
$response = $fapi->request('EmailAccounts.add', $data)`

**Comment by d00p** [comment]
What exactly is that `'sendinfomail' => 0 . uniqid()` part doing? sendinfomail is boolean....

**Comment by d00p** [comment]
Can you validate that the following patch resolves this issue?

```diff
diff --git a/lib/Froxlor/Api/Commands/EmailAccounts.php b/lib/Froxlor/Api/Commands/EmailAccounts.php
index 0093f5bc..f341c880 100644
--- a/lib/Froxlor/Api/Commands/EmailAccounts.php
+++ b/lib/Froxlor/Api/Commands/EmailAccounts.php
@@ -63,7 +63,7 @@ class EmailAccounts extends ApiCommand implements ResourceEntity
         * @param string $alternative_email
         *            optional email address to send account information to, default is the account that is being created
         * @param int $email_quota
-        *            optional quota if enabled in MB, default 0
+        *            optional quota if enabled in MB, default setting: system.mail_quota
         * @param bool $sendinfomail
         *            optional, sends the welcome message to the new account (needed for creation, without the user won't
         *            be able to login before any mail is received), default 1 (true)
@@ -85,7 +85,7 @@ class EmailAccounts extends ApiCommand implements ResourceEntity
                        $emailaddr = $this->getParam('emailaddr', $ea_optional, '');
                        $email_password = $this->getParam('email_password');
                        $alternative_email = $this->getParam('alternative_email', true, '');
-                       $quota = $this->getParam('email_quota', true, 0);
+                       $quota = $this->getParam('email_quota', true, Settings::Get('system.mail_quota') ?? 0);
                        $sendinfomail = $this->getBoolParam('sendinfomail', true, 1);

                        // validation
```

**Comment by RickStinson** [comment]
Thanks, the patch worked!
