### ISSUE TITLE
More complex "Access-log format" for nginx is not properly saved

### ISSUE THREAD

**Issue by patschi** [Froxlor/Froxlor#1139]
**Describe the bug**

I have a more complex `log_format` for nginx in a json-format to make it easier to parse from external utilities. Currently I have implemented that change directly in the nginx.conf, as the UI doesn't allow the same:

When saving the "Access-log format", it simply truncates it:
![image](https://github.com/Froxlor/Froxlor/assets/2029878/c18b7103-0e20-4819-95f2-539515bc2272)

The full line:
```
escape=json '{"timestamp":"$time_iso8601","remote_addr":"$remote_addr","remote_user":"$remote_user","body_bytes_sent":$body_bytes_sent,"request_time":$request_time,"status":$status,"request":"$request","request_id":"$request_id","request_method":"$request_method","request_uri":"$request_uri","uri":"$uri","http_referrer":"$http_referer","x-forwarded-for":"$http_x_forwarded_for","hostname":"$host","server_name":"$server_name","upstream_addr":"$upstream_addr","upstream_status":"$upstream_status","upstream_response_time":"$upstream_response_time","upstream_response_length":"$upstream_response_length","upstream_cache_status":"$upstream_cache_status","ssl":"$https","ssl_protocol":"$ssl_protocol","ssl_cipher":"$ssl_cipher","ssl_session_reused":"$ssl_session_reused","gzip_ratio":"$gzip_ratio","request_body":"$request_body","sent_http_content_type":"$sent_http_content_type","http_user_agent":"$http_user_agent"}'
```

**System information**
* Froxlor version: 2.0.19
* Web server: nginx
* DNS server: None
* POP/IMAP server: None
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Ubuntu 22.04.2

**To Reproduce**
1. Change value
2. Click Apply

**Expected behavior**
Save the value

**Logfiles**
n/a

**Additional context**
n/a

**Comment by d00p** [comment]
Can you confirm when checking database and developer-console of the browser, the content actually gets stored to the database completely? And can you verify whether the configuration files are generated correctly?
