### ISSUE TITLE
Generic: Definition of supported PHP versions in e.g. the documentation

### ISSUE THREAD

**Issue by patschi** [Froxlor/Froxlor#1140]
**Is your feature request related to a problem? Please describe.**
This issue is more generic, and not specific to the code. As with other projects, I'm not able to find any clear statements (e.g. not in the documentation or in GitHub) which specific PHP Versions are supported.

Every PHP versions bring tons of changes and could break Froxlor anytime. I think there should be a official communication on which PHP version are supported and were successfully tested.

For example a definition that 0.19 supports up to 7.4, 2.0 GA up to PHP 8.1, 2.0.19 up to PHP 8.2, etc.

**Describe the solution you'd like**
Clear statements in documentation which PHP versions in which Froxlor versions are supported and tested.

**Describe alternatives you've considered**
Alternatively I just need to test and wait for errors to occur or not.

**Additional context**
n/a

**Comment by d00p** [comment]
Please open in https://github.com/Froxlor/Documentation
