### ISSUE TITLE
FR: Auto-expand menu in Froxlor 2

### ISSUE THREAD

**Issue by patschi** [Froxlor/Froxlor#1142]
**Is your feature request related to a problem? Please describe.**
On larger screens you can see the entire menu on Froxlor 2 at first glance. But with the current theme you need to always click on the category to go to the corresponding page.

As the menu isn't too large and save clicks, it would be handy - just as in Froxlor 0.9 - to have all options expanded by default.

**Describe the solution you'd like**
A option to have the entire menu expanded by default, without clicking on it every time:
![image](https://github.com/Froxlor/Froxlor/assets/2029878/5ad44afb-b207-4741-9b18-ada2706adbda)

**Describe alternatives you've considered**
Alternatively custom code change, but trying to avoid differentiating from main Froxlor code.

**Additional context**
n/a

**Comment by d00p** [comment]
added setting to have menu expanded in 13b6ab0b074109d5dace8e753488a7e6107a47b5
