### ISSUE TITLE
FR: Remember search/sorting settings on various pages

### ISSUE THREAD

**Issue by patschi** [Froxlor/Froxlor#1143]
**Is your feature request related to a problem? Please describe.**
When going to e.g. Domains, making a specific filter and sorting, editing a domain and saving the same will redirect you back to the Domains page. This makes sense. However, all the filter and sorting settings are gone and not remembered.

**Describe the solution you'd like**
It would be very convenient that those settings are remembered. Maybe even persisted in e.g. localStorage/cookies or in account settings for most convenience. 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by d00p** [comment]
refs #1063

**Comment by patschi** [comment]
Oh, indeed - sorry for the duplicate!
