### ISSUE TITLE
FR: Show more details on Databases and FTP

### ISSUE THREAD

**Issue by patschi** [Froxlor/Froxlor#1147]
**Is your feature request related to a problem? Please describe.**
While I don't have customers - when clicking on "Databases" or "FTP" to manage/see the respective accounts, it's not clear what the specific hostname is which is supposed to be used. 

**Describe the solution you'd like**
It would be convenient from a user-perspective to see on those pages the Hostname/IP to be used to connect to the MySQL database or FTP server. Maybe just briefly shown above the table, or when viewing/editing a specific entry.

Possibly the Froxlor hostname can be re-used to gather the data. The port could be hard-coded.

**Comment by d00p** [comment]
added links to user-guide documentation in 13b6ab0b074109d5dace8e753488a7e6107a47b5
