### ISSUE TITLE
Improve default proftpd configuration template

### ISSUE THREAD

**Issue by patschi** [Froxlor/Froxlor#1148]
Using Ubuntu 22.04.2 with default proftpd.
When generating the configuration, the default is:

tls.conf:
```
TLSProtocol                             TLSv1 TLSv1.1 TLSv1.2
[...]
TLSOptions                              NoCertRequest NoSessionReuseRequired
```

Also in proftpd logs following can be seen:
```
May 26 20:20:20 froxlor proftpd[135232]: 2023-05-26 20:20:20,436 froxlor proftpd[135232]: mod_tls/2.9: NoCertRequest TLSOption is deprecated
```

So I'd propose three changes:
1. TLSv1 and TLSv1.1 is known to be insecure by now, so should be removed.
2. Adding TLSv1.3 to the list and only using `TLSv1.2 TLSv1.3`
3. Remove `NoCertRequest` as it has been deprecated by proftpd

I'm not sure if it's worth to enable TLS encryption by default. especially in these days:
```
TLSRequired                             on
```

**Comment by patschi** [comment]
Possibly, it would also make sense to prevent bruteforce attacks by adding something like this by default:
```
<Class whitelist>
From 127.0.0.1
</Class>

MaxLoginAttempts 3
<IfModule mod_ban.c>
 <IfClass whitelist>
  BanEngine off
 </IfClass>
 <IfClass !whitelist>
  BanEngine on
 </IfClass>
BanLog /var/log/proftpd/ban.log
BanTable /etc/proftpd/ban.tab
BanMessage "User %u was banned."
BanOnEvent ClientConnectRate 5/00:00:02 12:00:00 "Stop connecting frequently"
BanOnEvent MaxLoginAttempts 3/00:30:00 12:00:00
BanOnEvent AnonRejectPasswords 1/01:00:00 99:99:99
BanControlsACLs all allow user root
</IfModule>

<IfClass whitelist>
BanEngine off
DelayEngine off
</IfClass>
```

**Comment by d00p** [comment]
You did see this is closed? It's been fixed for coming versions
