### ISSUE TITLE
Using 0 as number causes field to be empty

### ISSUE THREAD

**Issue by patschi** [Froxlor/Froxlor#1149]
**Describe the bug**
When creating a customer and setting any value (like number of domains, customers, email accounts, etc) to `0`, the fields will be empty after saving and editing again:
![image](https://github.com/Froxlor/Froxlor/assets/2029878/0cdcd4c6-6cec-4987-a5e3-b026f63dacfc)

When saving again, it fails as those fields are empty:
![image](https://github.com/Froxlor/Froxlor/assets/2029878/5668b4c9-6ff3-47d7-ad46-2b2586240940)

**System information**
* Froxlor version: 2.0.19
* Web server: nginx

**To Reproduce**
As explained above.

**Comment by d00p** [comment]
Customer is fine, it's when creating/editing admin/reseller user
