### ISSUE TITLE
Missing progressbar for "String interning" on opcache info page

### ISSUE THREAD

**Issue by patschi** [Froxlor/Froxlor#1151]
**Describe the bug**
There's a fancy new opcache information page in Froxlor. When viewing something is obvious: The internal strings metric doesn't have any progressbar, while others do.

I'm not sure if it is a bug (as in it was missed to implemented), but there's the progressbar missing:
![image](https://github.com/Froxlor/Froxlor/assets/2029878/f2723bfc-f9dd-4da8-bc1c-3cda9e9185c6)

The metrics are using MB, so it should be easily be presentable in a progressbar.

**System information**
* Froxlor version: 2.0.19
* Web server: nginx

**Expected behavior**
Seeing a progressbar.

**Comment by d00p** [comment]
the opcache info pages is based off of https://github.com/amnuts/opcache-gui/blob/v2.4.1/index.php and there was no progressbawr for string interning - there is a newer version which seems to have been rewritten so we might adapt / integrate this for froxlor-2.1

**Comment by d00p** [comment]
Not a bug, intended as it's based on amnuts/opcache-gui
