### ISSUE TITLE
Feature request:  .Net Core and MSSQL support

### ISSUE THREAD

**Issue by uzeyir06** [Froxlor/Froxlor#1160]
Good job

Thank you for sharing your thoughts. I understand that dealing with .NET Core reverse proxies and setting up websites or APIs can be challenging, especially on Linux. Simplifying this process and adding support to a panel would indeed be beneficial and well-received by many. It could potentially make a significant impact.

Regarding hosting on Windows and the associated costs of Plesk and Windows licenses, as well as the resource consumption and performance issues on Windows, I understand that these factors are important considerations for you.

Simplifying the deployment and management of web applications and APIs on Linux, along with providing efficient resource utilization and improved performance, can certainly be advantageous. This is a valuable insight, and I appreciate you bringing it up.

**Comment by d00p** [comment]
hosting on windows is not supported, it's not our goal
