### ISSUE TITLE
Loading Speed of Customers List is very slow

### ISSUE THREAD

**Issue by robincle** [Froxlor/Froxlor#1161]
**Describe the bug**
If i request the list of all customers (/admin_customers.php?page=customers) as an administrator, the page needs a long time to load all the customers (amount of 36). The Chrome Network screen tells me that the following metrics are given: 13 requests, 1.1MB transferred, Finish 13.85s, DOMContentLoaded: 7.56s, Load 7.61s. The initial request (admin_customers.php) needs 7.15s.

Every other list in the froxlor setup is loading very fast.

**System information**
* Froxlor version: 2.0.21
* Web server: nginx 1.18.0
* DNS server: not activated/in use
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Ubuntu 22.04.2 LTS

**To Reproduce**
See above

**Expected behavior**
The list should be loaded much quicker.

**Logfiles**
No errors found in error log.

**Additional context**
-

**Comment by d00p** [comment]
Just added 40 customers to our demo with different values for web and traffic usage and the response takes about 1,5seconds
