### ISSUE TITLE
Privacy Unfriendly third-party integrations on website & communication tools

### ISSUE THREAD

**Issue by Lukas2112** [Froxlor/Froxlor#1166]
**Is your feature request related to a problem? Please describe.**
Privacy Unfriendly third-party integrations on website & communication tools. 

**Describe the solution you'd like**
The third-party sources are removed and Discord is replaced by a more data protection-friendly tool (MAtrix, XMPP, Mattermost etc.).

**Describe alternatives you've considered**
None

**Additional context**

**Comment by d00p** [comment]
You are not forced to use Discord - and no we most likely won't change to any other communication/community plattform anytime soon.
And please enlighten me, which of the cdns is not privacy "friendly"?

**Comment by d00p** [comment]
No reply
