### ISSUE TITLE
WebInstaller crashes

### ISSUE THREAD

**Issue by froxlorBear** [Froxlor/Froxlor#1167]
**Describe the bug**
The Webinstaller get "stuck" at the database setup.
It never goes beyond.

**System information**
* Froxlor version: 2.0.21-1
* Web server: apache2
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian 12

**To Reproduce**

**Expected behavior**
installing froxlor :)

**Logfiles**
Here are the mysql-Logs:
230802 19:24:28     33 Connect  froxroot@localhost on  using Socket
                    33 Query    SHOW DATABASES LIKE 'froxlor'
                    33 Query    CREATE DATABASE IF NOT EXISTS froxlor_tmp_64ca914c8d5b4
                    33 Query    DROP DATABASE IF EXISTS froxlor_tmp_64ca914c8d5b4
                    33 Query    SELECT `User` FROM `mysql`.`user` WHERE `User` = 'froxlor'
                    33 Query    CREATE USER 'froxlor_tmp_64ca914c8f627'@'localhost' IDENTIFIED BY '64ca914c8f62c'
                    33 Query    DROP USER 'froxlor_tmp_64ca914c8f627'@'localhost'
                    33 Query    FLUSH PRIVILEGES
                    33 Quit     

That is all. 

**Additional context**

**Comment by d00p** [comment]
Just clicked through an installation on a fresh debian 12 - works just fine. For support/help please join us on discord
