### ISSUE TITLE
Exception on mail account password update

### ISSUE THREAD

**Issue by hgassen** [Froxlor/Froxlor#1172]
**As a rule of thumb: before reporting an issue**
* see if it hasn't been [reported](https://github.com/Froxlor/froxlor/issues) (and possibly already been [fixed](https://github.com/Froxlor/froxlor/issues?utf8=✓&q=is:issue%20is:closed)) first
* try with the git master

**Describe the bug**

**System information**
* Froxlor version:2.0.21
* Web server: apache2
* DNS server: keiner
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian Bookworm

**To Reproduce**

- As user, go to Email -> Adressen
- Edit an existing address
- Click on Konto -> Passwort ändern
- Enter a new password that passes validation
- See error:

Uncaught exception0 Undefined constant "Froxlor\Api\Commands\PASSWORD_ARGON2I"
#0 /var/www/froxlor/customer_email.php(389): Froxlor\Api\Commands\EmailAccounts->update()
#1 {main}"

**Expected behavior**
Confirmation of pw update

**Comment by d00p** [comment]
`PASSWORD_ARGON2I` is available since php7.2 and froxlor requires 7.4, see https://www.php.net/manual/en/password.constants.php. I was not able to reproduce this on the demo (which is also debian 12)

**Comment by hgassen** [comment]
I tested with a custom PHP version that was compiled without --with-password-argon2. It works with the default PHP version. Thank you.
