### ISSUE TITLE
api / change subDomain path issues

### ISSUE THREAD

**Issue by RickStinson** [Froxlor/Froxlor#1173]
**Describe the bug**
when changing the documentroot in a subdomain via API, froxlor saves a wrong path.

**System information**
* Froxlor version: 2.0.21-1
* Web server: apache2

**To Reproduce**
- Set a Path for a SubDomain in the froxlor frontend, eg /bla.test.tld/
- Check the docroot via API (=everything fine): 
  ["documentroot"]=>
  string(79) "/bla.test.tld/"
-> Works!

-  set a new docroot via API
data = ['loginname'  => $loginname, 'domainname' => $domainname, 'documentroot' => '/somethingelse/' ];
$response = $fapi->request('SubDomains.update',$data);

- get the docroot via API:
["documentroot"]=>
    string(79) "/var/customers/webs/cust1/var/customers/webs/cust1/somethingelse/"

-  set a new docroot via API again
data = ['loginname'  => $loginname, 'domainname' => $domainname, 'documentroot' => '/somethingelse/' ];
$response = $fapi->request('SubDomains.update',$data);

- get the docroot via API:
["documentroot"]=>
    string(79) "/var/customers/webs/cust1/var/customers/webs/cust1/var/customers/webs/cust1/somethingelse/"

Seems to be an issue in the API.

**Comment by d00p** [comment]
Do you call the method as *admin* or as *customer* user?

**Comment by d00p** [comment]
Ah, well, you are using the wrong parameter, it's not `documentroot`, the parameter you want is called: `path`, see https://docs.froxlor.org/latest/api-guide/commands/subdomains.html#subdomains-update
