### ISSUE TITLE
after update from 0.1.38 to froxlor 2 some emails don't work

### ISSUE THREAD

**Issue by rubo77** [Froxlor/Froxlor#1174]
The update seemed to have run fine at first, but now some IMAP email accounts don't work any more.

The same password as before don't work any more.

Only sending from those accounts works a bit, but the sent email cannot be copied into the sent folder.

**System information**
* Froxlor version: 2
* Web server: nginx
* POP/IMAP server: Courier
* SMTP server: postfix
* OS/Version: Debian 10

**Comment by d00p** [comment]
Please see https://docs.froxlor.org/latest/general/migration-guide.html
And also use Discord or the forum for support
