### ISSUE TITLE
open subfolder navigation 

### ISSUE THREAD

**Issue by rubo77** [Froxlor/Froxlor#1176]
When right-clicking on a navigation menu item "open in new tab" there is added a part in the url after the hash like `#sub0`, but this is not used in the javascript.

The new page should open with the menu 0 opened already initially in that case

**Comment by d00p** [comment]
it is used in the javascript - it's bootstrap's toggle identifier... `data-bs-toggle="collapse" data-bs-target="#sub0"`.

Pull-requests to enhance the navigation are welcomed if you want to do it

**Comment by d00p** [comment]
Works just fine for menu entries pointing to a specific site. It is not intended that menu-categories are open/shown when opened in a new tab.

As said, pull-requests are welcomed, but until then: works as inteded
