### ISSUE TITLE
error during installation in red

### ISSUE THREAD

**Issue by rubo77** [Froxlor/Froxlor#1179]
When you add your credentials to access the db, and the database already exixst, the error message is very unobstrusive.

I needed some time to find out, whats wrong.

Better show an error in red

**Comment by d00p** [comment]
So. What's the exact error message? Maybe provide some more info, like OS, php version, webserver, etc....not very helpful this way

**Comment by d00p** [comment]
error was 
`SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'froxroot'@'localhost' to database 'froxlor'`

No froxlor bug

**Comment by rubo77** [comment]
The message was 

> 'Datenbank existiert bereits, Uberschreiben-Option oder anderen Namen wählen.'

But I guess, that it already would be in red if the stylesheet was loaded, I forgot to run 

    npm install
    npm run build

So the initial installation was without stylesheet and the message hat the same font like the rest of the text.

**Comment by envoyr** [comment]
So you can confirm that it's red/blue/green/whatever now? That would be more helpful :)

**Comment by d00p** [comment]
> So the initial installation was without stylesheet and the message hat the same font like the rest of the text.

Not in prebuilt releases. If you you want to use git/source then please follow https://docs.froxlor.org/latest/general/installation/source.html

So still: not a bug, we've discussed that on discord already
