### ISSUE TITLE
Nginx Location /{ not work

### ISSUE THREAD

**Issue by drexlma** [Froxlor/Froxlor#1185]
[        $vhost = preg_replace("/^(\s+)location(.+)\{(.+)\}$/misU", "location $2 {\n $3 \n}", $vhost);](https://github.com/Froxlor/Froxlor/blob/main/lib/Froxlor/Cron/Http/Nginx.php#L886)

Nach der Änderung der letzten version dieser Zeile funktioniert der location /{ xxx} Eintrag nicht mehr. Nur noch wenn ein Leerzeichen zwischen / und { ist.

das müsste das der Grund sein. https://github.com/Froxlor/Froxlor/compare/2.0.21...2.0.23#diff-dc8225dcb1b695c0419c8b3603474f839ceab27a7cfc276abc31b15c3ba1c3c2R886

**Comment by d00p** [comment]
Was heisst denn "funktioniert nicht", bitte Fehlermeldungen mitgeben, wo du was genau eingetragen hast etc.pp.

**Comment by drexlma** [comment]
naja du fügst dann den location pfad. bei nginx hinzu

Fehlermeldung: nginx: [emerg] duplicate location "/"

**Comment by d00p** [comment]
gib doch mal bitte genau an welche inhalte du in welche felder schreibst....oder sprich mit uns via Discord, dann braucht man sowas nicht immer in github zu diskutieren

**Comment by d00p** [comment]
liegt nicht am `/{` sondern am regex der führende leerzeichen erwartet vor location, das hier sollte funktionieren:

```diff
diff --git a/lib/Froxlor/Cron/Http/Nginx.php b/lib/Froxlor/Cron/Http/Nginx.php
index c0cf4749..33d80e86 100644
--- a/lib/Froxlor/Cron/Http/Nginx.php
+++ b/lib/Froxlor/Cron/Http/Nginx.php
@@ -883,7 +883,7 @@ class Nginx extends HttpConfigBase
                // remove comments
                $vhost = implode("\n", preg_replace('/^(\s+)?#(.*)$/', '', explode("\n", $vhost)));
                // Break blocks into lines
-               $vhost = preg_replace("/^(\s+)location(.+)\{(.+)\}$/misU", "location $2 {\n $3 \n}", $vhost);
+               $vhost = preg_replace("/^(\s+)?location(.+)\{(.+)\}$/misU", "location $2 {\n $3 \n}", $vhost);
                // Break into array items
                $vhost = explode("\n", preg_replace('/[ \t]+/', ' ', trim(preg_replace('/\t+/', '', $vhost))));
                // Remove empty lines
```
