### ISSUE TITLE
LE Zertifikat des Hosts für Dienste verwenden

### ISSUE THREAD

**Issue by lonesomewalker** [froxlor/Froxlor#1186]
**Is your feature request related to a problem? Please describe.**
Da es ja quasi schon zum guten Ton gehört, alle Dienste mit entsprechendem Zertifikat abzusichern, wäre es doch auch gut, wenn man bestehende, gültige Zertifikate verwendet, anstelle dem Dummy-Zertifikat.

**Describe the solution you'd like**
Unter /root/.acme.sh/ liegen die nötigen Files schon, man muß die nur noch:
a) verlinken
b) in die Diensteordner wegkopieren (das machen wir mittlerweile, weniger fehleranfällig, weniger Berechtigungsprobleme)
Dann müssen in den configs der Dienste entsprechend auch die Zertifikate/Fullchains angegeben werden.

**Additional context**
Zu berücksichtigen wäre Postfix, Dovecot und FTP. Ja, ich habe gesehen, es gibt auch exim und courier. Aber da geht das auch analog.

**Comment by hknet** [comment]
Hallo, bitte gerne auch dafür :)
Aktuell lösen wir das mit einer Krücke:

postfix - main.cf:
smtpd_tls_cert_file = /etc/ssl/froxlor-custom/hostname.crt
smtpd_tls_key_file = /etc/ssl/froxlor-custom/hostname.key
smtpd_tls_CAfile = /etc/ssl/froxlor-custom/hostname_CA.pem

dovecot - conf.d/10-ssl.conf:
ssl_cert = </etc/ssl/froxlor-custom/hostname_fullchain.pem
ssl_key = </etc/ssl/froxlor-custom/hostname.key

proftpd - tls.conf:
TLSRSACertificateFile                   /etc/ssl/froxlor-custom/hostname.crt
TLSRSACertificateKeyFile                /etc/ssl/froxlor-custom/hostname.key
TLSCACertificateFile                    /etc/ssl/froxlor-custom/hostname_chain.pem

Aber freilich - wenn das Zertifikat aktualisiert wird, dann wissen die drei Dienste davon wenig - daher läuft ein täglicher cronjob, der schaut ob sich das Zertifikat verändert hat und wenn ja, dann einen reload der Dienste auslöst; nicht perfekt - aber "gets the job done".
