### ISSUE TITLE
Integration von rspamd

### ISSUE THREAD

**Issue by lonesomewalker** [Froxlor/Froxlor#1187]
**Is your feature request related to a problem? Please describe.**
Spam ist ja schon immer ärgerlich gewesen, aber dank rspamd hat man anstelle spamassassin auch eine weitere gute Alternative.

**Describe the solution you'd like**
Im Forum hat bereits jemand einen Thread eröffnet dazu und einen quick-and-dirty Hack veröffentlicht.
Funktioniert, wäre aber schön, da was "Offizielles" zu haben, das nicht immer ein Patchen benötigt.

**Comment by d00p** [comment]
in current `main` (upcoming 2.2), testers are welcome
