### ISSUE TITLE
Customer overview page often does not respond in appropriate time

### ISSUE THREAD

**Issue by MarkusKepert** [Froxlor/Froxlor#1190]
**As a rule of thumb: before reporting an issue**
* see if it hasn't been [reported](https://github.com/Froxlor/froxlor/issues) (and possibly already been [fixed](https://github.com/Froxlor/froxlor/issues?utf8=✓&q=is:issue%20is:closed)) first
* try with the git master

**Describe the bug**
When logging in and navigating to admin_customers.php?page=customers, the PHP pool went to 100% CPU and the page isn`t loading. Since Version 2.0.21 it runs into HTTP error 503 with browser message and since update to 2.0.23 is shows blank screen.
Manually changing adress to index page shows a working froxlor. All other pages of froxlor works fine as well.
Trying the request multiple times sometimes lead to working  customer page

**System information**
* Froxlor version: 2.0.23
* Web server: apache2 2.4.38 php-fpm
* DNS server: none
* POP/IMAP Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian

**To Reproduce**
1. Login (with main admin user, 2FA enabled)
2. Go to Ressources->Customers
3.  drink some coffee
4. get new coffee
5. see....nothing

**Expected behavior**
see customer overview page :)

**Logfiles**
PHP error shows  AH01071: Got error 'PHP message: PHP Fatal error:  Maximum execution time of 60 seconds exceeded in /var/www/html/froxlor/vendor/twig/twig/src/Environment.php on line 766'

**Comment by d00p** [comment]
Refs #1161 , most likely fixed in https://github.com/Froxlor/Froxlor/commit/41ac71332544169fc17c25493e059931e353b42a (upcoming 2.1.x)
