### ISSUE TITLE
Redis support

### ISSUE THREAD

**Issue by xbh03** [Froxlor/Froxlor#1193]
**Is your feature request related to a problem? Please describe.**
I would like to use the Redis database in the applications of my customers.
I would like to install that without taking effect on MySQL actually used by default.

**Describe the solution you'd like**
Some configurations of Redis in the froxlor admin settings, like enabling it, installing that, and permitting to manage Redis databases directly in the user interface (froxlor customers)

**Describe alternatives you've considered**
Nothing, maintaining MySQL.
I would like to add Redis and not remove MySQL, but maintain all two alternatives for more flexibility.

**Additional context**
Using Redis can improve the application's performance for my customers and permit them to install new applications.

**Comment by d00p** [comment]
> I would like to use the Redis database in the applications of my customers.

Although it is technically possible to use redis as a "database" its mainly a key:value storage and no relational database management system. I think you mean you want to use it as cache-possibility for customers?

> I would like to install that without taking effect on MySQL actually used by default.

Can you elaborate? 

> I would like to add Redis and not remove MySQL, but maintain all two alternatives for more flexibility.

You can this already...just run `apt install redis-server` ... it's not removing mysql....

**Comment by d00p** [comment]
stale , no feedback. close.
