### ISSUE TITLE
Wrong host address for the froxlor DB user

### ISSUE THREAD

**Issue by Pacerino** [Froxlor/Froxlor#1194]
**Describe the bug**
Installation uses wrong ip address for the unprivileged user.

**System information**
* Froxlor version: 2.0.24
* OS/Version: Debian 12 Bookworm

**To Reproduce**
1. Install Froxlor
2. Open the Setup
3. Input Different IP into the MySql Host
4. Go forward
5. Getting error that the user "froxlor" dont have access to the DB

**Expected behavior**
That the installation completes

**Additional context**
I've created a new froxroot user. I can see that Froxlor is crearting the froxlor DB user with the IP Address of the DB as the "Host".
IP from Froxlor: 192.168.40.103
IP from DB: 192.168.40.102
Froxlor User allowed from: 192.168.40.102 <- There should be the .103 address
![grafik](https://github.com/Froxlor/Froxlor/assets/22194063/7f4d70c5-2fbd-42c3-8707-e157f0f55bc5)

**Comment by d00p** [comment]
Well can you tell me where the ip `192.168.1.12` comes from if 103 is your froxlor and 102 your database?
The installation process uses all given mysql-host values, localhost, 127.0.0.1 and the specified server ipv4 and ipv6 addresses to create the unprivileged database user. So there should definetly be more than one entry for the 'froxlor' user

**Comment by Pacerino** [comment]
I’m sorry, of course there should be the 192.168.40.102 which froxlor used as the host address.

Am 30.10.2023 um 16:56 schrieb Michael Kaufmann ***@***.***>:

﻿

Well can you tell me where the ip 192.168.1.12 comes from if 103 is your froxlor and 102 your database?
The installation process uses all given mysql-host values, localhost, 127.0.0.1 and the specified server ipv4 and ipv6 addresses to create the unprivileged database user. So there should definetly be more than one entry for the 'froxlor' user

**Comment by discordier** [comment]
Now it is 192.168.**40**.102?
We now have:
- 192.168.1.103
- 192.168.1.102
- 192.168.1.12
- 192.168.40.102

I also fail to see why this should be two different IPs, as the IP is the remote IP (aka Server IP connecting to) and in MySQL it is the source IP (aka client connecting from).

@Pacerino please elaborate on your setup.

**Comment by d00p** [comment]
> 192.168.40.102 is the DB
192.168.40.103 is the Froxlor Installation
froxroot has 192.168.40.103 as the allowed host
froxlor gets 192.168.40.102 from froxlor installation setup.

Please check your mysql-Database, the installer should create the following user@host combinations for the `froxlor` user:

- froxlor@localhost
- froxlor@127.0.0.1
- froxlor@192.168.40.102
- froxlor@192.168.40.103

**Comment by Pacerino** [comment]
Checked again and only the `froxlor@192.168.40.102` is getting created.
I'm running a freshly installed MariaDB on the 102 Server and a freshly created server for froxlor on 103.

Meanwhile we switched to HestiaCP. I dont know if you still want to investigate this issue or close it?

**Comment by d00p** [comment]
as we've successfully tested using external database-servers, I do not know what is wrong in your case; and as you've already switched to another panel, I'll close this.
