### ISSUE TITLE
task fails on rebuilding DNS, wrong return type of getMainSubdomainIds

### ISSUE THREAD

**Issue by mameier** [Froxlor/Froxlor#1202]
**Describe the bug**
After upgrade to froxlor 2.1.0-1 on bookworm, changing a domain resulted in this error during the cron task:

> PHP Fatal error:  Uncaught TypeError: Froxlor\Domain\Domain::getMainSubdomainIds(): Return value must be of type array, int returned in /var/www/html/froxlor/lib/Froxlor/Domain/Domain.php:261

**System information**
* Froxlor version: 2.1.0-1
* Web server: apache2
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: bookworm

**Cause**

The new function getMainSubdomainIds is expected to return an array of ids.  
Line 259 replaces the array by an integer, so an integer is returned

    public static function getMainSubdomainIds(int $id): array
	{
		$result_stmt = Database::prepare("
			SELECT id
			FROM `" . TABLE_PANEL_DOMAINS . "`
			WHERE
			isbinddomain = 1 AND
			domain LIKE CONCAT('%.', ( SELECT d.domain FROM `" . TABLE_PANEL_DOMAINS . "` AS d WHERE d.id = :id ))
		");
		Database::pexecute($result_stmt, [
			'id' => $id
		]);
		$result = [];
		while ($entry = $result_stmt->fetch(PDO::FETCH_ASSOC)) {
			$result = $entry['id']; // $result is replaced instead of extended
		}
		return $result;
	}

**Patch**

Just fix line 259 from 

    $result = $entry['id'];

to 

    $result[] = $entry['id];

**Comment by d00p** [comment]
Yup, just got that reported from a user on Discord, confirmed. Patch:

```diff
diff --git a/lib/Froxlor/Domain/Domain.php b/lib/Froxlor/Domain/Domain.php
index 82616d37..d919f8d5 100644
--- a/lib/Froxlor/Domain/Domain.php
+++ b/lib/Froxlor/Domain/Domain.php
@@ -256,7 +256,7 @@ class Domain
                ]);
                $result = [];
                while ($entry = $result_stmt->fetch(PDO::FETCH_ASSOC)) {
-                       $result = $entry['id'];
+                       $result[] = $entry['id'];
                }
                return $result;
        }
```

Bugfix release will follow this weekend. Thanks for reporting.

**Comment by mameier** [comment]
Das soll Dir erst einmal einer nach machen: Issue innerhalb von einer Minute zu korrigieren und nach 4 Minuten zu schließen ;-)
Vielen Dank
