### ISSUE TITLE
Can this control panel achieve scheduled synchronization of multiple sites?

### ISSUE THREAD

**Issue by shun556618** [Froxlor/Froxlor#1204]
For example: After publishing content in server A, server B synchronizes the content being published by server A. The main purpose is to achieve regular content synchronization between sites.

Excuse me, can this control panel realize the timing synchronization of multiple sites?
For example, after publishing content in server A, server B synchronizes the content published in server A.. Mainly want to realize the content synchronization between sites.

**Comment by d00p** [comment]
No, but I'm sure there are plenty of synchronization tools or other ways to achieve what you intend to do
