### ISSUE TITLE
Froxlor web interface not accessible after upgrade to 2.1: "Domain not configured"

### ISSUE THREAD

**Issue by chrschn** [Froxlor/Froxlor#1205]
Since Froxlor was upgraded on my Debian bullseye server from version 2.0.24-1 to 2.1.0-1 and meanwhile 2.1.1-1, the admin interface of Froxlor is not accessible anymore. I'm getting redirected to the `Domain not configured` page. The redirect happens when I open `my-domain.de/froxlor/`. I can access `my-domain.de` just fine.

My setup is as follows. `my-domain.de` is configured in Froxlor and assigned to a customer. For that domain, I configured an Alias for Apache in the Froxlor domain settings:
```
Alias /froxlor "/var/www/html/froxlor"
```

I verified that the domain has a proper customer ID set using the CLI:
```
$ /var/www/html/froxlor/bin/froxlor-cli froxlor:api-call admin Domains.get '{"domainname":"my-domain.de"}'
{
    "data": {
        "id": "3",
        "domain": "my-domain.de",
        "domain_ace": "my-domain.de",
        "adminid": "1",
        "customerid": "1",
        "aliasdomain": null,
        "documentroot": "/var/customers/webs/my-user/my-domain/",
        "wwwserveralias": "1",
        "parentdomainid": "0",
        "ssl_redirect": "1",
        "specialsettings": "Alias /froxlor \"/var/www/html/froxlor\"",
        "ssl_specialsettings": "php_admin_value open_basedir \"/var/www:/tmp:/var/lib/roundcube/:/var/log/roundcube/:/usr/share/roundcube/:/etc/roundcube/:/usr/share/php/\"\nAlias /roundcube /var/lib/roundcube/public_html",
        "include_specialsettings": "1",
        "deactivated": "0",
        ....
}  
```

I read the [v2.1 release notes](https://bit.ly/rls2100) and [migration guide](https://docs.froxlor.org/v2.1/general/migration-guide/2.1.html), but they didn't cover the issue I'm seeing.

**System information**
* Froxlor version: 2.1.1-1
* Web server: apache2
* OS/Version: Debian bullseye

**Logfiles**
There is no additional information in the Apache logs.

**Additional Context**
One thing thing I obsoerved, which may or may not be related to this issue: When Froxlor was initially upgraded from 2.0.24-1 to 2.1.0-1, the `letsencrypt` cron job failed once, see stack trace below. I don't know if that was just a transient error during the upgrade or if it points to different issue.
```
/usr/bin/php -q /var/www/html/froxlor/bin/froxlor-cli froxlor:cron 'letsencrypt' -q 1> /dev/null

froxlor[1222417]: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP COLUMN `ismainbutsubto`; check that it exists
froxlor[1222417]: --- DEBUG: 
#0 [internal function]: PDO->query() 
#1 /var/www/html/froxlor/lib/Froxlor/Database/Database.php(597): call_user_func_array() 
#2 /var/www/html/froxlor/install/updates/froxlor/update_2.1.inc.php(41): Froxlor\Database\Database::__callStatic() 
#3 /var/www/html/froxlor/install/updatesql.php(57): include_once('/var/www/html/f...') 
#4 /var/www/html/froxlor/lib/Froxlor/Cli/CliCommand.php(129): include_once('/var/www/html/f...') 
#5 /var/www/html/froxlor/lib/Froxlor/Cli/CliCommand.php(55): Froxlor\Cli\CliCommand->runUpdate() 
#6 /var/www/html/froxlor/lib/Froxlor/Cli/MasterCron.php(66): Froxlor\Cli\CliCommand->validateRequirements() 
#7 /var/www/html/froxlor/vendor/symfony/console/Command/Command.php(298): Froxlor\Cli\MasterCron->execute() 
#8 /var/www/html/froxlor/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run() 
#9 /var/www/html/froxlor/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand() 
#10 /var/www/html/froxlor/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun() 
#11 /var/www/html/froxlor/bin/froxlor-cli(71): Symfony\Component\Console\Application->run() #12 {main}
```

**Comment by d00p** [comment]
1) __Domain not configured__:

Dont use a customer-domain for froxlor or use an alias, that's not how it is intended. It will use the wrong permissions. See also  https://forum.froxlor.org/index.php?/topic/20176-froxlor-21-domain-not-configured/

2) __letsencrypt and sql error__

That most likey happened during the update, best way to avoid this would be to stop the cron temporarily during an update

**Comment by chrschn** [comment]
Thanks for the super fast response!

> 1. **Domain not configured**:
> 
> 
> Dont use a customer-domain for froxlor or use an alias, that's not how it is intended. It will use the wrong permissions. See also https://forum.froxlor.org/index.php?/topic/20176-froxlor-21-domain-not-configured/

Alright, here is how I recovered my system:
1. Accessed the web interface through `randomhostname.my-hoster.com`
2. Deleted `my-domain.de` from the customer domains
3. Set `my-domain.de` in the _Froxlor VirtualHost settings_
4. Added the vhost custom settings for Roundcube to the default web server config in _Resources / IP and ports_)

Now I can access Froxlor again at `my-domain.de/froxlor/`, but I lost the possibility to manage email addresses for that domain in Froxlor. Is there a way to do that?

BTW, step 4 took me a moment to figure out. I had expected an option to customize the vhost settings  in the Froxlor VirtualHost settings panel, but there is none. Maybe just a hint in that panel where to find the vhost settings would be nice.

>     2. **letsencrypt and sql error**
> 
> 
> That most likey happened during the update, best way to avoid this would be to stop the cron temporarily during an update

That's what I thought as well.

**Comment by d00p** [comment]
> Now I can access Froxlor again at my-domain.de/froxlor/, but I lost the possibility to manage email addresses for that domain in Froxlor. Is there a way to do that?

Well you didnt have to remove "my-domain.de" from the customer. You could've just used "froxlor.my-domain.de" for froxlor itself...(or any other non-existing subdomain)

**Comment by chrschn** [comment]
> Well you didnt have to remove "my-domain.de" from the customer. You could've just used "froxlor.my-domain.de" for froxlor itself...(or any other non-existing subdomain)

Oh, so you're suggesting to add the domain to a customer, create a subdomain, then using that for the Froxlor vhost? That kinda sounds pretty much like using a customer domain for Froxlor, but with extra steps. ;-)

**Comment by d00p** [comment]
eh no, i just said that it is possible to use a subdomain of a domain to have the possibility to use said domain as customer (and hence for emails, website. etc.).

**Comment by chrschn** [comment]
Got it. Thank you for your help!

**Comment by drexlma** [comment]
Das ist echt ärgerlich diese Änderung …. Kann man bitte bei so Änderungen nächstes mal eine deprecated Warnung ausgeben?

**Comment by d00p** [comment]
> Das ist echt ärgerlich diese Änderung …. Kann man bitte bei so Änderungen nächstes mal eine deprecated Warnung ausgeben?

Du kannst es doch deaktivieren, siehe https://docs.froxlor.org/latest/admin-guide/settings/#_3-settings-in-config-inc-php 

Wenn dein froxlor korrekt konfiguriert und eingerichtet ist, hast du hier auch keine Probleme

**Comment by d00p** [comment]
[first part was not related to this]

Wenn dein froxlor korrekt eingerichtet und konfiguriert ist solltest du hier keine Probleme haben.

**Comment by drexlma** [comment]
Klasse … Joa nur das bei mir froxlor auf Port 444 läuft mit einer Kundendomain und ich nun nicht mehr rein komme, bei allen Servern die ich betreue. Froxlor lies es zu. 
Das ist durchaus eine kritische Änderung die man nicht mit so einer einfachen Meldung kommuniziert.

**Comment by d00p** [comment]
Du könntest auch einfach nett fragen wie man dir in deinem speziellen Fall helfen kann.

Übrigens absolut kein Grund meiner Firma (die nichts direkt mit dem Open source projekt hier zu tun hat) auf Google schlecht zu bewerten. Ich würde dich bitten das bitte zurückzunehmen
