### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined method Froxlor\Cli\PhpSessionclean::processParameters() in /var/www/froxlor/scripts/php-sessionclean.php:28

### ISSUE THREAD

**Issue by Logicbloke** [Froxlor/Froxlor#1210]
**Describe the bug**
PhpSessionclean only seems to hold `configure`, `execute` and `cleanSessionfiles` functions

**System information**
* Froxlor version: 2.1.2
* Web server: nginx
* OS/Version: Ubuntu 18.04.6 LTS

**To Reproduce**
Go to /scripts/php-sessionclean.php and run the file in command line using php.

**Expected behavior**
No errors.

**Additional context**
I don't quite remember which version I had before the upgrade (when issues started happening) but I'm sure I haven't upgraded this in at least a couple of years.

**Comment by d00p** [comment]
There is no `scripts/php-sessionclean.php` file in froxlor 2.x, see https://docs.froxlor.org/latest/general/migration-guide/2.0.html#cron-helper-scripts
