### ISSUE TITLE
Missing certificate options after update to 2.1.2

### ISSUE THREAD

**Issue by mediaarchitekt** [Froxlor/Froxlor#1211]
After updating from froxlor 2.0.23 to 2.1.2 I can't delete certificates anymore. The whole options column for deleting SSL-Certs is gone. Only the table header shows "Options" at lines end. I run two servers for testing, both have the same error. After downgrading via snapshot, to 2.0.23, the test server shows the trash can for deleting SSL-Certs again.   

**System information**
* Froxlor version: 2.1.2
* Web server: apache2.4
* DNS server: -
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian 12 Bookworm

**To Reproduce**
1. Go to 'Ressources'
2. Click on 'SSL Certificates'
3. Look to the very right for 'Options'
4. No trash can is shown for deleting Certs

**Expected behavior**
I want to delete SSL-Certs, but can't.
![Bildschirmfoto vom 2023-12-20 21-30-26](https://github.com/Froxlor/Froxlor/assets/127331177/2d607b38-150b-499f-9edc-2a5535c10989)
![Bildschirmfoto vom 2023-12-20 21-31-12](https://github.com/Froxlor/Froxlor/assets/127331177/739e27b8-5ece-48d0-8e96-baaf2ca52643)

**Comment by d00p** [comment]
Let's Encrypt certificates can be deleted by deactivating lets encrypt for the domain as it's required to trigger the necessary actions for the removal via acme.sh
