### ISSUE TITLE
System settings > MySQL-Access-Hosts has invalid format of IPv6

### ISSUE THREAD

**Issue by realrellek** [Froxlor/Froxlor#1215]
**Describe the bug**
Fresh installation of froxlor fills in IP addresses where appropriate (which is appreciated). One such locations is in
Settings » System settings » MySQL-Access-Hosts

Here the default settings have been 
localhost,127.0.0.1,ipv4,ipv6,[ipv6]

Upon saving the page, the system notices that I am using an invalid format. It will take ipv6 only (without the brackets), so I guess this is the right setting here.

**System information**
* Froxlor version: 2.1.3
* Web server: apache2
* DNS server: not used
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian 12 Bookworm

**To Reproduce**
1. Install Froxlor (I did from tarball)
2. Go to System, Settings, System settings
3. Find "MySQL-Access-Hosts" with the "[ipv6]", which is not accepted by the system

**Expected behavior**
There should be no "[ipv6]" in the list

**Logfiles**
n/a

**Additional context**
n/a

**Comment by d00p** [comment]
Need to reproduce, never had two different ipv6 values in there...I'll check

**Comment by d00p** [comment]
I'm unable to reproduce this. Can you please specify exactly what has been entered in the corresponding ip fields on the installation form?

**Comment by realrellek** [comment]
Sure. I'm setting up another server shortly and will report back.

**Comment by realrellek** [comment]
Hello, I'm back :)

I am not sure what *exactly* leads to the issue, so here's in verbose mode what I did.

- Ordered a server
- Added both IPv4 (A) and IPv6 (AAAA) to the DNS zonefile
- SSH'd into the server, installed Bookworm base image
- Installed basic LAMP with MySQL from Oracle (via APT) and PHP from Sury
- Installed Froxlor [as per manual](https://docs.froxlor.org/latest/general/installation/tarball.html) using tarball
- In step 3 ("Details about your server"), Froxlor found quite some correct values, but IPv4 was empty. So I entered it. Then I reviewed advanced options, and entered IPv4 again (because switching emptied it)
- Copied the One-Liner into my terminal, let bash do its magic
- In Froxlor, I went to System > Settings, enabled Advanced mode, went to System settings
- Here the main IP address selected is the IPv6 (in brackets), which I left - I changed some defaults though (domain name as default path YES; allow API default for new customers NO; default index file NO; traffic emails NO; default for special settings NO; default php config to all subdomains NO; ServerAlias www)
- Click Save
- Go back to this page
- Now we have [IPv6] in MySQL-Access-Hosts

It will however not come back after you once fixed it, so guess several things lead to this. For example that you need a fresh installation.

As I said, I don't know what of the points above is important to trigger this value. I feel like only the last 5 steps are really relevant.

I hope that helps.

**Comment by d00p** [comment]
* Here the main IP address selected is the IPv6 (in brackets), which I left - I changed some defaults though (domain name as default path YES; allow API default for new customers NO; default index file NO; traffic emails NO; default for special settings NO; default php config to all subdomains NO; ServerAlias www)
* Click Save
* Go back to this page
* Now we have [IPv6] in MySQL-Access-Hosts

So, only after saving the System->Settings page the [ipv6] value appears in the list of mysql-access-hosts? What was the value before that? Wasnt the issue about having ipv6 and [ipv6] in the list of mysql-access-hosts right after installation?

**Comment by d00p** [comment]
Yes, now I can reproduce the issue, it's when ipv6 is selected as primary/main ip address

**Comment by realrellek** [comment]
> What was the value before that?
The same but without the "[ipv6]". It literally just added one item.

> Wasnt the issue about having ipv6 and [ipv6] in the list of mysql-access-hosts right after installation?
It wasn't there right after the installation. It was only there after the first save
