### ISSUE TITLE
Installation should ask for admin email (froxlor and server level)

### ISSUE THREAD

**Issue by realrellek** [Froxlor/Froxlor#1217]
**Is your feature request related to a problem? Please describe.**
Default email address is admin@host.domain.tld because as I understand it, it is best practise to not name the host after a website you intend to install (i.e. not example.com, but rather srv1.example.com or something)
Well anyway so chances are you will not use "host.domain.tld" as a domain for... stuff, but only so it is "there", so you don't have to enter the IP address.
Which means host.domain.tld would not have any email anti-spam thingies in the DNS (spf for example), which in turn means a mail from Froxlor would be considered spam.

**Describe the solution you'd like**
The installer should ask for the admin email address which is also used as the sender address for system mails.
And maybe a second one for server-level system mails - y'know, those who go through /etc/aliases where the comment even specifies "change this to a valid e-mail address you can access"

**Describe alternatives you've considered**
Install as usual and just change it afterwards in the settings. But you'd tend to forget that.
I don't know (and don't think?) if you can even change the address for /etc/aliases

**Additional context**
This kind of was a non-issue in older versions of froxlor because the /etc/aliases thing happened during copy-pasting config files anyway so if you look at what you do, you'll notice and change accordingly, but now with the convenient one-liner, all these opportunities seem to be hidden away from the user.

**Comment by d00p** [comment]
> This kind of was a non-issue in older versions of froxlor because the /etc/aliases thing happened during copy-pasting config files anyway so if you look at what you do, you'll notice and change accordingly, but now with the convenient one-liner, all these opportunities seem to be hidden away from the user.

You still can do the manual configuration btw...

**Comment by realrellek** [comment]
>You still can do the manual configuration btw...

Sure, and I did change this, I was just suggesting this to make it easier for the future - and also if you never used Froxlor before, you might not know this.

**Comment by d00p** [comment]
Sure, no problem. An email address is being asked for on the installation, it's just the one for the admin account itself. A possible solution would be to have a checkbox like "Use this email as sender address" or alternatively let the users specify one

**Comment by realrellek** [comment]
>A possible solution would be to have a checkbox like "Use this email as sender address" or alternatively let the users specify one

That sounds good. I'd appreciate to be able to set one for root user in /etc/aliases too, best at the time of installation as well. With that checkbox so the user could have the same one for each of them.

**Comment by d00p** [comment]
The /etc/aliases entry is also set via configuration. Current default is `root:               root@<SERVERNAME>` which is the same value as the sender email address and could now be set to the sender-address specified via installation. It is not a third email value in our settings somewhere

**Comment by realrellek** [comment]
That sounds good, use the same there as the sender for froxlor mails.
