### ISSUE TITLE
Making the default domain an alias domain results in an undefined offset in TrafficCron.php for v2.1.3

### ISSUE THREAD

**Issue by chrschn** [Froxlor/Froxlor#1221]
**Describe the bug**
When I make the default domain `mycustomer.server.hoster.tld` an alias of `my-customer.de`, the nightly traffic cronjob produces the following PHP notice:

```
PHP Notice:  Undefined offset: 6 in /var/www/html/froxlor/lib/Froxlor/Cron/Traffic/TrafficCron.php on line 168
```

The warning points to [this line](https://github.com/Froxlor/Froxlor/blob/7cc4c9fedbf30466f90d47c64ae07e40ce6eae48/lib/Froxlor/Cron/Traffic/TrafficCron.php#L168). I queried the database to find the customer whose standard subdomain has ID 6 and queried the subdomains:

```sql
SELECT `id`, `domain`, `customerid`, `parentdomainid`, `speciallogfile`  FROM `panel_domains` WHERE `aliasdomain` IS NULL AND `email_only` <> '1' AND `customerid` = 3;
+----+----------------------------+------------+----------------+----------------+
| id | domain                     | customerid | parentdomainid | speciallogfile |
+----+----------------------------+------------+----------------+----------------+
|  7 | my-customer.de             |          3 |              0 |              1 |
|  8 | my-customer-alias.de       |          3 |              0 |              0 |
|  9 | my-customer-other-alias.de |          3 |              0 |              0 |
+----+----------------------------+------------+----------------+----------------+
```

Note that there's no subdomain with ID 6. However, in the Froxlor domain list, there's the additional domain `mycustomer.server.hoster.tld`, which is not returned by the query above. This domain is marked as an alias of domain `my-customer.de`. When I remove the alias (i.e., set it to "no alias"), then the query above also returns the domain with ID 6:

```sql
SELECT `id`, `domain`, `customerid`, `parentdomainid`, `speciallogfile`  FROM `panel_domains` WHERE `aliasdomain` IS NULL AND `email_only` <> '1' AND `customerid` = 3;
+----+------------------------------+------------+----------------+----------------+
| id | domain                       | customerid | parentdomainid | speciallogfile |
+----+------------------------------+------------+----------------+----------------+
|  6 | mycustomer.server.hoster.tld |          3 |              0 |              0 |
|  7 | my-customer.de               |          3 |              0 |              1 |
|  8 | my-customer-alias.de         |          3 |              0 |              0 |
|  9 | my-customer-other-alias.de   |          3 |              0 |              0 |
+----+------------------------------+------------+----------------+----------------+
```

**System information**
* Froxlor version: 2.1.3-1
* Web server: apache2
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* OS/Version: Debian GNU/Linux 11 (bullseye)

**Expected behavior**
The traffic cronjob should work without warnings with any alias setting, or it should not allow configurations which result in warnings.

**Additional context**
The alias setting for the standard domain was enabled for a long time on this server., but this warning started to appear after Froxlor was updated from 2.1.2-1 to 2.1.3-1.

**Comment by d00p** [comment]
known and fixed for upcoming version see commit https://github.com/Froxlor/Froxlor/commit/4073984fd7391386ab8bbccc913755c646049d86

**Comment by chrschn** [comment]
Thanks!
