### ISSUE TITLE
Need permission again and again.

### ISSUE THREAD

**Issue by saifullahshams2** [Froxlor/Froxlor#1226]
Whenever I try to login it says you need to change permission again and again
Please see the picture below.
I use that command as a root user solve the problem temporary,
But when i login again after logout it shows same problem again.

See Picture 
![Screenshot_20240115_191212_Chrome](https://github.com/Froxlor/Froxlor/assets/133542218/40619d03-1fa6-4b20-bd8e-2e5b987731f7)

**Comment by d00p** [comment]
Then your settings might be wrong or possibly you've switched to another Webserver but the old ones still active. Please use the forum or discord for support.

**Comment by pieterhouwen** [comment]
For anyone that is Googling on how to fix this: https://github.com/froxlor/Froxlor/issues/1074#issuecomment-1405092298
