### ISSUE TITLE
Domains.delete doesn't delete mail data

### ISSUE THREAD

**Issue by Smith4545** [froxlor/Froxlor#1239]
**Describe the bug**
When removing a domain either through the web UI or via the API (Domains.delete), the corresponding email accounts are deleted from the database, but the Maildirs themselves are not removed.

**System information**
* Froxlor version: fb5958f5d415a41c84613c43b4e26ba986a29774
* Web server: apache2
* DNS server: none
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian 11

**To Reproduce**
1. Create a domain either via API or the web UI's admin interface.
2. Create a mail address on that domain.
3. Convert the mail address to a mail account. (let it send you a welcome mail)
4. Delete the domain via API or the web UI's admin interface.
5. The Maildir still exists on filesystem.

**Expected behavior**

Additionally to deleting the respective rows from `mail_users` here:

https://github.com/Froxlor/Froxlor/blob/fb5958f5d415a41c84613c43b4e26ba986a29774/lib/Froxlor/Api/Commands/Domains.php#L2138

The corresponding directory for the domain should be `rm -rf`'ed at the customers vmail basedir.

**Additional context**

Since Froxlor allows users to "keep" mail data in other situations independently from deleting accounts in mail_users, it may be beneficial to implement a similar functionality in this case as well.

**Comment by d00p** [comment]
As of now, yes, this is intended behaviour in order to not accidentally loose customer data.
I agree, a switch/parameter to specifically give option to remove files from the filesystem should be added
