### ISSUE TITLE
SSL deactivated for specific domain, but still trying to get one from Letsencrypt

### ISSUE THREAD

**Issue by mjunghanns** [Froxlor/Froxlor#1241]
**Describe the bug**
I ran into a problem with a specific domain.
Since this domain is not being actively used at the moment, I disabled the use of SSL in the domain's configuration. To my surprise, Froxlor was still trying to obtain a certificate from Letsencrypt. I was able to overcome this by re-enabling the use of SSL for that domain, then actively deactivate the option "Create SSL certificate (Let's Encrypt)" and then deactive the use of SSL altogether for this specific domain.

**System information**
* Froxlor version: v2.1.6
* Web server: apache2
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian 12 Bookworm

**To Reproduce**
Prerequisite:
A specific domain has SSL enabled and "Create SSL certificate (Let's Encrypt)" enabled
1. Go to 'Ressources'->'Domains', select 'Edit' on specific Domain
2. Deactivate SSL for this domain by disabling 'Create SSL certificate (Let's Encrypt)'
3. Scroll down to bottom, click "Save"

Despite SSL being disabled, the cronjob still tries to obtain a SSL certificate from Let's Encrypt every time it runs.

**Expected behavior**
Once SSL is deactivated, I would expect Froxlor to not trying to obtain a SSL certificate from Let's Encrypt. I would expect SSL to be disabled alltogether for the specific domain.

**Comment by d00p** [comment]
Can you verify that the following patch resolves the issue?

```diff
diff --git a/lib/Froxlor/Api/Commands/Domains.php b/lib/Froxlor/Api/Commands/Domains.php
index 8559e6e5..ad0d4c55 100644
--- a/lib/Froxlor/Api/Commands/Domains.php
+++ b/lib/Froxlor/Api/Commands/Domains.php
@@ -1528,13 +1528,12 @@ class Domains extends ApiCommand implements ResourceEntity
                                // enabled ssl for the domain but no ssl ip/port is selected
                                Response::standardError('nosslippportgiven', '', true);
                        }
-                       if (Settings::Get('system.use_ssl') == "0" || empty($ssl_ipandports)) {
+                       if (Settings::Get('system.use_ssl') == "0" || empty($ssl_ipandports) || !$sslenabled) {
                                $ssl_redirect = 0;
                                $letsencrypt = 0;
                                $http2 = 0;
-                               // we need this for the json_encode
-                               // if ssl is disabled or no ssl-ip/port exists
-                               $ssl_ipandports[] = -1;
+                               // act like $remove_ssl_ipandport
+                               $ssl_ipandports = [];

                                // HSTS
                                $hsts_maxage = 0;
```

**Comment by mjunghanns** [comment]
Hello Michael,
excellent! That did the trick! It is now working as expected. Thank you!
