### ISSUE TITLE
Cannot enter endDate for API Keys

### ISSUE THREAD

**Issue by HardyKrause** [froxlor/Froxlor#1243]
**As a rule of thumb: before reporting an issue**
* see if it hasn't been [reported](https://github.com/Froxlor/froxlor/issues) (and possibly already been [fixed](https://github.com/Froxlor/froxlor/issues?utf8=✓&q=is:issue%20is:closed)) first
* try with the git master

**Describe the bug**
When I want to enter the enddate for an API-Key its impossible. The Format that is written on left side (Label) does not fit the right side in the input element.
![grafik](https://github.com/Froxlor/Froxlor/assets/24795805/899a8890-bb15-4e81-8de4-f00115e91290)

**System information**
* Froxlor version: $version/$gitSHA1
2.1.6
Firefox on Windows 11
123.01

* Web server: apache2/nginx/lighttpd
apache2

**To Reproduce**
1. Go to api keys
2. Click on eye
3. Try to enter 01.01.2028, 01:01, if I write 1 or 01 it sets immediately back to TT
 

**Expected behavior**
I could enter the date

**Comment by d00p** [comment]
That might be due to a low wait-time until the save operation is called via javascript, it's intended to be used with the html-datetime selector - but yes, it should also be possible to enter a date manually and not get thrown "back"
