### ISSUE TITLE
Enabling Mailserver settings/Only E-Mail? disables Nameserver settings

### ISSUE THREAD

**Issue by Trellmor** [froxlor/Froxlor#1248]
**Describe the bug**
Enabling Mailserver settings/Only E-Mail? disables Nameserver settings.

**System information**
* Froxlor version: 2.1.8
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* OS/Version: Debian 12.5

**To Reproduce**
1. Go to 'Resources/Domains'
2. Click on 'Edit'
3. Toggle "Only email?" to on

**Expected behavior**
Nameserver settings should still be visible.

**Additional context**
I have some domains that are only used for mail, but DNS is hosted by Cloudflare. I want to disable "Create dns zone for domain" for those domains. Currently I need to uncheck "Only email?", then disable "Create dns zone for domain" and save, then check "Only email?" again.

**Comment by d00p** [comment]
Yes you're right, with enabled DNS feature, these settings should not be hidden. Thanks for the report.

**Comment by Trellmor** [comment]
Thank you.
