### ISSUE TITLE
Traffic Cronjob sends mail violating DMARC rules

### ISSUE THREAD

**Issue by alexlehm** [froxlor/Froxlor#1250]
**As a rule of thumb: before reporting an issue**
* see if it hasn't been [reported](https://github.com/Froxlor/froxlor/issues) (and possibly already been [fixed](https://github.com/Froxlor/froxlor/issues?utf8=✓&q=is:issue%20is:closed)) first
* try with the git master

**Describe the bug**
lib/Froxlor/Cron/Traffic/ReportsCron.php uses the recipient address of a report as From address which makes the mail undeliverable for strict DMARC domains

E.g. I use username@gmail.com as admin address and that means that the mail will be rejected by gmail since it is not DKIM signed

**System information**
* Froxlor version: 2.1.8
* Web server: apache2
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: debian 11

**To Reproduce**

1. Create a admin with an email address of gmail.com (or other strict DMARC domains)
2. create at least one domain for this admin
3. wait until 1st of the next month
4. check deferred mails with mailq, there will be one mail addressed to user@gmail.com which is deferred due to a DMARC reject violation

**Expected behavior**
The mail should use a local email address as From, e.g. webmaster@mydomain.de

**Comment by d00p** [comment]
use SMTP settings to send emails using valid smtp authentication
If you want to use webmaster@mydomain - set the admin-email to that and not user@gmail.com

**Comment by d00p** [comment]
Also 
> lib/Froxlor/Cron/Traffic/ReportsCron.php uses the recipient address of a report as From address which makes the mail
is simply not true, see From: https://github.com/froxlor/Froxlor/blob/v2.1/lib/Froxlor/Cron/Traffic/ReportsCron.php#L131 and recipient: https://github.com/froxlor/Froxlor/blob/v2.1/lib/Froxlor/Cron/Traffic/ReportsCron.php#L135

First one is the customer's admin and the second one the customer itself.

**Comment by d00p** [comment]
If you talk about the mail to the admin itself (which indeed sets the From to the same value as the recipient) - then yes this is intended as for now. A solution might be to set the global system sender-email (and possible smtp setting) as "From" there ...I'll check

**Comment by d00p** [comment]
You may want to test the following patch:

```diff
diff --git a/lib/Froxlor/Cron/Traffic/ReportsCron.php b/lib/Froxlor/Cron/Traffic/ReportsCron.php
index 01828c1d..cd8babaf 100644
--- a/lib/Froxlor/Cron/Traffic/ReportsCron.php
+++ b/lib/Froxlor/Cron/Traffic/ReportsCron.php
@@ -211,7 +211,7 @@ class ReportsCron extends FroxlorCron
                                        $_mailerror = false;
                                        $mailerr_msg = "";
                                        try {
-                                               $mail->SetFrom($row['email'], $row['name']);
+                                               $mail->SetFrom(Settings::Get('panel.adminmail'), Settings::Get('panel.adminmail_defname'));
                                                $mail->Subject = $mail_subject;
                                                $mail->AltBody = $mail_body;
                                                $mail->MsgHTML(nl2br($mail_body));
@@ -297,7 +297,7 @@ class ReportsCron extends FroxlorCron
                                        $_mailerror = false;
                                        $mailerr_msg = "";
                                        try {
-                                               $mail->SetFrom($row['email'], $row['name']);
+                                               $mail->SetFrom(Settings::Get('panel.adminmail'), Settings::Get('panel.adminmail_defname'));
                                                $mail->Subject = $mail_subject;
                                                $mail->Body = $mail_body;
                                                $mail->MsgHTML(nl2br($mail_body));
@@ -472,7 +472,7 @@ class ReportsCron extends FroxlorCron
                                        $_mailerror = false;
                                        $mailerr_msg = "";
                                        try {
-                                               $mail->SetFrom($row['email'], $row['name']);
+                                               $mail->SetFrom(Settings::Get('panel.adminmail'), Settings::Get('panel.adminmail_defname'));
                                                $mail->Subject = $mail_subject;
                                                $mail->AltBody = $mail_body;
                                                $mail->MsgHTML(nl2br($mail_body));
```

**Comment by alexlehm** [comment]
Thank you, I have patched that in my server
