### ISSUE TITLE
Install fails - Depends: mariadb-server but it is not going to be installed - Unable to correct problems, you have held broken packages

### ISSUE THREAD

**Issue by K0-RR** [froxlor/Froxlor#1253]
**As a rule of thumb: before reporting an issue**
* see if it hasn't been [reported](https://github.com/Froxlor/froxlor/issues) (and possibly already been [fixed](https://github.com/Froxlor/froxlor/issues?utf8=✓&q=is:issue%20is:closed)) first:   ✔️
* try with the git master:   too much for me

**System information**
* OS/Version: Ubuntu 20.04

**To Reproduce**
apt install froxlor

**Logfiles**
```
The following packages have unmet dependencies:
 froxlor : Depends: mariadb-server but it is not going to be installed or
                    default-mysql-server but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by d00p** [comment]
>  you have held broken packages.

First check that everything is clean, seems there are issues from prior actions. Try `apt install --fix-broken`

**Comment by K0-RR** [comment]
```
root@panel:/home# apt install --fix-broken
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by d00p** [comment]
Dont know your system or used 3rd party repositories. This works just fine with standard ubuntu/debian, see for example our showcase installation: https://www.youtube.com/watch?v=L3RM_yygfP4

Ensure there are no 3rd party sources that might cause issues or try to install mysql/mariadb server packages prior to froxlor

**Comment by K0-RR** [comment]
> try to install mysql/mariadb server packages prior to froxlor

Tried apt install `mariadb-server` and that one is broken but `default-mysql-server` installed fine and so froxlor after that.

However when I try to open the panel I get 403 Forbidden

**Comment by d00p** [comment]
See youtube video, see documentation: https://docs.froxlor.org/latest/general/installation/apt-package.html
and also please use discord or our forum for support. This seems to be a user issue, nothing code-related
