### ISSUE TITLE
Add support for Ubuntu Noble Numbat

### ISSUE THREAD

**Issue by kederer** [froxlor/Froxlor#1256]
Repository support for Ubuntu Numbat is missing.

when will this be included?

**Comment by d00p** [comment]
in v2.2

**Comment by kederer** [comment]
Do you have an ETA for 2.2

Depending on this we consider a downgrade or not.

Thanks a lot

**Comment by d00p** [comment]
The next 2-3 months. The nightly is currently usable (2.2.0-dev1), soon there will be a beta followed by a release candidate (testing channel) and then the final stable version.
