### ISSUE TITLE
custom_suffix of database too long

### ISSUE THREAD

**Issue by DZotya** [froxlor/Froxlor#1258]
**Describe the bug**
The custom suffix (of database name) is too long in case of database creation via api. There is no information about this data in documentation. The database creates but it is no available for customer just for admin. This action is not found in sys log.

**System information**
* Froxlor version: 2.1.9
* PHP: 8.2.20

**To Reproduce**
1. Try to create a database via api
2. Command: Mysqls.add
3. custom_suffix param is testloremipsum222hghh
4. The response error is _We are sorry, but a MySQL - error occurred. The administrator may find more information in syslog._

**Expected behavior**
Error message about the suffix length is greater than x characters. And information about it in documentation.

**Logfiles**
This action is not found in sys log.

**Comment by DZotya** [comment]
No error in syslog.

**Comment by d00p** [comment]
Can you please provide corresponding settings mainly the mysqlprefix setting and the exact API call you ran? I cannot reproduce this on the demo, the database with a custom name like `testloremipsum222hghh` gets added just fine

**Comment by d00p** [comment]
Please provide exact mysql or mariadb version as they have very different username/database name limits

**Comment by DZotya** [comment]
main API calling params are:

$command = 'Mysqls.add';

$commandParams = [
    'mysql_password' => 'ghjk4g5jhg34j#fG',
    'custom_suffix' => "testloremipsum222hghh",
    'description' => 'fdsgdfgdsfg'
];

$payload = [
    'command' => $command,
    'params' => $params
];

The database is created but no available for customer. It looks like the froxlor cannot handle db with this length

**Comment by d00p** [comment]
what is your setting for mysql-prefix in Settings -> Account settings -> SQL Prefix?

**Comment by d00p** [comment]
also your statement 
> The database is created but no available for customer.
only makes sense if there was some error after creating the database because the entry for froxlor to display the database to the customer is made after the database was created and as you posted you got the message `We are sorry, but a MySQL - error occurred. The administrator may find more information in syslog.` so there must be something.

And still need to know the exact dbms and version to be able to reproduce if you cant find any logged messages

**Comment by DZotya** [comment]
Mysql version number: 8.0.37

I have already asked my boss about the setting because I'm a customer not administrator so I have no permission for settings.

**Comment by DZotya** [comment]
![image](https://github.com/froxlor/Froxlor/assets/11869866/191948f1-12db-475b-a19b-97ae69817ecc)

**Comment by DZotya** [comment]
The customer name length is 12 chars.

**Comment by d00p** [comment]
yeah, mysql 8 has a limit of 32, your 12 characters from the customer-name + "_" + your custom database name.

I've implemented a check for this, it will be available in froxlor-2.2
