### ISSUE TITLE
Overwriting SSL Certificate from Let's Encrypt

### ISSUE THREAD

**Issue by hungrygeneration** [froxlor/Froxlor#1262]
When going to website I am not able to log in because Froxlor keeps overwriting the certificate.
![Screenshot 2024-07-24 205121](https://github.com/user-attachments/assets/71079de4-0cc2-4a0d-b2c7-9c46a8279904)
I have tried to regenerate the certificate with Let's Encrypt twice now and it keeps getting overwritten by this dummy certificate. When I set Froxlor up I did not have Let's Encrypt already installed (I did not know that was a prerequisite (didn't see it in the guide maybe I missed it??)

Thank you for developing this! Incredible software!

**System information**
* Froxlor version: Latest (downloaded today)
* Web server: apache2
* DNS server: None
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: none
* OS/Version: Ubuntu Server 22.04

**Comment by d00p** [comment]
I can only guess that something is not configured right,this works perfectly fine for me on a lot of machines. Maybe join us on discord an we'll sort it out?

**Comment by hungrygeneration** [comment]
OK sounds good. What is the discord?

**Comment by d00p** [comment]
https://discord.froxlor.org

**Comment by d00p** [comment]
Problem: Let's Encrypt got automatically disabled because the domain dns check was enabled and the server only had an internal/private IP (NAT).

Solution: disabled domain dns check, works as expected
