### ISSUE TITLE
force ssl redirect broken

### ISSUE THREAD

**Issue by lonesomewalker** [froxlor/Froxlor#1274]
**Describe the bug**
Opening a domain with valid ssl host and enabled rewrite in the backend does not redirect to https.

**System information**
* Froxlor version: latest stable
* Web server: apache2
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Ubuntu Jammy

**To Reproduce**
1. Go to domain
2. Click on force ssl redirect
3. Save and force a config rewrite
4. Still available by http

**Expected behavior**
Config should have a redirect by 301 or similar.

**Additional context**
New config:
```
<VirtualHost xxx:80>
  ServerName sub.domain.tld
  ServerAdmin who@car.es
  DocumentRoot "/var/customers/webs/part/sub.domain.tld"
  <Directory "/var/customers/webs/part/sub.domain.tld/">
  <FilesMatch \.(php)$>
    <If "-f %{SCRIPT_FILENAME}">
      SetHandler proxy:unix:/var/lib/apache2/fastcgi/1-part-sub.domain.tld-php-fpm.socket|fcgi://localhost
    </If>
  </FilesMatch>
    CGIPassAuth On
    Require all granted
    AllowOverride All
  </Directory>
  Alias /goaccess "/var/customers/webs/part/goaccess/sub.domain.tld"
  LogLevel warn
  ErrorLog "/var/customers/logs/part-sub.domain.tld-error.log"
  CustomLog "/var/customers/logs/part-sub.domain.tld-access.log" combined
</VirtualHost>
```

Old config:
```
<VirtualHost xxx:80>
  ServerName sub.domain.tld
  ServerAdmin who@car.es
  LogLevel warn
  ErrorLog "/var/customers/logs/part-sub.domain.tld-error.log"
  CustomLog "/var/customers/logs/part-sub.domain.tld-access.log" combined
  <IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteCond %{REQUEST_URI} !^/\.well-known/acme-challenge
    RewriteRule ^/(.*) https://%{HTTP_HOST}/$1 [R=301;L,NE]
  </IfModule>
  <IfModule !mod_rewrite.c>
    Redirect 301 / https://sub.domain.tld/
  </IfModule>
</VirtualHost>

```

**Comment by d00p** [comment]
Cannot reproduce on test-system. Please provide the complete row of that domain from `panel_domains` (you can do so via DM / Discord if you like)

**Comment by rex2630** [comment]
Can't reproduce either on latest nightly

**Comment by lonesomewalker** [comment]
There we go:
```
INSERT INTO `panel_domains` (`id`, `domain`, `domain_ace`, `adminid`, `customerid`, `aliasdomain`, `documentroot`, `isbinddomain`, `isemaildomain`, `email_only`, `iswildcarddomain`, `subcanemaildomain`, `caneditdomain`, `zonefile`, `dkim`, `dkim_id`, `dkim_privkey`, `dkim_pubkey`, `wwwserveralias`, `parentdomainid`, `phpenabled`, `openbasedir`, `openbasedir_path`, `speciallogfile`, `ssl_redirect`, `specialsettings`, `ssl_specialsettings`, `include_specialsettings`, `deactivated`, `bindserial`, `add_date`, `registration_date`, `termination_date`, `phpsettingid`, `mod_fcgid_starter`, `mod_fcgid_maxrequests`, `letsencrypt`, `hsts`, `hsts_sub`, `hsts_preload`, `ocsp_stapling`, `http2`, `notryfiles`, `writeaccesslog`, `writeerrorlog`, `override_tls`, `ssl_protocols`, `ssl_cipher_list`, `tlsv13_cipher_list`, `ssl_enabled`, `ssl_honorcipherorder`, `ssl_sessiontickets`, `description`) VALUES
(2,	'sub.domain.tld',	'sub.domain.tld',	1,	2,	NULL,	'/var/customers/webs/part/sub.domain.tld/',	0,	0,	0,	0,	0,	1,	'',	0,	0,	'',	'',	0,	0,	1,	1,	1,	1,	3,	'',	'Alias /public /var/customers/webs/part/sub.domain.tld/public.php\n\nAlias /Microsoft-Server-ActiveSync /var/customers/webs/part/sub.domain.tld/modules/z-push/index.php\n\n#For CalDAV support\nAlias /caldav /var/customers/webs/part/sub.domain.tld/modules/caldav/calendar.php\n\n#For CardDAV support\nAlias /carddav /var/customers/webs/part/sub.domain.tld/modules/carddav/addressbook.php\n\n#For WebDAV support\nAlias /webdav /var/customers/webs/part/sub.domain.tld/modules/dav/files.php\n\n#For WOPI support (Collabora Online and Office Online)\nAlias /wopi /var/customers/webs/part/sub.domain.tld/go/modules/business/wopi/wopi.php\n\n#For OnlyOffice support\nAlias /onlyoffice /var/customers/webs/part/sub.domain.tld/go/modules/business/onlyoffice/connector.php\n\nProxyTimeout 650\n\nRedirect 301 /.well-known/carddav /carddav\nRedirect 301 /.well-known/caldav /caldav',	0,	0,	'2000010100',	1724489961,	NULL,	NULL,	5,	-1,	-1,	1,	'0',	0,	0,	0,	1,	0,	1,	1,	0,	'',	'',	'',	1,	0,	1,	'');
```

**Comment by d00p** [comment]
`ssl_redirect` field value is `3` which means: 
> Tell the Let's Encrypt cron it's okay to generate the certificate and enable the redirect afterwards

So there might be an issue with issuing the let's encrypt certificate maybe?

**Comment by lonesomewalker** [comment]
Well, the LE certificate was generated flawlessly.

I do it this way:
- first enable ssl
- rewrite config manually
- then i do LE
- rewrite config manually
- then i enable redirect
- rewrite config manually

Manually rewriting because it goes instantly.
Rewrite done by:
```/usr/bin/php8.1 /var/www/html/froxlor/bin/froxlor-cli froxlor:cron 'tasks' --debug```

**Comment by d00p** [comment]
okay, the order implies there was an existing certificate prior to the redirect, let me check whether this caused the state if value=3 where it can never be deleted

**Comment by d00p** [comment]
no, cannot reproduce, with an existing certificate and no ssl-redirect as base, i ran the cron to ensure i get a plain http vhost. Then enabled ssl-redirect, set's the value to `2`, ran cron, value at `3`, ran cron again, value is `1` and redirect in vhost is generated perfectly fine

**Comment by d00p** [comment]
> Manually rewriting because it goes instantly.
Rewrite done by:
/usr/bin/php8.1 /var/www/html/froxlor/bin/froxlor-cli froxlor:cron 'tasks' --debug

Please use: `/usr/bin/php8.1 /var/www/html/froxlor/bin/froxlor-cli froxlor:cron  --force --debug`

**Comment by lonesomewalker** [comment]
Hm, well... whatever the difference between 'tasks' and without... looks like this is solved?
Is there no 'tasks' anymore?

**Comment by d00p** [comment]
you can also only run 'tasks' if you like but the important thing is the FORCE flag, and `--force` also includes running 'tasks' so you can leave that out

**Comment by lonesomewalker** [comment]
Okay, so this was PEBCAK.

Thx.
