### ISSUE TITLE
[Feature] More options to configure new Antispam feautre

### ISSUE THREAD

**Issue by hikaru-shindo** [froxlor/Froxlor#1282]
**Is your feature request related to a problem? Please describe.**
Before Froxlor 2.2 I had setup antispam for all via amavisd, spamassisin and dovecot sieve in a way that it would:

* Label spam with a mail header
* Not block any mails
* Automatically move marked mails to .Junk folder via sieve filter

The new Antispam feature is a really good addition but frustrates me in two ways as it is not possible to have a setup that:

* labels mails (X-Spam-Flag or X-Spam headers)
* does not change the subject
* accepts all mails

**Describe the solution you'd like**

I think it would be nice if the options could be extended so the customer is able to have more control over the behaviour of the Antispam feature.

It should be possible to:
* not set a block value / disable blocking of emails marked as spam
* disable subject rewrites
* if subject rewrites are enabled: set the format of the target subject

**Describe alternatives you've considered**

Currently I patched the froxlor Cron code to only set the `"add header"` action on the generated configs. This does however leave little control to the customer as some options of the UI are not applied.

**Additional context**

I'm currently using the following sieve filter in `/var/lib/dovecot/sieve/default.sieve`:

```
require "fileinto";
if header :contains "X-Spam-Flag" "YES" {
  fileinto "Junk";
}
```

It might be interesting to make this also configurable by mailbox in froxlor.

**Comment by d00p** [comment]
> labels mails (X-Spam-Flag or X-Spam headers)
does not change the subject
accepts all mails

Simply not true...and as always, you are free to adjust rspamd's config files according to your needs

**Comment by d00p** [comment]
> if subject rewrites are enabled: set the format of the target subject

way too specific for the ordinary enduser...

**Comment by d00p** [comment]
> require "fileinto";
if header :contains "X-Spam-Flag" "YES" {
  fileinto "Junk";
}

Well the default header in rspamd is `X-Spam` ... see https://github.com/rspamd/rspamd/discussions/3802

**Comment by hikaru-shindo** [comment]
> > labels mails (X-Spam-Flag or X-Spam headers)
> > does not change the subject
> > accepts all mails
> 
> Simply not true...and as always, you are free to adjust rspamd's config files according to your needs

Maybe I overlooked something but as far as I understand the code it is not possible to remove the `reject` and `rewrite` actions. See: https://github.com/froxlor/Froxlor/blob/d3ec02f2583eaeb6cfbe81f8aa47c157c7f824ae/lib/Froxlor/Cron/Mail/Rspamd.php#L186-L189

I do not see any conditional here and every new generation of this config file would overwrite any changes. As this file should be generated each time settings on an email address change any manual changes would be lost, or did I misinterpret that?

**Comment by hikaru-shindo** [comment]
> > require "fileinto";
> > if header :contains "X-Spam-Flag" "YES" {
> > fileinto "Junk";
> > }
> 
> Well the default header in rspamd is `X-Spam` ... see [rspamd/rspamd#3802](https://github.com/rspamd/rspamd/discussions/3802)

That's just the example. I already modified the code to support both but the point that it might be an interesting addition to the feature is the same regardless ;)

**Comment by d00p** [comment]
> > > labels mails (X-Spam-Flag or X-Spam headers)
> > > does not change the subject
> > > accepts all mails
> > 
> > 
> > Simply not true...and as always, you are free to adjust rspamd's config files according to your needs
> 
> Maybe I overlooked something but as far as I understand the code it is not possible to remove the `reject` and `rewrite` actions. See:
> 
> https://github.com/froxlor/Froxlor/blob/d3ec02f2583eaeb6cfbe81f8aa47c157c7f824ae/lib/Froxlor/Cron/Mail/Rspamd.php#L186-L189
> 
> I do not see any conditional here and every new generation of this config file would overwrite any changes. As this file should be generated each time settings on an email address change any manual changes would be lost, or did I misinterpret that?

You can either globally change how the subject is being rewritten if the threshold is reached. Alternatively, especially for "not rejecting" we could have "do not reject" and "do not rewrite subject" flag ...

We have intentionally omitted some options/ not added ALL possibilities as most enduser do not even bother or don`t understand/need these settings and the simple email form will become totally bloated

**Comment by hikaru-shindo** [comment]
> > if subject rewrites are enabled: set the format of the target subject
> 
> way too specific for the ordinary enduser...

Fair enough - just being able to enable and disable subject rewrite would be enough anyway. I just like to give the user as much control as possible but I can see this being confusing / overkill for the average person.

**Comment by d00p** [comment]
will be part of v2.2.2
