### ISSUE TITLE
duplicating domain does not duplicate document root with redirect

### ISSUE THREAD

**Issue by HardyKrause** [froxlor/Froxlor#1287]
**Describe the bug**
I have a domain where I changed the document root e.g. from /xyz to https:/abc.de.tld. When I duplicate the domain the actual document root with redirect is not duplicated. Instead, the former /xyz show in duplicated domain.

**System information**
Froxlor version: 2.2.4
Web server: apache2

**To Reproduce**
see bug description

**Expected behavior**
The document root should be duplicated.

**Comment by d00p** [comment]
This is intended, the documentroot is not being duplicated but instead set to the system-default, this is due to the possibility that you can duplicate domains and assign a different customer as owner.

**Comment by HardyKrause** [comment]
Thank you for the information.
