### ISSUE TITLE
Can't change catchall e-mail address

### ISSUE THREAD

**Issue by LordSimal** [froxlor/Froxlor#1288]
**Describe the bug**
When trying to change the active catchall e-mail address froxlor doesn't save the new catchall.

**System information**
* Froxlor version: 2.2.4-1
* Web server: apache2
* DNS server: Bind
* POP/IMAP server:Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian 11

**To Reproduce**
1. Login as admin to the froxlor panel
2. Go to a customer which has multiple e-mail accounts present AND an active catchall mail address
3. Try to change the active catchall mail address to another email address

**Expected behavior**
Froxlor changes the active catchall email address to the new one AND removes the flag from the old one

**Additional context**
Looking through the github repo i recognised, that the database field in `mail_virtual` is called `iscatchall` BUT the HTML form input name for the catchall input box is `mail_catchall`

Therefore, I tried to just change the input name from `mail_catchall` to `iscatchall` and save again which seems to work.

**Comment by d00p** [comment]
confirmed, weird, thanks for the find :)
