### ISSUE TITLE
Traffic Cronjob sends mail violating DMARC rules (similar issue to #1250)

### ISSUE THREAD

**Issue by alexlehm** [froxlor/Froxlor#1289]
**Describe the bug**
lib/Froxlor/Cron/Traffic/ReportsCron.php uses the admin address as From address which makes the mail undeliverable for strict DMARC domains, the mail is with subject "Sie erreichen bald Ihr Traffic-Limit"

E.g. an admin uses name@somedomain.de as admin address and the recipient address of the site owner is user@outlook.com, that means that the mail will be rejected by Outlook since it is not DKIM signed and the source domain is set to p=reject

**System information**
* Froxlor version: 2.2.4
* Web server: apache2
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian 11

**To Reproduce**
1. Create a reseller with an email address of a strict DMARC domain (p=reject) (that is not hosted on the Froxlor host)
2. Create at site owner with an email address on outlook.com (or another domain that enforces DMARC rules)
3. wait until 1st of the next month
4. the bounce email should go to the postmaster of the site running Froxlor with the rejection reason "Access denied, sending domain [SOMEDOMAIN.DE] does not pass DMARC verification and has a DMARC policy of reject."

**Expected behavior**
The mail should use a local email address as From, e.g. webmaster@mydomain.de

**Additional context**
A similar issue was fixed as #1250

**Comment by d00p** [comment]
Yes that's correct, there is no SMTP setting yet per froxlor-admin for their adress to send mail.

We can either change that behavior to use the system-sender (if set up with smtp) - without smtp credentials, this problem cannot be fixed

**Comment by alexlehm** [comment]
I guess it could just be the site-wide from email and use the name of the admin as real-name field

**Comment by d00p** [comment]
> I guess it could just be the site-wide from email and use the name of the admin as real-name field

This is what we'll do now.

> Or maybe have it switchable to use either the owner domain address or the global admin address of Froxlor

This would lead to every admin having its own SMTP settings
