### ISSUE TITLE
system.apache24 always sets to 0 when using Froxlor:importSettings

### ISSUE THREAD

**Issue by raczkow** [froxlor/Froxlor#1290]
I dump current Froxlor configuration with: `froxlor-cli froxlor:api-call -- admin Froxlor.exportSettings`. Then I try to load this config with `froxlor-cli froxlor:api-call -- admin Froxlor.importSettings`. It loads OK, but apache server won't reload any more. It fails with error: `Invalid command 'FastCgiExternalServer', perhaps misspelled or defined by a module not included in the server configuration`.
I found out, that after importing previously saved settings, one variable has changed: `system.apache24`. Everytime I do the import, `system.apache24` is set to 0. When I switch it manually in GUI, reloading of Apache works OK.

**System information**
* Froxlor version: 2.2.4
* Web server: apache2/
* DNS server: -
* POP/IMAP server: -
* SMTP server: -
* FTP server: pureftpd
* OS/Version: Debian 12

**To Reproduce**
1. Dump Froxlor config with `froxlor-cli froxlor:api-call -- admin Froxlor.exportSettings`
2. Load settings with `froxlor-cli froxlor:api-call -- admin Froxlor.importSettings`

**Expected behavior**
`system.apache24` keeps its value and doesn't change to '0'.

**Comment by d00p** [comment]
Well check the output file if the export, is it already `0` in there? Just to find the origin, whether it's the export or the import

**Comment by raczkow** [comment]
It's the problem in importing data. I've already done some debugging. I think the problem is in parsing variables from input and these generated by the form. They are not consistent. Froxlor\UI\Data `getFormFieldDataCheckbox()` gets three parameters: `$fieldname, $fielddata, $input`. `$fieldname` is set as `system_apache_24`. But `$input` array contains only `system_apache24`. So, `getFormFieldDataCheckbox()` always returns 0 as a new `system_apache_24` value.
