### ISSUE TITLE
After update to 2.2.5 API is not working anymore

### ISSUE THREAD

**Issue by papppeter** [froxlor/Froxlor#1293]
It is not an option to try it with git master
2.2.4 did not had the issue

**Describe the bug**
In FroxlorApi.php line 105:
                                                                                                                            
  Error: 500: Server error: `POST https://***/api.php` resulted in a `500 Internal Server Error` response:  
  {                                                                                                                         
      "message": "Internal PHP error: #2 touch(): Utime failed: Permission denied"                                          
  }                                                                                                                         
            

**System information**
* Froxlor version: 2.2.5
* Web server: apache2
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: ubuntu

**To Reproduce**
Try add database trough API

**Expected behavior**
It creates a database

**Comment by d00p** [comment]
> In FroxlorApi.php line 105:

there's no such file...except the example in `doc/example/` and this file does not even have 105 lines...

Also, if you'd compare the two versions, there were no changes near API... https://github.com/froxlor/Froxlor/compare/2.2.4...2.2.5

**Comment by papppeter** [comment]
sorry for your time, and thanks for the quick reply.

the issue was on our site. The file name fooled me.

**Comment by papppeter** [comment]
so the file was on our side, but issue happened in api. which go away after server restart.
