### ISSUE TITLE
ssl_redirect doe'nt create redirect in VHost if used AFTER LE creation

### ISSUE THREAD

**Issue by rseffner** [froxlor/Froxlor#1294]
**Describe the bug**
If you activare LE certificate creation AND ssl_redirect  TOGETHER then everithing works as expected.
If you try to activate ssl_redirect AFTER LE is enabled value in panel_domains gets "3" and VHost never gets redirect code.

**System information**
* Froxlor version: 2.2.5 from tar.gz

**To Reproduce**
- delete ssl_redirect and LE from one domain -> save -> cron
- activate LE again -> save -> cron
- activate ssl_redirect -> save ->cron
- check VHost and panel_domains

**Expected behavior**
Activating ssl_redirect should result in redirecing VHost.

**Additional context**
You'll find context in german Forum.

**Comment by d00p** [comment]
Can you test the following patch:

```diff
diff --git a/lib/Froxlor/Api/Commands/Domains.php b/lib/Froxlor/Api/Commands/Domains.php
index 0ed0fbc9..10e6a97e 100644
--- a/lib/Froxlor/Api/Commands/Domains.php
+++ b/lib/Froxlor/Api/Commands/Domains.php
@@ -1571,7 +1571,7 @@ class Domains extends ApiCommand implements ResourceEntity
                        }

                        // Temporarily deactivate ssl_redirect until Let's Encrypt certificate was generated
-                       if (($result['letsencrypt'] != $letsencrypt || $result['ssl_redirect'] != $ssl_redirect) && $ssl_redirect > 0 && $letsencrypt == 1) {
+                       if ($result['letsencrypt'] != $letsencrypt && $ssl_redirect > 0 && $letsencrypt == 1) {
                                $ssl_redirect = 2;
                        }
```

It should now disable the ssl-redirect temporarily only if let's encrypt was activated within the same request and with enabled ssl-redirect.

In your case, when let's encrypt is already enabled, the `$result` value (from the db) should be equal to the request value and hence not create a temporary disabled vhost resulting to ssl-redirect = 3 endlessly

**Comment by d00p** [comment]
did you find any time to test this @rseffner

**Comment by rseffner** [comment]
> did you find any time to test this @rseffner

Yes, it works with this changes as expected.
