### ISSUE TITLE
cant use CIDR format in "SPF for all domains" setting

### ISSUE THREAD

**Issue by rseffner** [froxlor/Froxlor#1295]
**Describe the bug**
Trying to add "ip6:2a01:***:***:6442::/64" or "ip6:2a01:***:***:10::2/64" in settings results in "Der Wert des Feldes "spf_spf_entry" hat nicht das erwartete Format."
Mayby an syntax check dislikes the "/"?

**System information**
* Froxlor version: 2.2.5

**To Reproduce**
system -> seetings -> antispam -> spf for all domains : input : save

**Expected behavior**
Would like to see that froxlor accepts SPF settings - also in CIDR format - as described e.g. here http://www.open-spf.org/action_browse_id_SPF_Record_Syntax_revision_7/.

**Comment by rseffner** [comment]
This change did not solve the problem.

**Comment by d00p** [comment]
try this:

```diff
diff --git a/actions/admin/settings/180.antispam.php b/actions/admin/settings/180.antispam.php
index 6a3c67b2..b6bc96b2 100644
--- a/actions/admin/settings/180.antispam.php
+++ b/actions/admin/settings/180.antispam.php
@@ -129,7 +129,7 @@ return [
                                        'settinggroup' => 'spf',
                                        'varname' => 'spf_entry',
                                        'type' => 'text',
-                                       'string_regexp' => '/^v=spf[a-z0-9:~?\s.-\/]+$/i',
+                                       'string_regexp' => '/^v=spf[a-z0-9:~?\s.\-\/]+$/i',
                                        'default' => 'v=spf1 a mx -all',
                                        'save_method' => 'storeSettingField'
                                ],
```

**Comment by rseffner** [comment]
Fine.
