### ISSUE TITLE
Setting to add a subdomain as admin is missing

### ISSUE THREAD

**Issue by MichaelSch** [froxlor/Froxlor#1301]
**Describe the bug**
I need a subdomain with custom vhost settings. According to [the forums](https://forum.froxlor.org/index.php?/topic/18919-eigene-vhost-direktiven-per-einzelner-subdomain-oder-inlcude/) and [the documentation](https://docs.froxlor.org/v2.2/admin-guide/resources/domains/#this-domain-is-a-subdomain-of-another-domain) I can add a domain as admin and set "This domain is a subdomain of another domain". However the setting mentioned is missing in the GUI.

**System information**
* Froxlor version: 2.2.5
* Web server: apache2
* DNS server: N/A
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian 12

![Bildschirmfoto 2024-12-16 um 16 33 37](https://github.com/user-attachments/assets/a3d151b9-6dc5-4a88-8917-09fa1fbf7475)
 What am I missing?

**Comment by d00p** [comment]
You do not need to manually set "is subdomain of another domain" - froxlor does this internally now. Seems I've missed this part in the docs
