### ISSUE TITLE
FR: Send Notification Mail When New Version Is Available

### ISSUE THREAD

**Issue by realrellek** [froxlor/Froxlor#1302]
**Is your feature request related to a problem? Please describe.**
Not really a problem, just a quality of life improvement.

**Describe the solution you'd like**
When a new froxlor version is released, the updater shows a notification, but only within the UI. I'd like if froxlor sends an email to the admin when it notices a new version being available. So that I can run the update however it is meant to be (apt-get/UI/CLI/whatever).
Maybe make it an option, so in case someone is administrating every day, this uber-admin doesn't get bothered with mails of this kind.

**Describe alternatives you've considered**
I've subscribed to Github releases and then I open 1Password to make sure I login to every server to update it. It's kind of tedious and a mail with a convenient link to the panel would go a long way.

**Additional context**
I mean, it's an email. And I think a flag that is reset when I actually run an upgrade, so I don't get multiple mails when I skip a version for whatever reason.

Thank you and Happy Easter :–)

**Comment by d00p** [comment]
Already possible, see https://docs.froxlor.org/latest/admin-guide/cli-scripts/#update

**Comment by realrellek** [comment]
So I'd have to set up a cronjob? Or how does it want to be used?

**Comment by d00p** [comment]
It's a manual command,.so yes, a cronjob would be the way to go ;)
