### ISSUE TITLE
Issue using Froxlor with Dovecot (Ubuntu 16.04)

### ISSUE THREAD

**Issue by pge** [Froxlor/Froxlor#419]
Hey,

i installed Froxlor on Ubuntu 16.04.

> apt-get install apache2 libapache2-mod-php7.0 php7.0-common php7.0-gd php7.0-mysql  php7.0-mcrypt php7.0-curl php7-0-intl \
php7.0-xsl php7.0-mbstring php7.0-zip php7.0-bcmath php7.0-iconv mysql-server

> cd /var/www/ && wget http://files.froxlor.org/releases/froxlor-latest.tar.gz
tar zxvf froxlor-latest.tar.gz
rm froxlor-latest.tar.gz
chown -R www-data:www-data /var/www/froxlor

Web-Installation and following:

Konfiguration > Distribution Ubuntu 14.04 > Service Mailserver IMAP/POP3 > Dovecot

done.

Now, when trying to access the Mail feature via a client, i get: 

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'froxlor.mail_virtual' doesn't exist

What's the issue here?

**Comment by d00p** [comment]
You've Installed with MySQL Strict-mode enabled which is not fully supported.

**Comment by pge** [comment]
Actually this is stock packaged mysql.
After adding: 

> sql_mode=IGNORE_SPACE,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

Theres still no change. At what point is this view created?

**Comment by d00p** [comment]
Installation of course...

**Comment by pge** [comment]
Well, it could be during the post-froxlor installation of the actual mailstack/creation of the first mail-users. So it seems to be a valid question to me :) 

So meaning if i disable strict-mode after installting the SQL Server, pre-installing froxlor things should be peachy? Or can i re-trigger the creation within a running installation?

**Comment by d00p** [comment]
1) 16.06 is not yet officially supported
2) you will need to reinstall

**Comment by pge** [comment]
Thanks! I'll gladly try. 
And also thanks for the 16.06(4) hint. 
Have a pleasant day!

**Comment by pge** [comment]
Info:

On creating a customer, Froxlor also replies

> A database error occurred
SQLSTATE[01000]: Warning: 1265 Data truncated for column 'add_date' at row 1

**Comment by d00p** [comment]
Info: then you are disabling wrong. Also please use the forum for support, not the Bugtracker

**Comment by tyronx** [comment]
So why not warn the user during install that strict mode is not supported instead of just closing the issue and let people deal with issues they couldn't possibly know about?

**Comment by d00p** [comment]
That's why: https://github.com/Froxlor/Froxlor/commit/1e03946df7e0a8aebe8d2c680b9349be81dafda3
