### ISSUE TITLE
Apply specialsettings to all subdomains not being read from database

### ISSUE THREAD

**Issue by donagrejja** [Froxlor/Froxlor#421]
When changing Apply specialsettings to all subdomains (*.example.com): in the domain settings and save.
It seems to be saved to the database but when i do "edit domain" again it will still show as enabled instead of corrently disabled.

**Comment by d00p** [comment]
this is not a field stored in the database but rather a one-time-action switch, has been explained a lot. You generally may want to apply all the special settings you supply to the subdomains of that domain. If not - and clear existing entries - you set it to 'no' when saving.

**Comment by donagrejja** [comment]
Ok thank you.

Question then. I had to disable this option even though i did not have any special settings to have php enabled for subdomains. If i did not disable the special settings for subdomains the default behaviour was to disable php even though php was enable for the main domain. is this also expected behaviour ?

**Comment by d00p** [comment]
no this option has nothing to do with getting php to work, this is a known bug which has already been fixed in current git-master, see https://github.com/Froxlor/Froxlor/commit/2d59e569df709caf7ca5af441235348d6abbc941
