### ISSUE TITLE
char _ missed in function validateDomain

### ISSUE THREAD

**Issue by rseffner** [Froxlor/Froxlor#423]
I like to add an DKIM CNAME for e.g. MailChimp use like "k1._domainkey". Thats not possible because of function validateDomain in function.validateDomain.php. Its needed to add a "_" to the pattern.

**Comment by d00p** [comment]
Be more specific - regarding DNS Editor or are you adding a new (Subdomain). Wenn cannot Just allow underscore, it's not always valid!

**Comment by rseffner** [comment]
MailChimp says: "create a CNAME record for k1._domainkey.yoursite.com with this value: dkim.mcsv.net." I tried this in DNS-Editor with a result similar "value not valid" until I added the "_" in the [quick and dirty!] pattern string of mentioned function. I did not add a subdomain "_domainkey".

**Comment by d00p** [comment]
You did test with latest git master in hope? There were changes already iirc

**Comment by d00p** [comment]
Just tested with our demo, the DNS editor surely allows adding _domainkey (or similar) entries. Only "problem" is, that the value for the CNAME entry is not valid when there's an underscore in the domain:

> Error
> Invalid domain-name for CNAME record

**Comment by rseffner** [comment]
No, I only use the .deb based stable versions.

**Comment by d00p** [comment]
when testing / reporting bugs - PLEASE always use the LATEST source available...just causes extra work this way.
At least try your scenario in our DEMO

**Comment by rseffner** [comment]
I tried it inside the demo system without problems. So I also looked at te git sources and cannot find anny differences in function.validateDomain.php - so I do not understand, why my systems tells "Fehlermeldung
Die Subdomain "k1._domainkey" enthält ungültige Zeichen".

**Comment by d00p** [comment]
because it's not a domainValidate thing but a pure DNS related validation that allows the underscore under certain circumstances

**Comment by rseffner** [comment]
I added a "_" to the regex pattern in domainValidation and it works now.

**Comment by d00p** [comment]
Well if it works for you, fine
