### ISSUE TITLE
Wrong Unit in traffic graphs mouseover

### ISSUE THREAD

**Issue by fleaz** [Froxlor/Froxlor#425]
Hi,

when looking at the traffic graphs the mouseover box for the single points always show one unit higher than it should. E.g. when the value is MB the mouseover shows GB. The unit in the header of the graphs is correct, wherefore I assume it's just a rendering bug in the frontend.

![froxlor_graph_bug](https://cloud.githubusercontent.com/assets/2489598/24997232/2996a77c-2036-11e7-906e-b04e79019e41.png)

**Setup**:
Froxlor 0.9.38.7 
Nginx 1.10.3
PHP 7.0.17
Debian Jessie

**Comment by nachtgeist** [comment]
The units for the traffic tool tips are hard-coded, regardless of the order of magnitude of the actual data...

**Comment by d00p** [comment]
This will change in 0.11. with new Frontend and new Chart library

**Comment by pquerner** [comment]
Is this covered by some test database so its easier to debug?

**Comment by d00p** [comment]
> Is this covered by some test database so its easier to debug?

what exactly do you mean? All the data froxlor uses is from the database

**Comment by pquerner** [comment]
I mean is there a command to locally create a test database so you can get right into debugging (without the need to manually populate the database).

**Comment by d00p** [comment]
No there is not
