### ISSUE TITLE
letsencrypt provide fullchain

### ISSUE THREAD

**Issue by stephan-l** [Froxlor/Froxlor#432]
Hi,

letsencrypt would be even more useful if froxlor saves the fullchain.pem at least for the panel certificate. Then the certificated could be used directly in dovecot and postfix.
The request was in the forum last year but I saw no feature request so far:
https://forum.froxlor.org/index.php?/topic/13344-lets-encrypt-fullchain-abspeichern/

**Comment by Commifreak** [comment]
I currently use these Certs with Postfix and Dovecot directly and never had an issue - could you be more specific?

Postfix:

```
smtpd_tls_cert_file = /etc/ssl/froxor-custom/mail.xxx.crt
smtpd_tls_key_file = /etc/ssl/froxlor-custom/mail.xxx.key
smtpd_tls_CAfile = /etc/ssl/froxlor-custom/mail.xxx_CA.pem
```

Dovecot:

```
ssl_cert = /etc/ssl/froxor-custom/mail.xxx.crt
ssl_key =  /etc/ssl/froxlor-custom/mail.xxx.key
ssl_ca =  /etc/ssl/froxlor-custom/mail.xxx_CA.pem
```

Working great with 0.9.38.7

**Comment by stephan-l** [comment]
Well that's interesting. According to the dovecot documentation chained certificates need to be provided in a single file. ssl_ca should be used for client cert verification but does the trick here.

Thanks for the help.

**Comment by schnuffle** [comment]
I added the full chain creation,
here's the commit: 6d32898e94d2d6f251acc5a1d52eb5e9766aa93a

**Comment by d00p** [comment]
> I added the full chain creation, here's the commit: 6d32898
And this is a closed pull-request...please do this in a separate, new PR
