### ISSUE TITLE
DNS editor does not allow unqualified CNAME entries

### ISSUE THREAD

**Issue by willydee** [Froxlor/Froxlor#434]
### Problem
It is not possible to create a concise `CNAME` record like
```
ssl     IN      CNAME   www
```
### Steps to reproduce
* Create a customer and domain
* Activate nameserver management for domain
* Fill form row with values `Record: 'ssl', Type: 'CNAME', Content: 'www'`

### Expected result
A valid record as above should be generated.

### What happens instead
```
Error
Invalid domain-name for CNAME record
```

Workaround is to enter `www.domain.tld` as content, which will then be expanded to a FQDN with a trailing dot. But IMHO it should also be possible to use non-FQDN as content (or `@`), since those are also perfectly valid records.

**Comment by d00p** [comment]
Source/RFC that states this is valid?

**Comment by willydee** [comment]
https://ftp.isc.org/isc/bind9/cur/9.11/doc/arm/Bv9ARM.pdf
Chapter 6, page 163:
```
$ORIGIN example.com.
WWW CNAME MAIN-SERVER
```
is equivalent to
```
WWW.EXAMPLE.COM. CNAME MAIN-SERVER.EXAMPLE.COM.
```

Not sure about the `@`, but can remember having seen that too in Bind zone files.

**Comment by d00p** [comment]
okay, thanks

**Comment by nachtgeist** [comment]
I think I remember troubles with unqualified cname values and pdns as backend - just as a reminder for testing a fix...

**Comment by d00p** [comment]
problem here is, we cannot reliably check wether the given entry is just a subdomain of the domain or a complete other domain, without forcing the user to either append or leave  out the trailing dot....any ideas?

**Comment by d00p** [comment]
Best solution after a short discussion: is there a dot at the end of the content -> it's an fqdn, if there's not, we'll append the zone's domainname
