### ISSUE TITLE
Dovecot authentication failing when password contains multibyte characters

### ISSUE THREAD

**Issue by willydee** [Froxlor/Froxlor#435]
### Steps to reproduce

* Configure Dovecot according to instructions
* Create an email address and mail account with a password containing umlauts: `Müsst3_kl4ppen`
* Try to log in using that password with an arbitrary IMAP client (tested with recent versions of Thunderbird and Roundcube Webmail)

### Expected result

User should be logged in

### What happens instead

Mail client reports authentication failure

**Comment by d00p** [comment]
Logs?

**Comment by willydee** [comment]
```
Apr 30 17:42:50 lithium dovecot: auth-worker(12274): Debug: sql(willy@*****,2a01:4f8:c17:146::2,<Ioa5KGROsLUqAQT4DBcBRgAAAAAAAAAC>): query: SELECT username AS user, password_enc AS password, CONCAT(homedir, maildir) AS userdb_home, uid AS userdb_uid, gid AS userdb_gid,  CONCAT('maildir:', homedir, maildir) AS userdb_mail, CONCAT('*:storage=', quota, 'M') as userdb_quota_rule FROM mail_users WHERE (username = 'willy@*****' OR email = 'willy@*****') AND ((imap = 1 AND 'imap' = 'imap') OR (pop3 = 1 AND 'imap' = 'pop3') OR 'imap' = 'smtp' OR 'imap' = 'sieve')
Apr 30 17:42:50 lithium dovecot: auth-worker(12274): sql(willy@*****,2a01:4f8:c17:146::2,<Ioa5KGROsLUqAQT4DBcBRgAAAAAAAAAC>): Password mismatch
Apr 30 17:42:50 lithium dovecot: auth-worker(12274): Debug: sql(willy@schott-baerenwalde.de,2a01:4f8:c17:146::2,<Ioa5KGROsLUqAQT4DBcBRgAAAAAAAAAC>): CRYPT(Müsst3_kl4ppen) != '$5$ivmdwgwvsd$arhQ/vKIvtJ5p6B63ZbupmU9/c5yXTQL6oIc9HQ6Tw7'
Apr 30 17:42:52 lithium dovecot: auth: Debug: client passdb out: FAIL#0111#011user=willy@*****
Apr 30 17:42:52 lithium dovecot: imap-login: Disconnected (auth failed, 1 attempts in 2 secs): user=<willy@*****>, method=PLAIN, rip=2a01:4f8:c17:146::2, lip=2a01:4f8:c17:146::2, secured, session=<Ioa5KGROsLUqAQT4DBcBRgAAAAAAAAAC>

```

**Comment by willydee** [comment]
It seems to be a Dovecot related problem. If I manually generate a password hash with `doveadm pw -s sha256-crypt -p Müsst3_kl4ppen`, the login also fails. Perhaps it should be emphasized (or enforced) in Froxlor that email passwords should only contain ASCII characters.

**Comment by nachtgeist** [comment]
What character set do your froxlor DB and the mail_users table use? UTF-8?

Also: what's the environment of the `dovecot` process? Since dovecot wipes its environment, it cannot be just printed by `cat /proc/$dovecotpid/environ`. See, if you have a file called /etc/default/dovecot and add one line
`env`
to its end, then issue `/etc/init.d/dovecot restart`.
Check, if you have anything like LC_* or LANG defined there and if its something non-utf8...

**Comment by nachtgeist** [comment]
closed due to inactivity
