### ISSUE TITLE
Apacheconfig missing (or am i blind)?

### ISSUE THREAD

**Issue by ragnar76** [Froxlor/Froxlor#437]
Hey,

i've just installed the latest version from your debian repository. after follwing the debian install guide, and following the tar guide later, i was not able to access it (404). the problem is, dpkg unpacks it to /var/www which is not the default www-root for debians apache 2.4 (its /var/www/html). so i had to write my own config and put it in /etc/apache/site-enabled (see below).

i think you should mention that in the docs

```
Alias /froxlor /var/www/froxlor
<Directory /var/www/froxlor>
    Options FollowSymLinks
    DirectoryIndex index.php

    <IfModule mod_php5.c>
        <IfModule mod_mime.c>
            AddType application/x-httpd-php .php
        </IfModule>
        <FilesMatch ".+\.php$">
            SetHandler application/x-httpd-php
        </FilesMatch>
    </IfModule>
</Directory>
```

**Comment by d00p** [comment]
Just edit sites-enabled/000-default and change /var/www/html to /var/www/ ...no need for your own configs...

**Comment by ragnar76** [comment]
imho, writing a separate config file is no magic at all, its a question of faith. but thats not the point here, a hint inside the docs would be great

**Comment by d00p** [comment]
there is NO NEED for a custom config files, that's the point. And for installation, froxlor just needs to be in the default webroot, which is usually /var/www/, only on jessie (and maybe ubuntu 16.06) it's /var/www/html

**Comment by ragnar76** [comment]
what i dont get, you provide a package for jessie, you now that the document root is /var/www/html but still, you install in /var/www ? why? if the package is the same for wheezy and jessie, why dont you fiddle around with the doinst script and copy the files to the right place?

**Comment by nachtgeist** [comment]
Granted, the Froxlor package doesn't adhere to the Debian Policy. But `/var/www/html` is still not the right™ place to put it. The cleanest destination for a Debian system would be /usr/share/froxlor and work with Alias directives from there.

However we decided against that quite a while back to keep deviations between distributions to a minimum.
