### ISSUE TITLE
Automatic file created with given mysql-password broken (authmysqlrc)

### ISSUE THREAD

**Issue by Starcalc** [Froxlor/Froxlor#438]
While configuring for Ubuntu Trusty (14.04) »  Mailserver (IMAP/POP3) »  Courier:

I gave the mysql-Password in the given field and let it "set" inside the files.
For /etc/courier/authmysqlrc, this fails, as the password is written BEFORE the MYSQL_PASSWORD information:
```
MYSQL_USERNAME froxlor
passwordformysqlgiven MYSQL_PASSWORD 
MYSQL_PORT 3306
MYSQL_DATABASE froxlor
MYSQL_USER_TABLE mail_users
MYSQL_CRYPT_PWFIELD password_enc
MYSQL_UID_FIELD uid
MYSQL_GID_FIELD gid
MYSQL_LOGIN_FIELD username
MYSQL_HOME_FIELD homedir
MYSQL_MAILDIR_FIELD maildir
MYSQL_QUOTA_FIELD (quota*1024*1024)
MYSQL_AUXOPTIONS_FIELD CONCAT("allowimap=",imap,",allowpop3=",pop3)
```

**Comment by d00p** [comment]
Yeah well, problem here is of course, that the variable name is the same as the replacer variable (MYSQL_PASSWORD <> MYSQL_PASSWORD)...i don't think we can change that without changing the replacer in **all config templates**

**Comment by discordier** [comment]
Shouldn't it work by only replacing the last occurence on a line if two matches are encountered?

**Comment by d00p** [comment]
Only in this case, must Not always be correct
