### ISSUE TITLE
More problems with mysql strict mode on ubuntu 16.04.2

### ISSUE THREAD

**Issue by memmerto** [Froxlor/Froxlor#439]
My environment:
* ubuntu 16.04.2 LTS
* mysql 5.7.18
* froxlor 0.9.37 upgrading to 0.9.38.7

In addition to the issue in #433, after hacking around it you will hit this error:

```
A database error occurred
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '0000-00-00' for column 'termination_date' at row 1
```

The update steps for database version 201609240 will not work against a database with strict mode compatibility enabled.  In particular, the 'alter table' steps for panel_domains may fail if any of the values for that column are invalid under the new data type.  Specifically, the text string '0000-00-00' is not a valid date representation.

A more convoluted upgrade process is required to change the data type of this column.  The column must be updated to a text data type, then the invalid entries ('0000-00-00') must be converted to valid entries (NULL), and finally the column can be changed to date data type.

Below are the steps I used to migrate the panel_domains table.

```
-- Step 1: change affected columns from date to 'varchar(10) null default null'
alter table panel_domains change registration_date registration_date varchar(10) null default null, change termination_date termination_date varchar(10) null default null;

-- Step 2: change '0000-00-00' dates to NULL
update panel_domains set registration_date = null where registration_date = '0000-00-00';
update panel_domains set termination_date = null where termination_date = '0000-00-00';

-- Step 3: change affected columns from 'varchar' to 'date null default null'
alter table panel_domains change registration_date registration_date date null default null;
alter table panel_domains change termination_date termination_date date null default null;
```

**Comment by d00p** [comment]
See https://github.com/Froxlor/Froxlor/issues/433#issuecomment-300783538
