### ISSUE TITLE
Implementing multi-server support in Froxlor

### ISSUE THREAD

**Issue by schallertd** [Froxlor/Froxlor#440]
Hi there,

we've been using Froxlor since many years in an environment, where we have separated the db, web and mail servers to different machines. This is not only good in terms of performance in larger environments, but also enables us to implement better security and isolation between different services. Since it works pretty well and could be pretty easily integrated into Froxlor stable, I thought I might drop some lines here for those interested.

The multi-server limitations in Froxlor are mainly caused by it's current mda/mta implementation, therefore the following things currently have to be adjusted:

* by default, froxlor creates the maildirs locally via cron and mkdir. this is not required and could be deprecated, as both exim/dovecot are able to automatically create the full maildir path upon first login or when receiving the first email for a new domain/mailbox

* statistics for mail usage (maildir size, traffic) can be populated and stored within the `mboxsize` row in the `mail_users` table directly from exim/dovecot.  the cron-script ./scripts/jobs/cron_mailboxsize.php could be replaced

* removing the mailbox data of deleted mailboxes from the filesystem is a bit trickier, as the webserver has no local access to the maildir anymore. this could be achieved with a simple script which periodically runs on the mailserver via cron and checks the db for removed mailboxes or domains. if detected, the script simply removes the maildir from the local maildir on the mail vm.

I will share updated scripts and config files if required. Of course some other minor things like mysql-client, libnss and nscd have to be installed and configured on every machine equally. Also all VMs need to be able to connect to the MySQL/MariaDB instance, which means they have to be in the same subnet or proper firewall rulesets are required to be in place.

The current config generation module and templates could be easily adapted to support config generation for services on different nodes.

Thanks

**Comment by merlin44** [comment]
Thanks for these valuable ideas! I would really appreciate if you could publish patches / configs for the proposed modifications as it sounds that you have already implemented them.

From what I have read in other pull requests and issues, the maintainer of Froxlor is not very open for changes or even discussions and mostly dismisses them in an arrogant and daunting tone. Probably this also explains why nobody strives to contribute to this project any further.

Irrespective of whether these changes would be integrated into the official version, I would really welcome you sharing them.

**Comment by d00p** [comment]
I do not dismiss anything without reasons...but thanks that you clearly appreciate an Open source Project which costs lots and lots of hours of my time with badmouthing me.
