### ISSUE TITLE
Implementing the Domain Connect protocol to support external DNS providers

### ISSUE THREAD

**Issue by schallertd** [Froxlor/Froxlor#442]
> Configuring a service such as mail or web hosting to work with a domain name is a complex and difficult task for users. This is because most services require changes to the DNS settings associated with a domain, and users don’t understand DNS. Domain Connect is a protocol that makes this easier for the user, and more consistent across providers. The protocol involves two parties.  DNS Providers who run DNS for a domain, and Service Providers who provide the services and applications attached to domains.

http://domainconnect.org/
http://domainconnect.org/dns-providers/
https://github.com/Domain-Connect/spec/blob/master/Domain%20Connect%20Spec%20Draft.pdf
https://datatracker.ietf.org/doc/draft-carney-regext-domainconnect/

**Comment by d00p** [comment]
Souonds good, also "using" or building upon our dns editor makes the most sense. Looking forward for a pull-request

**Comment by schallertd** [comment]
Unfortunately it's not working that way. Domain Connect only allows pre-defined zone templates for each service provider (eq. for initial connection of a domain like A, MX, TXT records). It wont allow manipulation of a domain's DNS on the fly.
