### ISSUE TITLE
[DNS Editor] SRV Entries and double dots ".." at the end

### ISSUE THREAD

**Issue by mklooss** [Froxlor/Froxlor#446]
# System information
* Froxlor version: 0.9.38.7
* Web server: apache2 for Customer (froxlor runs on nginx)
* DNS server: PowerDNS (Bind-backend)
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian Jessie amd64

# Steps to reproduce
1.
```
Record: _test._tcp
Type: SRV
Prior: 5
Content: 0 41144 test.domain.eu.
TTL: 3200
```
2. Save
3. Entry in DB of "Content" is now "0 41144 test.domain.eu.."

# Expected behavior

Steps 1 and 2 of "Steps to reproduce"
3. "0 41144 test.domain.eu."

i've created an crontask which fixed entries like that.

**Comment by mklooss** [comment]
my corrently crontab to fix this issues is this line.

```
echo -e 'UPDATE `domain_dns_entries` SET content = REPLACE(content, "..", ".") WHERE content LIKE "%.."' | mysql --defaults-file=/etc/mysql/debian.cnf froxlor
```

**Comment by d00p** [comment]
Can you check whether this patch fixes the issue? -> https://gist.github.com/d00p/e4c7a0d3605ac3b5cb5ffd3e028543ef
