### ISSUE TITLE
[DNS Editor] Subdomain with wildcard

### ISSUE THREAD

**Issue by mklooss** [Froxlor/Froxlor#447]
# System information
* Froxlor version: 0.9.38.7
* Web server: apache2 for Customer (froxlor runs on nginx)
* DNS server: PowerDNS (Bind-backend)
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian Jessie amd64

# Steps to reproduce

1. Add an Entry with the Subdomain as Type: "A" with the "Record"
"*.home"
2. save
3. Error Message: "The subdomain *.home contains invalid characters."

**Comment by d00p** [comment]
Please try the following changes -> https://gist.github.com/d00p/bf193d84370e78c4a652f78b49fdb23e

**Comment by mklooss** [comment]
thanks, yep it works,

but i have to also backports this commit :)

https://github.com/Froxlor/Froxlor/commit/8f4da0638e333d62d401879fb914b1f3945e94ae#diff-7433cd376203322a8a72605d218c0b0c

**Comment by d00p** [comment]
Well i assume you are Testing with current master :p
