### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by landabaso** [Froxlor/Froxlor#452]
I'm planning to update from Precise Ubuntu (which has already reached End Of Life support).
I guess I'll need to update Froxlor first since there are no scripts available for Zesty Zapus.

I'm running Froxlor 0.9.31.2.

I'd like to make sure which Ubuntu versions are supported on newer Froxlor versions before updating. However, I cannot find any list of changes or supported versions anywhere in the Wiki or the main Website.

* Do you guys have that list of supported OSS per Froxlor verision?
* Do you have a list of changes per release so that we can make sure everything will go smooth before updating?
* Also, is it there a guide or anything that we need to take into account before updating a Linux Distribution (Ubuntu Precise -> Zesty Zapus, for example)?

Thanks for all the work in this wonderful project!

**Comment by d00p** [comment]
Please do not use the issue-tracker for questions, that's what the forum (https://forum.froxlor.org) is for. Thank you
