### ISSUE TITLE
libnss-extrausers files not updated after FTP-User changes

### ISSUE THREAD

**Issue by fager** [Froxlor/Froxlor#454]
# Summary

libnss-extrausers files are only updated after new FTP-Users created. Changes of existing FTP-User Settings (shell, passwd, path) are not published to libnss-extrausers files.

# System information
* Froxlor version: c68682b0842dec23197c3673e49abdf123c8cc54
* Web server: apache2/php-fpm
* DNS server: not in use
* POP/IMAP server: not in use
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Ubuntu 16.04

Configuration with Debian 8.0 Templates

# Steps to reproduce

1. System configured for libnss-extrausers and FTP-shell selection enabled
2. create a new FTP-user with shell /bin/bash
3. wait for next master cronjob
4. "cat /var/lib/extrausers/passwd | grep FTPUSERNAME" contains /bin/bash
5. change FTP-user to shell /bin/false
6. wait for next master cronjob
7. "cat /var/lib/extrausers/passwd | grep FTPUSERNAME" contains /bin/bash instead of /bin/false

# Expected behavior

1. /var/lib/extrausers/* should be recreated after relevant User-Changes

# Actual behavior

1. /var/lib/extrausers/* File are only updated after FTP-User-Creation

# Log files/log entries
no System log entries after FTP-User-update

**Comment by d00p** [comment]
can you verify that the following patch resolves the issue?
https://gist.github.com/d00p/b1921241424c6c9b5b8fae8ae7f8ab70

**Comment by fager** [comment]
Yes. This patch works.
Verified Actions:

- change shell
- change path
- change password
- del user

Thanks for your quick answer.
