### ISSUE TITLE
SMTP Server keine verbidnung nach update auf debian 9

### ISSUE THREAD

**Issue by C0kkie** [Froxlor/Froxlor#455]
# Bug report vs. support request
If you're unsure of whether your problem is a bug or a configuration error
* contact us via IRC in #froxlor on freenode
* or post a thread in our forum at https://forum.froxlor.org

As a rule of thumb: before reporting an issue
* see if it hasn't been [reported](https://github.com/Froxlor/froxlor/issues) (and possibly already been [fixed](https://github.com/Froxlor/froxlor/issues?utf8=✓&q=is:issue%20is:closed)) first
* try with the git master

# Summary

Please provide a concise summary of the problem you're experiencing...

# System information
* Froxlor version: $version/$gitSHA1
* Web server: apache2/nginx/lighttpd
* DNS server: Bind/PowerDNS (standalone)/PowerDNS (Bind-backend)
* POP/IMAP server: Courier/Dovecot
* SMTP server: postfix/exim
* FTP server: proftpd/pureftpd
* OS/Version: ...

Seitdem ich gestern auf Debian 9 geupdated habe, kann ich keine Mals mehr empfangen doer senden via thunderbird, angeblich ist der SMTP Server nicht erreichbar

**Comment by d00p** [comment]
A) you are supposed to USE the issue template, not POST it

B) for Support, use the forum
