### ISSUE TITLE
https://demo.froxlor.org isn't accepting credentials.

### ISSUE THREAD

**Issue by roborich** [Froxlor/Froxlor#456]
I am unable to log into the Froxlor Demo.  It reloads the page completely on the form submission, and displays this error above the form.
```
Error
This account has been suspended because of too many login errors. 
Please try again in 900 seconds.
```

the following error is logged to the console
```
Unrecognized Content-Security-Policy directive 'reflected-xss'.
```

I have tried again after waiting the 900 seconds.  I've returned to the site and tried multiple times throughout the day.

**Comment by d00p** [comment]
yeah there isn't any reset-script yet...havent had the time since the servercrash
