### ISSUE TITLE
Proposal: custom try_files on Nginx

### ISSUE THREAD

**Issue by negrusti** [Froxlor/Froxlor#461]
Most of WordPress static caching plugins require modifications of try_files for root location.
It seems at present there is no possibility to achieve this in Froxlor.
Perhaps just a switch "do not generate default try_files", and then merging custom try_files directive from domain specialsettings will be sufficient.
Sample configurations:
Cache Enabler - 
https://www.keycdn.com/support/wordpress-cache-enabler-plugin/
WP Super Cache - 
https://codex.wordpress.org/Nginx#WP_Super_Cache_Rules
W3TC -
https://codex.wordpress.org/Nginx#W3_Total_Cache_Rules

**Comment by EricReiche** [comment]
I just wanted to push this.
Before switching to Nginx I assumed that I can use the custom domain configs for that, but now realized that it's impossible.

**Comment by negrusti** [comment]
I am not sure what the best approach is.
One option is to add a field to domains table "try_files", default value 1, and then add another condition in
/scripts/jobs/cron_tasks.inc.http.30.nginx.php
`if ($domain['phpenabled_customer'] == 1 && $domain['phpenabled_vhost'] == '1') {`
change to
`if ($domain['phpenabled_customer'] == 1 && $domain['phpenabled_vhost'] == '1' && $domain['try_files'] == 1) {`

**Comment by EricReiche** [comment]
Maybe add a try_files domain attribute which overwrites default config if not empty.

**Comment by d00p** [comment]
Theres always the "specialsettings" field per.domain to add custom content. @negrusti is right, it should Just be possible to disable the automatically generated try_files entry

**Comment by negrusti** [comment]
You mean keep the actual try_files string in that field? Could be too

**Comment by kezenwa** [comment]
Hi All, Please I want to know how current FROXLOR users are able to host WordPress websites on NGINX.

I asked this question in FROXLOR forum but has gotten no response. I want to know how current FROXLOR users are able to host wordpress websites and some other PHP websites on NGINX webserver .
My machine configuration are : 
CENTOS 7 + NGINX + PHP-FPM + PHP7.1 

Waiting for urgent response

**Comment by negrusti** [comment]
I do it like this:
https://gitlab.com/negrusti/Froxlor/compare/master...try_files?view=inline
So if there are any special vhost settings present, default try_files won't be generated. 
Please note that it will break all existing vhosts with special settings - you will need to add try_files manually to them.

**Comment by kezenwa** [comment]
@negrusti 
Is this an Update or what ?

I last downloaded FROXLOR 1 Month ago .
Please do let me know if this is an official Update or a Patch so at least I know what to do.

Also is this how most FROXLOR users are able to host PHP enabled websites such as WordPress on NGINX + PHP-FPM  ?

Thanks for your help

**Comment by kezenwa** [comment]
To apply the above suggestion, do I download a new FROXLOR from FROXLOR website or from Github ?

Also any way to stop FROXLOR from deleting  the default  "www.conf"   File    in   "/etc/php-fpm.d  folder ?

**Comment by d00p** [comment]
@kezenwa this is not our support forum.

**Comment by schnuffle** [comment]
+1
I'm using  a nearly similar patch to be able to customize the  try_files directive for the / location. 
For people that do not dive into code it might be a good idea that there's a flag activating special settings which introduces the try_files block into the special settings at first creation.
Afterwards it can be customized.

Regards

Schnuffle

**Comment by negrusti** [comment]
Many thanks!
