### ISSUE TITLE
Adding domain gives "General error: 1364 Field 'dkim_id' doesn't have a default value"

### ISSUE THREAD

**Issue by Linutux** [Froxlor/Froxlor#462]
When I try to add a subdomain in the customer's panel, all I get is:
A database error occurred
SQLSTATE[HY000]: General error: 1364 Field 'dkim_id' doesn't have a default value

What can I do about it?

Froxlor Version: 0.9.38.7
OS Version: Ubuntu 16.04

**Comment by d00p** [comment]
As always: froxlor does not yet Support MySQL Strict-mode...
