### ISSUE TITLE
Enhancement: Global email and file templates

### ISSUE THREAD

**Issue by christianhennen** [Froxlor/Froxlor#463]
Hi!

Here at @ZIMK we recently noticed that the customizable email and file templates are admin-specific. Since we configured every template to include our contact details and links to help resources, every admin is required to use the exact same templates. Right now, we copy them via database when a new admin is created or a template has been changed. 

For us, it would be beneficial to be able to configure and use these templates globally. Maybe this could be realized by introducing a 'global' flag for templates which could then be used in case no admin-specific templates are present. This wouldn't break the current functionality of admin-specific templates. Are there any plans on incorporating this and if not: What are your thoughts on this?

Thanks,
Chris

**Comment by d00p** [comment]
Sounds good to me. Would you be able to do that and create a pull request?

**Comment by christianhennen** [comment]
We're looking into it :)

**Comment by d00p** [comment]
No PR after 6 months, close
