### ISSUE TITLE
libnss-extrausers file permissions are too restrictive.

### ISSUE THREAD

**Issue by discordier** [Froxlor/Froxlor#465]
# Summary

When using `libnss-extrausers`, the herein added users are not able to login (either ssh or su) due to too restrictive file permissions.

|file/dir | permission (is) | permission (should) |
|-------|----|----|
| d `/var/lib/extrausers/` | `0700` | `0755` |
| f `/var/lib/extrausers/passwd` | `0644` | `0644` |
| f `/var/lib/extrausers/group` | `0644` | `0644` |
| f `/var/lib/extrausers/shadow` | `0644` | `0640` |

The permissions of the directory `/var/lib/extrausers/` are currently set to `0700` (See [class.Extrausers.php#L45](https://github.com/Froxlor/Froxlor/blob/a2e0de23e1ed19a8c174b09edcdf559d98b1b5d0/scripts/classes/class.Extrausers.php#L45)) but should be `0755`.
Permissions of the contained files turn out to be `0644`, however this should only apply to `/var/lib/extrausers/passwd` and `/var/lib/extrausers/group`, the file `/var/lib/extrausers/shadow` should be `0640`. To make a long story short, the files permissions should be the same as for the files in `/etc`

# System information
* Froxlor version: 0.9.38.7-1 + extrausers patches
* OS/Version: Debian stretch

# Steps to reproduce

1. Configure System with `libnss-extrausers` and let Froxlor generate the files.
2. On any root shell try `su web1 -s /bin/bash`

# Expected behavior

1. The user should be logged in.

# Actual behavior
The login is rejected.

# Log files/log entries
In `/var/log/auth` you will get:
```
su[10068]: No passwd entry for user 'web2'
su[10068]: FAILED su for web2 by root
```

**Comment by d00p** [comment]
Did you give the Users a real shell? Default is /bin/false...

**Comment by discordier** [comment]
I did.
The problem is not the shell but simply the permissions.
After fixing them as written above everything works like a charm. Otherwise you'll end up having problems ranging from "no such user" to `I have no name@server$` prompt if you should happen to get a shell due to `nscd`still having cached an user.

The problem is, that non privileged processes have no right to read the `passwd` or `group` in default Froxlor permissions. However, they need it to know "who they are".
This is perfectly in sync how standard shadow handling works, passwd and group are world readable, soly `shadow` is root only (as it is the only one containing sensitive information).

**Comment by d00p** [comment]
okay, just wanted to be sure ;)

**Comment by d00p** [comment]
Could you test whether the following patch resolves the issues?
https://gist.github.com/d00p/14448229e669a9586fbef020564690f9

**Comment by discordier** [comment]
Yep, works just fine.
I did exactly the same by hand.
