### ISSUE TITLE
Bug: nscd cache is not cleared after changing shell for FTP user

### ISSUE THREAD

**Issue by negrusti** [Froxlor/Froxlor#466]
With libnss-mysql on Ubuntu:
Change the shell from /bin/false to /bin/bash for FTP user
Login as that user via SSH/SFTP would not be possible until nscd is restarted or it's cache is cleared manually.
Intended behavior: cron task for cache invalidation after shell change

**Comment by d00p** [comment]
Should already be done, when editing a ftp user, a task #5 is inserted and the cronjob always regenerates libnss-extrausers files (if enabled) and runs **nscd -i group** if a job has run
