### ISSUE TITLE
Proposal: Add integration for CouchDB 

### ISSUE THREAD

**Issue by stracker-phil** [Froxlor/Froxlor#467]
# Summary

Currently froxlor comes with the customer_mysql.php module to manage MySQL databases only.

We need to provide an integration for CouchDB as well: http://couchdb.apache.org/

# Required features

* List existing databases
* Create new databases
* Delete databases
* Open an existing database with the built-in CouchDB UI "Futon"

**Comment by d00p** [comment]
You're welcome to do that and create a pull-request. I personally don't think this is something for the common user. Also it does not even seem to support PDO, which makes integration way more work
