### ISSUE TITLE
ab ins dist repo

### ISSUE THREAD

**Issue by flobee** [Froxlor/Froxlor#468]
Jungs: debian ist euer distribution channel. syscp anfänge mit erlebt, dann upgrade via debian und ich war glücklich. so erreicht ihr einfach mehr leute. das netz ist einfach zu voll mit vielerlei dingen und im linux bereich ist debian oder ubuntu das none plus ultra um software zu bekommen. go for it :)

**Comment by d00p** [comment]
Junge: beschäftige dich bitte zunächst mit den Richtlinien von Debian - wir erfüllen Sie schlichtweg nicht und werden es vermutlich auch nie (Generierung von Confings in Ordner von "anderen" Paketen, etc.) - Thema schon tausendmal gehabt und diskutiert.

**Comment by flobee** [comment]
Wow, was für eine wertschätzende Kommunikation.

**Comment by d00p** [comment]
"Jungs" ist ok, Singular aber nicht? Und viel zu wertschätzen gab es bei deinem issue wohl nicht: "ey, macht ma" als wäre das was was Mal eben gemacht werden kann, und dann kennst du anscheinend die Vorgaben und Richtlinien nicht, sonst hättest du das issue nicht so verfasst.

**Comment by flobee** [comment]
Es tut mir leid wenn mein Vorschlag bei dir druck Auslöst. 
Vielleicht habe ich es einfach zu salopp formuliert, mein Fehler: "Könnte es Sinn machen die App wieder in die Verteilung der Betriebsysteme, z.b Debian, wieder auf zu nehmen?

Danke für Feedback
Issue kann geschlossen werden. 
LG

**Comment by d00p** [comment]
Wieso wieder aufnehmen? Wir waren da noch nie drin

**Comment by flobee** [comment]
syscp|froxlor, syscp hats doch mal ins debian geschafft, oder irre ich mich? ist zwar schon ne weile her aber ich meine da war was und deswegen kenne ich das "ding" überhaupt. Nun ja. Und nach einer weile , und da ich die Software mag, hilft es vielleicht gegenüber den anderen Monstern die es so gibt :)
