### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by MatthiasLohr** [Froxlor/Froxlor#470]
Hey,

when do you provide a new release? I'm waiting for the deployment of the PHP subdomain fix (https://github.com/Froxlor/Froxlor/commit/2d59e569df709caf7ca5af441235348d6abbc941)... Would be really useful ;) Thanks in advance!

Best regards
Matthias

**Comment by d00p** [comment]
As soon as we have config-templates for debian-stretch; also, it is stable enough to use the current state (https://github.com/Froxlor/Froxlor/archive/master.zip)
