### ISSUE TITLE
libnss-extrausers template error

### ISSUE THREAD

**Issue by Af0x** [Froxlor/Froxlor#474]
hi, 

on following step I get an error on Debian Stretch:
/usr/bin/nano /etc/nsswitch.conf

It says "file not found". Before it was moved to .bak-extension. I changed the command to 
"nano /etc/nsswitch.conf" and it worked.

Regards,

Af0x

**Comment by d00p** [comment]
that is because nano resides in /bin instead of /usr/bin...there are many more things that need to be done in the stretch config template
