### ISSUE TITLE
URL to FPM article points to redmine.froxlor

### ISSUE THREAD

**Issue by pquerner** [Froxlor/Froxlor#477]
If PHP-FPM is activated, the FPM Articles from old redmine help wiki are pointed still in the template somewhere.

Screenshot:
![image](https://user-images.githubusercontent.com/4364044/30651955-61589bce-9e27-11e7-882e-325fded8490b.png)

Apache2 Link: http://redmine.froxlor.org/projects/froxlor/wiki/HandbookApache2_phpfpm
Nginx Link: http://redmine.froxlor.org/projects/froxlor/wiki/HandbookNginx_phpfpm

Should point to this githubs wiki.

# System information
* Froxlor version: 0.9.38.7
(others dont matter)

# Steps to reproduce

1. Login as admin in froxlor backend
2. (Have PHP-FPM activated)
3. Check links in PHP-FPM settings

# Expected behavior

1. Login as admin in froxlor backend
2. (Have PHP-FPM activated)
3. Check links in PHP-FPM settings
4. PHP-FPM handbooks should be hotlinked to githubs wiki

# Actual behavior

1. Login as admin in froxlor backend
2. (Have PHP-FPM activated)
3. Check links in PHP-FPM settings
4. You'll see wrong links to the handbooks at the top of the page (still pointing to redmine.froxlor.org)

**Comment by mainboarder** [comment]
in der aktuellen https://github.com/Froxlor/Froxlor/blob/master/lng/german.lng.php ist das nicht mehr drin, dafür finden sich dort die Verweise auf die korrekten URLs.
(Suche nach redmine bringt nichts, "FPM-Handbuch" dagegen bringt die Zeile mit dem Link zu Github)
