### ISSUE TITLE
Cronjob does not recognize imported domains?

### ISSUE THREAD

**Issue by Af0x** [Froxlor/Froxlor#478]
Hello,

after an import of domains, froxlor does not use the new domains within its cronjobs (config and LE) so that I had to manually open and save all imported domains again. 

I am not sure if this was my fault because I also edited the domains after the import via SQL.

Regards,

Af0x

**Comment by d00p** [comment]
Have you tried forcing the cronjob with --force parameter?

**Comment by Af0x** [comment]
yes

**Comment by d00p** [comment]
Can you provide the import-CSV so I can test with your data? d00p@froxlor.org if you do not want it published

**Comment by Af0x** [comment]
I add an example here. Just rename to example.csv. Regards!
[example.txt](https://github.com/Froxlor/Froxlor/files/1360978/example.txt)

**Comment by d00p** [comment]
what froxlor version are you using? Testing please only with current master branch and then you are missing required fields, see https://github.com/Froxlor/Froxlor/wiki/Domain-import-documenation

**Comment by d00p** [comment]
But yeah there is an inserttask missing so that the regeneration of configs is triggered and there seems to be a problem with the aliasdomain NULL value, but as said, you need to test with current git-master

**Comment by Af0x** [comment]
thank you d00p :)
