### ISSUE TITLE
PHP 7.2 deprecation warning

### ISSUE THREAD

**Issue by michaelzangl** [Froxlor/Froxlor#479]
# System information
* Froxlor version: 0.9.38.7-1
* Web server: apache2
* PHP-Version: | 7.2.0RC3

# Steps to reproduce
Use PHP 7.2, open home page

A warning appears:
```
#8192 The each() function is deprecated. This message will be suppressed on further calls
/var/www/froxlor/lib/functions/phphelpers/function.array_trim.php:34
```

**Comment by d00p** [comment]
just a deprecation warning, but thanks...the focus is not really on php-7.2 yet :)

**Comment by michaelzangl** [comment]
Other than that it seems to work well and I did not find anything that is broken (except that you have to adjust the paths to php-fpm)
