### ISSUE TITLE
Let's Encrypt no longer works when Domain errors out

### ISSUE THREAD

**Issue by chaos234** [Froxlor/Froxlor#480]
When a Domain makes a request to Let's Encrypt and errors out it blocks other requests from other Domains.

This should be caught so that the request get canceld after the 3rd error.
Each Block below is triggered 2-5 times and no, I did not changed anything on my system.

# System information
* Froxlor version: $version/$gitSHA1
* Web server: nginx/
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian 8 (latest)

# Log files/log entries
syslog:
<pre>
Could not get Let's Encrypt certificate for xxx: Verification ended with error: {"identifier":{"type":"dns","value":"xxx"},"status":"invalid","expires":"2017-10-19T21:10:07Z","challenges":[{"type":"dns-01","status":"pending","uri":"https:\/\/acme-v01.api.letsencrypt.org\/acme\/challenge\/zW8QIEYuAoeeUlplOQqVtyZ5poyN-mDR-qYs398mUnk\/2191075798","token":"zS2FnhcdaMGXXLtJZ4YjIosXCKpUit0JzISXh9VMQVM"},{"type":"http-01","status":"invalid","error":{"type":"urn:acme:error:unauthorized","detail":"Invalid response from http:\/\/xxx\/.well-known\/acme-challenge\/qn08Bdi5V82VJ3302BhIThgsuLOBtJQhclbhJzxBIfE [2a00:f48:2000:affe:fe00::6]: 404","status":403},"uri":"https:\/\/acme-v01.api.letsencrypt.org\/acme\/challenge\/zW8QIEYuAoeeUlplOQqVtyZ5poyN-mDR-qYs398mUnk\/2191075799","token":"qn08Bdi5V82VJ3302BhIThgsuLOBtJQhclbhJzxBIfE","keyAuthorization":"qn08Bdi5V82VJ3302BhIThgsuLOBtJQhclbhJzxBIfE.3mDRa2uuPrY4ScOuWLlHF_ivCTGS60U94exiwcaibNI","validationRecord":[{"url":"http:\/\/xxx\/.well-known\/acme-challenge\/qn08Bdi5V82VJ3302BhIThgsuLOBtJQhclbhJzxBIfE","hostname":"xxx","port":"80","addressesResolved":["46.4.77.233","2a00:f48:2000:affe:fe00::6","2a00:f48:2000:affe:fe00::36","2a00:f48:2000:affe:fe00::33","2a00:f48:2000:affe:fe00::24"],"addressUsed":"2a00:f48:2000:affe:fe00::6","addressesTried":[]}]},{"type":"tls-sni-01","status":"pending","uri":"https:\/\/acme-v01.api.letsencrypt.org\/acme\/challenge\/zW8QIEYuAoeeUlplOQqVtyZ5poyN-mDR-qYs398mUnk\/2191075800","token":"HQG-jONSRusu5NUMwBKA5bbGQeUnzrPxnA07yhg-8PY"}],"combinations":[[0],[1],[2]]}

letsencrypt Please check http://xxx/.well-known/acme-challenge/qn08Bdi5V82VJ3302BhIThgsuLOBtJQhclbhJzxBIfE - token not available; PHP error: {"type":2,"message":"file_get_contents(http:\/\/xxx\/.well-known\/acme-challenge\/qn08Bdi5V82VJ3302BhIThgsuLOBtJQhclbhJzxBIfE): failed to open stream: HTTP request failed! HTTP\/1.1 000 \r\n","file":"\/var\/www\/froxlor\/lib\/classes\/ssl\/class.lescript.php","line":232}

Could not get Let's Encrypt certificate for xxx: No challenges received for 3d.yannickfelix.ml. Whole response: {"type":"urn:acme:error:rateLimited","detail":"Error creating new authz :: Too many invalid authorizations recently.","status":429}
</pre>

**Comment by d00p** [comment]
Well that's what the self-check is for (see https://github.com/Froxlor/Froxlor/blob/master/lib/classes/ssl/class.lescript.php#L229 ) befor sending anything to Let's Encrypt

**Comment by chaos234** [comment]
Any responses to this problem?

Because a secound Domain hast this problem and errored out with a 404 that it can not finde the file :(
