### ISSUE TITLE
Feature: "User create sub domain" fails

### ISSUE THREAD

**Issue by friedrich-daniel** [Froxlor/Froxlor#481]
# Summary

Feature: "User create sub domain" fails
Error Message:
A database error occurred
SQLSTATE[HY000]: General error: 1364 Field 'dkim_id' doesn't have a default value

# System information
* Froxlor version: 0.9.38.7 (DB: 201612110)
* mysql version: Ver 14.14 Distrib 5.7.19, for Linux (x86_64) using  EditLine wrapper
* Web server: apache2
* DNS server: -
* POP/IMAP server: -
* SMTP server: -
* FTP server: -
* OS/Version: ...

# Steps to reproduce

1. Login as customer
2. Create sub domain

# Expected behavior

1. Login success
2. Sub domain will be created

# Actual behavior

1. Login success
2. MySql error message

# Log files/log entries
syslog:
<pre>
n/a
</pre>

**Comment by d00p** [comment]
as always, disable mysql-strictmode as froxlor is not yet compatible with that
