### ISSUE TITLE
Stored Cross-site Scripting (XSS)

### ISSUE THREAD

**Issue by ProDigySML** [Froxlor/Froxlor#483]
# Summary
Stored Cross-site Scripting (XSS) in page name allowing a user to get arbitrary JS execution. This isn't really a big issue as the website already has all session tokens using HTTPOnly, and you need to be an administrator (if using as the default) to post. It is quite reasonable for organisations to make other roles for contributors/authors, hence being worth the patch. I'm not too sure if this is still an issue in v3, as I couldn't get the server set up for it yet. 

# System information
* Froxlor version: v2.3.1-17-g6f82e6c	
* Web server: apache2
* DNS server: Bind
* POP/IMAP server: Courier
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Ubuntu 16.04

# Steps to reproduce

1. Log into the website
2. Create a new page
3. Set the page's name to `<img src=x onerror=alert(1)`
4. Visit the page list section of the admin panel and observe an alert box pop up. 

# Expected behavior

1. `<img src=x onerror=alert(1)` is HTML Encoded

# Actual behavior

1. JS code is arbitrarily executed

**Comment by d00p** [comment]
Are you sure you are talking about froxlor? There's no version anywhere near 2.3 (it's 0.9.x) and no "create new page"....

**Comment by ProDigySML** [comment]
Hi @d00p . Apologies, this was for a different application, but we did find XSS in the website. The X-XSS protection header counteracts the vulnerability in most major browsers. Would you still be interested in the issue, or would you like to close it?

**Comment by d00p** [comment]
Security related issues please via e-mail to team@froxlor.org first so we can fix it and release a new version for everyone to install before publishing it to the Internet ;)
