### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by vmp32k** [Froxlor/Froxlor#484]
# Summary

On the details page of an email address (*customer_email.php*), which happens to have forwarders, the following error occurs and none of the forwarders are being shown:

```
#2 Invalid argument supplied for foreach()
/customer_email.php:327	
```

The issue appears to have been introduced with: https://github.com/Froxlor/Froxlor/commit/421c29c4918a1fa193846cede4373b045b5d33f3

Using the following patch (partially reverting the commit above) resolves the issue (on PHP 7.1 at least):

```
diff --git a/customer_email.php b/customer_email.php
index 479493d6..a31d55eb 100644
--- a/customer_email.php
+++ b/customer_email.php
@@ -324,7 +324,7 @@ if ($page == 'overview') {
                        $forwarders = '';
                        $forwarders_count = 0;

-                       foreach ($row['destination'] as $dest_id => $destination) {
+                       while (list($dest_id, $destination) = each($result['destination'])) {
                                $destination = $idna_convert->decode($destination);
```

# System information
* Froxlor version: master 421c29c4918a1fa193846cede4373b045b5d33f3
* Web server: nginx 1.13.6, PHP 7.1.11-1+0\~20171027135525.10+stretch\~1.gbp2e638d
* DNS server: none
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian 9.2 (stretch)

# Steps to reproduce

1. Create a customer with an email address
2. Add a forwarder to the newly created email address
3. Click the email address to get to the "*Edit email-address*" page

# Expected behavior

1. Seeing a detail listing of the email address including the forwarders

# Actual behavior

1. A detail listing of the email address with **zero** forwarders
  `Forwarders (0): | Create forwarder`

# Log files/log entries
n/a

**Comment by d00p** [comment]
$row <> $result - stupid typo :p will fix asap
