### ISSUE TITLE
Apache 2.4: PHP disabled = vhost can't serve any files

### ISSUE THREAD

**Issue by ripieces** [Froxlor/Froxlor#485]
# Summary

When PHP is not enabled, the vhost file generated doesn't allow accessing files in the document root with Apache 2.4.

# System information
* Froxlor version: `0.9.38.7-1 (DB: 201612110)`
* Web server: `apache2/stable,stable,now 2.4.25-3+deb9u3 amd64 [installed]`
* OS/Version: `Linux xxx 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux`

# Steps to reproduce

1) Disable PHP on the domain or customer.
2) Try to access any file.

# Expected behavior

Files get served.

# Actual behavior

403 Forbidden

# Log files/log entries

/var/customers/logs/customer-error.log
<pre>
[Mon Nov 06 21:34:03.366181 2017] [authz_core:error] [pid 11159] [client xxx.xxx.xxx.xxx:xxxxx] AH01630: client denied by server configuration: /var/customers/webs/customer/domain/index.html
</pre>

# Possible solution:
Add this directive similarily to how it's done with PHP-enabeld vhosts:
```
  <Directory "/var/customers/webs/customer/domain/">
    Require all granted
    AllowOverride All
  </Directory>
```
Not sure if AllowOverride All is a good idea, but that is what the PHP vhosts have too.

**Comment by d00p** [comment]
Can you please test with the current git-master code? I remember already being told about this

**Comment by ripieces** [comment]
Thank you for your reply. Sadly it's not fixed for my case, since I am using `Webserver interface:  FPM-FCGI`.

It's using https://github.com/Froxlor/Froxlor/blob/master/scripts/jobs/cron_tasks.inc.http.15.apache_fcgid.php in that case I think, which doesn't create that directive when PHP is not enabled.
