### ISSUE TITLE
Invalid open_basedir with php-fpm

### ISSUE THREAD

**Issue by lobeck** [Froxlor/Froxlor#487]
A customer managed to create a invalid config and thus php-fpm fails to reload and crashes.

When creating a new subdomain, the customer entered the following path:

`/https://docs.google.com/document/d/$DOCUMENTID/?editusp=sharing`

Note the `/` and the `=`.

This creates a php-fpm config with the following line:

`php_admin_value[open_basedir] = "/var/customers/webs/$CUSTOMER/https/docs.google.com/document/d/$DOCUMENTID/editusp`

Note the path gets cut at the `=` and therefore the line is lacking the closing quote.

I've already analyzed it and found several validation issues here and i'm not sure on which one to patch.

- check for colon is too late

https://github.com/Froxlor/Froxlor/blob/master/customer_domains.php#L337-L339

Should be moved to line 330.

- code duplication in `customer_domains.php`

https://github.com/Froxlor/Froxlor/blob/master/customer_domains.php#L581-L583

the same as above and all of the checks are duplicated here.

- makeSecurePath not killing `=`

https://github.com/Froxlor/Froxlor/blob/master/lib/functions/filedir/function.makeSecurePath.php#L32

Not sure if this needs fixing, but would be another way to remediate it. (Thats also the reason why the colon check is never triggered, as `makeSecurePath` kills the colon)

- no lengths check in fpm interface

https://github.com/Froxlor/Froxlor/blob/master/lib/classes/phpinterface/class.phpinterface_fpm.php#L296

Only values 0 and 1 of the explode result are used, but it's never checked for left over values, so maybe we could check here for `len() == 2`

If you drop me some hints on where you'd like the fixes, i'll happily apply them and create PRs.

**Comment by d00p** [comment]
thanks for the deep analysis
