### ISSUE TITLE
Support Let's Encrypt directory meta terms-of-service

### ISSUE THREAD

**Issue by cpu** [Froxlor/Froxlor#488]
Hi folks :wave:

I noticed that `class.lescript.php` has [a TODO about the Let's Encrypt `/directory` not returning a meta element with a `terms-of-service` key](
 https://github.com/Froxlor/Froxlor/blob/5540b02e352fc421763d01d4e69beca6fd6ea11d/lib/classes/ssl/class.lescript.php#L600:L605
):
> 		// FIXME: Current license should be found in /directory but LE does not implement this yet

I wanted to file a quick note that [we have implemented this for the production API endpoint](https://community.letsencrypt.org/t/api-directory-endpoint-meta-field-addition/38526) and Froxlor can now implement this feature.

Thanks!

**Comment by Dessa** [comment]
maybe we should merge analogic/lescript@4d07bb1d67d295fe71b6734f7627cbc7c68d3924 (and the other commits leading up to version 0.1.6 of the script if applicable) into our copy, which seems to implement this.

**Comment by d00p** [comment]
done
