### ISSUE TITLE
Restart of Dovecot after letsencrypt certificate update

### ISSUE THREAD

**Issue by SebiGo** [Froxlor/Froxlor#489]
# Summary
I have experienced twice so far, that once the letsencrypt certificate was renewed automatically, dovecot (and potentially postfix?) were still working with the expired certificate. Therefore mail clients were prompting an certificate exception. A simple service restart fixed the issue.

# System information
* Froxlor version: 0.9.38.7-1
* Web server: Apache
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: n/a
* OS/Version: Debian Jessie

# Steps to reproduce
1. Enable LetsEncrypt, issue a certificate for your mail domain
2. Enable SMTPS-Section in Dovecot/Postfix (/etc/dovecot/conf.d/10-ssl.conf)
3. Wait for 90 days until certificate expiry

# Expected behavior
1. Once the certificate is renewed, Dovecot/Postfix are reloaded and the new certificate is used

# Actual behavior
1. Dovecot is not reloaded and still works with the old certificate

**Comment by d00p** [comment]
well, technically you can of course use the froxlor generated certificates for others services, but restarting them on renew is not froxlor's task. We restart the webserver as we are generating ssl certificates for WEB.
What you can do is, writing a little batch-script and use this as "webserver reload command". It can on the side restart apache and on the other side, check whether the ssl-certs have changed and then restart or do whatever you need :)
