### ISSUE TITLE
FR: Journaling Function like Exchange Journaling for Customers

### ISSUE THREAD

**Issue by Jazz7584** [Froxlor/Froxlor#490]
FeatureRequest:
What about a Journaling Function providing per customer?

- Creating a journal@domain.de Mailbox
- Copy everyemail sent or received for this customer in this Mailbox
- per each domain or just the whole customer

So then a archiving software could archive the emails.

In germany it's for business since 2017 necessary.

Thanks for reply.
Jazz

EDIT:::
I've created the hack for Postfix in the console, so froxlor just needs to integrate it in the WEB UI
1. Create a mysql table

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS `journal_virtual` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `domain` varchar(255) NOT NULL DEFAULT '',
  `destination` text NOT NULL,
  `domainid` int(11) NOT NULL DEFAULT '0',
  `customerid` int(11) NOT NULL DEFAULT '0',
  `popaccountid` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `email` (`domain`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=390 ;

2. Create a Mailbox for Journal Emails like journal@domain.tld

3. Add at /etc/postfix/main.cf
##### Journaling

recipient_bcc_maps=mysql:/etc/postfix/mysql-virtual_journal_maps.cf
sender_bcc_maps=mysql:/etc/postfix/mysql-virtual_journal_maps.cf

4. create a file /etc/postfix/mysql-virtual_journal_maps.cf
user = <USER>
password = <PASSWORD>
dbname = froxlor
table = journal_virtual
select_field = destination
where_field = domain
additional_conditions = and TRIM(destination) <> ''
hosts = 127.0.0.1 

5. Add in the mysql Table for domain @domain.tld like @test.de and in destination the Journalmailbox.

6. Done

**Comment by d00p** [comment]
"In germany it's for business since 2017 necessary." - hab ich nie was von gehört...

**Comment by willydee** [comment]
https://it-service.network/blog/2016/11/29/langzeitarchivierung-daten-gobd/

Having said that, it is not mandatory to store a copy of each and every
email, but anything that might be business and tax relevant.

A journaling mailbox as intended by the original poster can easily be
implemented using existing Froxlor functionality, at least for incoming
mails: just create a forwarding rule for every recipient you need to keep
track of. Storing a copy of outgoing mails requires some configuration in
the SMTP service, but that is beyond the scope of Froxlor.

Best,
willydee

**Comment by d00p** [comment]
Yup, don't think that's froxlor's business. If you need that for whatever reason, adjust your mailserver configs to do these actions globally, nothing froxlor needs to do specifically

**Comment by Jazz7584** [comment]
Hi
Wolllte ja auch nur mal was beitragen. Und wie gesagt im business Umfeld ist es ein muss. eine Forward Regel reicht ja nicht da die gesendeten emails eben fehlen. 

Aber gut schade dachte könnte helfen.
LG Jazz

**Comment by d00p** [comment]
Firmen die das Umsetzen (müssen) haben dafür sicherlich eine externe Archivierungs-Lösung. Froxlor hat damit kaum mehr was zu tun. Das ist vorrangig eine Mailserver-Config Sache - ein Konto anzulegen dafür ist im Grunde schon "zu spät" und reicht auch sicherlich rechtlich gesehen nicht als "archiviert" aus (kann ich nicht 100% sagen)

**Comment by Jazz7584** [comment]
Hi
Ja das stimmt dass man eine externe Lösung benötigt. Aber damit die funktionieren benötigt man eben ein Journal Postfach welches alle E-Mails ein und ausgehend enthält. 
Nicht alle Firmen haben einen Exchange welcher genau das macht.
Über die oben gezeigte Lösung kann man das dann aber pro Domain festlegen. 

War ja wie gesagt nur ein Vorschlag und vielleicht kann es ja einer gebrauchen.
