### ISSUE TITLE
Add Session params for php vhost configuration

### ISSUE THREAD

**Issue by ryou90** [Froxlor/Froxlor#491]
Currently only php_admin_value[session.save_path] and php_admin_value[upload_tmp_dir] are configurable.

Please add the other session params.
Need this for setting up redis as session handler  

thx

**Comment by d00p** [comment]
Use .htaccess ...?

**Comment by ryou90** [comment]
Working with nginx ;)

**Comment by d00p** [comment]
Adjust php.ini?
