### ISSUE TITLE
 A database error occurred When Adding Customers

### ISSUE THREAD

**Issue by Blackphantom96** [Froxlor/Froxlor#495]
I have a LAMP stack running on Ubuntu 16.04, and I follow this instructions https://myvpsource.com/install-froxlor-ubuntu-16-04
bur when I try to create a customer this is the error message 

**A database error occurred
SQLSTATE[01000]: Warning: 1265 Data truncated for column 'add_date' at row 1**
 
thaks!

**Comment by d00p** [comment]
tested with the latest git-version?

**Comment by Blackphantom96** [comment]
Yep!

**Comment by d00p** [comment]
MySQL Strict Mode?

**Comment by Blackphantom96** [comment]
is off

**Comment by d00p** [comment]
Unable to reproduce...never had issues adding customers

**Comment by Blackphantom96** [comment]
I don't know, I just keep telling you.
