### ISSUE TITLE
TLSv1.1 missing from SSLOptions in Apache config

### ISSUE THREAD

**Issue by mgollo** [Froxlor/Froxlor#497]
I didn't find an existing issue using the GitHub search, so I guess it hasn't been reported yet.

# Summary
Froxlor produces Apache configs with TLSv1.0 and TLSv1.2 enabled, but TLSv1.1 disabled. It should enable all three or only TLSv1.1 and TLSv1.2.

# System information
* Froxlor version: 0.9.38.7-1 (from APT repo)
* Web server: apache2
* DNS server: none
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: none
* OS/Version: Debian GNU/Linux Jessie 8.10

# Steps to reproduce
1. Create an SSL vHost
2. Check TLS settings

# Expected behavior
The SSL settings should read SSLProtocol -ALL +TLSv1 +TLSv1.1 +TLSv1.2

# Actual behavior
The SSL settings do read SSLProtocol -ALL +TLSv1 +TLSv1.2

**Comment by Dessa** [comment]
i don't think there is added value in enabling tls1.1 since:
1. most (older) browsers disable it by default
2. these browsers which do not either:
2.1 support tls 1.2
2.2 don't *disable* tls 1.0
2.3 are horribly out of date

**Comment by mgollo** [comment]
AFAICT, changing this is a minor change without any downside, so I don't understand why your are opposing it even if there is not much added value. Even if it only adds value to one per mill of the users (meaning people connecting to a website managed by Froxlor), I would still consider it worth the effort.

**Comment by dphi** [comment]
@mgollo, which problem is solved by your proposal?

I'd argue that every added feature increases the attack surface. - Thus, I'd expect a significant improvement...

**Comment by mgollo** [comment]
Well, since both TLSv1.0 and TLSv1.1 are handled by OpenSSL, I wouldn't say there's much of an increased attack surface. And while TLSv1.1 is not a revolution compared to v1.0, it is still an improved protocol. So if for some reason (and yes, that does actually happen), a client does not support v1.2 but 1.0 and 1.1, it is better if v1.1 is offered. 
Maybe giving the users a choice in the panel might even be better. 

A general remark: My hosting provider only offers TLSv1.1 and TLSv1.2, all older protocols are disabled, which I consider very good. One of the owners of this company is a security researcher who played a major role in the recent discovery of the ROBOT attack, so I guess they know what they are doing. Have a look at the SSLlabs server test result of one of my websites if you are interested: https://dev.ssllabs.com/ssltest/analyze.html?d=ip.gollo.at&s=178.63.68.96&latest

**Comment by mgollo** [comment]
I just did a search on all these TLS versions, and I stumbled over this:
https://ecommerce.shopify.com/c/ecommerce-discussion/t/disabling-the-use-of-the-tlsv1-0-protocol-443497#comment-443642

It seems that TLSv1.0 must not be enabled any more if you want to be PCI compliant after June 30, 2018. I think this is a very good reason to discuss this issue.

**Comment by d00p** [comment]
It's been removed a year ago, here's the commit: https://github.com/Froxlor/Froxlor/commit/76c200a56c9cd47e461f6b2bf8c0c16f8ca7639e

**Comment by d00p** [comment]
It's now a setting, you can therefore enable TLSv1.1 if you like, see 4bcdfc0786067b69f9eef1c3da60d51ed2c625be
