### ISSUE TITLE
FTP Error

### ISSUE THREAD

**Issue by BlutwurstPro** [Froxlor/Froxlor#499]
Hi,
ich habe Froxlor auf einer frischen Debian 8.9 Version installiert und habe alles soweit Konfiguriert.

Wenn ich sich ein "Kunde" ein FTP Konto erstellt und sich mit diesem verbinden möchte, kommt folgender fehler:

Status:	Auflösen der IP-Adresse für webspace.*******.de
Status:	Verbinde mit *.*.*.*:21...
Status:	Verbindung hergestellt, warte auf Willkommensnachricht...
Status:	Initialisiere TLS...
Status:	Überprüfe Zertifikat...
Status:	TLS-Verbindung hergestellt.
Befehl:	USER test
Antwort:	331 Password required for test
Befehl:	PASS *******
Fehler:	GnuTLS-Fehler -110: The TLS connection was non-properly terminated.
Status:	Server hat die TLS-Verbindung nicht ordnungsgemäß geschlossen
Fehler:	Herstellen der Verbindung zum Server fehlgeschlagen

**Comment by d00p** [comment]
Please use the forum @ https://forum.froxlor.org/ for support. Also provide debug log information

**Comment by BlutwurstPro** [comment]
ok
