### ISSUE TITLE
Subdomain under nginx is not pointing to correct subfolder

### ISSUE THREAD

**Issue by chaos234** [Froxlor/Froxlor#501]
I recently created this subodmain: https://magix-enchanted-calculator.deltanet-production.de which should point into the filder /gow in my root folder.

But when I try to open https://magix-enchanted-calculator.deltanet-production.de/version.html it gives me 404 error because it isn't pointing correctly.

I am not sure if this is froxlor's, nginx's, php5-fpm's (yes, I use PHP 5 and not 7 and I will not update) or my brower's (chrome, latest version) fault.

I re-recreated all config files twice incl. de shell cmd for force execute the master cron from froxlor but even if I use STRG+F5 it isn't pointing to the correct location.

SSL and SSL redirect are enabled but no HSTS so what is going wrong?

**Comment by d00p** [comment]
Attach generated vhosts please.

**Comment by chaos234** [comment]
vHost is fine, checked it out - it was the length of the URL which nginx could not handle.

After google'ing a bit, I found: https://www.claudiokuenzler.com/blog/484/nginx-start-emerg-error-could-not-build-server-names-hash so I commented out the effected line and setted the value to 128 and now it is working.

Not sure why nginx (only?) has this problem or why there is such a hash functionallity but maybe you can add this as hint in froxlor so that owners/administrators can take care of this problem in combination with froxlor? Or maybe enabling it by default and setting it to 128 directly?

Your choise at the end, only a suggestions for now so I'll leave this open but you can close it if you want ;)

**Comment by d00p** [comment]
Well its nginxs "server_names_hash_bucket_size" setting. I did not check why nginx sets this and For what this is used exactly. Nginx admins should know about this restriction and can adjust it accordingly when needed (same with e.g. Apache worker setting or similar).
