### ISSUE TITLE
Support ticket menu forwards to index.php in customer panel, if domain settings are hidden

### ISSUE THREAD

**Issue by IDLe-Engineering** [Froxlor/Froxlor#502]
# Summary
If the domain settings are disabled for the customer, the support ticket menu links to index.php due to a bug in customer_ticket.php

# System information
* Froxlor version: 0.9.38.8-1
* Web server: apache2
* OS/Version: Debian Jessy

# Steps to reproduce

1. Disable "Domains" in admin settings -> panel settings -> Menu items in customer panel
2. Log in as customer
3. Try to browse to "Support Ticket" section

# Expected behavior

1. Support ticket section opens

# Actual behavior

1. Request is re-directed to index.php of the dashboard

**Comment by d00p** [comment]
Seems to come from a merge here https://github.com/Froxlor/Froxlor/commit/e3587fb346148cbca0f54db1804dfad9183d568d#diff-7be7fac722d8302e557a0a3c65f1cd93 - thanks for finding this

**Comment by IDLe-Engineering** [comment]
No problem. For me locally, I added the ticket menu to the customer panel config to be able to hide it (some may not want to have the ticket feature for their customers) in 100.panel.php and changed the redirect in customer_tickets.php to the appropriate list item.

**Comment by d00p** [comment]
eh, you can hide the ticket-system by disabling it :)

**Comment by IDLe-Engineering** [comment]
but wouldn't that also disable it then for my admins - if i want them to be able to write tickets?

**Comment by d00p** [comment]
ah okay, so you want your admins/resellers to be able to use it, but not your customers?

**Comment by IDLe-Engineering** [comment]
yes, but it's not important. I actually use it for the customers. I was just thinking of a use-case where this would make sense, if I had changed it here on GitHub for everyone.
