### ISSUE TITLE
support for wildcard subdomain CNAMES

### ISSUE THREAD

**Issue by rseffner** [Froxlor/Froxlor#504]
# Summary

Adding "*.xxx  CNAME   domain.tld." using froxlors DNS-editor results in an error "Die Subdomain "*.xxx" enthält ungültige Zeichen."

# System information
* Froxlor version: 0.9.38.7-1
* DNS server: Bind
* OS/Version: debian 9

# Steps to reproduce

1. open DSN-editor of nay domain
2. fill in "*.something" into record, "CNAME" into type
3. fill in the rest as needed

# Expected behavior

1. adding of the record

# Actual behavior

1. error message as shown in summary

**Comment by d00p** [comment]
Just tried to reproduce with current demo (git-master as of now) and this works just fine. Are you sure you've tested with latest git-version?

**Comment by rseffner** [comment]
No, not testet with latest git - as mentionend with latest stable (.deb package).

Do you mean, running froxlor in production from git is as solid as stable releases?

**Comment by d00p** [comment]
works with current code-base
