### ISSUE TITLE
isc_lex_gettoken() failed: unbalanced quotes in DNS zone (DKIM)

### ISSUE THREAD

**Issue by Logicbloke** [Froxlor/Froxlor#507]
# Summary
Looks like a recent change in the build file for the DNS zones has caused an extra (" and ") to be added on the DKIM entry in the zone.

# System information
* Froxlor version: 0.9.38.8
* Web server: apache2
* DNS server: Bind9

# Steps to reproduce
1. Enable DKIM on one of your domains or subdomains.
2. Rebuild config.
3. bind9 doesn't reload zone because of unbalanced quotes.

# Expected behavior
1. bind9 should load the zone.

# Actual behavior
1. bind9 doesn't load the zone.

# Log files/log entries
syslog: isc_lex_gettoken() failed: unbalanced quotes

**Comment by d00p** [comment]
Already fixed, see https://github.com/Froxlor/Froxlor/pull/503
