### ISSUE TITLE
SSL Redirect option causes some trouble with the punycode converter

### ISSUE THREAD

**Issue by leonmydla** [Froxlor/Froxlor#510]
Adding a Punycode Domain and enabling the SSL-Redirect option leads to an error during the cronjob.
My guess is, that while creating the redirect configuration statement froxlor tries to convert the domain to the punycode format but passes the already converted version to the converter, since it spits out an InvalidArgumentException with the message 'This is already a Punycode string'.

# System information
* Froxlor version: 0.9.37
* Web server: Apache 2.4.10-10+deb8u11
* DNS server: --
* POP/IMAP server: Dovecot 2.2.13-12~deb8u3
* SMTP server: Postfix 2.11.3-1+deb8u2
* FTP server: ProFTPD 1.3.5-1.1+deb8u2
* OS/Version: Debain Jessie 3.16.39-1+deb8u2

# Steps to reproduce
1. Add an IDN Domain
2. Enable the 'SSL redirect' option in the domain configuration
3. Wait for the froxlor cronjob to fail

# Expected behavior
1. Add an IDN Domain
2. Enable the 'SSL redirect' option in the domain configuration
3. Wait for the froxlor cronjob to create a vhost container with a proper https redirect statement

# Actual behavior
1. Add an IDN Domain
2. Enable the 'SSL redirect' option in the domain configuration
3. The froxlor cronjob throws an InvalidArgumentException Exception with the message 'This is already a Punycode string' (see stacktrace below)

# Log files/log entries
PHP Stack trace:
<pre>
PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'This is already a Punycode string' in /var/www/custom/froxlor/lib/classes/idna/ext/Punycode.php:173
Stack trace:
#0 /var/www/custom/froxlor/lib/classes/idna/ext/IdnaConvert.php(327): Mso\IdnaConvert\Punycode->encode(Array)
#1 /var/www/custom/froxlor/lib/classes/idna/class.idna_convert_wrapper.php(66): Mso\IdnaConvert\IdnaConvert->encode('https://xn--los...')
#2 /var/www/custom/froxlor/scripts/jobs/cron_tasks.inc.http.10.apache.php(849): idna_convert_wrapper->encode('https://xn--los...')
#3 /var/www/custom/froxlor/scripts/jobs/cron_tasks.inc.http.10.apache.php(926): apache->getVhostContent(Array, false)
#4 /var/www/custom/froxlor/scripts/jobs/cron_tasks.php(82): apache->createVirtualHosts()
#5 /var/www/custom/froxlor/scripts/froxlor_master_cronjob.php(77): require_once('/var/www/custom...')
#6 {main}
  thrown in /var/www/custom/froxlor/lib/classes/idna/ext/Punycode.php on line 173
</pre>

**Comment by d00p** [comment]
Unable to reproduce with current git master.

Adding domain 'täst.local', setting ssl ip/ports, enable ssl-redirect. Force Cronjob and correct results.
