### ISSUE TITLE
Own vHost settings not writing when SSL redirect is on

### ISSUE THREAD

**Issue by mattrabe** [Froxlor/Froxlor#511]
# Summary

On Edit domain screen - When a site has "SSL redirect" enabled , the values written into "Own vHost-settings" will be written only to the "ssl" .conf file, and not to the "normal" conf file. I can see why this is irrelevant for many vhost directives, but for one particular directive it is important and breaks functionality: ServerAlias.

# Details

I have domain names abc.com and xyz.com that should both display the same website. To do so, I have created one domain in Froxlor, abc.com, and added the following to "Own vHost-settings":

```
ServerAlias xyz.com
ServerAlias www.xyz.com

```

This works fine with SSL off. This also works fine with SSL on. In both cases, I get the following directives added to both `35_froxlor_normal_vhost_abc.com.conf` and `35_froxlor_ssl_vhost_abc.com.conf`:

```
ServerAlias xyz.com
ServerAlias www.xyz.com
DirectoryIndex index.php index.html
```

However, if I turn on "SSL redirect" for the site, these directives ONLY appear in `35_froxlor_ssl_vhost_abc.com.conf` and NOT in `35_froxlor_normal_vhost_abc.com.conf`, therefore if a user goes to http://xyz.com/ they will be delivered incorrect content (in my case, the froxlor panel login).

# System information
* Froxlor version: 0.9.38.7-1
* Web server: apache2
* OS/Version: Debian 8.9

**Comment by d00p** [comment]
Why would you need to manually add "ServerAlias" to the vhost-container? And you are right, it's a redirect so no other entries are relevant

**Comment by mattrabe** [comment]
Hmmm... I explained the “why” pretty thoroughly under “Detail” I feel. Perhaps there is another option for doing this that is preferred and I am not aware of??

ServerAlias is the only directive I can think of that is relevant even with a redirect, but it seems important unless there is another way to do this.

**Comment by d00p** [comment]
> Perhaps there is another option for doing this that is preferred and I am not aware of??

Yes, you add the domain as admin to froxlor and set it as an alias domain for another :) this way froxlor will generate corresponding ServerAlias entries...no need to do them manually

**Comment by mattrabe** [comment]
Will do, thank you!

**Comment by mattrabe** [comment]
For anyone finding this ticket - If you're a dummy like me and added ServerAlias directives to the "Own vHost-settings" then you're doing it wrong. Do as d00p says - add additional domains for each domain name and set "Alias for domain" to the primary domain. Works like a charm.
