### ISSUE TITLE
default (selected) value for PHP-FPM Config

### ISSUE THREAD

**Issue by gunnyst** [Froxlor/Froxlor#514]
When trying to edit a PHP configuration, the field for "PHP-FPM Config" has the first element pre-selected (not the one effectively assigned).

The bug is in 0.9.39, admin_phpsettings.php at line 352 where

`$fpmconfigs .= makeoption($row['description'], $row['id'], $id, true, true);`

should become

`$fpmconfigs .= makeoption($row['description'], $row['id'], $result['fpmsettingid'], true, true);`

(btw. I have notice a few more of those, but will post them as soon as I stumble over the next one)

**Comment by d00p** [comment]
If possible, post them all here, thx

**Comment by gunnyst** [comment]
OK.... one more here, always on the same version 0.9.39:

When we **edit a domain (as admin)**, you'll be able to select any PHP configuration you want, even though (!) you assigned only specific ones to a customer. Easy to fix like this:

In admin_domains.php @ 1138 add:

`$allowed_phpconfigs = json_decode($result['allowed_phpconfigs']);`

In admin_domains.php @ 2208 (or 2210 if you moved in 2 new lines above) extend the SQL query to:

`WHERE c.id IN (" . implode(", ", $allowed_phpconfigs) . ")`

The very same thing applies to the case when we **add a domain as admin**: even though we choose a customer, we always have all choices for PHP configurations. But since there is no AJAX interface and little JS (at least so I believe) this is hard/impossibile to fix.

**Comment by d00p** [comment]
> When we edit a domain (as admin), you'll be able to select any PHP configuration you want, even though > (!) you assigned only specific ones to a customer. Easy to fix like this:

ehm, that's because you are the admin? Of course YOU as admin can select ALL configs

**Comment by gunnyst** [comment]
... but as an admin I have defined that these should not be available to that customer!

That's why there are two issues:

If the admin assigns a PHP configuration (to a domain), that was not assigned to a customer (which btw. is allowed to edit these things), he could possibly stumble over an inconsistency: whenever he'll try to save his domain-settings he'll set another PHP configuration than originally put in place by the admin and thereby possibly selecting a not working one (if the error made by the admin in the first place was to not assign a required PHP configuration to the customer, but just simply selecting it when creating the domain!).

On the other hand I got close to 10 configurations (5 different PHP versions, some with EXEC/FOPEN functions and some without) and I usually just need only up to 2 configs per customer, but have multiple domains per customer. Now for every domain I've to go through a list of things that should not be there (and risking as already happened) to choose the wrong one. This personal issue obviously lies at the moment I set up a new domain and that again would only benefit from a fix for the moment I create a domain (=> AJAX/JS)...

But no worries, I still can live with this little inconsistency... the admin should simply never make mistakes ;-)

**Comment by d00p** [comment]
> ... but as an admin I have defined that these should not be available to that customer!

for the customer to chose from, not for yourself...

For the inconsistency: yes, that can happen. I understand the need to only show available configs in the select box, maybe i'll have an idea on how to make this easier.

**Comment by gunnyst** [comment]
Would be nice, but please place it under "nice-to-have"... anyway, since it really depends on the customer the only two ways I can think of are:

- a dynamic update when changing customer during creation of a domain (AJAX)
- a two-step setup (non-AJAX)
