### ISSUE TITLE
Mail path duplicated, mail delivered to wrong directory

### ISSUE THREAD

**Issue by EricReiche** [Froxlor/Froxlor#516]
# Summary
I have a problem with my mail delivery on an Ubuntu freshly migrated from Debian.
When Postfix receives an email, it stores it in `/var/customers/mail/var/customers/mail/CUSTOMER/EMAIL@DOMAIN/new`
Part of the path is duplicated.
Courier is looking in the correct path, namely
`/var/customers/mail/CUSTOMER/EMAIL@DOMAIN/new`
So it can not find them.

# System information
Ubuntu 17 with postfix and Courier. 

* Froxlor version: 0.9.39 (DB: 201801260)
* Web server: nginx
* DNS server: none
* POP/IMAP server: Courier
* SMTP server: postfix
* OS/Version: Ubuntu 17 4.13.0-32-generic, using mainly the proposed Ubuntu 14 config

# Steps to reproduce

postconf -n says `virtual_mailbox_base = /var/customers/mail/`
This is the suggested line for postfix in Ubunutu 14:
`virtual_mailbox_base = /var/customers/mail/`

When looking through the config diff, this seems to have changed and would probably match the weird behavior:
https://config.froxlor.org/?distribution=ubuntu_precise&from=0.9.34&to=9999&submit=

in mail_users DB table, `homedir` is `/var/customers/mail/` and maildir is `CUSTOMER/EMAIL@EXAMPLE.DE/`
This is valid for existing and newly created mailboxes.

Rest of postconf is here https://nopaste.xyz/?3add336f1057b4de#UiqJmo1+LgX6cdGxvqF/qygY94R5bh6MQ4Ws89Jhi0c=

# Expected behavior
Mail gets delivered to
`/var/customers/mail/CUSTOMER/EMAIL@DOMAIN/new`

# Actual behavior
Mail gets delivered to
`/var/customers/mail/var/customers/mail/CUSTOMER/EMAIL@DOMAIN/new`

# Log files/log entries
mail.log says "delivered to maildir" and removes it from mailq.

**Comment by EricReiche** [comment]
diff from the config viewer
https://config.froxlor.org/?distribution=ubuntu_precise&from=0.9.34&to=9999&submit=#

[postfix_dovecot] /etc/postfix/main.cf
`
# Virtual delivery settings
-virtual_mailbox_base = <VIRTUAL_MAILBOX_BASE>
+virtual_mailbox_base = /
`
This change is missing from the postfix_courier block and could possibly fix it.

**Comment by d00p** [comment]
You've just posted the diff for the config yourself which Shows its fixed...Set virtual_mailbox_base to / and you're good to go

**Comment by EricReiche** [comment]
right. But shouldn't that be fixed in the config templates?

**Comment by d00p** [comment]
Ah, Courier related Postfix Not fixed...got it ;) still, remember that froxlor does Not automatically Update your Configs to avoid overwriting customizations.

**Comment by EricReiche** [comment]
Yes, I understand. Fix works as expected for me, so my issue is solved.
