### ISSUE TITLE
Wrong nginx config files / vhosts

### ISSUE THREAD

**Issue by ms81** [Froxlor/Froxlor#517]
# Bug report
Froxlor generates wrong nginx vhosts.

wrong line:
...
 fastcgi_pass unix:/var/lib/apache2/fastcgi/1-user-domainxxx.de-php-fpm.socket;
...

correct line should be:
...
 fastcgi_pass unix:/var/lib/apache2/fastcgi/user-domainxxx.de-php-fpm.socket;
...

Problem is the **"1-"** added to the filename of the php-fpm.socket

# Summary

Bad Gateway error, php-fpm not working because it dont find the sockets.

This happens since 0.9.39.5, with 0.9.38.8 everything was fine. 
No config changes.

# System information
* Froxlor version: 0.9.39.5
* Web server: nginx
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Ubuntu 16.04

# Log files/log entries
2018/02/15 20:10:22 [crit] 10212#10212: *1 connect() to unix:/var/lib/apache2/fastcgi/1-froxlor.panel-xxxxxxxxx.de-php-fpm.socket failed (2: No such file or directory) while connecting to upstream, client: 2001:a62:xxx:xxx:xxx, server: xxxxxxxxx.de, request: "GET /admin_index.php?s=2b06b52374b4b649af5ae7810a6a222e HTTP/1.1", upstream: "fastcgi://unix:/var/lib/apache2/fastcgi/1-froxlor.panel-xxxxxxxx.de-php-fpm.socket:", host: "xxxxxxxx.de", referrer: "https://xxxxxxxx.de/admin_settings.php"

**Comment by d00p** [comment]
Ehm, the **1-** is intended, it's the fpm-daemon id so they don't collide. Can you please nopaste the fpm-pool config for user-domainxxx.de? works perfectly fine for me using apache and nginx

**Comment by d00p** [comment]
Just tried to reproduce, works perfectly here

**Comment by d00p** [comment]
Great you found it :)
