### ISSUE TITLE
[Feature-Request] Adding TLS-Settings per domain

### ISSUE THREAD

**Issue by WeWin55** [Froxlor/Froxlor#519]
Hi,

it would be a nice feature to edit the tls-settings per domain. For example, one customer would like to have a lot of users and needs a good compatibility to most devices. The other customer needs high security conditions.

Just add the settings from picture one, to the SSL-Settings on the customers domain settings (picture 2).
Picture 1:
![1](https://user-images.githubusercontent.com/12202669/36320653-2d3f825e-1347-11e8-8f32-97be949f2702.PNG)
Picture 2:
![2](https://user-images.githubusercontent.com/12202669/36320656-2fc79d54-1347-11e8-8450-f245ea984de1.PNG)

Futhermore a DH-file would be nice :)

#Generate the parameters
openssl dhparam -out dhparam_4096.pem 4096

#Add the following to your Apache config.
SSLOpenSSLConfCmd DHParameters "/etc/ssl/certs/dhparam_4096.pem"

Thanks for your nice work and much updates 👍

**Comment by d00p** [comment]
If you let people chose TLS per domain, I guess you would need to allow SSL-CipherList too...I tend to implement but only for admin's with permission 'change_serversettings'

**Comment by d00p** [comment]
Currently working on that. New `Domains.add()` and `Domains.update()` parameter will be:
```
bool $override_tls
array $ssl_protocols
string $ssl_cipher_list
string $tlsv13_cipher_list
```

**Comment by wrosenauer** [comment]
This is marked as closed but I'm currently using 0.10.23.1 and tried to set the TLS protocol versions on a domain differently to the global settings. This hasn't had any effect though. Not a problem right now since I wanted to change the global settings anyway to the same. Doing so immediately was effective on all domains. Is this expected or a bug which should be reported?

**Comment by d00p** [comment]
If you want to set this per domain you also have to set the `$override_tls` flag (should be on top of the settings in the UI, _Override system TLS settings_)

**Comment by wrosenauer** [comment]
Thanks, I missed that option indeed. Sorry
