### ISSUE TITLE
froxlor master cronjob not called with parameters

### ISSUE THREAD

**Issue by tnebe** [Froxlor/Froxlor#524]
Hi,
I upgraded to latest version of froxlor and receiving a error via mail:

```
*** Froxlor Master Cronjob ***

Below are possible parameters for this file

--[cronname]		includes the given cron-file
--force			forces re-generating of config-files (webserver, nameserver, etc.)
--debug			output debug information about what is going on to STDOUT.
```

This comes after setting this according to the configuration menu. From my point of view, the script is definetely called without parameters

```
#/etc/cron.d/froxlor
*/5 * * * *	root	/usr/bin/nice -n 5 /usr/bin/php -q /var/www/froxlor/scripts/froxlor_master_cronjob.php
```
but maybe hast to from this script.

https://github.com/Froxlor/Froxlor/blob/d5b9ad345235b4dd6ad6048f5ac1e08c26261fda/scripts/froxlor_master_cronjob.php#L27

Anything wrong here? Thanks!

**Comment by ebrahim** [comment]
I've got the very same problem.

**Comment by d00p** [comment]
If the script runs for the first time, it creates a whole other cron.d/froxlor file (various lines, different time periods etc.). Just run it manually once with --force parameter and check out the cron.d/froxlor file

**Comment by ebrahim** [comment]
Worked. Thanks.
