### ISSUE TITLE
Feature Request: Renew Button for Lets Encrypt certificates

### ISSUE THREAD

**Issue by fager** [Froxlor/Froxlor#526]
Let's Encrypt certificates are not updated after domain is changed.

# System information
* Froxlor version: 0.9.38.8

# Steps to reproduce

1. domain configured with "no alias"
2. Let's Encrypt certificate generated
3. domain configuration is changed to "WWW alias"
4. Result: certificate without SAN until certificate expiredate is reached

# Expected behavior

* automatic renew if certificate-related configurations are changed or
* renew button in "SSL certificates" to manualy trigger update

See also: https://forum.froxlor.org/index.php?/topic/13877-lets-encrypt-zertifikate-nach-alias-%C3%A4nderung-aktualisieren/

**Comment by JuKu** [comment]
I suggest this feature too!

**Comment by sharky009** [comment]
+1

**Comment by nachtgeist** [comment]
@fager: this definetely shouldn't have happened.

Was the editing you mentioned in step 3 done as admin or customer? (i.e. did your browser show admin_domains.php or customer_domains.php in its location bar?)

**Comment by fager** [comment]
@nachtgeist: all changes were made with admin permissions.
