### ISSUE TITLE
View "PHP-configs used by domain" not valid

### ISSUE THREAD

**Issue by rseffner** [Froxlor/Froxlor#532]
# Summary

View "PHP-configs" shown an config as "not used" but it ist used by one domain.

# System information
* Froxlor version: 0.9.39.5
* Web server: apache2
* DNS server: bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: debian 8

# Steps to reproduce

1. there is a second admin, managing his own customers
2. this admin allows one of his customers a bunch of php-configs
3. this customer selected on php-config for one of his subdomains
4. phpinfo an the fcgi-starter-script shows using selected php-config
5. looking in php - php-configs, these config isn't used - perhaps in this special case of "only" a subdomain uses this config

# Expected behavior

1. every uses php-config should shown as used to not delete them bei cleaning operations

# Actual behavior

1. looking in php - php-configs, these config isn't used - perhaps in this special case of "only" a subdomain uses this config

**Comment by d00p** [comment]
Subdomains are not shown in the list of php-configs

**Comment by rseffner** [comment]
Please look at this case from a differnet point of view to answer th question "why not?".
If an server admin checks his php configurations for unsupported versions or insecure configurations to clean up his system its dangerous to shom him unused pgp configuration sets which were still not unused. The output "is not used" ist still wrong!

**Comment by d00p** [comment]
I did not say "no" nor did i close this ticket, i just wanted to clearify the current state

**Comment by rseffner** [comment]
I also only liked to suggest to change the counting behavior or to clearify the output. In my use case, also mentioning subdomians will be the best.
