### ISSUE TITLE
VirtualHost directive for system-hostname not created

### ISSUE THREAD

**Issue by Logicbloke** [Froxlor/Froxlor#534]
# Summary

Froxlor's hostname VirtualHost is not being generated despite having the following option checked:
Access Froxlor directly via the hostname

And despite the hostname being actually given in the System Settings.

Also, checking the following [Enable Let's Encrypt for the froxlor vhost] will show that a certificate was fetched for the froxlor vhost while it's not under the proper ssl certificates folder /etc/ssl/froxlor-custom and nowhere to be found.

Any clues?

# System information
* Froxlor version: 0.9.39.5
* Web server: Apache/2.4.18 (Ubuntu)
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Ubuntu 16.04.1

**Comment by d00p** [comment]
Edit IP/Port and check for "Create vHost-Container" flag

**Comment by d00p** [comment]
Also: please use the forum for support
