### ISSUE TITLE
[Feature Request] Add installer option to enable SSL

### ISSUE THREAD

**Issue by iandk** [Froxlor/Froxlor#538]
More and more sites use SSL with certificates that mostly come from Let's Encrypt.
To further support this it would be nice to add an option to the installer, which enables SSL, adds an SSL IP and maybe even enables Let's Encrypt.

**Comment by d00p** [comment]
checking the option in the installation process or later in the setings...no difference, why make the installation more and more complicated to have all possible options available? It's just the basic installation. You are REQUIRED to go through the settings afterwards anyway to ensure everything is adjusted to your system and needs.
