### ISSUE TITLE
[Feature Request] Add installer option to add IPv6

### ISSUE THREAD

**Issue by iandk** [Froxlor/Froxlor#539]
Most of the modern systems already use Dualstack (IPv4 + IPv6).
Currently, the IPv6 address must be added manually to froxlor, it would be easier to add an option to add an IPv6 address directly to the installer. 
This could be done with a validation, to for instance only show the IPv6 field if IPv6 connectivity is detected.

**Comment by d00p** [comment]
"The REMOTE_ADDR key is set by the web server, not PHP. If the web server listens on v6 and the user connects that way, it'll be a v6 address"

Also there is no way to determine all system-available ip-addresses (and know whether the webserver listens on them) without executing anything on the shell which might not be allowed by either default php.ini or other restrictions
