### ISSUE TITLE
Feature request: apache mod_chroot

### ISSUE THREAD

**Issue by solkmaaker** [Froxlor/Froxlor#545]
# System information
* Froxlor version: 0.9.39.5 (DB: 201802130)
* Web server: apache2
* OS/Version: Debian 9
## Implement apache mod_chroot usage.

Current problem, when using mpm_itk is that, although every apache process will run as its owner when virtualhost config states:
`  <IfModule mpm_itk_module>
    AssignUserID $USER $GROUP
  </IfModule>
`
users are not isolated from each other and all users are able to view system files and other user files  when they upload some sort of php file manager.

mod_chroot itself resolves problem that user is able to view system files by jailing apache master process.
It will require to state global chroot folder, in froxlor case it will probably be /var/customer/webs, also some libraries must be preloaded, for php name resolving, and timezone files, resolv.conf, and some other config files must be present in chroot jail.
Since server reconfiguration is done by cron (and run by root using cli php), this will not affected by apache module.

Also, user folders must be created as 750, currently they are created as 755

This setup will result that users are able to view all folders in /var/customer/webs, but they cannot look into folders, and folder /var/customer/webs looks to them as root folder (/)
Apache virtual host DocumentRoot in this case will be /$USER

**Comment by JB1985** [comment]
Do you use PHP Openbasedir?

**Comment by solkmaaker** [comment]
Yes, i do, and i see what you are saying.

File manager i used:
[https://github.com/Rugoals/phpFileManager](https://github.com/Rugoals/phpFileManagerl)

Indeed, when i try to access upper folder, php file manager gives me:
```
I/O Error./var/customers/webs/
--
```
But, if i use "shell" in that particular file manager, i can do:
```
# pwd
/var/customers/webs/testuser/fm
# ls ../../../../../
bin
boot
dev
etc
home
initrd.img
initrd.img.old
lib
lib64
media
mnt
opt
proc
root
run
sbin
srv
sys
tmp
usr
var
vmlinuz
vmlinuz.old
```
I have another web server instance which uses mpm_itk with mod_chroot (no froxlor), and there, same file manager is unable to "see" folder listings (in froxlor case this would be folders with usernames), but it cannot go up because of mod_chroot.
And manager cannot look into other users folders because of folder permissions (700) and every user apache vhost is running as that particular user, so no access to other user folders.
