### ISSUE TITLE
Domainimport does not use Default Redirect Code

### ISSUE THREAD

**Issue by Af0x** [Froxlor/Froxlor#546]
Hello,
if you import Domains via csv and enter an URL as Docroot it does not use the Redirect Code set under the webserver-settings. It always uses 301.
Regards,
Af0x

**Comment by d00p** [comment]
It's not the import but the cronjob ;) This should also be the case when you add the domain as admin. Could you try again with the attached patch?


[fix-default-domain-redirectcode.diff.txt](https://github.com/Froxlor/Froxlor/files/1928792/fix-default-domain-redirectcode.diff.txt)

**Comment by d00p** [comment]
It's a patch file....https://git-scm.com/docs/git-apply

**Comment by Af0x** [comment]
I tried to run the Master_cronjob and got this

> PHP Parse error:  syntax error, unexpected end of file in /path/to/froxlor/lib/functions/output/function.RedirectCode.php on line 166

**Comment by Af0x** [comment]
now I was able to run the job but it failed with Error:

> Syntax error on line 14 of /etc/
apache2/sites-enabled/35_froxlor_normal_vhost_domain.tld.conf

Line 14 says something like this:

> RewriteRule ^/(.*) https://%{HTTP_HOST}/$1 [R=307 ();L,NE]

I set 307 as default.

**Comment by Af0x** [comment]
now it works from my perspective, thank you :)
