### ISSUE TITLE
problematic splitting of e.g. dns TXT records

### ISSUE THREAD

**Issue by rseffner** [Froxlor/Froxlor#548]
# Summary

If I add an "google-verification-code=43_char_long_id" TXT record, froxlor ist splitting it into an zonefile entry equals like "google-verification-code=first_part_of_43_char_long_id" and "last_6_chars".
So any DNS request results in a string consistin a space between the two parts an the Google-Check fails.

# System information
* Froxlor version: 0.9.39.5
* Web server: apache2
* DNS server: Bind9
* OS/Version: debian8

# Steps to reproduce

1. add an TXT record of 68 chars
2. dig or nslookup for these record
or
3. try it using the google site verification

# Expected behavior

1. no spaces in DNS request answer

# Actual behavior

1. an space in DNS request answer
dig domain.tld txt
;; ANSWER SECTION:
domain.tld.           18000   IN      TXT     "google-site-verification=CRKxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxa0v" "AbxxWQ"

**Comment by d00p** [comment]
> perhaps you can mov the size limit from 64 up to about 255 (as bind9 works with).

Should be okay I guess
