### ISSUE TITLE
PHP can't connect to DB

### ISSUE THREAD

**Issue by jacubillo** [Froxlor/Froxlor#550]
# Bug report 
Installer can't connect to the DB. 

# Summary
This is shown when trying to install froxlor after typing the DB credentials>
SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'

Found this as the reason>
https://stackoverflow.com/questions/36864206/sqlstatehy000-1698-access-denied-for-user-rootlocalhost-tried-everyth

And this as the solution> (from the above link)
$sudo mysql -u root
[mysql] use mysql;
[mysql] update user set plugin='' where User='root';
[mysql] flush privileges;
[mysql] \q

**Comment by d00p** [comment]
Known, but nothing froxlor can do/Change from within web
