### ISSUE TITLE
Cron says "Certificate file does not exist" but it exists.

### ISSUE THREAD

**Issue by Linutux** [Froxlor/Froxlor#551]
My froxlor (newest stable version, Ubuntu 16.04) shows some error, I don't understand. When I execute

> /usr/bin/php /var/customers/webs/sysuser/froxlor/scripts/froxlor_master_cronjob.php --force

I get

> 141.0.21.56:443 :: certificate file "/etc/apache2/froxlor-ssl/a.asdyx.de.crt" does not exist! Cannot create ssl-directives

but the file does exist. I don't understand what's happening here.

**Comment by d00p** [comment]
what are the files permissions (should be 0600)? The cron runs as root so it should be able to read most of the time. Also, the cron does a simple "file_exists()" call to verify the file exists....so it cannot exist if this functions returns false...

**Comment by d00p** [comment]
no answer
