### ISSUE TITLE
show domain registration date to customers

### ISSUE THREAD

**Issue by sebastian-schmid** [Froxlor/Froxlor#553]
# Summary

It would be great if customers can see the domain registration date. As admin or reseller I can set a "Bei Registry hinzugefügt" date as "JJJJ-MM-TT".

# Expected behavior

The date could be shown on the domain overview page as a seperate column or just under the domain name.

# Actual behavior

The date is not visible for customers.

**Comment by d00p** [comment]
> Show the remaining days or highlight domains that are about to expire.

From a customer point of view, I would like to know whether it will auto-expire or renewed, or else this information is only partly helpful
