### ISSUE TITLE
PHP7.2 & PHP7.2-fpm

### ISSUE THREAD

**Issue by LostnIL** [Froxlor/Froxlor#559]
When trying to install PHP7.2-fpm, the panel's configuration files/settings default to PHP5. Unable to get PHP-FPM working via Wiki Instructions or the Instructions provided by Panel > Configuration > DB8 > Other > FPM .. It displays PHP5 related instructions and syntax. 

I attempted to install php7.2-fpm packages, adjust Froxlor's settings to reflect PHP7.2 directories and path but when running the cron takes the panel generates configurations that cause syntax errors in apache2. 

I assume this is because it is defaulting PHP5 syntax or isn't PHP7 aware? I'm not sure. 

# System information
* Froxlor version: 0.9.38.7-1 (DB: 201612110)
* Web server: Apache2
* DNS server: Bind
* OS/Version: Jessie

**Comment by d00p** [comment]
> Froxlor version: 0.9.38.7-1 (DB: 201612110)

please test with current git-master. Froxlor works just fine with php-7.2

**Comment by ragnos** [comment]
While i agree with the statement that Froxlor works with 7.2, there are still some deprecation warnings i experienced during testing:

While opening the Domains-page as customer, and while opening the Configurations-page as admin , each multiple times. It also has countless appearances during a forced cronjob (more then my terminal buffer could take):
```
PHP warning/error
#8192 assert(): Calling assert() with a string argument is deprecated

 

/lib/functions/filedir/function.makeCorrectDir.php:32
```

0.9.39.5 (DB: 201802130)
Debian Jessie
Apache2.4.10
PHP7.2.8-fpm compiled from source

**Comment by d00p** [comment]
Just a Deprecation warning - nothing to do with the initially reported problem.

**Comment by d00p** [comment]
Then I guess you just need to adjust the setting? Settings -> Cron settings -> Cron execution command (php-binary)

**Comment by d00p** [comment]
Also, any feedback on 0.10.0 would be appreciated in the corresponding forum https://forum.froxlor.org/index.php?/forum/15-0100-api/ and not a github issue - thanks
