### ISSUE TITLE
The name 'prefix' for the ftp and sql prefix is wrong

### ISSUE THREAD

**Issue by mortzel** [Froxlor/Froxlor#565]
# Summary
The name 'prefix' for the ftp and sql prefix is wrong. The 'prefix' is added to the end of the username so it should be called suffix.

# System information
* Froxlor version: 0.9.39.5
* Web server: apache2
* DNS server: PowerDNS (standalone)
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian 9

**Comment by d00p** [comment]
Also wrong, as the numbering is at the end of these names "web1ftp2" it would be an infix :)

But, as it is a prefix to the numbering, we chose prefix; also to comply with the naming "customer"-prefix etc. So, no need to be gramatically super correct here
