### ISSUE TITLE
xenial.xml not included in the tar.gz released package

### ISSUE THREAD

**Issue by landabaso** [Froxlor/Froxlor#568]
xenial.xml is not lib/configfiles/ for release 0.9.39.5: http://files.froxlor.org/releases/froxlor-latest.tar.gz

Workaround: download it manually:
https://github.com/Froxlor/Froxlor/blob/master/lib/configfiles/xenial.xml

**Comment by Dessa** [comment]
not a bug.

**Comment by landabaso** [comment]
Yeah. Never said it was a bug.
I decided to install Xenial in a new server after confirming it was supported on the Live Demo https://demo.froxlor.org/ (which is at version 0.9.35.5)
However, I was surprised not to find the config files later after installing it and going through the Froxlor installation.
You might want to consider releasing a package with up to date config files or may be adding a note somewhere on the Live Demo.
Anyway, thanks for this great peace of soft!

**Comment by d00p** [comment]
Demo is always latest git- master, not the current stable release

**Comment by landabaso** [comment]
I see. I did not know. It's a bit tricky. The Dashboard shows version 0.9.39.5 under "Froxlor details".
TBH it's not a big issue I guess. I immediately thought these config files must exist somewhere because I saw them on the demo.
I just thought it was worth mentioning it here in case you wanted to take some action for avoiding possible further misunderstandings by others. Thanks anyway!
