### ISSUE TITLE
Install script does not check all requirements

### ISSUE THREAD

**Issue by micw** [Froxlor/Froxlor#569]
# Bug report

# Summary

The install script checks some prerequisites to run froxlor. Not all requirements are checked, so froxlor may fail to work after setup.

# System information
* Froxlor version: 0.9.39.5
* OS/Version: alpine / 3.8

# Steps to reproduce

Run the install script. Ensure that all requirement are installed so that the script is fine

# Expected behavior

Froxlor should run properly

# Actual behavior

froxlor does not work due to missing requirements

# The following extra requirements needs to be installed

php extensions: session, simplexml, ctype
other tools: mysql-client (used during setup to create a database backup)

**Comment by d00p** [comment]
on it
