### ISSUE TITLE
Backup feature doesnt make any sense... 

### ISSUE THREAD

**Issue by erikdemarco** [Froxlor/Froxlor#571]
Hi. 

Froxlor is very lightweight i like it very much. But your backup feature is really really really 100x doesnt make any sense when theres no restore feature. Why theres a backup feature but no restore feature?

**Comment by d00p** [comment]
The feature exists for customers to claim all their stored data which they cannot access via FTP (e.g. mail and database files). It archives and stores them into the customers docroot so they can be downloaded. Nothing more, nothing less. For anything more comprehensive I'd suggest using one of the million available backup-solutions that are focusing on that feature
