### ISSUE TITLE
Feature Request: Move pm controll to PHP configuration

### ISSUE THREAD

**Issue by bjoern-tantau** [Froxlor/Froxlor#573]
It would be nice if the settings from PHP-FPM versions for Process manager control (pm) would be moved to the PHP configurations. As every pool-file can have its own settings this would allow for finer control if some sites need more or less processes.

As a workaround, in order to add some new settings I had to create a new dummy PHP-FPM version with the desired pm settings and then change the start command from `service php7.1-fpm restart` to `systemctl restart php7.1-fpm` (and I had to change the pool directory).

**Comment by d00p** [comment]
agreed
