### ISSUE TITLE
No delete when add second spf record

### ISSUE THREAD

**Issue by michaellevante** [Froxlor/Froxlor#574]
Hi, 

we have activated in the settings the option "Domain SPF settings" an set an global SPF Record. Now we will add a domain a manual SPF. After the add we have two SPF records and the global SPF record is not deleted. We correct the File " lib/functions/dns/function.createDomainZone.php" in line 127: 

if (Settings::Get('spf.use_spf') == '1' && $entry['type'] == 'TXT' && $entry['record'] == '@' && strtolower(substr($entry['content'], 0, 7)) == '"v=spf1') {

We replace the 
== '"v=spf1') { 

with 

== 'v=spf1') {

Best regard
Michael

**Comment by d00p** [comment]
If you change the amount of characters in the right side of the condition, the string that is being cut down to 7 characters on the left side will NEVER match - hence, always false - cannot be correct. Also, the **== '"v=spf1') {** is intended, as the line HAS TO start with the character **"**
