### ISSUE TITLE
Cannot set http/2 anywhere except on the Froxlor vhost

### ISSUE THREAD

**Issue by landabaso** [Froxlor/Froxlor#575]
Server running apache 2.4.34 (I already activated `Use modifications for Apache 2.4
`):

Then, on: `System->Settings->Froxlor VirtualHost settings->` there's an option for:
`HTTP2 Support
enable HTTP2 support for ssl.`, which is what I expected.

I don't activate the HTTP2 support for the froxlor vhost since I only need it on other domains.

Then, on `Domains->` I select & edit a domain to activate http/2. However, the domain's panel does not show an option for http/2 because the `visible` flag for the field is `false`:

`formfield.domains_edit.php`, line 226:

`'http2' => array('visible' => ($ssl_ipsandports != '' ? true : false) && Settings::Get('system.webserver') != 'lighttpd' && Settings::Get('system.http2_support') == '1', ...`

I debugged it a bit and `Settings::Get('system.http2_support') ` is `false`.

How can I set `system.http2_support`?
I cannot find the option under Server->Settings->Webserver settings or anywhere else.

**EDIT**

I see the problem.
I need to activate HTTP2 for the froxlor vhost first.

This is confusing. Shouldn't this option be under "Webserver settings" instead of "Froxlor VirtualHost settings "?

**Comment by d00p** [comment]
you are right, the settings belongs to "webserver" not "Froxlor vhost settings". The "Enable http2" setting is global. When enabled of course the froxlor-vhost will include the corresponding vhost settings for http2. For customer domains, it's per domain.
