### ISSUE TITLE
Feature Request: Support PGP encryption for backups

### ISSUE THREAD

**Issue by MatthiasLohr** [Froxlor/Froxlor#590]
Froxlor should support PGP encryption of backups to increase security. That could be realized by adding a field pgp_public_key to the users basic data or within the backup dialog. After the backup archive was created successfully, and a pgp key is available, the archive should be encrypted, so only the owner of the according private key is able to read that backup.

That would be especially useful if it takes a long time to create the backup (e.g. overnight) and you do not want to have your plaintext backup stored that long.

What do you think about that?

Best regards
Matthias

**Comment by d00p** [comment]
Well, the "backup" feature is more like a "retreive all my data" for customers. If you want a REAL backup (with possibilities to restore, etc.) you should use something specially designed for that task. Froxlor will never integrate a full features backup functionality as there are so many (opensource) projects that do a great job at this already and which are focusing on that.

**Comment by MatthiasLohr** [comment]
Then let's rename it so "Support PGP encryption for 'retreive all my data'". Would ask for the same feature for that.

**Comment by d00p** [comment]
Well, I'm not sure many people will use that but hey, why not. Are you interested in providing a PullRequest? :)

**Comment by MatthiasLohr** [comment]
Yes, why not. Give me some time for implementing this (I first have to (re)learn the structure of Froxlor). Thanks for reopening the feature request.

**Comment by MatthiasLohr** [comment]
@d00p, I have now some code prepared (currently in testing stage). Does a pull request has a change to get merged (regarding the 0.10 rewrite) for 0.9.x?

**Comment by d00p** [comment]
No new features in 0.9.x

**Comment by MatthiasLohr** [comment]
Then I will wait for 0.10 for providing a pull request.

**Comment by d00p** [comment]
Why wait? 0.10.0 is current MASTER

**Comment by MatthiasLohr** [comment]
Because it's not released yet. I want to have a stable code base for developing this feature. Otherwise, I have to rearrange the pull request after possible major changed in your code. And because I don't now how "finalized" the code is right now ("Like every other version before: when its done"), I will wait.

**Comment by d00p** [comment]
As said, there will be no new features added to 0.9.x as the next major release will be 0.10.0

**Comment by d00p** [comment]
So, 0.10.x is out....anything new here? :)

**Comment by MatthiasLohr** [comment]
Not yet, didn't recognize that 0.10.x is released. When I find the time, I will start with implementing that.

**Comment by envoyr** [comment]
I think I'm interested in implementing this in 0.11.x, but I think it will be a post-release feature since the current 0.11.x todo is relatively full.

**Comment by envoyr** [comment]
added in 5731f5f
