### ISSUE TITLE
Users created with the API can not create e-mails.

### ISSUE THREAD

**Issue by JB1985** [Froxlor/Froxlor#597]
Github Version: 0.10.0 (DB: 201811180)
Debian: 9
Postfix with Dovecot IMAP

A user reported that he created two email addresses. That seem to be true, see Screenshot:

![image](https://user-images.githubusercontent.com/9932751/49004386-74004b00-f164-11e8-8179-246c57996767.png)

But now, he cant see/or Login to the Email User and I cant create new user.

![image](https://user-images.githubusercontent.com/9932751/49004474-9f833580-f164-11e8-81b7-34fc872ac305.png)

The link to create new Emails is missing.

In the database I cant find the users in mail_users and mail_virtual

All users who were not created with the API work without any problems.

**Comment by d00p** [comment]
Did the user create the emails using external API? What's the content of table mail_virtual?

**Comment by d00p** [comment]
> The link to create new Emails is missing

The screenshot says otherwise..."E-Mail Adresse anlegen"...

**Comment by d00p** [comment]
Also, need the exact parameters you've created the user via API with...

**Comment by JB1985** [comment]
I found the mistake. It has the hook in the domain missing that is an email domain.

I am sorry! But I dont know, why "Email Domain" was disabled.

The API Output was correct.

{
    "status": 200,
    "status_message": "successfull",
    "data": {
        "id": "XXX",
        "domain": "domain.xyz",
        "adminid": "1",
        "customerid": "93",
        "aliasdomain": null,
        "documentroot": "/var/customers/webs/webXXX/",
        "isbinddomain": "0",
        "isemaildomain": "1",
        "email_only": "0",
        "iswildcarddomain": "0",
        "subcanemaildomain": "0",
        "caneditdomain": "1",
        "zonefile": "",
        "dkim": "0",
        "dkim_id": "0",
        "dkim_privkey": "",
        "dkim_pubkey": "",
        "wwwserveralias": "1",
        "parentdomainid": "0",
        "phpenabled": "1",
        "openbasedir": "1",
        "openbasedir_path": "0",
        "speciallogfile": "0",
        "ssl_redirect": "0",
        "specialsettings": "",
        "deactivated": "0",
        "bindserial": "2000010100",
        "add_date": "1542797671",
        "registration_date": null,
        "termination_date": null,
        "phpsettingid": "4",
        "mod_fcgid_starter": "-1",
        "mod_fcgid_maxrequests": "-1",
        "ismainbutsubto": "0",
        "letsencrypt": "0",
        "hsts": "0",
        "hsts_sub": "0",
        "hsts_preload": "0",
        "ocsp_stapling": "0",
        "http2": "1",
        "notryfiles": "0"
    }
}

**Comment by d00p** [comment]
Okay I'll check Domain.add() maybe something went wring there. Basically it does not matter whether internally added via Webinterface or externally via API as it both uses the API in the end.

**Comment by JB1985** [comment]
I reopen this Issue again, because I think there is a bug in add Domain and Mailserver settings (isemaildomain).

If I want to add a Domain I do in Mailserver settings isemaildomain 1, after I save adding a domain the Mailserver settings are unset, ismaildomain = 0.

Can you look @d00p if you can find the mistake?

**Comment by JB1985** [comment]
Unfortunately the bug still seems to be there.

Can you please check again these actions if there is not another error in it?

Dec 24 15:20:16 srvXXX Froxlor: [Customer Action web1] [information] [API] added email forwarder for 'aleph@domain.xyz'
Dec 24 15:21:38 srvXXX Froxlor: [Customer Action web1] [information] [API] toggled catchall-flag for email address 'j@domain.xyz'
Dec 24 15:26:52 srvXXX Froxlor: [Customer Action web1] [information] [API] updated email account 'second@domain.xyz'
Dec 24 15:58:54 srvXXX Froxlor: [Kunde Action web1] [information] [API] edited domain 'domain.xyz'
Dec 24 16:07:34 srvXXX Froxlor: [Kunde Action web1] [information] [API] edited domain 'domain.xyz'
Dec 24 16:27:26 srvXXX Froxlor: [Kunde Action web1] [information] [API] edited domain 'domain.xyz'
Dec 24 17:16:02 srvXXX Froxlor: [Kunde Action web1] [information] [API] added subdomain 'www.domain.xyz'

That is what I could find in the logs as actions.

**Comment by d00p** [comment]
Exact steps to reproduce please

**Comment by d00p** [comment]
no feedback, unable to reproduce
