### ISSUE TITLE
Bug: backup page broken

### ISSUE THREAD

**Issue by MatthiasLohr** [Froxlor/Froxlor#601]
# Bug report

## Summary

The backup page seems to be broken with (at least) 0.9.40. When trying to create a new backup task with path ```/```, the following error occurs:
```
Fatal error: Uncaught Error: Call to undefined function standar_error() in /var/customers/webs/matthias/dev/froxlor/customer_extras.php on line 584 Error: Call to undefined function standar_error() in /var/customers/webs/matthias/dev/froxlor/customer_extras.php on line 584 Call Stack: 0.0001 402144 1. {main}() /var/customers/webs/matthias/dev/froxlor/customer_extras.php:0
```

# System information
* Froxlor version: 0.9.40

# Steps to reproduce

1. Login
2. Go to Extras->Backup
3. Create a Backup with all options enabled and path ```/```

# Expected behavior

No error/success message

# Actual behavior

```
Fatal error: Uncaught Error: Call to undefined function standar_error() in /var/customers/webs/matthias/dev/froxlor/customer_extras.php on line 584 Error: Call to undefined function standar_error() in /var/customers/webs/matthias/dev/froxlor/customer_extras.php on line 584 Call Stack: 0.0001 402144 1. {main}() /var/customers/webs/matthias/dev/froxlor/customer_extras.php:0
```

**Comment by d00p** [comment]
That should of course be *standard_error", darn

**Comment by MatthiasLohr** [comment]
Oops, too obvious. Not even noticed. If, then I would have directly attached a pull request with, sorry.
