### ISSUE TITLE
Let's Encrypt fullchain is not created for some domains

### ISSUE THREAD

**Issue by Aragorn77** [Froxlor/Froxlor#605]
The Let's Encrypt fullchain.pem is not created for some domains.
From what I saw:

In the froxlor database, table domain_ssl_settings, for that domain the field ssl_fullchain_file was empty (NULL). 
When I inserted the fullchain into it, the file was created at the next froxlor run.
But I tried it for a 2. domain and it did not work, no fullchain file was created.

**Comment by d00p** [comment]
which froxlor version? fullchain was introduced in 0.9.40 - if there was a certificate already which has not yet been renewed since you've installed 0.9.40 of course there is not fullchain - wait for the renew or delete the certificate and create a new one

**Comment by d00p** [comment]
no response
