### ISSUE TITLE
PHP-Versions do not match vor 0.10.0

### ISSUE THREAD

**Issue by foliengriller** [Froxlor/Froxlor#606]
The composer.json says that PHP 5.3 is required.

In the new Code, something like this is done
` json_decode($json_result, true)['data'];`
That ihmo requires PHP 5.4 to work.

Then also something like this is done
`empty($this->getUserDetail('ip')`
That ihmo requires PHP 5.5 to work properly, says PHPStorm.

And this in Froxlor API Example requires PHP 7.0 to work.
`__construct(string $host, string $api_key, string $api_secret)` 

So which is the PHP-Version it should work with? So we can change to code or the composer.json

**Comment by d00p** [comment]
0.10.0 ia currently testing/development, so, please give me a bit to sort all out before changing anything.
Yea, the example is >= php-7 - on purpose because the time 0.10.0 will be a stable release, php7 is default on the current stable distributions.
Whether we stay 5.3 compatible or go for 5.6 or even 7.0 - we will see

**Comment by d00p** [comment]
Just ran a few phpcompatibility checks - I think the best would be to drop 5.3 support and go for a mininum of php-5.6 - that should cover everything (except doc/example/). What do you think?

**Comment by d00p** [comment]
marked php7 as recommended, but minimum requirement stays 5.6 for now (no reason to force 7.0 when not needed). Thanks for the hint :)

**Comment by PHPGangsta** [comment]
One reason to set PHP 7.1 as a minimum for 0.10: All PHP versions < 7.1 don't have security support anymore:
http://php.net/supported-versions.php

Please don't support people using insecure versions of PHP. By increasing the minimum required version for a new feature release of Froxlor, you help to make the world a better place, and soft-force people to upgrade to a supported secure PHP version. If someone does not want to upgrade to PHP >=7.1, he cannot use the new shiny version 0.10... He can decide what to do then.

**Comment by Dessa** [comment]
jessie doesn't have php7 (and *no* we *don't* support external repos shipping it.)
