### ISSUE TITLE
Feature Request: Support Automatic Installation via shell script

### ISSUE THREAD

**Issue by allamiro** [Froxlor/Froxlor#611]
# Summary

Foxlor should support automatic or automated installation via shell scripts similar to the other CP

STEPS 
1. Download The script
2. Execute the Script
3. Installation will begin to download the tar ball extract it and then yum i nstall all the required scripts and generate the admin name and passwords

**Comment by d00p** [comment]
any volunteers for testing? :) Please contact me at team@froxlor.org or visit us on IRC (freenode.net/#froxlor)

**Comment by fager** [comment]
A combination with the configuration import/export feature would be nice to set all nessasary configurations during the automated installation.
I can do some testing.

**Comment by d00p** [comment]
The shell-installer will tell you that you can run the corresponding config-services.php script.

You can download the test-installer here: https://files.froxlor.org/froxlor-install.phar

**Comment by d00p** [comment]
See https://github.com/Froxlor/Froxlor-Installer/
