### ISSUE TITLE
Implement Openkdim

### ISSUE THREAD

**Issue by llucps** [froxlor/Froxlor#619]
Since dkim-filter is deprecated it would be great to implement its replacement Openkdim.

I set up dmarc reports on my server and neither Yahoo and auth-results@verifier.port25.com don't like the current dkim-filter implementation. On auth-results@verifier.port25.com complains about the dkim selector having an underscore. Fortunately Google doesn't complain and passes de dmarc test. 

```
----------------------------------------------------------
DKIM check details:
----------------------------------------------------------
Result:         permerror (syntax error in s= tag: Error in "dkim_1": invalid character U+005F ('_') in domain label)
ID(s) verified: 

DNS record(s):

NOTE: DKIM checking has been performed based on the latest DKIM specs
(RFC 4871 or draft-ietf-dkim-base-10) and verification may fail for
older versions.  If you are using Port25's PowerMTA, you need to use
version 3.2r11 or later to get a compatible version of DKIM.
```

**Comment by d00p** [comment]
Froxlors DKIM implementation is really really old - don't use that currently

**Comment by negrusti** [comment]
It will be easier to have a hook to run a script on (sub)domain creation - there we can create DKIM keys for OpenDKIM, Rspamd etc. etc.

**Comment by d00p** [comment]
creation of key is not the problem...the using service and integration is

**Comment by negrusti** [comment]
I don't think any other integration is needed IF DNS is not managed on the server

**Comment by Logicbloke** [comment]
I could probably work on this. Should I just ditch dkim-milter and implement OpenDKIM or let the user select between the 2?

**Comment by negrusti** [comment]
I think I've not seen dkim-milter in production for quite a while...

**Comment by d00p** [comment]
dkim-milter is not really used anymore. Config templates for OpenDKIM would be nice

**Comment by negrusti** [comment]
/etc/opendkim.conf:

> AutoRestart             Yes
> AutoRestartRate         10/1h
> UMask                   002
> Syslog                  yes
> SyslogSuccess           Yes
> LogWhy                  Yes
> ReportAddress           root@example.com
> Canonicalization        relaxed/simple
> ExternalIgnoreList      refile:/etc/opendkim/TrustedHosts
> InternalHosts           refile:/etc/opendkim/TrustedHosts
> KeyTable                refile:/etc/opendkim/KeyTable
> SigningTable            refile:/etc/opendkim/SigningTable
> Mode                    sv
> PidFile                 /var/run/opendkim/opendkim.pid
> SignatureAlgorithm      rsa-sha256
> UserID                  opendkim:opendkim
> Socket                  inet:12301@localhost
> 

/etc/opendkim/KeyTable:
> default._domainkey.example.com example.com:default:/etc/opendkim/keys/example.com/default.private

/etc/opendkim/SigningTable:
> *@example.com default._domainkey.example.com

/etc/opendkim/TrustedHosts:

> 127.0.0.1
> localhost

**Comment by negrusti** [comment]
Key creation:
mkdir -p /etc/opendkim/keys/example.com  
opendkim-genkey -r -d example.com -D /etc/opendkim/keys/example.com  
chown opendkim:opendkim /etc/opendkim/keys/example.com/default.private

**Comment by negrusti** [comment]
Postfix:

> milter_protocol = 2
> milter_default_action = accept
> smtpd_milters = inet:localhost:12301
> non_smtpd_milters = inet:localhost:12301

**Comment by negrusti** [comment]
Rspamd
Key generation:
> rspamadm dkim_keygen -b 2048 -d example.com -s default -k /var/lib/rspamd/dkim/example.com.default.key > /var/lib/rspamd/dkim/example.com.default.public

dkim_signing.conf:
> path = "/var/lib/rspamd/dkim/$domain.$selector.key";

and it will pick up the keys automatically

**Comment by d00p** [comment]
Ehm, `lib/configfiles/*.xml` and pull request?

**Comment by negrusti** [comment]
I hope @Logicbloke can help with that :)

**Comment by Logicbloke** [comment]
It seems that while opendkim.conf can be configured manually, things like KeyTable, SigningTable or TrustHosts will need to be generated.

Also even within opendkim.conf some people would want the SignatureAlgorithm and the port in Socket configurable.

As far as key generation is involved, I think Froxlor is already doing it. Needs another standardized name for the keys (preferably without the underscore) which is what this ticket is about.

I'll see what I can do with the configuration, I have the project forked.

**Comment by d00p** [comment]
> Also even within opendkim.conf some people would want the SignatureAlgorithm and the port in Socket configurable.

Yeah but openDKIM is, like postfix/docecot, a one-time-configuration. Nothing froxlor generates regularly via cronjob. And same as FTP or mail-services, the user can adjust any part of it or ports according to his needs. But not from within the GUI, that would be madness, too many options :)

**Comment by d00p** [comment]
So please stay as close to the standaed/default configuration and only adjust necessary parts (like we do that for every service)

**Comment by negrusti** [comment]
Absolutely, so the only thing Froxlor needs to do is to create/update these two:
/etc/opendkim/KeyTable
/etc/opendkim/SigningTable
and generate the keys

**Comment by d00p** [comment]
Is there any SQL interface to let OpenDKIM read that from the database?

**Comment by negrusti** [comment]
Yes there is:
https://fossies.org/linux/opendkim/opendkim/README.SQL

**Comment by d00p** [comment]
then it would be nice if the one doing the configs could do it the SQL way, as we do that the same with postfix, ftp, etc.

**Comment by Logicbloke** [comment]
@d00p Do you know of a handy GUI XML editor? The files are huge and the structure isn't well-outlined when opening it on a text-editor.

**Comment by pquerner** [comment]
Any IDE can handle XML fine. I like PhpStorm as my IDE.

**Comment by makuser** [comment]
What's the problem here? Is anybody working on OpenDKIM? I have been running it with Froxlor the last few years and would be able to copy my implementation into a PR, and make it look a bit nicer, etc if nobody else has done anything for OpenDKIM.

**Comment by d00p** [comment]
Problem as always, time time time and no one wants to do it for ALL supported systems (config templates are required for this for sure). If you want to get this going, hell yeah go for it :)

**Comment by makuser** [comment]
Config templates are so damn easy. Near stock actually. OpenDKIM is much easier to implement compared to dkim-milter, as it already supports SQL OOTB.

Will do.

**Comment by Logicbloke** [comment]
@d00p Can we just ditch the underscore in the dkim txt record?

`root@server:/var/www/froxlor# grep -rwb . -e dkim\_
./lib/Froxlor/Dns/Dns.php:4939:                         self::addRequiredEntry('dkim_' . $domain['dkim_id'] . '._domainkey', 'TXT', $required_entries);
./lib/Froxlor/Dns/Dns.php:10261:                                                        } elseif ($record == 'dkim_' . $domain['dkim_id'] . '._domainkey' && ! empty($dkim_entries)) {
./lib/Froxlor/Cron/Dns/DnsBase.php:6225:                                $privkey_filename = \Froxlor\FileDir::makeCorrectFile(Settings::Get('dkim.dkim_prefix') . '/dkim_' . $domain['dkim_id']);
./lib/Froxlor/Cron/Dns/DnsBase.php:6351:                                $pubkey_filename = \Froxlor\FileDir::makeCorrectFile(Settings::Get('dkim.dkim_prefix') . '/dkim_' . $domain['dkim_id'] . '.public');
./lib/Froxlor/Cron/Dns/DnsBase.php:6811:                                        $privkey_filename = \Froxlor\FileDir::makeCorrectFile(Settings::Get('dkim.dkim_prefix') . '/dkim_' . $domain['dkim_id']);
./lib/Froxlor/Cron/Dns/DnsBase.php:7231:                                        $pubkey_filename = \Froxlor\FileDir::makeCorrectFile(Settings::Get('dkim.dkim_prefix') . '/dkim_' . $domain['dkim_id'] . '.public');
`

I guess this should solve OP's issue.

**Comment by makuser** [comment]
Even though removing the underscore was the right thing, I did not cover or update that in my opendkim config, and it bit me just now, when I contacted one (non-Google) mail server that actually did check this.

**Comment by Neustradamus** [comment]
To follow this important ticket :)

**Comment by d00p** [comment]
Surpassed by antispam-feature in v2.2 (rspamd) which integrates domainkey
