### ISSUE TITLE
Cannot use FastCgiExternalServer in Debian 9 (stretch)

### ISSUE THREAD

**Issue by princeofnaxos** [Froxlor/Froxlor#621]
FastCgiExternalServer cannot be used on Debian 9 Stretch. Please read this page: https://serverfault.com/questions/859014/debian-9-stretch-lamp-setup-with-sandboxed-users-using-fpm for more info.

I have now manually commented out line 344 in lib/Froxlor/Cron/Http/Apache.php so that this directive is not written to the vhost files.

# System information
* Froxlor version: git-master
* Web server: apache2.4
* PHP version: 7.2-fpm
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian 9

**Comment by d00p** [comment]
that's why you NEED to activate the setting PHP-FPM -> Use mod_proxy / mod_proxy_fcgi

**Comment by d00p** [comment]
Also, please report any "problems" you run into to the forum first in case it's not a bug (like this one)

**Comment by princeofnaxos** [comment]
> that's why you NEED to activate the setting PHP-FPM -> Use mod_proxy / mod_proxy_fcgi

I have activated php-fpm....

**Comment by princeofnaxos** [comment]
Very unclear.... 

# a2enmod proxy_fcgi
Considering dependency proxy for proxy_fcgi:
Module proxy already enabled
Module proxy_fcgi already enabled

Still, the directive "FastCgiExternalServer" is used in the virtual host, and "ProxyPassMatch" is nowhere to be found.

**Comment by d00p** [comment]
Then be sure the cronjob ran...also, support on the forum or IRC. Not here

**Comment by d00p** [comment]
i meant the froxlor setting "Use mod_proxy / mod_proxy_fcgi" not the a2enmod
