### ISSUE TITLE
PHP 7 features used while having minimum 5.6

### ISSUE THREAD

**Issue by PHPGangsta** [Froxlor/Froxlor#624]
PHP 7 features ("scalar type hints" and "return type declarations") are used in
doc/example/FroxlorAPI.php

According to the following answer, PHP 7 will not be the minimum version of 0.10.0, you want to stick to 5.6 as minimum:
https://github.com/Froxlor/Froxlor/issues/606#issuecomment-451517778

**Comment by d00p** [comment]
As already stated in the forum, this example is not needed to run froxlor, hence does not need to be 5.6 compliment and it's done this way on purpose to clearify data types
