### ISSUE TITLE
DNS Management for a sub domain

### ISSUE THREAD

**Issue by tobiasredel** [Froxlor/Froxlor#632]
# Summary

It is not possible to enable DNS Management only for a subdomain (xxx.yyy.com) when DNS Management is disabled for the primary domain (yyy.com). It is possible to configure the subdomain as a normal domain and to enable DNS Management only for that domain but it would cause a BIND error during zone configuration of xxx.yyy.com saying that there is no zone file for yyy.com.

# System information
* Froxlor version: 0.9.40.1
* Web server: apache2
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian Stretch

# Steps to reproduce

1. Configure a domain xxx.yyy without DNS Management
2. Configure a domain www.xxx.yyy as a normal domain being a subdomain of xxx.yyy with DNS Management
3. Check BIND logs

# Expected behavior

1. Zone configuration only for www.xxx.yyy (not for xxx.yyy)

# Actual behavior

1. Error configuring zone file for www.xxx.yyy without a present zone file for xxx.yyy

**Comment by d00p** [comment]
Correctly, if I reproduce this, I get the froxlor-cron-error:
[error] Database inconsistency: domain  (ID #2) is set to to be subdomain to non-existent domain ID #1. No DNS record(s) will be created for this domain.

**Comment by d00p** [comment]
Could you try with the following patch? A zonefile should be created then:

```diff
diff --git a/lib/Froxlor/Cron/Dns/DnsBase.php b/lib/Froxlor/Cron/Dns/DnsBase.php
index 82f9d372..f51ff6bc 100644
--- a/lib/Froxlor/Cron/Dns/DnsBase.php
+++ b/lib/Froxlor/Cron/Dns/DnsBase.php
@@ -151,7 +151,7 @@ abstract class DnsBase
                                if (isset($domains[$domains[$key]['ismainbutsubto']])) {
                                        $domains[$domains[$key]['ismainbutsubto']]['children'][] = $domains[$key]['id'];
                                } else {
-                                       $this->logger->logAction(\Froxlor\FroxlorLogger::CRON_ACTION, LOG_ERR, 'Database inconsistency: domain ' . $domain['domain'] . ' (ID #' . $key . ') is set to to be subdomain to non-existent domain ID #' . $domains[$key]['ismainbutsubto'] . '. No DNS record(s) will be created for this domain.');
+                                       $domains[$key]['ismainbutsubto'] = 0;
                                }
                        }
                }
```

**Comment by tobiasredel** [comment]
The patch is working fine! Zone file for subdomain only is being created.

**Comment by d00p** [comment]
and does it work as expected? :)

**Comment by tobiasredel** [comment]
Yes - I disabled the DNS Management for the top domain - no error like before. Thank you very much for your support. Being a big fan of froxlor for a long time now!
