### ISSUE TITLE
Using a IDN for standard subdomains

### ISSUE THREAD

**Issue by heavygale** [Froxlor/Froxlor#633]
# System information
* Froxlor version: 0.9.40.1 
* Web server: nginx
* OS/Version: debian strech

# Summary
If a IDN is used for standard subdomains it must be provided in punycode notation in the system settings. If it is specified "as is", as froxlor demands it on every other domain-input, it doesn't get converted and nginx won't behave as expected with the generated config file.

# Possible solutions
- Either make sure to convert the specified domain to punycode notation while generating the config files....
- or add a note to `$lng['serversettings']['stdsubdomainhost']['description']` telling the user to use punycode notation if a IDN is beeing specified. (simpler, but contrary to the froxlor standard)

**Comment by d00p** [comment]
As discussed and reproduced on IRC, this is already fixed in 0.10.x as the std-subdomain is being created using the Domains.add() API call which IDNA-converts the domain :)
