### ISSUE TITLE
Moving customer to another admin doesn't work

### ISSUE THREAD

**Issue by princeofnaxos** [Froxlor/Froxlor#637]
# Bug report vs. support request
If you're unsure of whether your problem is a bug or a configuration error
* contact us via IRC in #froxlor on freenode
* or post a thread in our forum at https://forum.froxlor.org

As a rule of thumb: before reporting an issue
* see if it hasn't been [reported](https://github.com/Froxlor/froxlor/issues) (and possibly already been [fixed](https://github.com/Froxlor/froxlor/issues?utf8=✓&q=is:issue%20is:closed)) first
* try with the git master

# Summary

When moving the customer to another admin, they always get 'adminid=1'. 

# System information
* Froxlor version: 0.10.0/master
* Web server: apache2
* OS/Version: macOS Mojave 10.14.0 

# Steps to reproduce

1. Edit a customer
2. Choose an administrator (the current admin is _not_ preselected)
3. Click 'Save'

# Expected behavior

1. The number of customers for the selected admin should be raised

# Actual behavior

1. The number of customers for Siteadmin is raised (or unchanged)

**Comment by d00p** [comment]
So, does the moving itself not work or just is the number of customers added to the wrong admin?

Also, you don't need to post the ISSUE_TEMPLATE header :P

**Comment by d00p** [comment]
> Choose an administrator (the current admin is not preselected)

That is intended: "Leave this empty for no change."

**Comment by princeofnaxos** [comment]
Moving the customer doesn't work. If I change the adminid in the database, and then move the customer, the adminid is always changed to '1'.

**Comment by d00p** [comment]
You should *NOT* change stuff manually in the database...

**Comment by discordier** [comment]
@d00p I suppose he wanted to test if the moving works at all and therefore "moved" the customer by hand in the DB to anything other than "ID 1" and tried to move the customer to another admin and in his case the customer appears to always be moved to admin with "ID 1".
At least this is how I understand what he has written.

**Comment by princeofnaxos** [comment]
Correct.

Edwin Boersma
Fasterminds
http://www.fasterminds.com

Tel.: +46709726431
Tel.: +46313011801
