### ISSUE TITLE
Feature Request: Support XMPP server support.

### ISSUE THREAD

**Issue by s1-ranjan** [Froxlor/Froxlor#641]
It would be a great feature if Froxlor is able to manage XMPP user per domain.
Prosody / metronome is a great tool to run XMPP server, Hope to listen on this soon.

**Comment by d00p** [comment]
Ehm, Not really froxlors part...there are so many great free xmpp server with a good interface to manage users...

**Comment by s1-ranjan** [comment]
Can you please name some of them, so that I can have it on my vps.

**Comment by d00p** [comment]
There's Google for that...but here: https://www.igniterealtime.org/projects/openfire/
