### ISSUE TITLE
Check IPs and Ports list when system.le_froxlor_enabled = 1

### ISSUE THREAD

**Issue by timdeluxe** [Froxlor/Froxlor#642]
# Summary

It took me a big amount of time to find it out and maybe a check with a warning could help other users.

Here the details: In the settings i enabled lets encrypt for the froxlor vhost (technically system.le_froxlor_enabled = 1). However i did not get a SSL vhost for froxlor itself, only the unencrypted port 80 one. I neither got a certificate, etc.
My error was that under "IPs and Ports" i had a SSL enabled IP but that one did not have "Create vhost container" enabled. Enabling that solved all my problems...

Maybe you could create a check if you enable system.le_froxlor_enabled and warn the user if you find SSL enabled IPs while none of them has "create vhost container" enabled. It could save another user a lot of time.
Or you could even lock that settings if such an IP with "create vhost container" is not found and give a hint on that setting?

# System information
* Froxlor version: 0.9.40.1-1+jessie1
* Web server: apache2
* DNS server: None used with froxlor
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian 9 (stretch)

# Steps to reproduce

1. Set up froxlor according to manual
2. Set up lets encrypt according to manual
3. Create an IP with SSL enabled but with "create vhost container" disabled
4. Enable lets encrypt for froxlor vhost in the froxlor virtualhost settings

# Expected behavior

Warning when enabling that lets encrypt setting
OR
Locked lets encrypt setting (that specific one)

# Actual behavior

SSL vhost for froxlor gets not created and no specific error is shown.

**Comment by d00p** [comment]
Agreed

**Comment by d00p** [comment]
Hm, not as easy as it seems, basically every setting in "Settings" -> "Froxlor Vhost Settings" requires a vhost-container to be generated, thinking of a way to display this information usefully

**Comment by timdeluxe** [comment]
Indeed, however not all of them are for SSL. Maybe you could lock all settings there if neither a normal nor a SSL vhost for froxlor ist activated. Unlock all settings if only a SSL vhost or both are activated. And finally lock the SSL settings if there is only the normal vhost for froxlor is activated (as already proposed above).
And maybe a general information on the top (if possible) with a hint to the "IPs and Ports" menu would be good.

**Comment by timdeluxe** [comment]
@d00p I may see it wrong, but your commit only fixes the case, when none of the IPs has vhostcontainer activated. The specific issue, which i described in the opening message will still not be catched with that.

**Comment by d00p** [comment]
I see your point, need to check for ssl-enabled ips not having vhost-contaier...yup you're right, thanks
