### ISSUE TITLE
Feature: pm.status_path = /status

### ISSUE THREAD

**Issue by drexlma** [Froxlor/Froxlor#643]
ENABLE / DISABLE PHP-FPM pm.status_path = /status 

Wird fürs Monitoring verwendet.

**Comment by d00p** [comment]
I'm unsure if a simple enable/disable is sufficient to make this work as it  possibly requires changes in the vhosts too (and restriction so that it is not callable from anywhere/public)

**Comment by drexlma** [comment]
I know. however, it is very helpful for https://amplify.nginx.com and icinga

**Comment by d00p** [comment]
will think of something for 0.10.0

**Comment by patschi** [comment]
Without seeing this issue first: I have the exact same use-case for this. Currently I've manually edited the required file, but having this integrated into Froxlor in the future might help a lot.

I thought of a multi-line input field to "PHP Configurations", which simply gets added to each pool-configuration. IMHO that is the best place to allow such configuration.

**Comment by negrusti** [comment]
One problem I see is the site itself can have /status URL, hard-coding this is not an option

**Comment by patschi** [comment]
This path is php-fpm-socket side and not directly accessible via webserver. When the amplify agent queries the data, it queries that directly from the phpfpm socket. (at least with nginx setup)

Beside that that's why I suggested an input field to manually add some kind of configuration, then you basically have all kind of freedom which settings you would like to add.

**Comment by pquerner** [comment]
I feel like this ticket needs more information. I feel quite lost without more information here.

**Comment by patschi** [comment]
What kind of information are you missing? The feature request is about adding `pm.status_path = /status` to the PHP-FPM pool configuration of a specific vhost (while, in the best scenario, `/status` should be configurable)
