### ISSUE TITLE
Froxlor powerdns database not compatibile

### ISSUE THREAD

**Issue by tczaude** [Froxlor/Froxlor#645]
# Summary

Please provide a concise summary of the problem you're experiencing...

PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'change_date' in 'field list' in scripts/jobs/cron_tasks.inc.dns.20.pdns.php:170

# System information
* Froxlor version: 0.9.40.1 (DB: 201809280)
* Web server: nginx
* DNS server: PowerDNS (standalone)
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Gentoo

# Steps to reproduce

1. https://github.com/PowerDNS/pdns/blob/master/modules/gmysqlbackend/schema.mysql.sql
2. Regenconfig files
3.

**Comment by d00p** [comment]
If i read that correctly, than this field is being dropped in pdns 4.2.0 ( https://github.com/PowerDNS/pdns/blob/7a0bef6560e7b589d74b22ff9667fa621c787e6d/modules/gmysqlbackend/4.1.0_to_4.2.0_schema.mysql.sql ) and the website says current stable is 4.1.x and debian stable still has 4.0.x and in your case gentoo's portage holds 4.1.x - so....what version of pdns are you using? Just to be sure.

Solution in any case would be to also drop the field in froxlors usage
