### ISSUE TITLE
Feature Request: Allow HTTP BASIC in URL

### ISSUE THREAD

**Issue by patschi** [Froxlor/Froxlor#646]
I just tried specifing a phpMyAdmin URL like `https://pma:password@froxlor.domain.tld/pma/` at `Settings - Panel Settings - phpMyAdmin URL`. Unfortunately the validator seems not to accept `:` or `@` within the URL and fails with following error:

```
The value for the field "panel_phpmyadmin_url" is not in the expected format.
```

It would be nice to be able to specify a HTTP-BASIC auth URL, as I'd like to hide PMA behind a simple HTTP BASIC Authentication for security-purposes, and also to let users just click on the link without manually entering the HTTP Basic Auth.

**Comment by d00p** [comment]
Hm why specify that if every customer can then see user/password anyway? Yeah, outsiders do not know....but hm...also stored as plaintext value in the database...

**Comment by patschi** [comment]
Yes, it would be readable and also plaintext in the database, but this shouldn't replace the phpMyAdmin authentication itself anyway. The intention is to get rid of "outsiders" like crawlers, bots, and that kind of annoying stuff. IMHO allowing this kind of links might be sort of "nice-to-have" and should not have negative impact for anyone.

I'm glad to take a look myself and file a PR for that, of course as long as you're okay with.

**Comment by d00p** [comment]
Sounds okay to me ;)
