### ISSUE TITLE
Question: Requirement for webalizer or awstats?

### ISSUE THREAD

**Issue by patschi** [Froxlor/Froxlor#647]
Is there any reason for the requirement of either webalizer or awstats? For example when generating the nginx configurations, either the `location{}` block for webalizer or awstats is generated, but there's no possibility to turn off both:
https://github.com/Froxlor/Froxlor/blob/2166999fefc09d217555c2e06452176567f0d26b/lib/Froxlor/Cron/Http/Nginx.php#L975-L980

Furthermore: The only setting at `Statistics Setting` is to enable or disable `awstats`. But no option to disable statistics at all:
![image](https://user-images.githubusercontent.com/2029878/52541801-591f9900-2d99-11e9-89d4-61a11173fcf6.png)

Is there any reason for that? If not, might be a PR to change that be welcome?

**Comment by d00p** [comment]
The whole traffic calculation is based on that

**Comment by patschi** [comment]
Ah! Makes sense! Thanks for solving this mystery! 

For anyone who is interested in: Found relevant code part.
https://github.com/Froxlor/Froxlor/blob/4ee735a81fc289b23701d0f5c9a860c4f5c217d7/lib/Froxlor/Cron/Traffic/TrafficCron.php#L191-L210
