### ISSUE TITLE
Feature Request: LetsEncrypt, ECDSA Support

### ISSUE THREAD

**Issue by patschi** [Froxlor/Froxlor#651]
The new signature algorithm ECDSA is used more and more and has various advantages over the good old RSA and therefore I'd like to see ECDSA support in the future. There's a good read by Cloudflare about ECDSA: [ECDSA: The digital signature algorithm of a better internet](https://blog.cloudflare.com/ecdsa-the-digital-signature-algorithm-of-a-better-internet/).  ECDSA is faster while being more secure compared to RSA, and is getting more usual over time.

**In terms of nginx**: So at least in nginx it is easily possible to run RSA and ECDSA side-by-side for compatibility reasons. The `ssl_certificate` and `ssl_certificate_key` just needs to be defined twice, one for RSA and one for ECDSA - see [nginx documentation](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_certificate).

**In terms of LetsEncrypt**: For ECDSA it is required to request an own certificate. Unfortunately I'm not sure how this works - at least in `acme.sh` you simply provide a parameter for that.

Just an other idea: What about migrating over to the proofen-`acme.sh` client to solve the whole LetsEncrypt-certificate-requesting stuff and outsource some work this way?

**Comment by d00p** [comment]
> Just an other idea: What about migrating over to the proofen-`acme.sh` client to solve the whole
> LetsEncrypt-certificate-requesting stuff and outsource some work this way?

could be possibility yes...

**Comment by patschi** [comment]
I know this has been closed back in February, however do I see it correct that it is currently the choice between RSA **OR** ECDSA?

**Comment by d00p** [comment]
Yes, these are the possibilities acme.sh provides, afaik, see https://github.com/Neilpang/acme.sh#10-issue-ecc-certificates; also, a better place for support would be our forum or IRC channel :)

**Comment by patschi** [comment]
I just want to ensure I did not missed anything. Running ECDSA-only might not be the best idea as of now, blocking users from accessing the sites. That's why my original issue pointed out the compatibility running RSA and ECDSA side-by-side.

I know that ACME can only request one each time. But you can simply run acme.sh twice (the intended way), one for RSA and one for ECDSA to have both for the same domain and the best compatiblity In nginx for example you only need to provide `ssl_certificate` and `ssl_certificate_key` twice and nginx handles the rest.

As it was more a technical question regarding this specific issue/implementation and not really a support-inquiry or so. That's why I thought commenting here might be the best place rather than IRC/forum.

I'm tending to open a new issue, and referencing to this one, for RSA & ECDSA support. I think that might be fine for you too?

**Comment by d00p** [comment]
Yes
