### ISSUE TITLE
Enhancement: nginx config, IF is evil

### ISSUE THREAD

**Issue by patschi** [Froxlor/Froxlor#653]
**Enhancement**
When a redirect is configured, by default following nginx configuration is active:
```
if ($request_uri !~ ^/.well-known/acme-challenge/[-\w]+$) {
  return 301 https://domain.tld/$request_uri;
}
```

Instead I'd rather recommend using following less-CPU-intensive (no regex):
```
location / {
  return 301 https://domain.tld/$request_uri;
}
```

**Result**
This should behave just like before, but getting rid of the IF. The reason why this works is that `location /.well-known/acme-challenge {}` is more precise than simple `location / {}` and that is why nginx prefers the well-known-location once a LetsEncrypt request comes in. *(Tested on multiple domains on my setup.)*

The full `server{}` block then looks like:
```
server { 
	listen ...;
	server_name domain.tld www.domain.tld;
	include /etc/nginx/acme.conf;
	location / {
		return 301 https://$host$request_uri;
	}
}
```

The included `acme.conf` file looks like:
```
location /.well-known/acme-challenge {
	alias /var/www/letsencrypt/.well-known/acme-challenge;
	default_type text/plain;
}
```

**Ressources**

- http://nginx.org/en/docs/http/ngx_http_core_module.html#location
- https://www.digitalocean.com/community/tutorials/understanding-nginx-server-and-location-block-selection-algorithms
- http://agentzh.blogspot.com/2011/03/how-nginx-location-if-works.html
- https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#server-name-if

**Reason & benefit**

Benefits
* Due to performance and stability reaons it is generally recommended getting rid of IF-conditions wherever possible, even nginx themself recommend it that way. This way we follow the best-practise by replacing the IF's and keeping the same result.
* Another good aspect is removing the more CPU-intensive regex for the IF.

Even it works on my setup after intensive tests, I'd appreciate any tests from other users as well.

**Relevant code parts**

https://github.com/Froxlor/Froxlor/blob/73c05fb2310be67be0dc59dfd5837188eeb758cc/lib/Froxlor/Cron/Http/Nginx.php#L247-L249

https://github.com/Froxlor/Froxlor/blob/73c05fb2310be67be0dc59dfd5837188eeb758cc/lib/Froxlor/Cron/Http/Nginx.php#L508-L510

**Comment by d00p** [comment]
Okay, thank you very much for the detailed report - very helpful. So we need to ensure the alias is included before the `location / {}` block and it's all right :P nice
