### ISSUE TITLE
opcache.restrict_api default PHP config allows all sites to acces the opcache API (PHP-FPM)

### ISSUE THREAD

**Issue by dtugend** [Froxlor/Froxlor#655]
# Summary

- The Default PHP Config is created with opcache.restrict_api = "{DOCUMENT_ROOT}".
- The way PHP-FPM is set up with Froxlor the opcache will be shared by all sites.
- Thus all sites with default config can access the Zend Opcache API and e.g. Flush the cache for all. It might also have security implications (e.g. it's possible to see cache fragments of other websites, didn't check if contents of those can be seen as well).

# Possible solutions

## 1) Fix default config

- Limit the opcache API in default to Froxlor VHost instead of that.

## 2) Separate into own master Processes

- some work
- e.g. by customer (or whatever is suitable for you)
- Can be combined with 1)
- each master would have their own opcache (can mean quite a lot of memory consumption with many customers if set too high, since it will be the sum of the opcache.memory_consumption for each customer)
- could have better performance with regards to cache fragmentation
- for more info see: https://ma.ttias.be/a-better-way-to-run-php-fpm/

# System information
* Froxlor version: 0.9.40.1-1 (DB: 201809280)
* Web server: apache2.4
* DNS server: Bind9
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: `Linux h2 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux`

**Comment by d00p** [comment]
opcache with php-fpm process is ALWAYS shared per master-process...there is no other way. Has been discussed multiple times

separate into own master processes? Makes php-fpm itself meaningless if i have a master-process for every customer / domain. Makes no sense for froxlor.
