### ISSUE TITLE
PHP exception in ticketarchive job

### ISSUE THREAD

**Issue by Martin-vH** [Froxlor/Froxlor#656]
From the master cronjob, I'm getting the following mail:

### Cron <root@mail> /usr/bin/nice -n 5 /usr/bin/php -q /var/www/froxlor/scripts/froxlor_master_cronjob.php --ticketarchive 1> /dev/null

```
PHP Fatal error:  Uncaught Exception: Invalid ticket id in /var/www/froxlor/lib/classes/ticket/class.ticket.php:137
Stack trace:
#0 /var/www/froxlor/lib/classes/ticket/class.ticket.php(70): ticket->readData()
#1 /var/www/froxlor/lib/classes/ticket/class.ticket.php(84): ticket->__construct(NULL, 1)
#2 /var/www/froxlor/scripts/jobs/cron_ticketarchive.php(39): ticket::getInstanceOf(NULL, 1)
#3 /var/www/froxlor/scripts/froxlor_master_cronjob.php(80): require_once('/var/www/froxlo...')
#4 {main}
 thrown in /var/www/froxlor/lib/classes/ticket/class.ticket.php on line 137
```

I don't use support tickets, there is just one test ticket. If I view it in the archived tickets view, I'm getting the same error in the GUI.
Any ideas why this is happening?

**Comment by d00p** [comment]
Dump content of ticket table please so I can test with your data.

**Comment by Martin-vH** [comment]
Sure, here your are: [panel_tickets.sql.gz](https://github.com/Froxlor/Froxlor/files/2868711/panel_tickets.sql.gz)

**Comment by d00p** [comment]
okay, problem is, the cron does not call the functions as any user but the readData() functions needs that. If you really need this, I'll get something done - but the ticket-feature is deprecated and not part of the future versions of froxlor

**Comment by d00p** [comment]
0.10.0-rc1 is out and ticketsystem has been removed from froxlor
