### ISSUE TITLE
Bug: Plans create with empty name, edit not possible

### ISSUE THREAD

**Issue by drexlma** [Froxlor/Froxlor#658]
Wenn du einen Plan erstellst, kannst du es ohne namen speichern, da der name nicht required ist.

Danach funktioniert das editieren nicht mehr.

**Comment by d00p** [comment]
Current master I guess?

**Comment by d00p** [comment]
Ups, wrong button

**Comment by drexlma** [comment]
Master throws with me n 500 errors because the vendor-folder does not exist. Therefore tested only with 9.x master.

**Comment by d00p** [comment]
0.9.x is old. Read the installation notes here in the wiki on 0.10/master
