### ISSUE TITLE
extrausers/passwd with "Froxlor User" and ssmtp make problems

### ISSUE THREAD

**Issue by drexlma** [Froxlor/Froxlor#659]
Beim Mailversand steht n falscher Absender Name dran :) 

ssmtp.conf
`
root=postmaster@se4.se-medien.de
mailhub=172.18.0.1
#FromLineOverride=YES
`

mail header:
From: "Froxlor User" <evkiki@customer.php.se4.se-medien.de>

extrausers:
/var/lib/extrausers/passwd:evkiki:x:10002:10002:Froxlor User:/var/customers/webs/evkiki/:/bin/false

könnte man den Namen dort ändern? :) 

Keine hohe Prio.

**Comment by d00p** [comment]
May to the customers name?

**Comment by drexlma** [comment]
i think so.
