### ISSUE TITLE
Error on reactivating a deactivated customer

### ISSUE THREAD

**Issue by princeofnaxos** [Froxlor/Froxlor#660]
If a customer has been deactivated, an error occurs when trying to reactivate it. The error is:

```
A database error occurred
SQLSTATE[28000]: Invalid authorization specification: 1133 Can't find any matching row in the user table
```

Froxlor version: 0.10.0-master
OS: Debian 9 Stretch
Webserver: Apache 2.4
mySQL: Ver 9.1 Distrib 10.1.37-MariaDB

**Comment by d00p** [comment]
Please set `$sql['debug'] = true;` in your lib/userdata.inc.php - the trace helps finding the issue
