### ISSUE TITLE
function makeoption() in lib/install/class.FroxlorInstall.php is not defined and called on line 742

### ISSUE THREAD

**Issue by adebai** [Froxlor/Froxlor#661]
# Bug report vs. support request
If you're unsure of whether your problem is a bug or a configuration error
* contact us via IRC in #froxlor on freenode
* or post a thread in our forum at https://forum.froxlor.org

As a rule of thumb: before reporting an issue
* see if it hasn't been [reported](https://github.com/Froxlor/froxlor/issues) (and possibly already been [fixed](https://github.com/Froxlor/froxlor/issues?utf8=✓&q=is:issue%20is:closed)) first
* try with the git master

# Summary

Please provide a concise summary of the problem you're experiencing...

# System information
* Froxlor version: $version/$gitSHA1
* Web server: apache2/nginx/lighttpd
* DNS server: Bind/PowerDNS (standalone)/PowerDNS (Bind-backend)
* POP/IMAP server: Courier/Dovecot
* SMTP server: postfix/exim
* FTP server: proftpd/pureftpd
* OS/Version: ...

# Steps to reproduce

1.
2.
3.

# Expected behavior

1.
2.
3.

# Actual behavior

1.
2.
3.

# Log files/log entries
syslog:
<pre>
example
</pre>

**Comment by adebai** [comment]
On page 2, after filling the form, this error code is gotten.

> Fatal error: Uncaught Error: Call to undefined function makeoption() in /var/www/panel/install/lib/class.FroxlorInstall.php:742 Stack trace: #0 /var/www/panel/install/lib/class.FroxlorInstall.php(130): FroxlorInstall->_showDataForm() #1 /var/www/panel/install/lib/class.FroxlorInstall.php(111): FroxlorInstall->_showPage() #2 /var/www/panel/install/install.php(22): FroxlorInstall->run() #3 {main} thrown in /var/www/panel/install/lib/class.FroxlorInstall.php on line 742

> 

When i checked the file, the function makeoption() is not defined and no file is included that contains makeoption().

**Comment by d00p** [comment]
Installation is not yet ported to newer layout, for testing at the moment only an update from 0.9.40.1 works

**Comment by d00p** [comment]
Also, next time, fill the TEMPLATE of the issue, do not post the template-content....thanks
