### ISSUE TITLE
Implement DMARC

### ISSUE THREAD

**Issue by Logicbloke** [Froxlor/Froxlor#662]
Hey guys,

Any plans to add support for DMARC? I think this is a simple one that can be added fairly simply.

**Comment by d00p** [comment]
Not high priority but yeah, sure.

**Comment by LeBaux** [comment]
Personally, I consider SPF/DMARC/DKIM support essential for a tool to manager web-server. While I understand it might not be a priority for everyone, it is a disqualifying factor for me.

**Comment by d00p** [comment]
it is essential yes, but it only makes sense if froxlor is the managing DNS server, froxlor cannot add/edit dns entries in foreign systems

**Comment by LeBaux** [comment]
If you look at the ISPConfig/Vesta and others, they just generate the records for you. I understand SPF/DMARC have little to do with Froxlor, but DKIM requires actual implementation. SPF/DMARC are simple from there, honestly.

**Comment by d00p** [comment]
we are froxlor and not ipsconfig or anything else. And i never said we won't implement generation of dmarc records, just that it only makes sense when using the dns feature which is not very heavily used among the users (almost noone runs their own nameserver). Also this issue is not about DKIM

**Comment by discordier** [comment]
> (almost noone runs their own nameserver).

I do and would love having DMARC and DKIM! :smile_cat:
Especially as DNS may now be changed via API - provides a way to have customers change their `remote.example.org` DNS entries which they need to make their "MS Exchange servers" reachable... I know it is not that common for ISPs to allow this but we do.

The problem I see is, how can one add "own" entries to these records (in this issue DMARC) like a custom `rua` or `ruf` per domain?

All of this needs much planning ahead and I do not see this happening in the mid-near future.

**Comment by makuser** [comment]
Is anybody working on this already, even little steps?
I need this feature too.

**Comment by Logicbloke** [comment]
Yeah this one is just a DNS entry. I kind of let DMARC down since it prevented some of my emails from being delivered especially if the filter is at 100% and you're sending from Gmail or another IP. Exceptions can be added of course.

**Comment by crazy4chrissi** [comment]
I recommend to setup [rspamd](https://rspamd.com/). It includes DKIM signing and checking, SPF checking and DMARC. And a really good spamfilter, better than amavisd/spamassasin.
Sure you have to generate keys and configure them in DNS yourself.
With the new Froxlor API, no problem to do so automatically for all domains configured in Froxlor.

**Comment by Neustradamus** [comment]
To follow this important ticket!

**Comment by Neustradamus** [comment]
@d00p: Excellent, good job!

Happy New Year 2024!
