### ISSUE TITLE
BUG:  "log_format" directive is not allowed here

### ISSUE THREAD

**Issue by tczaude** [Froxlor/Froxlor#663]
# Summary

When You set in panel custom log file

> **Access-log** formatEnter a custom log-format here according to your webservers specifications, leave empty for default

You recive

> "log_format" directive is not allowed here

Log format should be included in main file nginx.conf or in custom conf directory example "include conf/logs.conf" i thing is better solution

similar problem in this link
https://linuxacademy.com/community/posts/show/topic/9687-nginx-lemp-stack-error-when-setting-custom-access-log-in-vhost-docs-dont-match-video

# System information
* Froxlor version:  0.9.40.1 
* Web server: nginx-1.15
* DNS server: Bind/PowerDNS (standalone)/PowerDNS (Bind-backend)
* POP/IMAP server: Courier/Dovecot
* SMTP server: postfix/exim
* FTP server: proftpd/pureftpd
* OS/Version: Gentoo

**Comment by d00p** [comment]
Problem is, we do not generate the nginx.conf so we cannot just add an "include ..." to it

**Comment by tczaude** [comment]
Your patch should work ok :)
No we wait for .010 
Thanks
