### ISSUE TITLE
Error on renewing LetsEncrypt certs "No Key ID in JWS header"

### ISSUE THREAD

**Issue by s-hemer** [Froxlor/Froxlor#664]
I just got one warning mail yesterday, stating that there are illegal string offsets in `class.lescript_v2.php` (line66-69) so I checked various thing and realized that I forgot to update the `/etc/cron.d/froxlor` to call `/usr/bin/php` instead of the old `/usr/bin/php5` (that for whatever reasons was specified there). But that was just the note that there is something wrong in the LetsEncrypt cert renewal:

The syslog is full of `{"type":"urn:ietf:params:acme:error:malformed","detail":"No Key ID in JWS header","status":400}` responses. Same for running `froxlor_master_cronjob.php --letsencrypt` manually.. The last successful certs update was in mid of January, at least one month after I switched to php7 (beside the cronjob entry). That let me assume that there must be some other issue and also that warning from the mail was long after the first syslog entries.

What I can add: it started with the domains that I have enabled to use LetsEncrypt the earliest with (and that became invalid tonight after at least one week of renewal tries) but also a domain that is still valid (and was added later, cannot say when actually). I decided this to be an issue as I did no changes manually in the recent time (years) and just used froxlor for configuring domains and LetsEncrypt. But correct me if I oversaw something (did not found anything related to froxlor).

# System information
* Froxlor version: 0.9.40.1-1
* PHP version: PHP 7.0.33
* OS/Version: Debian 9.8

**Comment by d00p** [comment]
1) the path to php to use in the cron.d file is a setting, you can adjust that there

2) for now, quick solution is to use ACMEv1. Future versions of froxlor will have another implementation of let's encrypt anyway

**Comment by s-hemer** [comment]
Thanks for that very fast reply.

1.) thanks for the hint, adjusting this is of course the more persistent way but as I said it was just the initial warning that made me look deeper and definitively not the reason (although I do not have any explanation why even the warning happened). 

2.) I may have forgotten to switch to v2 myself, but it must have been ages ago (so not in January when the last successful renewal was executed). V1 works for now.

Let me know if I should further investigate on this issue (also in advance of another future  implementation).

**Comment by s-hemer** [comment]
I should do my other work but I can't stop thinking about this, so maybe at least as a memo to myself:

Regarding the different let's say generations of certificates I already outlined, it may be a similar issue resulting from the initial generation with V1 (I am pretty sure that this was the case at least for the first domains) as discussed at [letsencrypt.org](https://community.letsencrypt.org/t/acme-v2-missing-jws-header-with-acme-sh/55665/3) and the related issue Neilpang/acme.sh#1360

May be irrelevant with the new implementation you mentioned, though.

**Comment by d00p** [comment]
0.10.0-rc1 is out now, it's using acme.sh
