### ISSUE TITLE
Feature Request: (more) GDPR compliant logrotate

### ISSUE THREAD

**Issue by sokai** [Froxlor/Froxlor#665]
# Summary
## Short
Changing the logrotate to `daily` and `rotate 7`.

## Long(er)
Because ATM there is no UI for changing `/etc/logrotate.d/froxlor` individually we have to change all files in https://github.com/Froxlor/Froxlor/tree/master/lib/configfiles.

## Background
* Froxlor saves IP addresses in the logs
* with GDPR saving IP addresses is allowed only **when essential required**
* maybe it's okay to save IP addresses for technical reasons (attacks, abuse, …) – but max. 7 days
* read more at https://serverfault.com/a/920466

# Acknowledgement
I know
* this is only a quick workaround
* there should be a/more discussion about GDPR related things (and Froxlor)
* …

I can
* make the changes and generate a PR
  * but ATM I do not know how a Froxlor update can handle this (please guide me)

**Comment by d00p** [comment]
basically, this is part of the one-time service configuration so an "update" is not required.
And what froxlor provides is just a recommendation / example - you are always free to adjust any config off any service to your needs or your countries (law) requirements.

Of course we can adjust the logrotation to `daily` and `rotate 7` - pull requests are very welcomed. it's not more than adjusting that in the XML files in `lib/configfiles/`

**Comment by sokai** [comment]
Thanks @d00p for your fast reply!

> basically, this is part of the one-time service configuration so an "update" is not required.

That means, with a Froxlor update the changes will not be applied on a running Froxlor.(? Only new installations are effected.)

> And what froxlor provides is just a recommendation / example - you are always free to adjust any config off any service to your needs or your countries (law) requirements.

:+1: Indeed, but I think the suggested changes will be closer to the GDPR … – But everybody should self-valuate and (maybe) change things, releated to the GDPR!

> Of course we can adjust the logrotation to `daily` and `rotate 7` - pull requests are very welcomed. it's not more than adjusting that in the XML files in `lib/configfiles/`

Okay, I will prepare a PR … :-)
