### ISSUE TITLE
Future: implement dovecot 2.3 submission proxs

### ISSUE THREAD

**Issue by drexlma** [Froxlor/Froxlor#668]
wäre was für die zukunft. debian bietet nur 2.2 an. wäre also was für debian 10. 
Aktuell teste ich gerade bisschen rum. Ich würde hier, wenn es läuft, mein ergebnis bereit stellen.

Bisher bekomme ich es jedoch nicht zum laufen. -> " unknown user" :/

`protocols = imap sieve submission

protocol submission {

}

service submission-login {
  inet_listener submission {
    port = 587
  }
}
service submission {
}`

**Comment by d00p** [comment]
Ist das halt nicht ansich Postfix sache?

**Comment by Dessa** [comment]
dazu ein klares: jein.

in einer konfiguration ohne smtp rejections (die ja ansich nicht zutrifft weil wir den postfix ja checken lassen ob die from adresse vom loginuser stammt (glaube ich zumindest?!)) ist es sinnvoll da wir uns einen db lookup sparen - dovecot/auth hat den kram ja schon da.

als das ding in 2.3 dazukam wollt ich mir das auch mal genauer ansehen, kam aber bisher nicht dazu.
ich meine naemlich dass ein outbound content filter dann eher nicht funktioniert aber den haben wir ja eh nicht in der standardconfig - wie gesagt, muss ich mal schauen
