### ISSUE TITLE
Nginx: duplicate location /

### ISSUE THREAD

**Issue by drexlma** [Froxlor/Froxlor#669]
nginx: [emerg] duplicate location "/" in /etc/nginx/sites-enabled/30_froxlor_ssl_vhost_pm1.de1.dbe.academy.conf:38

Ich will folgendes in die vhost eintragen

location / {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            #Change to match you container addresses and ports
            proxy_pass http://172.18.0.9:3000/;
            proxy_set_header X-Forwarded-Ssl on;
     }

geht aber nicht weil 

	location / {
		index index.html index.htm;
	}

noch drin steht.

Kann man da ne auswahl im backend hinzufügen?

**Comment by d00p** [comment]
_eigentlich_ merged froxlor diese angaben mit den automatisch generierten zusammen, müsst ich mir mal genauer anschauen, danke für den hinweis

**Comment by d00p** [comment]
Also rein die merge-function (`Froxlor\Cron\Http\Nginx::mergeVhostCustom`) tut genau was sie soll. Der Content sieht danach so aus:
`location / {
	index index.html index.htm;
	proxy_set_header Host $http_host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;
	#Change to match you container addresses and ports
	proxy_pass http://172.18.0.9:3000/;
	proxy_set_header X-Forwarded-Ssl on;
}`

Jetzt schau ich mal wieso das ggfls nicht gemacht wird

**Comment by d00p** [comment]
Sagst du mir mal welche Froxlor Version du nutzt und hast du ggfls die Möglichkeit das auf einem Testsystem mit der aktuellen 0.10.0-rc1 zu testen?

**Comment by drexlma** [comment]
Ich nutze das leider direkt live. Sobald das SSL Problem behoben ist sag ich dir bescheid.

**Comment by d00p** [comment]
anything new?

**Comment by drexlma** [comment]
gleiches Problem aber 

wenn ich im eigenen v-host "location / {" eintrage funktioniert es
und mit "location /{" funktioniert es nicht. das leerzeichen ist wohl sehr entscheidend.

**Comment by d00p** [comment]
Hm, muss man Mal den regex prüfen

**Comment by d00p** [comment]
Ist denn `location /{` überhaupt korrekter syntax?

**Comment by drexlma** [comment]
> Ist denn `location /{` überhaupt korrekter syntax?
http://nginx.org/en/docs/http/ngx_http_core_module.html#location



gute Frage,
es funktioniert zumindest mit der aktuellsten nginx version

**Comment by d00p** [comment]
Can you test attached patch with current git-master?


[0002-fix-vhost-parts-merging-in-nginx-cron-fixes-669.patch.txt](https://github.com/Froxlor/Froxlor/files/3246994/0002-fix-vhost-parts-merging-in-nginx-cron-fixes-669.patch.txt)
