### ISSUE TITLE
HTTP2 Unterstützung nginx

### ISSUE THREAD

**Issue by drexlma** [Froxlor/Froxlor#670]
in der vhost steht nicht drin das es auch https2 kann. Auch wenn die Option unter Einstellungen gesetzt ist.

server {
	listen 172.18.0.4:443 ssl;

http2 fehlt dort.

**Comment by d00p** [comment]
Testest du auch mit aktuellem master? Laut Code ist das drin wenn SSL=true und http2 aktiviert

**Comment by drexlma** [comment]
ach mh ne noch immer mit dem lesten build.

denkst du der master ist schon reif für einen Produktiv-Server? :D

**Comment by d00p** [comment]
Ich sag nur das man am besten mit dem aktuellen Entwickler stand testet bevor man fehler meldet die vllt schon behoben sind
