### ISSUE TITLE
Using InnoDB instead of MyISAM: It's time to say goodbye.

### ISSUE THREAD

**Issue by patschi** [Froxlor/Froxlor#671]
## Situation

Froxlor 0.10 brings quite a lot of changes under the hood and also a very cool API, beside that it also adds compatibility for MySQL 8. While I'm absolutely not a fan of MySQL and I'm happy with my MariaDB, I think it is a very good time to say goodbye to MyISAM.

MyISAM is old, more unreliable on crashes (no crash recovery) and doesn't have transaciton logs, doesn't support foreign key constraints, no table locking and some other stuff. Even MySQL 8 deprecates and removes some functionality of MyISAM: https://www.percona.com/blog/2016/10/11/mysql-8-0-end-myisam/ (And notice, that's a post back in October 2016)

It's definitely time to get rid of MyISAM finally.
Adding foreign key constraints might be an other step.

### Option 1: Adding `ALTER TABLE` statements procedure to the normal update process.

**Pro**: Everyone has InnoDB automatically.
**Contra**: Might delay the update process noticeably, depending on the database size. (However the updates should be done in maintenance windows anyway)

### Option 2: Only use InnoDB by default on newer installations and offer a CLI command to perform the migration in an automated way by firing the `ALTER TABLE` sql statements manually.

**Pro**: Everyone can schedule the recommended upgrade when there's enough time for maintenance.
**Contra**: Users might not know about the migration to InnoDB and stick with MyISAM. This might cause issues in the future when MyISAM is dropped completely.

## Note

I'm running Froxlor using InnoDB since the beginning of the installation just fine, without any troubles, issues or performance difference. I think it's safe to migrate and should not have any sideeffects.

**Comment by d00p** [comment]
sounds good :)

**Comment by tczaude** [comment]
I vote. MyIsam breaks with hight load froxlor db in some situations. I will waiting 😃

**Comment by tczaude** [comment]
I vote. MyIsam breaks with hight load froxlor db in some situations. I will waiting 😃

**Comment by patschi** [comment]
I don't think this is somehow related to myISAM. Theoretically InnoDB is slower, as it has transaction logs and such stuff, which MyISAM doesn't.

**Comment by tczaude** [comment]
I agree Innodb is theoretically slower but no in all cases but this no problem for froxlor. 
MyISAM when You have big overload IO randomly crash table... With innodb / aria problem not exist.
One plus MyIsam have fast rapier tools :)
