### ISSUE TITLE
[feature request] database name prefixes + custom name

### ISSUE THREAD

**Issue by ghost** [Froxlor/Froxlor#672]
I would like to choose the names for my databases.

I have now 7 databases called mostly like

user1
user2
...
user7

Is difficult to know which one is doing what
thx.

**Comment by d00p** [comment]
Thats what the description is for. The naming is intentionally this way. When there are many customers on your server and they all use wordpress, they will all try to name the db `wordpress`. Not only would we have to check for existance prior to adding a new database but also this exposes database names (e.g. `database name 'wordpress' already in use`)

**Comment by jucajuca** [comment]
thx, maybe you can still think about a way to do this, for example using prefixes, and allowing a bit of the name to be set manually. for example

usr1_joomla
usr1_wordepress
usr1_phpapp
...

it would make  froxlor a bit better. I use it for myself and manage the dbs also through phpmyadmin, where the names make little sense

**Comment by d00p** [comment]
possible yes

**Comment by pquerner** [comment]
What would you prefer? Customer (id, name) prefix ? Extra field ("database name") (including prefix)

**Comment by jucajuca** [comment]
yes, the customer name as prefix and the database name attached to it should work, like:

customername_dbname
