### ISSUE TITLE
PowerDNS - Fatal error: Trying to set unknown parameter 'allow-recursion'

### ISSUE THREAD

**Issue by tczaude** [Froxlor/Froxlor#673]
In config is variable 'allow-recursion' and is unknow for 
net-dns/pdns-4.1.5 if is set pdns started but not handling dns request 

# System information
Froxlor version: 0.9.40.1 (DB: 201809280)
PowerDNS (standalone)
OS/Version: Gentoo 

1. Bad config in panel

**Comment by d00p** [comment]
Yes, powerdns doc says: `Warning: Recursion was removed from the Authoritative Server in version 4.1.0`
(see https://github.com/PowerDNS/pdns/pull/4752)

Most distros currently still have 4.0.x - but yeah, we need to adjust the config templates for some for the next release (0.10.x)
