### ISSUE TITLE
/admin_settings.php

### ISSUE THREAD

**Issue by drexlma** [Froxlor/Froxlor#685]
PHP warning/error
#8 Undefined index: databaseCharset

 

admin_settings.php:273
 

PHP warning/error
#8 Undefined index: domainIpTable

 

admin_settings.php:273
 

PHP warning/error
#8 Undefined index: froxlorLocalGroupMemberForFcgidPhpFpm

 

admin_settings.php:273
 

PHP warning/error
#8 Undefined index: subdomainLetsencrypt

 

admin_settings.php:273
 

PHP warning/error
#8 Undefined index: subdomainSslRedirect

 

admin_settings.php:273
 

PHP warning/error
#8 Undefined index: webserverGroupMemberForFcgidPhpFpm

 

admin_settings.php:273

**Comment by d00p** [comment]
git pull ;) see https://github.com/Froxlor/Froxlor/commit/72016a5735e77634522e53975f3b2b63ba1f8a2d
