### ISSUE TITLE
/admin_settings.php?page=overview&part=ssl&s=xxx

### ISSUE THREAD

**Issue by drexlma** [Froxlor/Froxlor#686]
actions/admin/settings/190.ticket.php:23
 

PHP warning/error
#8 Undefined index: ticket

 

actions/admin/settings/190.ticket.php:26
 

PHP warning/error
#8 Undefined index: ticket

 

actions/admin/settings/190.ticket.php:36
 

PHP warning/error
#8 Undefined index: ticket

 

actions/admin/settings/190.ticket.php:45
 

PHP warning/error
#8 Undefined index: ticket

 

actions/admin/settings/190.ticket.php:53
 

PHP warning/error
#8 Undefined index: tickets

 

actions/admin/settings/190.ticket.php:59
 

PHP warning/error
#8 Undefined index: tickets

 

actions/admin/settings/190.ticket.php:59
 

PHP warning/error
#8 Undefined index: tickets

 

actions/admin/settings/190.ticket.php:59
 

PHP warning/error
#8 Undefined index: tickets

 

actions/admin/settings/190.ticket.php:59
 

PHP warning/error
#8 Undefined index: ticket

 

actions/admin/settings/190.ticket.php:64
 

PHP warning/error
#8 Undefined index: ticket

 

actions/admin/settings/190.ticket.php:72
 

PHP warning/error
#8 Undefined index: ticket

 

actions/admin/settings/190.ticket.php:82
 

PHP warning/error
#8 Undefined index: ticket

 

actions/admin/settings/190.ticket.php:90
 

PHP warning/error
#8 Undefined index: ticket

 

actions/admin/settings/190.ticket.php:99
 

PHP warning/error
#8 Undefined index: ticket

 

actions/admin/settings/190.ticket.php:108
 

PHP warning/error
#8 Undefined index: ticket

 

actions/admin/settings/190.ticket.php:116
 

PHP warning/error
#8 Undefined index: ticket

 

actions/admin/settings/190.ticket.php:130
 

PHP warning/error
#8 Undefined index: ticket

 

actions/admin/settings/190.ticket.php:136
 

PHP warning/error
#8 Undefined index: ticket

 

actions/admin/settings/190.ticket.php:136
 

PHP warning/error
#8 Undefined index: ticket

 

actions/admin/settings/190.ticket.php:136

**Comment by d00p** [comment]
There is no more ticket-system in 0.10.x

**Comment by drexlma** [comment]
aaah ok hab nicht richtig geupdated :)
