### ISSUE TITLE
Disabling SSL-vhost for  if system.ssl_cert_file  not exist

### ISSUE THREAD

**Issue by drexlma** [Froxlor/Froxlor#687]
Kann jedoch nicht genau sagen wieso.

...
[debug] System certificate file "/etc/nginx/nginx.pem" does not seem to exist. Disabling SSL-vhost for "xxx.eu1.jobsuche-regional.com"
...

das ist in der alten version kein Problem. 
Danach scheint er die Zertifikate zu löschen.

**Comment by d00p** [comment]
That happens if you do not have Let's Encrypt activated nor a custom ssl-certificate assigned to a domain then froxlor checks whether you have specified a certificate for the used IP/port and THEN even falls back to the system settings (SSL settings) which might be where `/etc/nginx/nginx.pem`comes from.

**Comment by d00p** [comment]
Btw `Disabling SSL-vhost for if system.ssl_cert_file not exist` ... for? for what? Would be important to know-. Also, if possible provide steps to reproduce

**Comment by drexlma** [comment]
neuer Versuch mit rc2 (upgrade von 0.9.40.1 - standard installation)

#  php /var/www/froxlor/scripts/froxlor_master_cronjob.php --force --debug
[error] jobboerse-berlin.org :: certificate key file "/etc/apache2/apache2.key" does not exist! Cannot create ssl-directives

geht um die Variable system_ssl_key_file und system_ssl_cert_file

**Comment by drexlma** [comment]
achja wenn ich die einstellungen leere kommt nur 
[debug] System certificate file "" does not seem to exist. Disabling SSL-vhost for "jobboerse-berlin.org"

**Comment by drexlma** [comment]
So ich hab eben unter nginx, debian 9-slim das teil **neu installiert**. per default steht unter "Einstellungen"->"Ssl-Einstellungen" jeweils 2 werte drin


----

Pfad zum SSL-ZertifikatGeben Sie den Pfad inklusive Dateinamen des Zertifikats an (meist .crt or .pem). |   /etc/nginx/nginx.pem
-- | --
Pfad zum SSL Private-KeyGeben Sie den Pfad inklusive Dateinamen der Schlüssel-Datei an (der private-key, meist .key). |   /etc/apache2/apache2.key
----- 

hab dann eine SSL Ip eingerichtet, Lets aktiviert und dann die domain hinzugefügt

aaber 
[error] localhost :: certificate key file "/etc/apache2/apache2.key" does not exist! Cannot create ssl-directives
[error] cimnet.de :: certificate key file "/etc/apache2/apache2.key" does not exist! Cannot create ssl-directives
gleiches spiel

**Comment by d00p** [comment]
Na vllt erstellst du das Zertifikat dann auch mal....Das ist nichts was froxlor selbst generiert.
Zudem: Benutze doch bitte für normalen Support unser Forum....

**Comment by drexlma** [comment]
Wieso funktioniert es dann problemlos mit der Version 0.9.40.1?  ;) bin für n einfachen Upgrade. 

openssl genrsa -out /etc/apache2/apache2.key 2048﻿

wäre das nicht auch was fürs wiki? dann könnte man in den einstellungen vllt aufs wiki verweisen?

**Comment by d00p** [comment]
Auch bei 0.9.x war das schon...seit Jahren...

**Comment by drexlma** [comment]
:) da existieren die Dateien nicht  bei mir und es funktioniert trotzdem.

**Comment by d00p** [comment]
Support -> forum.
