### ISSUE TITLE
nginx: [emerg] "log_format" directive is not allowed here in /etc/nginx/sites-enabled/30_xxx:9

### ISSUE THREAD

**Issue by drexlma** [Froxlor/Froxlor#688]
nginx: [emerg] "log_format" directive is not allowed here in /etc/nginx/sites-enabled/30_froxlor_normal_vhost_xxxe.conf:9
wenn unter "Access-Log Format" was eingetragen wird.

-> http://nginx.org/en/docs/http/ngx_http_log_module.html#log_format
Syntax: | log_format name [escape=default\|json\|none] string ...;
-- | --
log_format combined "...";
http

Froxlor 0.41

**Comment by d00p** [comment]
bitte keine fehler für 0.9.x melden...testen bitte immer mit aktueller git-master version
(fixed in 0.10.x -> https://github.com/Froxlor/Froxlor/commit/b1bbb1847d34064fff7a33d25cc2d013c95b1869)

**Comment by drexlma** [comment]
thx ist dort schon gefixt
