### ISSUE TITLE
vendor fehlt in rc2

### ISSUE THREAD

**Issue by drexlma** [Froxlor/Froxlor#690]
PHP message: PHP Warning:  require(/var/www/froxlor/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/froxlor/install/install.php on line 18

Hier wäre eine Fehlermeldung praktisch wie ich den fehlenden Vendor Ordner bekomme. 
Hab ihn mir ausm rc1 geholt

**Comment by d00p** [comment]
Sollte das release-script eigentlich machen, muss ich prüfen, danke

**Comment by d00p** [comment]
Hm, sicher das du das .tar.gz geladen hast? Der Ordner mit allen Dateien ist da enthalten...wenn du dir das via git clone holst musst du natürlich manuell `composer install` ausführen

**Comment by Dessa** [comment]
du hast das archiv von github? mach das mal nicht, denn da ist vendor/ nicht drin, github nimmt fuer das archiv den reinen git-hash vom tag und macht da nichts extra mit, ist aber notwendig in unserem fall

**Comment by drexlma** [comment]
ach ok, dann wäre trotzdem eine Fehlermeldung gut mit Lösung. oder in der Readme.
