### ISSUE TITLE
Ungültige IP-Adresse: "172.18.0.2"

### ISSUE THREAD

**Issue by drexlma** [Froxlor/Froxlor#691]
Fehlermeldung beim anlegen einer neuen IP-Adresse (IPs und Ports->  IP-Adresse/Port hinzufügen)
Ungültige IP-Adresse: "172.18.0.2"
Ungültige IP-Adresse: "192.168.178.1"

sieht danach aus als ob Private Adressen nicht erlaubt sind?

**Comment by d00p** [comment]
Genau so ist es...

**Comment by drexlma** [comment]
ok und wenn ich Froxlor in einem Unternehmensnetzwerk verwenden will? 
Interner Cloud-Dienst, Intranet, Forum, Chat? 


wenn nein, dann sollten die IT-Ler in größeren Firmen zumindest drauf hingewiesen werden:

https://github.com/Froxlor/Froxlor/pull/692

oder die machen es wie ich, per MySQL in die Tabelle panel_ipsandports rein gehen und von hand die IP hart eintragen.

**Comment by d00p** [comment]
Dann mach das wenn du willst....gedacht ist es halt so nicht, wir verbieten das nicht umsonst
