### ISSUE TITLE
Im wiki fehlt der hinweiß auf den composer 

### ISSUE THREAD

**Issue by drexlma** [Froxlor/Froxlor#694]
https://github.com/Froxlor/Froxlor/wiki/Install-froxlor-from-tarball#1-download-the-tarball

-> https://github.com/Froxlor/Froxlor/issues/690

**Comment by d00p** [comment]
Nein fehlt er nicht, du guckst nur an der falschen stelle: https://github.com/Froxlor/Froxlor/wiki/Install-froxlor-from-git-sources
(oder du benutzt das falsche archiv, bitte NICHT das von github nutzen, siehe #690)
