### ISSUE TITLE
Let's Encrypt Umgebung, kein effekt?

### ISSUE THREAD

**Issue by drexlma** [Froxlor/Froxlor#696]
Wenn ich das auf Stage-Stelle, scheint er trotzdem das live zu nehmen.

**Comment by d00p** [comment]
Bitte etwas mehr Info wenn du schon eventuelle Fehler meldest...oder Versuch es doch erstmal via Forum, vllt machst du einfach was falsche

**Comment by drexlma** [comment]
actions/admin/settings/131.ssl.php:139

**Comment by d00p** [comment]
...sorry, ne, so nicht

**Comment by d00p** [comment]
Versuch das mal:
```diff
diff --git a/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php b/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php
index 07e1ec27..ae0547e7 100644
--- a/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php
+++ b/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php
@@ -282,6 +282,9 @@ class AcmeSh extends \Froxlor\Cron\FroxlorCron
                        if (Settings::Get('system.letsencryptreuseold') != '1') {
                                $acmesh_cmd .= " --always-force-new-domain-key";
                        }
+                       if (Settings::Get('system.letsencryptca') == 'testing') {
+                               $acmesh_cmd .= " --staging";
+                       }
 
                        $acme_result = \Froxlor\FileDir::safe_exec($acmesh_cmd);
```

**Comment by drexlma** [comment]
dann bitte auch den {{settings.system.letsencryptchallengepath}} nehmen für den richtigen Pfad :) 
und nicht \Froxlor\Froxlor::getInstallDir() ? 

sonst passt das mit der Datei https://github.com/Froxlor/Froxlor/blob/974b151d02e76f4a4767843eeb1bc56421956af7/lib/configfiles/jessie.xml#L82 Zeile 82 nicht mehr zusammen.

**Comment by drexlma** [comment]
perfekt :) nun läuft auch die version bei mir produktiv, ohne probleme.
