### ISSUE TITLE
SSL vhost created for domain when not selected

### ISSUE THREAD

**Issue by MrBMT** [Froxlor/Froxlor#697]
# Summary

When Creating a domain, despite leaving SSL IP address(es) unticked, the vhost is being created for both HTTP and HTTPS.

# System information
* Froxlor version: 0.10.0-rc2
* Web server: apache2
* DNS server: N/A (disabled)
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian 9

# Steps to reproduce

1. Enable SSL under Settings
2. Add SSL IP address under IPs and Ports
3. Create domain, do not tick the IP under SSL IP address(es)

# Expected behavior

1. vhost created for HTTP only

# Actual behavior

1. vhost created for HTTP and HTTPS

**Comment by d00p** [comment]
Yup, reproducable with freshly added domains, existing domains are not affected as far as I can tell

**Comment by d00p** [comment]
Small dilemma...SSL-IPs parameter is optional, but falls backs to the default-ssl-ip setting if left empty...from API side this could be correct and wanted by the admin (thats why he set default ssl-ips), but I think it's more of a frontend issue. API default should be empty, and frontend should tick the checkboxes accordingly if there's default-ssl-ips
