### ISSUE TITLE
Update / Upgrade from 0.9.40.1

### ISSUE THREAD

**Issue by tobiasredel** [Froxlor/Froxlor#698]
While trying to install froxlor 0.10 rc1/rc2 it is mentioned that database will get overwritten in case there is an old "froxlor" instance.
Is there any way to do a proper upgrade from 0.9.40.1 to the new composer based froxlor 0.10?

Thanks in advance!

**Comment by d00p** [comment]
https://github.com/Froxlor/Froxlor/wiki/Updating-Froxlor
