### ISSUE TITLE
feature request: run cronjobs from web interface

### ISSUE THREAD

**Issue by jucajuca** [Froxlor/Froxlor#699]
Hi,

It would be very helpful to be able to run the cronjobs from the web interface. At the moment I have to wait five minutes or run them through ssh. 

thx

**Comment by d00p** [comment]
That would require some sort of daemon waiting for requests which we do not have not plan to include. If you want to test something, use ssh, if it's productive, 5min is more than enough (even though you can set it lower if you want to)

**Comment by jucajuca** [comment]
ok thanks.
how about doing this with shell_exec? 
just an idea : )

**Comment by d00p** [comment]
Wow never thought of this :P - well, you need root privileges for the cronjob....if executed from within the panel it's either ww-data (webserver user) or when using fcgid/fpm some other unprivileged user (as it should be!) - so no, not possible
