### ISSUE TITLE
[Feature request] Internal / Intranet Domains through VPN

### ISSUE THREAD

**Issue by tobiasredel** [Froxlor/Froxlor#701]
Currently it is not possible to add VPN server IPs within froxlor to setup VPN / Intranet pages.
I understood, that this has been configured like that on purpose. Is there any specific reason to do so ? And is it planned to be supported in a new release?

Thanks in advance!

**Comment by d00p** [comment]
might break some parts of functionality, mostly dns related I'd say. There is nothing really planned as only few people use froxlor in such an environment. You COULD try forking the repository, enable private-network in the corresponding validations (see https://github.com/Froxlor/Froxlor/blob/master/lib/Froxlor/Validate/Validate.php#L84 which is the function to use for validation ips) and see if it breaks anything :)

Or simpler: just change the IP values directly in the table `panel_ipsandports` :P

**Comment by tobiasredel** [comment]
Yes - did so already - was just wondering of a specific reason - i can also notice some dns related issues which i am not really able to solve until know - but will have a deeper look to understand what is going on

Von meinem iPhone gesendet

**Comment by d00p** [comment]
Private network ip's are now allowed but will show a notice
