### ISSUE TITLE
question: location of certs

### ISSUE THREAD

**Issue by jucajuca** [Froxlor/Froxlor#702]
I noticed that the letsencrypt certificates are stored in a non-standard location:
/etc/ssl/froxlor-custom

Is it possible to change this? I would like to use the standard location.

If not, how can I manually renew a certificate specifying its location?

**Comment by d00p** [comment]
1) please use the forum at https://forum.froxlor.org/ for questions
2) the path for the ssl-certificates is a setting, so you can change it to your needs
3) DO NOT use /etc/ssl/ or any USED folder here, as froxlor wipes it completely when re-generating all the files!
