### ISSUE TITLE
problem sending with IDN-Punycode encoded e-mail address

### ISSUE THREAD

**Issue by cventastic** [Froxlor/Froxlor#703]
Hello, I cant debug this over IRC. Sorry.

# Summary

Please provide a concise summary of the problem you're experiencing...

When I send e-mails to a IDN-Punycode encoded e-mail address, with Thunderbird, I get the following error:

Jul 12 19:45:01 stretch postfix/smtpd[4572]: NOQUEUE: reject: RCPT from unknown[192.168.1.1]: 553 5.7.1 <test@xn--svensgert-22a.de>: Sender address rejected: not owned by user test@svensger??t.de; from=<test@xn--svensgert-22a.de> to=<test1@xn--svensgert-22a.de> proto=ESMTP helo=<[192.168.1.1]>

# System information
* Froxlor version: 
master: https://github.com/Froxlor/Froxlor/commit/db3c95ea10006374a51b4764663029b816460f99
0.9.40.1-branch: https://github.com/Froxlor/Froxlor/commit/00eb5ed87b746d4f8ae741ba37e91b2a8e2b12a5
* Web server: apache2
* DNS server: Bind
* POP/IMAP server: Dovecot 2.2.27-3+deb9u4
* SMTP server: postfix 3.1.12-0+deb9u1
* FTP server: proftpd/pureftpd
* OS/Version: Linux stretch 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux

# Steps to reproduce

1) I install froxlor from 0.9.40.1-branch or directly from master. 
Both configured as documented.
2) I set up one IDN-Punycode Domain. 
svensgerät.de
3) Next I deploy two e-mail addresses, via Frontend. But I think it also works if I use only one e-mail address.
test@svensgerät.de
test1@svensgerät.de

# Expected behavior

1. I set up the domain.
2. Set up the two e-mail addresses.
3. Can send E-Mails between them.

# Actual behavior

1. I set up the domain.
2. Set up the two e-mail addresses.
3. Now i send an e-mail from test@svensgerät.de to test1@svensgerät.de with Thunderbird. I get the attached error in Thunderbird.
![Selection_033](https://user-images.githubusercontent.com/13015146/61150616-27dffc00-a4e4-11e9-863f-6c8d5df418f3.png)

And I can also see the error in mail.log:

# Log files/log entries

Jul 12 19:45:01 stretch postfix/smtpd[4572]: NOQUEUE: reject: RCPT from unknown[192.168.1.1]: 553 5.7.1 <test@xn--svensgert-22a.de>: Sender address rejected: not owned by user test@svensger??t.de; from=<test@xn--svensgert-22a.de> to=<test1@xn--svensgert-22a.de> proto=ESMTP helo=<[192.168.1.1]>

If I dont use Thunderbird:

Trying 192.168.1.11...
Connected to 192.168.1.11.
Escape character is '^]'.
220 mail.localhost ESMTP Postfix (Debian/GNU)
auth plain login test@xn--svensgert-22a.de
503 5.5.1 Error: send HELO/EHLO first
ehlo 192.168.1.1
250-mail.localhost
250-PIPELINING
250-SIZE 52428800
250-VRFY
250-ETRN
250-AUTH PLAIN LOGIN
250-AUTH=PLAIN LOGIN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN
AUTH LOGIN
334 VXNlcm5hbWU6
dGVzdEB4bi0tc3ZlbnNnZXJ0LTIyYS5kZQ==
334 UGFzc3dvcmQ6
RmAdAKSdjMh
235 2.7.0 Authentication successful
MAIL FROM:<test@xn--svensgert-22a.de>
250 2.1.0 Ok
RCPT TO:<test1@xn--svensgert-22a.de>
553 5.7.1 <test@xn--svensgert-22a.de>: Sender address rejected: not owned by user test@svensger??t.de

Now if I update the User inside the database:
    
email: test@xn--svensgert-22a.de
username: test@svensgerät.de
`
UPDATE mail_users SET username="test@xn--svensgert-22a.de" where email="test@xn--svensgert-22a.de";
`
email: test@xn--svensgert-22a.de
username: test@xn--svensgert-22a.de

The error is gone.

**Comment by d00p** [comment]
What did you enter as "username" for incoming and outgoing mailserver? I know for a fact that this is working as I just recreated it. Yes, thunderbird does not allow to specify special charachter domains in the "e-mail address" field when adding a new account but it DOES allow that with the username fields which are the ones used for authentication.

So please, show exactly how you've added the new account and with what values

**Comment by cventastic** [comment]
It doesnt matter:

e-mail address: test@xn--svensgert-22a.de
username incoming: test@svensgerät.de
username outgoing: test@svensgerät.de

After I created the account I can see the following log message:

Jul 12 21:19:24 stretch dovecot: imap-login: Disconnected (auth failed, 3 attempts in 18 secs): user=<test@svensger?t.de>, method=PLAIN, rip=192.168.1.1, lip=192.168.1.11, session=<FCy0yICNGJXAqAEB>

But Thunderbird says: 
Passwort Ok!
After clicking 'Done' in the create e-mail address window.

When i try to send now, Thunderbird tires to authenticate:

Jul 12 21:22:16 stretch postfix/smtpd[5418]: warning: unknown[192.168.1.1]: SASL PLAIN authentication failed:
Jul 12 21:22:22 stretch postfix/smtpd[5418]: warning: unknown[192.168.1.1]: SASL LOGIN authentication failed: VXNlcm5hbWU6

And if I use:

e-mail address: test@xn--svensgert-22a.de
username incoming: test@xn--svensgert-22a.de
username outgoing: test@xn--svensgert-22a.de

Imap Login works:

Jul 12 21:27:13 stretch dovecot: imap-login: Login: user=<test@svensgerät.de>, method=PLAIN, rip=192.168.1.1, lip=192.168.1.11, mpid=5456, session=<8VXF5YCNUJXAqAEB>
Jul 12 21:27:13 stretch dovecot: imap(test@svensgerät.de): Logged out in=8 out=422

And I get the old error...

Jul 12 21:28:21 stretch postfix/smtpd[5447]: NOQUEUE: reject: RCPT from unknown[192.168.1.1]: 553 5.7.1 <test@xn--svensgert-22a.de>: Sender address rejected: not owned by user test@svensger??t.de; from=<test@xn--svensgert-22a.de> to=<test1@xn--svensgert-22a.de> proto=ESMTP helo=<[192.168.1.1]>

**Comment by d00p** [comment]
> e-mail address: test@xn--svensgert-22a.de
> username incoming: test@svensgerät.de
> username outgoing: test@svensgerät.de

works perfectly with thunderbird 60.7.2 on linux...No idea what you are doing other than me.
What are the specs for port / ssl and authentication?

**Comment by d00p** [comment]
I mean, basically it's not a big deal changing this...but i really try to avoid people having to remember the punycode of their domain :)

**Comment by cventastic** [comment]
Im on Thunderbird 60.8.0 (64-bit)
Its only a testsystem inside a vagrant box, so there is plaintext auth and no ssl.
But it appeared on our livesystem, the other day and we wanted to know why.

If you have email addresses as usernames, you have to remember punycode anyway. And thats not unreasonable to do.

And there has to be punycode encoding, when Thunderbird is sending the mail, otherwise it looks like this:
MAIL FROM:<test@svensgerät.de>
501 5.1.7 Bad sender address syntax
