### ISSUE TITLE
FR: conflcts with letsencrypt and redirects

### ISSUE THREAD

**Issue by jucajuca** [Froxlor/Froxlor#712]
I think that if the redirection to https is activated the following line is required. (in the ssl-conf file)

```
#Letsencrypt
Alias "\.well-known/acme-challenge" "/var/www/froxlor/.well-known/acme-challenge"

#<Directory "/var/www/froxlor/.well-known/acme-challenge">
#	Require all granted
#</Directory>
```

And it would be nice to have an advice about proxy redirects:

The following line would be needed to let let's encrypt work (in the custom apache conf of the interface):

`ProxyPassMatch ^/\.well-known !`

**Comment by d00p** [comment]
There should be a global alias when you configured froxlor correctly (after enabling let's encrypt). See `configuration -> [distro] -> Webserver -> [apache or nginx]`

Custom entries, if necessary can be done globally for each domain or domain-based. Proxy configuration is not part of froxlor for now.

**Comment by jucajuca** [comment]
Yes, true, but I am almost sure that if I activate a https redirect the generation of the certificate will fail because the mentioned alias will be not included in the ssl-conf file. 

Alias "\.well-known/acme-challenge" "/var/www/froxlor/.well-known/acme-challenge"

The alias work for port 80 but if there is a redirect to 443 the challenge will fail because the alias is not present in the ssl-conf. Maybe I am wrong but I have got a lot errors because of this.

**Comment by d00p** [comment]
You don't need that in your non-redirecting vhost because you should have something like that in e.g. `/etc/apache2/conf-enabled/acme.conf`:

```
Alias "/.well-known/acme-challenge" "/var/www/froxlor/.well-known/acme-challenge"
<Directory "/var/www/froxlor/.well-known/acme-challenge">
        Require all granted
</Directory>
```
