### ISSUE TITLE
Issue with php-fpm and try_files

### ISSUE THREAD

**Issue by kionez** [Froxlor/Froxlor#717]
There's a issue in /scripts/jobs/cron_tasks.inc.http.35.nginx_phpfpm.php at line 32, the try_files return code has a whitespace between "=" and "404", so the server tries the request uri, then "=" and then "404", the correct syntax [1] is "=404".

1: http://nginx.org/en/docs/http/ngx_http_core_module.html#try_files

**Comment by d00p** [comment]
Thanks, but you checked 0.9.x code, please only report issues for current git-master (0.10.x)

**Comment by kionez** [comment]
Sorry, I wrote this because i thought that reports could also be made on the stable branch.

**Comment by d00p** [comment]
0.9.x is only kept for security-related backports if any. Anything else is upcoming release of 0.10.0 :)
