### ISSUE TITLE
Enable PHP 7.3? 

### ISSUE THREAD

**Issue by terraboss** [Froxlor/Froxlor#718]
Hi,
I'm running the latest and greatest Froxlor version at my Vhost. An Debian GNU/Linux 8.11 (jessie) system. Nextcloud is complaining about an outdated PHP 7.0.33-1+0~20181208203043.8+jessie~1.gbp2ff763 version. Froxlor admin panel is running with 7.3.0-2+0~20181217092615.24+jessie~1.gbp54e52f 

I've tried anything to get rid of php 7.0 but without success. 

Can someone guide me through this process to change the default php version for all webs? 

Thanks in advance!

```
root@host:~# sudo a2enmod php7.3
Considering dependency mpm_prefork for php7.3:
Considering conflict mpm_event for mpm_prefork:
Considering conflict mpm_worker for mpm_prefork:
Module mpm_prefork already enabled
Considering conflict php5 for php7.3:
**Module php7.3 already enabled**
```

**Comment by d00p** [comment]
Not a code issue. Please use our forum (forum.froxlor.org) for support
