### ISSUE TITLE
Issue with libnss-extrausers, php-fpm and API "Customers.add" having "customer.ftpatdomain" sets to 1

### ISSUE THREAD

**Issue by kionez** [Froxlor/Froxlor#720]
Hi,

i'm trying the new API of froxlor 0.10.0, but i've noticed an issue in user creation.
I have a standard debian Buster, with nginx+php-fpm+libnss-extrausers.

When i call "Customers.add", the API creates the new system user in /var/lib/extrausers/ but it goes wrong because it creates "loginname@" instead of "loginname", forcing php-fpm daemon to not restarting (because it search for username "loginname").

I do a little research in code and I suppose that line 108 of ./Froxlor/Api/Commands/Ftps.php should be something like:
`if (Settings::Get('customer.ftpatdomain') == '1' && !$is_defaultuser) {`

Instead of:
`if (Settings::Get('customer.ftpatdomain') == '1') {`

(but it's just a quick guess, I haven't checked the code well yet)

**Comment by d00p** [comment]
That seems about right, thank you very much
