### ISSUE TITLE
Error in example/FroxlorAPI when API return no data

### ISSUE THREAD

**Issue by kionez** [Froxlor/Froxlor#722]
If someone ask for empty data, for example: "Certificates.get" for a domain that doesn't have any certificate, it fails with: 

`PHP Fatal error:  Uncaught TypeError: Return value of FroxlorAPI::getLastResponse() must be of the type array, bool returned`

So i modified the doc/example/FroxlorAPI.php replacing in line 118

`	$this->last_body = $resp['data'];`

with:
 
```
	if ($resp['data'] === FALSE)
		$this->last_body = array();
	else
		$this->last_body = $resp['data'];

```

( I know, today I'm a nuisance, but I'm adapting my dev-scripts to the new APIs and I'm reporting everything I find :) )

**Comment by d00p** [comment]
It's perfectly fine, thanks for your work. The API should (externally called) always return a valid apiresponse (array). I'll check Certificates.get, thanks

**Comment by d00p** [comment]
The sample FroxlorAPI class _requires_ you to check for an error (using `getLastError()`) prior to trying to read any result using `getLastResponse()` - I'll add a check to `getLastResponse()` to return an empty array if the last call was unsuccessful

**Comment by kionez** [comment]
I do a check, the API doesn't return an error, there is a debug print_r output I added in requestCurl() function, showing that there's no error in the response:
```
array(3) {
  'status' =>
  int(200)
  'status_message' =>
  string(11) "successfull"
  'data' =>
  bool(false)
}
```

And there's the code I use to get certificates:
```
        $fapi->request('Certificates.get', array('id'=>$dom['id'],'domainname'=>$dom['domain']));
        if (! empty($fapi->getLastError())) { echo "Error: " . $fapi->getLastError() . "\n"; exit(); }
        $certificati = $fapi->getLastResponse();
```

**Comment by d00p** [comment]
```
array(3) {
  'status' =>
  int(200)
  'status_message' =>
  string(11) "successfull"
  'data' =>
  bool(false)
}
```
hm, okay, this is technially correct :) Maybe we shouldn't force `getLastResponse()` to return an `array`?

**Comment by kionez** [comment]
I don't know if is better to change getLastResponse expected type or changing the way the data is returned, i.e.: returning an array with "count" equal to 0 and "list" as empty array, IMHO seems more consistent with what the user expects.

**Comment by d00p** [comment]
`list()` returns `['count' => x, 'list' => []]` and `get()` returns the entity as array, so yes, `Certificates.get()` should even throw an Exception when the domain does not have a certificate rather than returning `false`
