### ISSUE TITLE
[Feature request]: Add HTTP2 support for subdomains

### ISSUE THREAD

**Issue by dirkey** [Froxlor/Froxlor#725]
Any subdomain created by the user won't add the http2 support in the apache vhost file. We can either add a option to add this support, or get the support from the domain.

**Comment by sokai** [comment]
@d00p As far as I see you implemented the requested feature for Apache only, right?

→ I wish that feature too, for nginx – should I create a new ticket?

Thanks in advance! :+1:

**Comment by d00p** [comment]
No, it's there also for nginx
