### ISSUE TITLE
[Feature request/Request for comments] Abstract database support to allow adding additional engines

### ISSUE THREAD

**Issue by squash** [Froxlor/Froxlor#726]
I'm a happy user of Froxlor overall, I use it for both shared servers for customer sites and also internal applications. Our internal applications are moving away from mysql, but I'd like to be able to continue to use Froxlor to manage them.

So at a high level, are you interested in database abstraction for Froxlor? This would be two-fold, as both Froxlor's internal queries would be abstracted, as well as allowing for it to manage multiple database engines.

The concept was discussed many years ago on the old forum with the response that it was a goal but not officially on any schedule. (https://forum.froxlor.org/index.php?/topic/60-using-postgresql/) 

I'm happy to do the work to do this, if it might be accepted by the project.  My personal need is to have PGSQL and CockroachDB available, but adding additional engines should be relatively easy once an abstraction layer exists.

**Comment by d00p** [comment]
there does not seem to happen anything
