### ISSUE TITLE
bug/feat request: sepparate Own vHost-settings field for HTTPS

### ISSUE THREAD

**Issue by jucajuca** [Froxlor/Froxlor#727]
### Use case:

running python applications with mod_wsgi

### problem:

there is only one  "Own vHost-settings" for both HTTP and HTTPS. When trying to use mod_wsgi this will create a conflict because the configurations are copied both to the HTTP and the HTTPS files. Unfortunately mod_wsgi is not so intelligent and it will report an error because this "duplicates previous WSGI daemon"

```
apache2_invoke: Enable module wsgi
apache2_reload: Your configuration is broken. Not restarting Apache 2
apache2_reload: AH00526: Syntax error on line 54 of /etc/apache2/sites-enabled/35_froxlor_ssl_vhost_domain.com.conf:
apache2_reload: Name duplicates previous WSGI daemon definition.
```

**Comment by d00p** [comment]
how about this?
```
<If "%{HTTPS} == 'on'">
    # ssl-related stuff
</If>
```

**Comment by jucajuca** [comment]
I tried it but I got the following error:

AH00526: Syntax error on line 43 of /etc/apache2/sites-enabled/35_froxlor_normal_vhost_domsain.com.conf:
WSGIDaemonProcess not allowed here
Action 'configtest' failed.
The Apache error log may have more information.

**Comment by d00p** [comment]
But it is allowed without IF???

**Comment by jucajuca** [comment]
Just tested:
In both "normal" and SSL confs the WSGIDaemonProcess directive will trigger an error if it is located within an IF clause.

Without the IF clause the error mentioned above will happen.

**Comment by d00p** [comment]
So it seems yes.

**Comment by d00p** [comment]
Currently working on that. Adding fields `ssl_specialsettings` and `include_specialsettings`(whether or not to include non-ssl specialsettings too).
This will add these two parameters to `IpsAndPorts` and `Domains` API

**Comment by d00p** [comment]
In `IpsAndPorts` I will also add the fields `ssl_default_vhostconf_domain` and `include_default_vhostconf_domain` respectively

**Comment by d00p** [comment]
Could you try testing your scenario with the new settings in the git-version?

**Comment by jucajuca** [comment]
great, it works!
but you should make the include_specialsettings option true by default I think. Otherwise the existing HTTP settings do not get copied into HTTPS. In most cases this would be the best behaviour.

**Comment by jucajuca** [comment]
Sorry, I meant "**Include non-SSL vHost-settings in SSL-vHost**" should be activated by default for the next release.
Otherwise everyone will get their HTTPS sites "deactivated" as the ssl settings will be empty ; )

**Comment by d00p** [comment]
Yes, good call, this does only apply to updaters though, the installation default will be *false*

**Comment by snoopotic** [comment]
Ah. stumbled over this change... :D
Would have been nicer "...optionally allow including of non-ssl default-vhost settings" should be enabled by default as this is the behaviour before this change.
I have some settings that do reverseproxying that suddenly showed a default page...

**Comment by d00p** [comment]
Well, it's both kind of correct. But "more correct" is to not include. I've set the value to 1 for all updater coming from 0.10.0-201910110 to keep the compatibility (changed that after release, sorry, you were too fast updating :p)
