### ISSUE TITLE
add backup support to Froxlor

### ISSUE THREAD

**Issue by starnetwork** [Froxlor/Froxlor#734]
# Summary
every Server Management Panel should have backup option
please consider to add some based Borgbackup or duplicati based incremental backups to backup account, emails, FTP, DB and files so it's will be able to restore it if needed.

Regards,

**Comment by d00p** [comment]
Has been discussed many times. Froxlor is not a Backup Tool. There are many open source solutions for backup/restore/etc.

The Customer can already request a backup/dump of his files if enabled to be able to access all of his data. But that's it.

**Comment by starnetwork** [comment]
Hi,
Froxlor maybe not backup tool but it's Server Management Panel
and each Server Management Panel should have that option
there is some unique backups things, for example backup User with user settings and restore user that should be part of integrated solution since it's not be 3d party solution
Please re-consider it

**Comment by d00p** [comment]
> there is some unique backups things, for example backup User with user settings and restore user that should be part of integrated solution since it's not be 3d party solution

and that's one of the reasons. There are many ways of doing backups properly. Every admin does this task in another way or has his own preferences. Why not use established, well-tested backup solutions which are developed especially for that task?! As said, had this discussion a million times and customers do have the possibility to backup all their data within froxlor but I won't code a complete backup-solution into froxlor. You are free to fork and do that your own

**Comment by d00p** [comment]
It's just the data, if you delete the customer from froxlor you won't be able to simply restore with that. It's just the users webdata, mysql-databases and maildirs.

Enable backup for customers in settings -> account settings. As customer, click on "backup" left in the Extras menu and create a backup-task. Wait for it to complete and download files via http/ftp from the given directory

**Comment by starnetwork** [comment]
if you delete the customer from froxlor you won't be able to simply restore with that
this is what we try to get here, for example if user deleted by mistake, got compromised or any other problem, to be able restore it on one click
as it's work in other Server Management Panel like webmin, DirectAdmin, WHM, Plesk and more...

**Comment by d00p** [comment]
If that is your concern I definetly recommend a TRUE backup solution. Of not, then please use any of the others
