### ISSUE TITLE
[Feature Request] (un)Suspend of Customers via API

### ISSUE THREAD

**Issue by bady85** [Froxlor/Froxlor#735]
Since Froxlor now has an API, I think it would be helpful if we could also suspend and unsuspend customers via API, e.g. because an abuse has arrived or the billing is overdue.

Thanks

**Comment by d00p** [comment]
Admin-API (in addition to the [docs/example](https://github.com/Froxlor/Froxlor/tree/master/doc/example))

```php
$data = [
    'id' => customer-id,
    'deactivated' => 1|0
];

$fapi->request('Customers.update', $data);
```
