### ISSUE TITLE
[Bug?] php syntax error

### ISSUE THREAD

**Issue by df8oe** [Froxlor/Froxlor#736]
Since Froxlor 0.10.1 it is no longer possible to add a new domain. There is an unknown php syntax in a couple of lines in lib/Froxlor/Api/Commands/Customers.php in lines 251...267.

I can find this in apache logs:
[Sun Oct 20 13:06:08.686447 2019] [:error] [pid 3896] [client 2003:f4:1a8:d545:35:46b:85a2:c9ff:46774] PHP Parse error:  syntax error, unexpected '?' in /var/www/froxlor/lib/Froxlor/Api/Commands/Customers.php on line 251, referer: https://xyz.de/thisisthewebpath/admin_domains.php?s=session-id&page=domains&action=add

Maybe this is related to an old php version 5.6.30 (which is self maintained for this server)?

**Comment by d00p** [comment]
0.10.x is >=php7

**Comment by lonesomewalker** [comment]
How to change this in the database? Because if the server is messed up after an update, it would be very handy to have a solution to fix that :-)

**Comment by d00p** [comment]
`panel_fpmdaemons`
