### ISSUE TITLE
error 500 from monolog when upgrading to 0.10.2

### ISSUE THREAD

**Issue by kimusan** [Froxlor/Froxlor#737]
# Summary
I have tried upgrading from 0.9.40 to 0.10.2 (and .1) but when I get to first load after admin login (admin_update.php) it fails with an error 500. The apache logfile indicates that it is a problem with monolog:
`[Mon Oct 21 21:15:11.626784 2019] [:error] [pid 12130] [client 85.xx.xx.xx:40546] PHP Fatal error:  Uncaught LogicException: Missing stream url, the stream can not be opened. This may be caused by a premature call to close(). in /var/www/html/froxlor/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:96\nStack trace:\n#0 /var/www/html/froxlor/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/html/froxlor/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/www/html/froxlor/vendor/monolog/monolog/src/Monolog/Logger.php(434): Monolog\\Logger->addRecord(250, 'viewed admin_up...', Array)\n#3 /var/www/html/froxlor/lib/Froxlor/FroxlorLogger.php(173): Monolog\\Logger->addNotice('viewed admin_up...', Array)\n#4 /var/www/html/froxlor/admin_updates.php(24): Froxlor\\FroxlorLogger->logAction('30', 5, 'viewed admin_up...')\n#5 {main}\n  thrown in /var/www/html/froxlor/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 96, referer: http://hosting.xx.yy.zz/froxlor/`

removing the first line with $log-> in admin_update.php and I get a bit further - biu then the "missing stream url.." error is just shown in the admin panel instead. 
Any ideas for what can be wrong? 

# System information
* Froxlor version: 0.10.2
* Web server: apache2
* DNS server: external
* OS/Version: ubuntu 16.0.4 LTS

# Steps to reproduce

1. followed the steps on the wiki for upgrade
2.
3.

# Expected behavior

1. system working and upgrading 
2.
3.

# Actual behavior

1. error 500
2.
3.

# Log files/log entries
syslog: 
<pre>
[Mon Oct 21 21:15:11.626784 2019] [:error] [pid 12130] [client 85.xx.xx.xx:40546] PHP Fatal error:  Uncaught LogicException: Missing stream url, the stream can not be opened. This may be caused by a premature call to close(). in /var/www/html/froxlor/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:96\nStack trace:\n#0 /var/www/html/froxlor/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/html/froxlor/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/www/html/froxlor/vendor/monolog/monolog/src/Monolog/Logger.php(434): Monolog\\Logger->addRecord(250, 'viewed admin_up...', Array)\n#3 /var/www/html/froxlor/lib/Froxlor/FroxlorLogger.php(173): Monolog\\Logger->addNotice('viewed admin_up...', Array)\n#4 /var/www/html/froxlor/admin_updates.php(24): Froxlor\\FroxlorLogger->logAction('30', 5, 'viewed admin_up...')\n#5 {main}\n  thrown in /var/www/html/froxlor/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 96, referer: http://hosting.xx.yy.zz/froxlor/

</pre>

**Comment by d00p** [comment]
Do you by any means use file logging besides MySQL and syslog and possibly there are no permissions to write to the specified file?

**Comment by kimusan** [comment]
The system is a clean ubuntu install which has been running froxlor for a few years now. It wasn't until 0.10.x it started failing. 
Only logging I can think of is from froxlor in /var/customers/logs/ and the usual syslog in /var/log 

The log lines mentioned above are from /var/log/apache2-error.log

the logs in /var/customers/logs are all owned by www-data like the froxlor folder and content

**Comment by kimusan** [comment]
I wonder if it is because my panel_settings table does not have the logger.* settings yet as the db has not yet been updated, but the logger mechanism expects it to be there?

**Comment by d00p** [comment]
settinggroup = 'logger' should give you settings, it's been there for ages....

**Comment by kimusan** [comment]
mysql> select * from panel_settings where settinggroup like "logger";
+-----------+--------------+----------+-------+
| settingid | settinggroup | varname  | value |
+-----------+--------------+----------+-------+
|        21 | logger       | enabled  | 1     |
|        22 | logger       | log_cron | 0     |
|        23 | logger       | logfile  |       |
|        24 | logger       | logtypes | file  |
|        25 | logger       | severity | 1     |
+-----------+--------------+----------+-------+

**Comment by kimusan** [comment]
I changed it to this, and then it seems to be fixed:
mysql> select * from panel_settings where settinggroup like "logger";
+-----------+--------------+----------+--------------+
| settingid | settinggroup | varname  | value        |
+-----------+--------------+----------+--------------+
|        21 | logger       | enabled  | 1            |
|        22 | logger       | log_cron | 0            |
|        23 | logger       | logfile  |              |
|        24 | logger       | logtypes | syslog,mysql |
|        25 | logger       | severity | 1            |
+-----------+--------------+----------+--------------+
5 rows in set (0,01 sec)

**Comment by d00p** [comment]
Yes, you've had "file" as logtype but logfile was empty

**Comment by kimusan** [comment]
My problem here is, that I have not configured anything in relation to this so it has been introduced during the many automatic upgrades without getting corrected.

**Comment by d00p** [comment]
no it has not. No occurence of `logger` in both update scripts, 0.9.x and 0.10.x - it's been there since SysCP...so, no, no automatic upgrade messed up your settings nor has it been introduced later on.
