### ISSUE TITLE
Redirects and reverse proxy broken in custom VHost settings

### ISSUE THREAD

**Issue by schmatzler** [Froxlor/Froxlor#740]
# Summary

I've upgraded from the last 0.9 release to 0.10.3 and now all redirects or reverse proxies I've set in the custom VHost settings of the domains are broken.

Examples:

1. I want to serve pyload on one of my subdomains, so I've entered this into the custom VHost settings:

```
<Location />
  RequestHeader unset Accept-Encoding
  ProxyPass http://127.0.0.1:8001/
  ProxyPassReverse http://127.0.0.1:8001/
  Order allow,deny
  Allow from all
</Location>
```

2. On some domains I have entered redirects to other domains in the VHost settings:

`Redirect / https://example.com/`

All of these don't work anymore with 0.10.3, but they worked fine on 0.9

In my Apache error log I can see this message:

> No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive

# System information
* Froxlor version: 0.10.3
* Web server: apache2 2.4.41
* OS/Version: Debian 10 Buster

# Steps to reproduce

1. Configure Froxlor with Apache2 FPM
2. Create a subdomain (with SSL and Letsencrypt) and enter a redirect / reverse proxy into the custom VHost settings
3. You get an Error 500 instead of the actual redirect / application you want to serve

# Expected behavior

1. Getting redirected to the specified location or
2. Application behind the reverse proxy is served

# Actual behavior

1. Error 500 and Apache complains about missing DirectoryIndex

# Log files/log entries
apache2 log:
<pre>
No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive
</pre>

**Comment by schmatzler** [comment]
Note: If there **is** and index document in the DocumentRoot it will get served and the VHost settings are ignored.

**Comment by schmatzler** [comment]
Note #2: When I look into the .conf file located in /etc/apache2/sites-enabled my VHost settings are not in there. It looks like they don't get saved at all.

**Comment by d00p** [comment]
There ist not much tust changed there in 0.10.x - we never did anything with the directoryindex.

Also, of there are no vhosts generated at all then maybe something else is Off.

Can you post the Output of a Manual cronrun with `--force --debug` parameter?

**Comment by schmatzler** [comment]
The vhost config files are generated, but all of the custom VHost settings are missing in them. I can still see them all in the webinterface, but not in the .conf files.

`/usr/bin/php -q /var/www/froxlor/html/scripts/froxlor_master_cronjob.php --force --debug
[information] TasksCron: Searching for tasks to do
[information] TasksCron: Task10 started - setting filesystem quota
[information] Running Let's Encrypt cronjob prior to regenerating webserver config files
[information] Requesting/renewing Let's Encrypt certificates
[information] No new certificates or certificates due for renewal found
[information] apache::createIpPort: creating ip/port settings for  195.201.85.19:80
[debug] 195.201.85.19:80 :: inserted vhostcontainer
[information] apache::createIpPort: creating ip/port settings for  195.201.85.19:443
[debug] 195.201.85.19:443 :: inserted vhostcontainer
[information] apache::createIpPort: creating ip/port settings for  [2a01:4f8:13b:3c82::2]:80
[debug] [2a01:4f8:13b:3c82::2]:80 :: inserted vhostcontainer
[information] apache::createIpPort: creating ip/port settings for  [2a01:4f8:13b:3c82::2]:443
[debug] [2a01:4f8:13b:3c82::2]:443 :: inserted vhostcontainer
[information] apache::createVirtualHosts: creating vhost container for domain 18, customer a
[information] apache::createVirtualHosts: creating vhost container for domain 47, customer b
[information] apache::createVirtualHosts: creating vhost container for domain 23, customer c

[...]

[information] apache::writeConfigs: rebuilding /etc/apache2/sites-enabled/
[information] apache::writeConfigs: rebuilding /etc/apache2/htpasswd/
[information] apache::writeConfigs: rebuilding /etc/apache2/sites-enabled/
[information] Froxlor\Cron\Http\ApacheFcgi::reload: running service php7.3-fpm restart
[information] Froxlor\Cron\Http\ApacheFcgi::reload: reloading Froxlor\Cron\Http\ApacheFcgi
[notice] Creating passwd file
[notice] Writing 50 entries to passwd file
[notice] Succesfully wrote passwd file
[notice] Creating group file
[notice] Writing 44 entries to group file
[notice] Succesfully wrote group file
[notice] Creating shadow file
[notice] Writing 50 entries to shadow file
[notice] Succesfully wrote shadow file
[notice] Checking system's last guid`

Looks good to me. Regular websites without special VHost settings still work fine.

**Comment by d00p** [comment]
Well possibly its your SSL vhosts and you are Missing the new checkbox to include specialsettings also in ssl-vhosts (because there is a specific ssl-specialsettings Option now)

**Comment by schmatzler** [comment]
You are right and I totally missed that.

Everything works as intended now :) Thanks!
