### ISSUE TITLE
libnss-extrausers user not created when customer has no ftp resources 

### ISSUE THREAD

**Issue by mortzel** [Froxlor/Froxlor#741]
# Summary
When running php-fpm with libnss-extrausers and creating a customer with 0 ftp account froxlor doesn't create a user and group in the extrausers files and so php-fpm crashes when a domain is created for this cusomter since there is no linux user for the domain.

This is caused because the users in the extrausers file are created from the default ftp user of the customer.

# System information
Froxlor version: 0.10.3
Web server: nginx & php-fpm
DNS server: PowerDNS (standalone)
POP/IMAP server: Dovecot
SMTP server: postfix
FTP server: proftpd
OS/Version: Debian 10

# Steps to reproduce
1. Create a Customer with 0 allowed ftp accounts
2. Add a domain to this user

**Comment by d00p** [comment]
When adding a new customer (even with 0 ftp users) there is always a default ftp user created (with the exact loginname as given for creation). Did you by any chance delete the default ftp user additionally?

**Comment by d00p** [comment]
Can you verify that the default ftp user for that customer exists? Also it would be necessary to know whether you've added the customer via interface or via API externally

**Comment by mortzel** [comment]
When i checked the default user didn't existed and i created it. The customer was created via the interface by a reseller.

The problem occurs when all tfp accounts of the reseller are used. When creating a new customer from the reseller account there is a error message "No more resources available",  but the customer is created anyway with no default ftp account.

**Comment by d00p** [comment]
> The problem occurs when all tfp accounts of the reseller are used. When creating a new customer from the reseller account there is a error message "No more resources available", but the customer is created anyway with no default ftp account.

that was the key, thanks :)
