### ISSUE TITLE
php warning on editing customer or hosting plan

### ISSUE THREAD

**Issue by TimoStramann** [Froxlor/Froxlor#742]
# System information
* Froxlor version: 10.3.0
* Web server: apache2
* OS/Version: RedHat7

# Steps to reproduce

1. Create a hosting-plan and save
2. Go to hosting plan overview
3. Click edit hosting-plan and wait

# Log files/log entries
PHP Warning:
<pre>
PHP warning/error
#8 Undefined index: api_allowed
 
lib/formfields/admin/customer/formfield.customer_edit.php:89
</pre>

**Comment by d00p** [comment]
it's just a notice that does not impair functionality. Thanks for pointing that out
