### ISSUE TITLE
Wrong fastcgi_split_path_info with Nginx+PHP fpm

### ISSUE THREAD

**Issue by kionez** [Froxlor/Froxlor#744]
With Nginx+PHP fpm the fastcgi_split_path_info parameter is generated wrong:
`                fastcgi_split_path_info ^(.+\.php)(/.+)\$;`
instead of:
`                fastcgi_split_path_info ^(.+\.php)(/.+)$;`

(i.e.: https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/ )

I've created a PR: #743

**Comment by d00p** [comment]
Any particular reason for `.+` to stay at the end instead of `.*` as shown on https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/ ?

**Comment by kionez** [comment]
The `.+` matches at least one character, so maybe `.*` is better, I've updated the PR with the same code shown in official docs
