### ISSUE TITLE
Error with Certificates.add / escape-sequences like \n via API

### ISSUE THREAD

**Issue by bady85** [Froxlor/Froxlor#746]
Hello,

when I want to add a SSL Certificate via API I get the Message "Der angegebene Zertifikatsinhalt scheint kein gültiges Zertifikat zu sein.". 

The sented string is ok, but on Froxlor a "rn" will be added after the start and before the end certificate.

I think it could be due to the json_decode(stripslashes($request), true); in the api.php (which convert the line break after ---Begin Certificate---)), 
When I remove the stripslashes for testing there, the certificate is created without any problems and the superfluous rn are no longer present.

Does the certificate need to be edited before sending it to the API?

Thanks

**Comment by d00p** [comment]
Need to run a few checks. No the certificate should not be "edited" in anyway. See corresponding Unit tests. API is fine. Possibly the api.php interface. Can you show me the exact request you've sent to api.php?

**Comment by d00p** [comment]
Can you verify that the following changes to `api.php` are working in your case?

```diff
diff --git a/api.php b/api.php
index 5e98ad02..02ddc2c5 100644
--- a/api.php
+++ b/api.php
@@ -23,7 +23,7 @@ if (empty($request)) {
 }
 
 // decode json request
-$decoded_request = json_decode(stripslashes($request), true);
+$decoded_request = json_decode($request, true);
 
 // is it valid?
 if (is_null($decoded_request)) {
@@ -32,6 +32,7 @@ if (is_null($decoded_request)) {
 
 // validate content
 try {
+       $decoded_request = stripcslashes_deep($decoded_request);
        $request = \Froxlor\Api\FroxlorRPC::validateRequest($decoded_request);
        // now actually do it
        $cls = "\\Froxlor\\Api\\Commands\\" . $request['command']['class'];
@@ -72,3 +73,8 @@ function json_response($status, $status_message = '', $data = null)
        echo $json_response;
        exit();
 }
+
+function stripcslashes_deep($value)
+{
+       return is_array($value) ? array_map('stripcslashes_deep', $value) : stripcslashes($value);
+}
```

**Comment by bady85** [comment]
Hello,

now it seems to be working, thank you!
