### ISSUE TITLE
Regression in 0.10.4

### ISSUE THREAD

**Issue by Guite** [Froxlor/Froxlor#747]
After upgrading from 0.10.3 to 0.10.4 the following warning is reported by the cronjob:

```
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /.../lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php on line 98
PHP Stack trace:
PHP   1. {main}() /.../scripts/froxlor_master_cronjob.php:0
PHP   2. Froxlor\Cron\MasterCron::run() /.../scripts/froxlor_master_cronjob.php:20
PHP   3. Froxlor\Cron\Http\LetsEncrypt\AcmeSh::run() /.../lib/Froxlor/Cron/MasterCron.php:111
PHP   4. Froxlor\Cron\Http\LetsEncrypt\AcmeSh::needRenew() /.../lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php:113
PHP   5. count() /.../lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php:98
```

Corresponding line of code: https://github.com/Froxlor/Froxlor/blob/0.10.4/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php#L98

Seems to be introduced 15 hours ago by aa85c648a3b039e360541d7280f8d7bbebce824c

**Comment by hknet** [comment]
to compensate for both or either variable being not-countable I put this quick and dirty in to force those variables being an array added lines in /lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php

...
$customer_ssl = $certificates_stmt->fetchAll(\PDO::FETCH_ASSOC);
+                if (!is_array($customer_ssl)) {
+                        $customer_ssl = array();
+               }

...
                        $froxlor_ssl = Database::pexecute_first($froxlor_ssl_settings_stmt);
                }
+                if (!is_array($froxlor_ssl)) {
+                        $froxlor_ssl = array();
+                }

this is a quick workaround and I'm not aware of sideeffects, but this is no guarantee either.

please take this as proposed fix therefore

**Comment by Guite** [comment]
Next one:
```
PHP Warning:  Invalid argument supplied for foreach() in /.../lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php on line 241
PHP Stack trace:
PHP   1. {main}() /.../scripts/froxlor_master_cronjob.php:0
PHP   2. Froxlor\Cron\MasterCron::run() /.../scripts/froxlor_master_cronjob.php:20
PHP   3. Froxlor\Cron\System\TasksCron::run() /.../lib/Froxlor/Cron/MasterCron.php:111
PHP   4. Froxlor\Cron\System\TasksCron::rebuildWebserverConfigs() /.../lib/Froxlor/Cron/System/TasksCron.php:52
PHP   5. Froxlor\Cron\Http\ApacheFcgi->init() /.../lib/Froxlor/Cron/System/TasksCron.php:148
PHP   6. Froxlor\Cron\Http\LetsEncrypt\AcmeSh::run() /.../lib/Froxlor/Cron/Http/HttpConfigBase.php:37
```

Corresponding line of code: https://github.com/Froxlor/Froxlor/blob/0.10.4/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php#L241

**Comment by d00p** [comment]
Yikes, that went through for me, maybe I was just lucky, I'll fix that up and get you guys 0.10.5

**Comment by d00p** [comment]
I can't seem to be able to reproduce that, might be due to my data currently, could you verify whether the following changes fix the issues?

```diff
diff --git a/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php b/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php
index 34cb19e0..6456bfd4 100644
--- a/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php
+++ b/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php
@@ -84,6 +84,9 @@ class AcmeSh extends \Froxlor\Cron\FroxlorCron
                                )
                ");
                $customer_ssl = $certificates_stmt->fetchAll(\PDO::FETCH_ASSOC);
+               if (!$customer_ssl) {
+                       $customer_ssl = array();
+               }
 
                $froxlor_ssl = array();
                if (Settings::Get('system.le_froxlor_enabled') == '1') {
@@ -93,6 +96,9 @@ class AcmeSh extends \Froxlor\Cron\FroxlorCron
                                (`expirationdate` < DATE_ADD(NOW(), INTERVAL 30 DAY) OR `expirationdate` IS NULL)
                        ");
                        $froxlor_ssl = Database::pexecute_first($froxlor_ssl_settings_stmt);
+                       if (!$froxlor_ssl) {
+                               $froxlor_ssl = array();
+                       }
                }
 
                if (count($customer_ssl) > 0 || count($froxlor_ssl) > 0) {
@@ -181,7 +187,7 @@ class AcmeSh extends \Froxlor\Cron\FroxlorCron
                        $froxlor_ssl = $needRenew['froxlor_ssl'];
 
                        $cert_mode = 'issue';
-                       if ($froxlor_ssl) {
+                       if (count($froxlor_ssl) > 0) {
                                $cert_mode = 'renew';
                                $certrow['id'] = $froxlor_ssl['id'];
                                $certrow['expirationdate'] = $froxlor_ssl['expirationdate'];
```

**Comment by Guite** [comment]
Looks good. The admin panel says there are no pending tasks anymore though. Can I somehow enforce it to run through all task types explicitly in order to verify it works properly?

**Comment by d00p** [comment]
`php /var/www/froxlor/scripts/froxlor_master_cronjob.php --force --debug`

If there are no tasks / no renews it's a good test too :) Else, what I just did, removed a certificate to generate a new one. So looks like this is set :)

**Comment by Guite** [comment]
> So looks like this is set :)

Yep.
