### ISSUE TITLE
ProFTP: Uploading files larger than 12kb fail

### ISSUE THREAD

**Issue by Af0x** [Froxlor/Froxlor#748]
Hello,

I have upgraded from Debian Stretch to Buster and since then there seems to be an issue with ProFTP as I can´t upload any files larger than 12kb. Above this value it fails close to the end.

Can anyone confirm this as well?

I set the DebugLevel of ProFTp to 10 but there seems to be no error.

Further I tried a different FTP-client (Filezilla in binary mode) and compared the original file with the transferred file. It turns out that the transferred file was saved with UNIX line endings (LF) and the original was DOS/-Windows (CR-LF).

So now I search for an idea what to investigate next or an idea if the problem is on the side of the client or the server.

Regards,

Af0x

**Comment by d00p** [comment]
Support questions please in the forum, clearly not a froxlor issue

**Comment by Af0x** [comment]
sorry, copy pasted to forum. This issue can be deleted (if possible).
