### ISSUE TITLE
MySQL Count is not adjusted after Mysqls.delete

### ISSUE THREAD

**Issue by bady85** [Froxlor/Froxlor#749]
When I delete a database with the API command Mysqls.delete, the database is deleted, but I get the message 

>  [406] Requested parameter "loginname" is empty where it should not be for "Customers:get" 

 and the customer's MySQL count is not updated. Example: The customer is allowed to have 1 database, deletes it, Froxlor will still display that he has 1 of 1 database in use, but under Databases no database will be displayed and the customer cannot create another database, because his limit is used up.

**Comment by bady85** [comment]
I get the same Message when I use the Mysqls.update command to update a mysql.

**Comment by d00p** [comment]
Do you call that as admin/reseller? or as user?

**Comment by bady85** [comment]
I call it as admin

**Comment by d00p** [comment]
Just for clarification: when used as admin/reseller, the `customerid` or `loginname` **must be** given in order to a) check whether the customer belongs to the admin/reseller and b) admin/resellers cannot have myqsl-resources so it must be explicitly for a customer
