### ISSUE TITLE
(My)SQL Users got deleted after IP change

### ISSUE THREAD

**Issue by snoopotic** [Froxlor/Froxlor#751]
#Summary

I recently changed my Froxlor host's main IPv4 address.
Within this change I recognized all mysql-db users created by froxlor got deleted. oO
Luckily NOT the databases just the users got deleted.
Also: not the froxlor user (but this is also a not froxlor-created one)
Luckily I just had 6 of them and could recreate them by my apps setting (took a while to look them up). But if this is a regression maybe this could be harmful to bigger set ups.

I remember, all the db users had granted HOST permission entries for localhost as well as the host's IPv4 I recently deleted.

In my change I guess there are 2 possible causes:
1) Deleting IP-adresses in admin_ipsandports.php?page=ipsandports. After unchecking all Domains' usage of the IP I could delete the IP in that admin panel. If there is a query also deleting database users using that IP maybe you will find the issue there.

2) But I guess the issue is here:  admin_settings.php?page=overview&part=system. After deleting the IP I had to change the Systems IP-address to the new one and choose new defaults. But hitting the SAVE button errors me that "MySQL-Access-Hosts" can't be empty. SO possibly before 0.10.x this setting wasn't set? So I set it up to "localhost" and saved successfully. Maybe there is a query deleting all users somehow by making a change here?

After that everything looked good in first view but in second all applications that use Mariadb/mysql had connection problems and I found out all users were deleted. eek. 

I will try to reproduce it in a playground setup but you should consider looking at it.

# System information
* Froxlor version: 0.10.5 (DB: 201910200)
* Web server: apache2 (Debian Buster)
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian Buster
* DB Version: MariaDB Ver 15.1 Distrib 10.3.17-MariaDB

# Steps to reproduce

1. install froxlor 0.9x set use ipv4
2. create database user
3. upgrade to froxlor 0.10.5
4. set up new ip v4
5. delete old ip
6. go to admin_settings.php?page=overview&part=system and reconfigure new default IP
7. also set (empty) MySQL-Access-Hosts to localhost
8. see mysql users got deleted!? (unconfirmed yet)

# Expected behavior

MySQL Users are kept and maybe just the new entry of MySQL-Access-Hosts is granted.

# Actual behavior

MySQL Users got deleted from database.

# Log files/log entries

sadly nothing but ad some point of time I got a lot of
"[Warning] Access denied for user 'dbuser6'@'localhost' (using password: YES)" in my mysql.error log.

**Comment by d00p** [comment]
Main question: HOW did you change the IP?
You know, there is a script for that: `install/scripts/switch-server-ip.php` which takes care of everything. If you manually deleted entries from the database - cant help it

**Comment by d00p** [comment]
> also set (empty) MySQL-Access-Hosts to localhost

empty? Unlikely...the code forces `127.0.0.1` and `localhost` to be in the list at least, see https://github.com/Froxlor/Froxlor/blob/master/lib/Froxlor/Settings/Store.php#L282

**Comment by d00p** [comment]
>  If there is a query also deleting database users using that IP maybe you will find the issue there.

there is not, see https://github.com/Froxlor/Froxlor/blob/master/lib/Froxlor/Api/Commands/IpsAndPorts.php#L533

**Comment by d00p** [comment]
> After deleting the IP I had to change the Systems IP-address to the new one and choose new defaults. 

Also very unlikely, system does not allow you to delete the main-system ip

**Comment by d00p** [comment]
> see mysql users got deleted!? (unconfirmed yet)

well simply check with `SELECT * FROM mysql.user`

**Comment by snoopotic** [comment]
> Main question: HOW did you change the IP?

Mainly by walking through the froxlor-settings - adding the new IP in "IPs and Ports" and then after unchecking the old IP from all froxlor Domains - I was able to delete the v4-IP
As I also have IPv6 in use and these v6 IPs did not change. This saved my access to froxlor I guess :P

> You know, there is a script for that: `install/scripts/switch-server-ip.php` which takes care of everything. If you manually deleted entries from the database - cant help it

No! didn't. Now it's too late :D But very nice there is one! :)

> > also set (empty) MySQL-Access-Hosts to localhost
> 
> empty? Unlikely...the code forces `127.0.0.1` and `localhost` to be in the list at least, see https://github.com/Froxlor/Froxlor/blob/master/lib/Froxlor/Settings/Store.php#L282

That's why I used brackets - I am unsure what was before there but In first place I only changed IP-Adress, Standard-IP/Port and Standard-SSL-IP/port and got this "Ungültige MySQL-Host-Adresse: "" " that is caused by empty "MySQL-Access-Hosts" setting. Thus I set it.

I never touched these  system settings after my upgrades from 0.9.x so maybe there is no check in upgrade procedures and possibly could have been empty?

> > After deleting the IP I had to change the Systems IP-address to the new one and choose new defaults.
> 
> Also very unlikely, system does not allow you to delete the main-system ip

Hmm. But I was able to do so? Maybe it was possible as I am accessing Froxlor from IPv6... Also the old IP on my Host was a NAT-IP now I have a native IPv4. So this old IP was just known from the Host...

Hmm ok. Well, I already solved my problems now. (so far)
Thank you for your replies. Maybe I can reproduce it if I find time.

**Comment by d00p** [comment]
> Mainly by walking through the froxlor-settings - adding the new IP in "IPs and Ports" and then after unchecking the old IP from all froxlor Domains - I was able to delete the v4-IP

So, it wasnt your default system-ip? Which can only be ONE? Because that would not be able to be deleted through the UI

> I never touched these system settings after my upgrades from 0.9.x so maybe there is no check in upgrade procedures and possibly could have been empty?

There were no changes to this field / setting in the upgrade from 0.9.x to 0.10.x

> Hmm. But I was able to do so? 

No idea, best to be sure: check your setting (settings -> system-settings)
```
IP-address
What's the main IP-address of this server?
```

> Maybe it was possible as I am accessing Froxlor from IPv6... Also the old IP on my Host was a NAT-IP now I have a native IPv4. So this old IP was just known from the Host...

doesnt matter what kind of IP...it's about whether it's set as "main ip" so which IP can be deleted through ip's and ports

> Maybe I can reproduce it if I find time.

I hope we can find out with enough info about your settings before/after the upgrade

**Comment by snoopotic** [comment]
> > Mainly by walking through the froxlor-settings - adding the new IP in "IPs and Ports" and then after unchecking the old IP from all froxlor Domains - I was able to delete the v4-IP
> 
> So, it wasnt your default system-ip? Which can only be ONE? Because that would not be able to be deleted through the UI

Ah! Well, I remember... I went to this System Settings after recognizing froxlor was not working... I helped myself by editing the 10_froxlor_ipandport_... entry for that old-ip (I run froxlor behind a certain port - not 443)... then I had 5 minutes to set the new main ip in froxlor system settings.
After that I unchecked the old IP on few Domains I missed. Then I could delete the old IP.
Yip... so obviously in my description it's an a different order:
1) change main IP and set MySQL-Access-Hosts
2) then delete old IP

**Comment by snoopotic** [comment]
I guess I produced a scenario that ran this one:

https://github.com/Froxlor/Froxlor/blob/c2a98806167d2cc98774585230e2ec150888e72e/lib/Froxlor/Database/DbManager.php#L187

**Comment by d00p** [comment]
`\Froxlor\DatabaseDbManager::correctMysqlUsers()` is called when updating the default-ip or when updating the mysql-access-hosts settings. I really cannot think of a scenario where you did manage to empty that fields and it additionally can somehow bypass all checks and call `correctMysqlUsers()`.

Please, as said earlier, provide an example if existing users from the `mysql.user` table, there should be at least `user@localhost` and `user@127.0.0.1` for the froxlor customer's databases

**Comment by wittich** [comment]
Somehow I managed to produce the same bug, all froxlor DB users are gone:

```
select Host, User from mysql.user;

+--------------+------------------+
| Host         | User             |
+--------------+------------------+
| 127.0.0.1    | root             |
| localhost    | debian-sys-maint |
| localhost    | phpmyadmin       |
| localhost    | root             |
| localhost    | roundcube        |
+--------------+------------------+
```
I manually added the Froxlor user again to regain access to the Froxlor Backend:

```
CREATE USER 'froxlor'@'localhost' IDENTIFIED BY '*******************';
GRANT ALL PRIVILEGES ON froxlor.* TO 'froxlor'@'localhost';
```

All other users a still gone, luckily it was on a testing server. I remeber the last acation I did I changed the field MySQL-Access-Hosts (`mysql_access_host`). I checked later in the DB and the field value was set to empty "".

I change some other settings before, so I'm not sure what triggers that behavior. I'll try if I can reproduce it...

**Comment by d00p** [comment]
Okay i'll check whether I can add a unit test for that to verify the false behaviour

**Comment by d00p** [comment]
So with just changing the settings I cannot reproduce to end up with an empty value (because the interface does not allow empty values and even IF it would, `\Froxlor\Settings\Store::storeSettingMysqlAccessHost()` would ensure that in any case, `127.0.0.1` and `localhost` are being added to the list of hosts.

Additionally, this would never explain why your `froxlor` database user has been deleted too, as froxlor only adjusts the database-user privileges and hosts of the *customer* databases/users, not its own.

**Comment by wittich** [comment]
I found in the mysqllog just before the dropping of users started, following update command:

```
UPDATE `panel_settings` SET `value` = '172.31.xxx.xxx'
                                WHERE `settinggroup` = 'system' AND `varname` = 'ipaddress'
-- and then it starts...
DROP USER 'froxlor'@'127.0.0.1'
DROP USER 'froxlor'@'localhost'
--...
```
Still, couldn't reproduce the whole behavior...

**Comment by d00p** [comment]
Okay, good hint, I'll dig into that, thanks

**Comment by d00p** [comment]
Dirty little thing, looks like never really changed the `system.ipaddress` in production (why would they though). Totally missed that. Thanks for digging into that so deep, sure helped a lot!

**Comment by snoopotic** [comment]
Thank you guys.
Love that. :)
