### ISSUE TITLE
froxlor.panel_customers: Warning  : Row size too large (> 8126)

### ISSUE THREAD

**Issue by dphi** [Froxlor/Froxlor#752]
# Summary
mysqlcheck warns about the row size of the panel_customer table of Froxlor.

# System information
* Froxlor version: 0.10.5
* MariaDB: 10.3.17-0+deb10u1
* OS/Version: Debian 10.1

# Steps to reproduce
check logfiles/ mysqlcheck

# Log files/log entries
mysql.error (sporadic)
<pre>
[Warning] InnoDB: Cannot add field `customernumber` in table `froxlor`.`panel_customers` because after adding it, the row size is 8619 which is greater than maximum allowed size (8126) for a record on index leaf page.
</pre>

$ mysqlcheck -D froxlor --silent (sporadic)
<pre>
froxlor.panel_customers
Warning  : Row size too large (> 8126). Changing some columns to TEXT or BLOB or using ROW_FORMAT=DYNAMIC or ROW_FORMAT=COMPRESSED may help. In current row format, BLOB prefix of 768 bytes is stored inline.
</pre>

**Comment by d00p** [comment]
confirmed, that seems to be happening on the latest debian mariadb, just checked, before update mysqlcheck  said `OK` for all tables. Then ran `mysql_upgrade` and after that, mysqlcheck complains.
