### ISSUE TITLE
[Bug] Message when adding an entry to MySQL-Access-Hosts: SQLSTATE[42000]: Syntax error or access violation

### ISSUE THREAD

**Issue by clarkx86** [Froxlor/Froxlor#758]
# Summary
I just encountered the following scenario when adding a new entry to my MySQL-Access-Hosts under _Settings > System settings > MySQL-Access-Hosts_:

# System information
* PHP version: 7.2.19-0ubuntu0.18.04.2 (FPM-FCGI)
* MySQL version: 5.7.27-0ubuntu0.18.04.1
* Web server: apache2
* FTP server: proftpd
* OS/Version: Ubuntu 18.04

# Steps to reproduce
1. Goto _Settings > System settings > MySQL-Access-Hosts_
2. Add a new entry (seperated by a comma, no whitespace)
3. Click on "Save"
4. Error message pops up (see attached image below)

# Expected behavior
1. Settings should apply normally, new privileges should be granted to existing databases

# Actual behavior
1. User encounters the following error screen:
![grafik](https://user-images.githubusercontent.com/46745823/69000638-14e69980-08d3-11ea-91b5-2d4806a116fe.png)
2. When refreshing the page, the entry **is** still in the text box, when clicking on "Save" a second time, the new settings get applied successfully
3. Databases prior to this change are not affected by the new entry in the MySQL-Access-Hosts

Something I observed after looking at the Froxlor system log is that even after clicking "Save" the second time (so the settings get applied without an error screen), the database privileges won't get granted for existing databases. Only new databases created _after_ applying the new MySQL-Access-Hosts entry are affected by this change. Existing databases stay untouched no matter what.

**Comment by d00p** [comment]
Could you please enable debugging in `lib/userdata.inc.php` so we can get a trace, just add/set:
```php
$sql['debug'] = true;
```
and try to reproduce the issue?

**Comment by clarkx86** [comment]
I reproduced the issue with `$sql['debug'] = true;` and it produced the following result:
```
Dear froxlor-team,

the following error has been reported by a user:

-------------------------------------------------------------
42000 SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL' at line 1

File: lib/Froxlor/Database/Database.php:83

Trace:
#0 lib/Froxlor/Database/Database.php(83): PDOStatement->execute(Array)
#1 lib/Froxlor/Database/Manager/DbManagerMySQL.php(106): Froxlor\Database\Database::pexecute(Object(PDOStatement), Array)
#2 lib/Froxlor/Database/DbManager.php(181): Froxlor\Database\Manager\DbManagerMySQL->grantPrivilegesTo('froxlor', NULL, ' < MY EXTERNAL IP-ADDRESS HERE > ', true)
#3 lib/Froxlor/Settings/Store.php(276): Froxlor\Database\DbManager::correctMysqlUsers(Array)
#4 [internal function]: Froxlor\Settings\Store::storeSettingMysqlAccessHost('system_mysql_ac...', Array, '127.0.0.1,local...')
#5 lib/Froxlor/UI/Form.php(324): call_user_func(Array, 'system_mysql_ac...', Array, '127.0.0.1,local...')
#6 lib/Froxlor/UI/Form.php(284): Froxlor\UI\Form::saveFormField('system_mysql_ac...', Array, '127.0.0.1,local...')
#7 admin_settings.php(67): Froxlor\UI\Form::processFormEx(Array, Array, Array, 'system', false, true, false)
#8 {main}


					GRANT ALL PRIVILEGES ON `froxlor`.* TO :username@:host IDENTIFIED BY :password
-------------------------------------------------------------

Froxlor-version: 0.10.2
DB-version: 201910120

End of report			
```

**Comment by d00p** [comment]
Can you check whether there is a password set for the user `froxlor` as it seems `NULL` is being passed to the `grantPrivilegesTo()` function:

```sql
SELECT * FROM mysql.user WHERE `User` = 'froxlor';
```

There should be no row in that resultset where `Password` is empty. Can you confirm that?

**Comment by clarkx86** [comment]
Strangely enough, I don't have a `Password` column, there's just:
`password_expired`, `password_last_changed` and `password_lifetime`

But there _is_ a `authentication_string` column? None of the rows in the `authentication_string`-colum are empty or `NULL` however.

**Comment by d00p** [comment]
Thank you for the information so far, I'll run a few tests and see what' up there :)

**Comment by clarkx86** [comment]
No problem! If you need any more information/ logs, let me know :).

**Comment by d00p** [comment]
Okay, so far, it seems that MySQL-5.7 and MySQL-8 have that issue, see https://travis-ci.com/Froxlor/Froxlor/builds/136873933

**Comment by d00p** [comment]
So, okay, we got the `authentication_string` now instead of `Password` - question is, does froxlor do the right thing for adding the new user using that hashed password (works with `Password`).

Easiest way would be to implement the change https://github.com/Froxlor/Froxlor/commit/e6dad6c6d0a78ca198e80f730f986ff917457a75 and do a `SELECT` in `mysql.user` again and check whether the `authentication_string` is equal for one User and all the given Hosts - could you test that? I currently destroyed my dev box while trying to install mysql-8 over mariadb-10 xD

**Comment by clarkx86** [comment]
Of course :), no problem!

I just implemented the changes and I can confirm that it indeed works now without throwing an exception (settings seem to get applied normally), _but_ the `authentication_string` for the new host _does_ differ from the `localhost` and and the IP-address of the hostmachine.

**Comment by d00p** [comment]
darn - thought so but hoped for better :) Can you tell whether the `authentication_string` indeed is the users password hashed?

**Comment by clarkx86** [comment]
I hashed the password for the unprivileged `froxlor` user with `SELECT PASSWORD(' <password> ');` and it matches the password with the `localhost` and it's IP-address (which makes sense, I guess ;D), but I don't where the `authentication_string` hash for the external host comes from...

**Comment by d00p** [comment]
And the external Host is the ip you've added to the mysql-access-hosts array?

**Comment by clarkx86** [comment]
Yes, that is the correct IP-address which I've appended to the list :).

**Comment by d00p** [comment]
Just to be sure, if you set the `authentication_string` for user@new-ip-address to the same value as e.g. user@localhost - does a connection work then?

**Comment by d00p** [comment]
Okay, that was a nice step forward, now mysql-5.6 does not like that anymore but we'll get that next

**Comment by clarkx86** [comment]
> 
> 
> Just to be sure, if you set the `authentication_string` for user@new-ip-address to the same value as e.g. user@localhost - does a connection work then?

I will be able to test this later this evening, due to me being @ university right now. I will share the results later with you :)!

**Comment by clarkx86** [comment]
Hey! Sorry for the delay.
I updated the `authentication_string` with
```mysql
UPDATE mysql.user SET authentication_string=password(' < password > ') WHERE Host=' < remote host > ';
```
to match the other `authentication_string`-hashes (and double checked to verify that it is indeed the same), but I still can't seem to establish a connection from the remote host. (`bind-address = 0.0.0.0` in `/etc/mysql/mysql.conf.d/mysqld.cnf`, MySQL service restarted):
```
Access denied for user '< user >'@'< froxlor host >' (using password: YES)
```

This might be a problem with my configuration however, I will troubleshoot further and edit this reply if the issue had something to do with my config.

**Comment by d00p** [comment]
Okay, so we got that going :P Very nice. Now i just have to figure out why mysql-5.6 does not like that anymore :p

**Comment by d00p** [comment]
Should be fixed
