### ISSUE TITLE
SQL error when searching for certificates by domainname

### ISSUE THREAD

**Issue by crazy4chrissi** [Froxlor/Froxlor#764]
# Bug Report

# Summary
When searching for SSL certificates by domainname as admin, I get an SQL error.

# System information
* Froxlor version: 0.10.8-1 (DB: 201911220)
* Web server: apache2
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian Stretch

# Steps to reproduce

1. Log in as Admin
2. Click "SSl certificates"
3. Enter something into the searchbox, e.g. "foo"
4. Click "Go"

Reproduced on two servers running Froxlor.

# Expected behavior

1. See a list of ssl certificates for domains containing "foo"

# Actual behavior

1. Following SQL error:

    SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE `d`.`domain` LIKE '%foo%' ORDER BY CONCAT( IF( ASCII( LEFT( `d`.`domain`, ' at line 5

**Comment by d00p** [comment]
Fixed in https://github.com/Froxlor/Froxlor/commit/c2b88200f0d9a18d50533770cd030e34da7c6b82
