### ISSUE TITLE
List of domains / certificates ordered in a strange way

### ISSUE THREAD

**Issue by crazy4chrissi** [Froxlor/Froxlor#765]
# Bug report

# Summary

As admin, I can order the list of domains or certificates by domain name in ascending or descending order. The result seems to be ordered alphabetically by the first character, but the second characters are not ordered alphabetically.

# System information
* Froxlor version: 0.10.8-1 (DB: 201911220)
* Web server: apache2
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian Stretch

# Steps to reproduce

1. Log in as Admin
2. Click on "Domains" or "Certificates"

# Expected behavior

1. The list of domains should be ordered alphabetically

# Actual behavior

1. The list of domains seems to be ordered alphabetically based on the first character only

Example:
![grafik](https://user-images.githubusercontent.com/6806325/70041779-0b8d4a80-15be-11ea-974e-39f8ae29abfd.png)

**Comment by d00p** [comment]
Can you check whether this is only the case is `natural sorting` is activated in the settings?

**Comment by crazy4chrissi** [comment]
> 
> 
> Can you check whether this is only the case is `natural sorting` is activated in the settings?

Yes. I deactivated "natural sorting" and now the domains are sorted as expected.

**Comment by d00p** [comment]
Okay, the `natural sorting` is only for usernames etc. the following patch should fix that:

```diff
diff --git a/lib/Froxlor/Api/ApiCommand.php b/lib/Froxlor/Api/ApiCommand.php
index 1f67a7a4..9b7dcc6e 100644
--- a/lib/Froxlor/Api/ApiCommand.php
+++ b/lib/Froxlor/Api/ApiCommand.php
@@ -346,6 +346,15 @@ abstract class ApiCommand extends ApiParameter
                        } else {
                                $order .= " ORDER BY ";
                        }
+
+                       $nat_fields = [
+                               '`c`.`loginname`',
+                               '`a`.`loginname`',
+                               '`adminname`',
+                               '`databasename`',
+                               '`username`'
+                       ];
+
                        foreach ($orderby as $field => $by) {
                                $sortfield = explode('.', $field);
                                foreach ($sortfield as $id => $sfield) {
@@ -365,7 +374,7 @@ abstract class ApiCommand extends ApiParameter
                                ])) {
                                        $by = 'ASC';
                                }
-                               if (\Froxlor\Settings::Get('panel.natsorting') == 1) {
+                               if (\Froxlor\Settings::Get('panel.natsorting') == 1 && in_array($field, $nat_fields)) {
                                        // Acts similar to php's natsort(), found in one comment at http://my.opera.com/cpr/blog/show.dml/160556
                                        $order .= "CONCAT( IF( ASCII( LEFT( " . $field . ", 5 ) ) > 57,
                                        LEFT( " . $field . ", 1 ), 0 ),
```

**Comment by crazy4chrissi** [comment]
Hmmm. But still, also for usernames, I would consider this a strange way of sorting and not "natural". On the other hand, "natural sorting" could make sense for domains two, if I have "web1.domain.com" and "web11.domain.com" for example.

**Comment by crazy4chrissi** [comment]
Natural Sorting in MySQL seems not really straight forward. Most proposed solutions I found sort some words in a weird way. See https://stackoverflow.com/questions/153633/natural-sort-in-mysql/12257917

A stored procedure as in https://stackoverflow.com/a/12257917/1433331 seems to be overkill. Maybe drop "natural sorting" altogether?

**Comment by d00p** [comment]
I personally think it still makes sense for usernames, the settings description fits best: 
```
Sorts lists as web1 -> web2 -> web11 instead of web1 -> web11 -> web2
```
But for everything else, not required I guess

**Comment by crazy4chrissi** [comment]
Ok. Actually, I don't care much.
