### ISSUE TITLE
SSL certificates for redirecting subdomains cause "server certificate does NOT include an ID which matches the server name"

### ISSUE THREAD

**Issue by crazy4chrissi** [Froxlor/Froxlor#767]
# Bug report

# Summary

I see lots of these errors in `/etc/apache2/errors.log` :

    AH01909: sub.example.com:443:0 server certificate does NOT include an ID which matches the server name

It seems all these are subdomains that redirect somewhere and do not actually have an SSL certificate configured in Froxlor, only their base domain (`example.com`) has.

# System information
* Froxlor version: 0.10.8-1 (DB: 201911220)
* Web server: apache2
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian Stretch

# Steps to reproduce

1. Create a Domain `example.com` with an SSL certificate configured
2. Create a Subdomain of that domain (`sub.example.com` ) that redirects to some URL. Do not configure an SSL certificate for this subdomain.
3. Let Froxlor generate webserver logs
4. restart apache

# Expected behavior

1. Froxlor does not generate SSL configuration for the subdomain `sub.example.com` 
2. No errors in Apache log.

# Actual behavior

1. Froxlor generates an Apache configuration file for the subdomain `sub.example.com`  that points to an SSL certificate that is the same certificate as for `example.com`. This does not make sense, as this is neither valid nor configured that way. It would only make sense if the certificate of `example.com` was a wildcard certificate.
2. Errors in Apache log:

    `AH01909: sub.example.com:443:0 server certificate does NOT include an ID which matches the server name`

Maybe there should be an extra option for wildcard domains. This should be a property of a certificate. If enabled, Froxlor should use this wildcard certificate for all subdomains.

**Comment by d00p** [comment]
Problem is: how can let's encrypt validate that domain of it redirects so something else?

**Comment by crazy4chrissi** [comment]
I have not enabled letsencrypt for the subdomain that has the redirect configured. I don't want letsencrypt to do anything with it. I have configured letsencrypt for the base domain and that works. But the same certificate gets assigned to the subdomain by froxlor somehow.

**Comment by crazy4chrissi** [comment]
Enabling letsencrypt for domains that redirect is another problem. I noticed that this can be worked around by enabling in Froxlor the "redirect to https"  option.

**Comment by crazy4chrissi** [comment]
> 
> 
> Problem is: how can let's encrypt validate that domain of it redirects so something else?

Regarding this problem: Froxlor has control over the redirect and could redirect everything except `.well-known/acme-challenge`.

**Comment by d00p** [comment]
Hm, yes, the form for adding / editing subdomains needs a `SSL` option, which adds/removes the linking to ssl-enabled IP's from the parentdomain accordingly so customer are able to deactivate SSL for Subdomains even if the main domain has SSL enabled.

I guess the same even applies to main-domains, but we'd need an extra option for admins which allows/forbids this setting for customers to change. As this is quite a massive change, i'd rather not quickly do that for 0.10.9 today but plan that for next weeks release
