### ISSUE TITLE
more ssl settings

### ISSUE THREAD

**Issue by Tealk** [Froxlor/Froxlor#769]
Hello,

it would be great if you had more adjustment possibilities in the ssl settings.
e.g:
```
SSLHonorCipherOrder
SSLSessionTickets
SSLUseStapling
```

**Comment by d00p** [comment]
`SSLUseStapling` ist already possible via setting "OCSP stapling" per domain

**Comment by Tealk** [comment]
Is "SSLStaplingCache" not required in connection with "SSLUseStapling"?

**Comment by d00p** [comment]
So? Froxlor generates the corresponding directive for that

**Comment by Tealk** [comment]
Oh okay, I didn't see that, thanks.

**Comment by d00p** [comment]
refs #767
