### ISSUE TITLE
error after update from 0.9.40 to 0.10.9

### ISSUE THREAD

**Issue by noname-x** [Froxlor/Froxlor#770]
# System information
* Froxlor version: 0.10.9-1 (201911220)
* Web server: nginx
* OS/Version: debian 9 (stretch)

# Steps to reproduce
1. Update from 0.9.40 (working) to 0.10.9 (not working)

# Expected behavior
1. Open/view the Froxlor admin web interface

# Actual behavior
1. blank page

# Log files/log entries
syslog:
<pre>
Stack trace:
#0 /var/www/froxlor/lib/init.php(456): eval()
#1 /var/www/froxlor/index.php(20): require('/var/www/froxlo...')
#2 {main}
  thrown in /var/www/froxlor/lib/init.php(456) : eval()'d code on line 6" while reading response header from upstream, client: ip.ip.ip.ip, server: domain.com, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:8888", host: "domain.com"
2019/12/07 00:12:46 [error] 5928#5928: *10 FastCGI sent in stderr: "PHP Fatal error:  Uncaught Error: Class 'Settings' not found in /var/www/froxlor/lib/init.php(456) : eval()'d code:6
</pre>

**Comment by d00p** [comment]
Custom theme/templates?

**Comment by noname-x** [comment]
> Custom theme/templates?

Yeah, that was my mistake. The hint with my own template brought me to the solution.

I could have thought of it before. ;)

Thank you very much.
