### ISSUE TITLE
[bug] Install Config for CentOS 7 uses wrong paths

### ISSUE THREAD

**Issue by k5sql** [Froxlor/Froxlor#771]
# Bug report

# Summary
Installation/configuration steps assume Debian-like paths for Apache. Some configuration steps reference /etc/apache2{,/sites-enabled} where CentOS uses /etc/httpd and by default does not include the ./sites-{available,enabled} directories.

Installation/configuration steps do not provide any info for DNS on CentOS at all, though Bind9 seems to work just fine if you follow the Ubuntu instructions but substitute or symlink the paths.

# System information
* Froxlor version: 0.10.8
* Web server: apache2
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: CentOS Linux release 7.7.1908 (Core)

# Steps to reproduce

1. Untar the package
2. Begin setup
3. Reach configuration phase

# Expected behavior

1. Correct instructions for CentOS/RHEL/Fedora paths

# Actual behavior

1. Apache paths use Debian-like style
2. Option to configure DNS is absent on CentOS 7

**Comment by starcodekei** [comment]
* As an aside, I have kept back from the 0.10.9 update due to other bugs reported (chiefly the possible MySQL users being deleted issue) to avoid impacting production

**Comment by starcodekei** [comment]
* As an aside, I have intentionally skipped updating as the system was just installed 2 days ago and in the process of going live. Due to bug reports posted here, waiting to see if they will negatively impact production.

**Comment by d00p** [comment]
You are aware that you can/need to adjust the settings (where all of these paths can be changed) prior to configuration? 

Yes there might be some parts missing for CentOS, most likely because almost noone uses froxlor with CentOS and we do not have a maintainer for that

**Comment by k5sql** [comment]
Indeed. The openness of the configuration made this possible in the first place - a factor that is greatly appreciated compared to some of the paid panels that don't like their users editing things...

I wouldn't mind contributing for CentOS where possible.

**Comment by d00p** [comment]
Sounds great. And yes, there are ideas for presetting settings according to the used distribution on installation phase. Just didn't have the time yet

**Comment by d00p** [comment]
Closed in favor of #772

**Comment by d00p** [comment]
yikes, #772 is already closed in favor for this one :P sry

**Comment by d00p** [comment]
So, there's #773 for the dns task, maybe more adjustments of the config-templates, this can be closed
