### ISSUE TITLE
[Feature Request] Add config instructions for DNS on CentOS/RHEL

### ISSUE THREAD

**Issue by k5sql** [Froxlor/Froxlor#773]
# Feature Request

# Summary

* Would be nice to have DNS configuration instructions for CentOS/RHEL systems. 
* Debian/Ubuntu instructions can (mostly) be followed, if the correct paths for CentOS/RHEL are substituted/symlinked

# System information
* Froxlor version: 0.10.8
* Web server: apache2
* DNS server: Bind9
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: CentOS Linux release 7.7.1908 (Core)

# Steps to reproduce

1. Install froxlor
2. Go to configuration->Cent/RHEL 7

# Expected behavior

1. Service config instructions for DNS

# Actual behavior

1. No service for Nameserver listed under Cent/RHEL 7

# Comment
* Intentionally have not updated to 0.10.9 as the system running 0.10.8 is being made production ready and cannot take an update right now (ensuring update will not negatively impact production; no separate test system available - yet)

**Comment by d00p** [comment]
Pull requests are welcomed, I don't know anyone using centos, the config templates for that are all community contributed

**Comment by daxara** [comment]
these are included in https://github.com/Froxlor/Froxlor/pull/842

**Comment by daxara** [comment]
created a pull request just for this one: https://github.com/Froxlor/Froxlor/pull/844

**Comment by d00p** [comment]
merged in https://git.io/JfVFE

**Comment by d00p** [comment]
https://github.com/Froxlor/Froxlor/commit/b23e4a4d852d5fe3342ec8cd2d98e34e1e97a6fe fixes this and more
