### ISSUE TITLE
[Bug] Exception occurs while clicking on traffic details

### ISSUE THREAD

**Issue by FroxlorsMeinerEiner** [Froxlor/Froxlor#774]
# Bug report vs. support request
If you're unsure of whether your problem is a bug or a configuration error
* contact us via IRC in #froxlor on freenode
* or post a thread in our forum at https://forum.froxlor.org

As a rule of thumb: before reporting an issue
* see if it hasn't been [reported](https://github.com/Froxlor/froxlor/issues) (and possibly already been [fixed](https://github.com/Froxlor/froxlor/issues?utf8=✓&q=is:issue%20is:closed)) first
* try with the git master

# Summary

An exception occurs while opening traffic details.

# System information
* Froxlor version: 0.10.9
* Web server: apache2
* DNS server: none
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian Buster, Mysql 8.x

# Steps to reproduce

1. Login to admin panel
2. Click on traffic
3.Click on any detail of a customer

Same happend if you login as customer

# Expected behavior

1. No Exception occurs and details are shown

# Actual behavior

1.QLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DESC, `month` DESC LIMIT 12' at line 4

**Comment by d00p** [comment]
Just followed the steps to reproduce but cannot reproduce the issue in any traffic view

**Comment by d00p** [comment]
I think mysql8 might cause the problem; when i read that correctly ordering with `GROUP BY` has been removed

**Comment by d00p** [comment]
Can you verify that the following patch fixes the issue?

```diff
diff --git a/customer_traffic.php b/customer_traffic.php
index 8989f108..933ffd99 100644
--- a/customer_traffic.php
+++ b/customer_traffic.php
@@ -112,11 +112,14 @@ if (! is_null($month) && ! is_null($year)) {
 
        eval("echo \"" . \Froxlor\UI\Template::getTemplate('traffic/traffic_details') . "\";");
 } else {
-       $result_stmt = Database::prepare("SELECT `month`, `year`, SUM(`http`) AS http, SUM(`ftp_up`) AS ftp_up, SUM(`ftp_down`) AS ftp_down, SUM(`mail`) AS mail
+       $result_stmt = Database::prepare("
+               SELECT `month`, `year`, SUM(`http`) AS http, SUM(`ftp_up`) AS ftp_up, SUM(`ftp_down`) AS ftp_down, SUM(`mail`) AS mail
                FROM `" . TABLE_PANEL_TRAFFIC . "`
                WHERE `customerid` = :customerid
-               GROUP BY `year` DESC, `month` DESC
-               LIMIT 12");
+               GROUP BY `year`, `month`
+               ORDER BY `year` DESC, `month` DESC
+               LIMIT 12
+       ");
        Database::pexecute($result_stmt, array(
                "customerid" => $userinfo['customerid']
        ));
```

**Comment by FroxlorsMeinerEiner** [comment]
Just wait I try it...

**Comment by FroxlorsMeinerEiner** [comment]
Yes it is working :-)
