### ISSUE TITLE
[Feature] Refacoring traffic and diskspace calculation to group stats per period, for example day

### ISSUE THREAD

**Issue by FroxlorsMeinerEiner** [Froxlor/Froxlor#775]
# Bug report vs. support request
If you're unsure of whether your problem is a bug or a configuration error
* contact us via IRC in #froxlor on freenode
* or post a thread in our forum at https://forum.froxlor.org

As a rule of thumb: before reporting an issue
* see if it hasn't been [reported](https://github.com/Froxlor/froxlor/issues) (and possibly already been [fixed](https://github.com/Froxlor/froxlor/issues?utf8=✓&q=is:issue%20is:closed)) first
* try with the git master

# Summary

If changing period to collect traffic and disk usage more than once a day, stats should be merged for example a day, or after a month to avoid huge amounts of usage records.

# System information
* Froxlor version: 0.10.9
* Web server: apache2
* DNS server: none
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian Buster, MySql 8.x

# Steps to reproduce

1. Set Consettings of traffic and disk usage for example to 5 Minutes
2. After a while 12 Months there many records in the tables
3. Open Customers, this will take long time

# Expected behavior

1. If setting cronsettings traffic and diskusage  to smaller values, ui is also fast as collecting much less traffic and disk usage stats
2. Traffic and customer are available within less than 1 second

# Actual behavior

1. Too many records in panel_traffic, panel_traffic_admins, panel_diskspace and disk_space_admins, made UI tab customers and traffic very slow (1-5 minutes)

**Comment by d00p** [comment]
has been refactored for 2.0, not relevant anylonger
