### ISSUE TITLE
sudo apt-get install libnss-mysql nscd does not work on Ubuntu

### ISSUE THREAD

**Issue by udeshjr** [Froxlor/Froxlor#777]
I'm not a pro on linux but I think this need some amendments
What I get. Running Ubuntu 18.04
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libnss-mysql-bg

**Comment by d00p** [comment]
Nowhere in our config-templates is libnss-mysql-bg mentioned for 18.04, you need to use libnss-extrausers; please just follow the corresponding config templates and also please use our forum for support, not the bugtracker

**Comment by d00p** [comment]
These guides will be updated soon as libnss-mysql is not available on modern distros. You should use libnss-extrausers
