### ISSUE TITLE
SSLSessionTickets breaks Debian Jessie Support

### ISSUE THREAD

**Issue by kroimon** [Froxlor/Froxlor#784]
# Summary

[SSLSessionTickets](https://httpd.apache.org/docs/current/mod/mod_ssl.html#sslsessiontickets) is "Available in httpd 2.4.11 and later, if using OpenSSL 0.9.8f or later".
Debian Jessie is using Apache 2.4.10 which does not start when SSLSessionTickets is present in the configuration files.

# System information
* Froxlor version: 37c434d4fcae0ce0f6d73d87e9e040ed18701c27
* Web server: apache2
* OS/Version: Debian 8 Jessie

# Steps to reproduce

1. Update to latest Froxlor master
2. Rebuild config files

# Expected behavior

1. Apache should start

# Actual behavior

1. Apache fails to start with unknown directive in config file

**Comment by d00p** [comment]
Sadly there is no chance to get the apache version (as it depends on the `ServerTokens` setting) so looks like this has to be a new option to disable this completely

**Comment by axelwehner** [comment]
Thanks for the fast solution.
If anyone is wondering which setting in Jessie needs to be disabled, the option can be found at:
_Settings -> SSL settings -> Enable usage of TLS sessiontickets globally_
