### ISSUE TITLE
[Feature request] Ability to add columns in overview

### ISSUE THREAD

**Issue by mr-manuel** [Froxlor/Froxlor#787]
# Feature Request

# Summary

* It would be great, if we manually can add/remove columns in the Customers/Domains overview.

For example:
* Customers overview: add the applyed hosting plan, Email and other fields.
* Domains overview: add the document root, separate logfile enabled, Emaildomain enabled, Only email? enabled and other fields.

# System information
* Froxlor version: 10.10

# Steps to reproduce

1. Open Froxlor and navigate to "Ressources -> Customers" or "Ressources -> Domains"

# Expected behavior

1. Able to add/remove columns in the overview.

# Actual behavior

1. Not able to add/remove columns in the overview.

**Comment by d00p** [comment]
Good idea for 0.11.x (new interface / template engine)

**Comment by HardyKrause** [comment]
I support this idea. Actually it is difficult to find out which domains are email-only-domains.  It would be great, if there could be an icon like Lets Encrypt icon to show, if this is an email-only-Domain.

**Comment by envoyr** [comment]
:v: Hi, I have just implemented this feature in the 0.11-dev branch. Added in https://github.com/Froxlor/Froxlor/commit/a615b04eb4c040b09a3ba91829b42c596e79eb41 ff.
