### ISSUE TITLE
[Feature request] DNS zu IP zeigt auch auf den Server

### ISSUE THREAD

**Issue by drexlma** [Froxlor/Froxlor#788]
Doofe idee... ich hab gerade nen Server mit 270 Domains die in Froxlor drin sind.... diesen muss ich ausmisten. Davon sind ca. 40% eig. nicht mehr auf dem Server. 

Nun wäre es cool zu sehen bei welchen Domains der DNS Eintrag A bzw MX nicht auf den Server zeigt. 

Ich hab hier n kleines hässliches Script
```
$domains =  array(....);
$root_ip = array(....);
foreach($domains as $domain){
	$a_ip = gethostbyname($domain);
	getmxrr($domain,$mxhosts);
	Echo $domain;
	echo ';';
	echo $a_ip;
	echo ';';
	echo implode(',',$mxhosts);
	echo ';';
	$found = false;
	foreach($mxhosts as $mx_host){
	
		$mx_ip = gethostbyname($mx_host);
		echo $mx_ip.',';
		If(in_array($mx_ip,$root_ip) ){
			$found = true;
		}
	}
	echo ';';
	If(in_array($a_ip,$root_ip) ){
		$found = true;
	}
	
	if($found){
		echo 'Ja';
	} else {
		echo 'Nein';
	}
	Echo "\n";

}```

**Comment by d00p** [comment]
`man dig`, `dig -f [file]`

Ich bin der meinung es ist nicht froxlor's aufgabe domainnamen aufzulösen um zu sehen welche noch auf den server zeigen?! Kannst dir ja via API die Domainliste ziehen und an `dig` übergeben und mittels bash oder was auch immer all deine (einmaligen) Prüfungen vornehmen
