### ISSUE TITLE
[Feature request] Domain-Anzahl, E-Mail-Adressen in der Kundenübersicht.

### ISSUE THREAD

**Issue by drexlma** [Froxlor/Froxlor#789]
Domain-Anzahl, E-Mail-Adressen in der Kundenübersicht.
wäre hilfreich um zu wissen wen ich geg. löschen kann. 

Ja ich kann mir da sicher auch n SQL schreiben.

**Comment by drexlma** [comment]
Ach gibts schon unter Ressourcenverbrauch

**Comment by d00p** [comment]
Es gibt doch auch für alles einen `listingCount()` API call - und in der **Kundenübersicht** hast du doch alles auf dem Dashboard
