### ISSUE TITLE
Check creation of CRT before writing private key to system

### ISSUE THREAD

**Issue by Balthyr** [Froxlor/Froxlor#790]
# Steps to reproduce
For example change an existing A record of an domain and generate an ssl certificate for it.

# Expected behavior
Write private key only to file on System if CRT was generated successfully by acme.sh Else do nothing. 

# Actual behavior
Froxlor writes Private Key without checking generation of CRT.

# Log files/log entries
/var/log/apache2/error.log:
<pre>
AH00016: Configuration Failed
</pre>

# Additional information
Our monitoring reported issues that apache is not running and the log entry that we've got is the above one. This error is due to ssl certificate issues. Espacilly with generated Let's Encrypt Certificates because the domain doesn't point to the server itself where froxlor is installed.

Please let us know if you need any further information.

**Comment by d00p** [comment]
But why did you keep the whole issue template content?

**Comment by d00p** [comment]
Are you sure you are using the latest 0.10.11 release? Because there is a validation that should avoid the `AH00016` error because it won't use the invalid certificates

**Comment by Balthyr** [comment]
Thank you for that hint. That helped! Sometimes it helps to check a second time.
