### ISSUE TITLE
froxlor_bind.conf wrong AXFR entries when DNS is offline

### ISSUE THREAD

**Issue by khoschi** [Froxlor/Froxlor#791]
This is a minor issue:
when DNS resolution is not available for the nameserver entries from the panel configurtion for bind, these entries will show up unresolved in the config file, thus bind won't start anymore, as only IP addresses ar permitted in AXFR entries.

For replication testing open the froxlor webpage, navigate to bind config and enter two comma separated hostnames that do not resolve. Have the config files created again via cron and bind will stop working.
This is a rare event - if your DNS is not responding while the config file is recreated bind will be dead as well. Entries in the hosts file will be ignored.

**Comment by d00p** [comment]
In which setting did you enter the hostnames?

**Comment by khoschi** [comment]
System ->  Settings -> Nameserver Settings (bind9) -> Nameservers (two DNS names)
MX empty, AXFR contains 3 IPs of slaves.
If DNS resolves, this results in 5 IP entrys per allow-transfer in the config file. If not, the first two entries are the names, the last three are the IPs.
This makes sense as the nameservers should be in the ACL, but strictly interpreted the names shouldn't show up anyway in allow-transfer.

As said before, this is ONLY an issue when DNS does not resolve while cron rebuilds the configs.

**Comment by d00p** [comment]
So if it's only related to `allow-transfer`, wen can skip the ma entries if not resolved to an IP, right?

**Comment by khoschi** [comment]
Yes. allow-transfer is at the master containing the list of slaves that are allowed to copy the zone. Froxlor does not offer a slave configuration right now (allow-update would be the statement in that case, with a list of master IPs) or dynamic update for ddns (allow-update with a key).
The nameservers should show up in resolv.conf, hosts and within the zones itself as IP and maybe glue records.

**Comment by d00p** [comment]
Can you validate whether the following patch resolves this issue?

```diff
diff --git a/lib/Froxlor/Cron/Dns/Bind.php b/lib/Froxlor/Cron/Dns/Bind.php
index a556eef5..2c2ae9f9 100644
--- a/lib/Froxlor/Cron/Dns/Bind.php
+++ b/lib/Froxlor/Cron/Dns/Bind.php
@@ -112,7 +112,10 @@ class Bind extends DnsBase
                        if (count($this->ns) > 0) {
                                foreach ($this->ns as $ns) {
                                        foreach ($ns["ips"] as $ip) {
-                                               $bindconf_file .= '             ' . $ip . ";\n";
+                                               $ip = \Froxlor\Validate\Validate::validate_ip2($ip, true, 'invalidip', true, true, true);
+                                               if ($ip) {
+                                                       $bindconf_file .= '             ' . $ip . ";\n";
+                                               }
                                        }
                                }
                        }
```

**Comment by khoschi** [comment]
This patch fixes the syntax error issue. If a non-resolving host is configured as nameserver, the cronscript will issue a php dns-does-not-resolve warning and will not enter a hostname where only IPs are allowed.

If names resolve, it will enter v4 and v6 IPs of the nameservers into the allow-transfer, and the hosts specified in AXFR setting.
