### ISSUE TITLE
Acme.sh cronjob removal

### ISSUE THREAD

**Issue by quthla** [Froxlor/Froxlor#792]
I was using acme.sh on my server even before Froxlor started using it but now Froxlor is breaking it by always removing the cronjob

https://github.com/Froxlor/Froxlor/blob/master/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php#L429

This is really bad. Maybe Froxlor should keep its own copy of acme.sh and not mess with the installed one?

**Comment by d00p** [comment]
Need to check whether two installs on the same system are possible. Managing SSL certificates outside of froxlor manually is not intended, but yes, you are right, we should not interfere with existing installations ... let's see if that is possible

**Comment by quthla** [comment]
As an easy fix, you could also just leave the cronjob intact. It doesn't really hurt anyway.

**Comment by d00p** [comment]
Yes, im currently thinking about giving more work to acme.sh itself and use their cronjob etc. but it's not a quick thing as it changes quite a few things

**Comment by d00p** [comment]
> As an easy fix, you could also just leave the cronjob intact. It doesn't really hurt anyway.

Well it does hurt on renewing, like, when acme.sh already renewed and froxlors cronjob runs and says: now let's renew, this certificate is due, then acme.sh will tell froxlor: nope, not due for renew, skip it, and froxlor continues to use the old one

**Comment by quthla** [comment]
There are many ways around this but probably the worst is removing the cronjob.

https://github.com/acmesh-official/acme.sh/blob/master/README.md

```
13. How to stop cert renewal
To stop renewal of a cert, you can execute the following to remove the cert from the renewal list:

acme.sh --remove -d example.com [--ecc]
The cert/key file is not removed from the disk.

You can remove the respective directory (e.g. ~/.acme.sh/example.com) by yourself.
```
You can take care of renewal in froxlor then.

**Comment by d00p** [comment]
Too bad this answer came right after a release. Well then let's do it that way for 0.10.14 ;)

**Comment by quthla** [comment]
You can also just read Le_CertCreateTime from the domain conf, see if that changed and then act accordingly.

Or parse the output of --renew and check if the domain was skipped.

**Comment by d00p** [comment]
Pull requests are welcomed ;)

**Comment by d00p** [comment]
has more impact on the acmesh cronjob file than expected, postponed to 0.10.15

**Comment by quthla** [comment]
Which impact exactly?

**Comment by d00p** [comment]
The whole process of either issue or renew has to be restructured. The current plan is to just mirror the generated certificate files in froxlors database (so the cronjob that generates vhosts and includes the certificates etc. does not need to be touched, same goes for the front-end page of certificates) and a "renew" is more like a "check database content against file system content" so that acme.sh can do what it is supposed to do
