### ISSUE TITLE
Access-Log Format nur verfügbar wenn system.awstats_enabled

### ISSUE THREAD

**Issue by drexlma** [Froxlor/Froxlor#793]
system_logfiles_format ist nur verfügbar wenn 
 \Froxlor\Settings::Get('system.awstats_enabled') == 1

Ich will das aber auch ohne nutzen können

**Comment by drexlma** [comment]
Hiermit kam das erst hinzu

https://github.com/Froxlor/Froxlor/commit/b355711de93a330c284ed7b82f84d7090174b442#diff-4b23800e27000c4098c78918678b15af

**Comment by d00p** [comment]
Das ist schon korrekt so, da sonst die Traffic-Berechnung via webalizer, das keine Custom-Formate erlaubt, nicht funktioniert

**Comment by drexlma** [comment]
muss das dann nicht auf == 0 sein? 

ich muss awstat aktivieren um das format ändern zu können?

**Comment by d00p** [comment]
Ja musst du, begründung siehe meine erste Antwort
