### ISSUE TITLE
crash regex nginx in specialsettings?

### ISSUE THREAD

**Issue by drexlma** [Froxlor/Froxlor#794]
komisches verhalten beim rewrite regex generieren :O 

/([a-z] {
                        2
                })

vhost config 
`...
location / {
 proxy_buffering off;

  rewrite ^/$ /index.php?language=de&site=base;
  rewrite "^/([a-z]{2})/$" /index.php?language=de&site=base;
  rewrite "^/([a-z]{2})/([a-z0-9_]+)/$" /index.php?language=de&site=base;
  rewrite "^/([a-z]{2})/([a-z0-9_]+)/pubimg/([0-9_]+)/(.*)/$" /public_img.php?language=$1&site=$2&id=$3&hash=$4;
  rewrite "^/([a-z]{2})/([a-z0-9_]+)/upload/(.*)$" /index.php?language=$1&site=$2&modul=upload&path=$3;
  rewrite "^/([a-z]{2})/([a-z0-9_]+)/add/(.*)$" /index.php?language=$1&site=$2&modul=add&path=$3;
  rewrite "^/([a-z]{2})/([a-z0-9_]+)/add_ok/(.*)$" /index.php?language=$1&site=$2&modul=add&status=ok&path=$3;
  rewrite "^/([a-z]{2})/([a-z0-9_]+)/dir/(.*)$" /index.php?language=$1&site=$2&modul=filesystem&path=$3;
  rewrite "^/([a-z]{2})/([a-z0-9_]+)/list/(.*)$" /index.php?language=$1&site=$2&modul=filesystem_list&path=$3;
  rewrite "^/([a-z]{2})/([a-z0-9_]+)/elist/(.*)$" /index.php?language=$1&site=$2&modul=filesystem_elist&path=$3;
....
}`

result 
```
server {
...
        location / {
                index index.php index.html index.htm;
                proxy_buffering off;
                rewrite ^/$ /index.php?language=de&site=base;
                rewrite "^/([a-z] {
                        2
                })/$" /index.php?language=de&site=base;

                rewrite "^/([a-z] {
                        2
                })/([a-z0-9_]+)/$" /index.php?language=de&site=base;
...

```

**Comment by d00p** [comment]
Wie schon häufig gesagt: wir können keinen kompletten nginx-config parser implementieren und wollen es auch nicht. Durch die nutzung von RegEx sind einfach unglaublich viele Sachen möglich die wir beim automatischen zusammenführen von unserer config mit kunden-angaben nicht abbilden können, zumindest nicht ohne enormen aufwand. Für froxlor ist halt alles in geschweiften Klammern ein Direktiven-Block. Am einfachsten löst du das in dem du includes benutzt, z.B.

```
location / {
    include /etc/nginx/extras/rewrites-domain.tld.conf;
}
```

Was er dann auch entsprechend ohne Fehler zusammenführen kann. Ungefähr so:

```
server {
...
        location / {
                index index.php index.html index.htm;
                proxy_buffering off;
                include /etc/nginx/extras/rewrites-domain.tld.conf;
...
```

**Comment by drexlma** [comment]
ok danke.

**Comment by drexlma** [comment]
macht es sinn hier was dazu zu schreiben?
$lng['serversettings']['default_vhostconf']['description'] ?

**Comment by d00p** [comment]
Feel free to do it
