### ISSUE TITLE
Default PHP FPM settings cause PHP calls to open URLs served by PHP to fail within same pool

### ISSUE THREAD

**Issue by Lantizia** [Froxlor/Froxlor#796]
Spoken at length about this with d00p on the #froxlor IRC channel.

Basically consider not having "pm.max_children = 1" (whilst "pm = static") as any website (including Wordpress, easily tested by using the 'Site Health' page on the WP dashboard) which uses PHP to call a URL on it's own website which is served by PHP... will endlessly be waiting and never get a reply and time out... no matter if the request was made with cURL or fsockopen, etc...

Perhaps set this to 2, so at least this basic functionality works "out of the box".  But maybe also the default PHP FPM settings are due for a minor overhaul anyway... thinking about why we use these particular default php fpm settings, such as... static vs dynamic... why those particular disabled_functions (like disabling curl)... the number of children/idle processes... etc...

I know these can be set/overridden by anyone using the UI anyway.  It just maybe needs a quick rethink to ensure that any "out of the box" default settings are still a recommended set for a minimal/small server (whilst still ensuring security).  Then anyone can crank up the performance/settings using that template as a safe starting point.

**Comment by d00p** [comment]
I think the best way is to roll with the current debian standards here. I will also update the php.ini but somehow thought about how to overwrite possible customized default-configs but still provide an always updated default - so I might switch from "use the phpconfigs from database-entry with id=1" to "read file from templates/misc/" like awstats-model and standardcustomer-index file

**Comment by Lantizia** [comment]
Yeah I had given some thought to something similar.

It would appear something (I'm guessing Froxlor?) has moved...
**/etc/php/7.3/fpm/pool.d/www.conf** to **/etc/php/7.3/fpm/pool.d/www.conf.dpkg-dist**

So perhaps if these pool.d conf files support some kind of 'include', the Froxlor-written config files could 'include' the distro's (not just Debian, but whichever distro's) default pool.d config first... then override with what we set in Froxlor secondarily after that line?

**Comment by d00p** [comment]
> 

> It would appear something (I'm guessing Froxlor?) has moved...
> **/etc/php/7.3/fpm/pool.d/www.conf** to **/etc/php/7.3/fpm/pool.d/www.conf.dpkg-dist**

Not exactly, the dpkg-dist file is provided by the package (distributed default config) and is not used (it does not end in .config). The original www.conf which is installed by default is removed by froxlor because the whole pool.d-directory is managed by froxlor and if no configs are generated for a specific php-fpm version, a dummy is being created.
