### ISSUE TITLE
Usage recalculation seems to count usage twice

### ISSUE THREAD

**Issue by philipp-vt** [Froxlor/Froxlor#797]
Situation: Admin id 2 has four customers which have 5,120, 23,808, 1,024, and 0 MB mail space assigned to their mail accounts. If you hit the usage recalculation functionality, froxlor calculates the admin's (!) usage of email quota as 59,904, which is exactly twice the correct value.

The calculation to me seems to be wrong in lib/Froxlor/User.php, line 247:
`$admin[$field . '_new'] = $admin_resources[$cur_adm][$field];`

The array field $admin['email_quota_used_new'] is therefore not initialized with 0, but with the value from $admin_resources. $admin_resources[2]['email_quota_used'] is calculated in line 126 by summing up all quota assigned by the admin's customers. In my opinion, the field now already contains the correct value (it in fact does contain 29,952).

But in line 262, the customer's assigned quota is added again to the $admin['email_quota_used_new'] field:
`$admin[$field . '_new'] += $acustomer[$field];`

which ends up in having the quota assigned by customers counted twice.

The behavior seems to be correct if you change line 247 to initialise the field with zero:
`$admin[$field . '_new'] = 0;`

I assume this is a bug or is there any reason behind this behavior?

Thanks
Philipp

**Comment by d00p** [comment]
The fields are all initialized with 0 using the `initArrField()` function in the same file. I currently cannot understand why the used quota would be doubled but nothing else of these fields? From the code-perspective you are right, it looks like it gets its values assigned two times, need further investigation, maybe even refactoring :) Pretty old part of froxlor

**Comment by philipp-vt** [comment]
Thanks for the quick fix, d00p - and thanks for all the energy you invest in making Froxlor even better!

You are right, other fields have been doubled as well (FTP for example), but the problem came up for mail quota in my case.
