### ISSUE TITLE
FR: ssl_session_tickets should be disabled by default

### ISSUE THREAD

**Issue by patschi** [Froxlor/Froxlor#799]
For security reasons it would be more beneficial to disable `ssl_session_tickets` for nginx by default.

The long reason is mentioned over here: https://github.com/mozilla/server-side-tls/issues/135. Also see in the Mozilla configuration [here](https://ssl-config.mozilla.org/).

The short version is:
- It disables forward secrecy (FS)
- nginx generates tickets on startup and remains the exact same during the whole runtime, what isn't optimal. Tickets are only newly generated on a restart of nginx.

**Comment by d00p** [comment]
As you have the possibility to change the behaviour, we will stick with the default which is ON, see http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_session_tickets
