### ISSUE TITLE
Health check URL for monitoring

### ISSUE THREAD

**Issue by halfgaar** [Froxlor/Froxlor#801]
My pending upgrade of Froxlor made me think of [Gitlab's health check](https://docs.gitlab.com/ee/user/admin_area/monitoring/health_check.html). It would be nice if Froxlor had something like that too. 

It can check thinks like system database login, whether all services are configured and running, whether all daemons operate and accept logins (with some internal test account), "IPs and Ports" consistency with actual server IP address, etc.

The HTTP status code can then be used to indicate OK or error, so it integrates easily in Nagios/Icinga/other monitoring.

It may be too broad a feature request, but I did still want to mention it.

**Comment by d00p** [comment]
There are monitoring tools for that on a level we could never do that, like zabbix, munin, etc. same for backup, that's why we don't put everything into froxlor what others do way better

**Comment by halfgaar** [comment]
That's not what I meant. I meant an internal health check that can be checked by those other monitoring tools. The 'database validation' link is part of what I mean: correct DB char set, IP domain references, 'froxlor-user in the customer groups (for FCGID/php-fpm)', 'Main domains with no SSL-Port assigned don't have any subdomains with active SSL redirect', 'False SSL-redirect flag for non-ssl domains', 'Webserver-user in the customer groups (for FCGID/php-fpm)'.

A URL that can be checked with a special auth token or IP whitelist (don't need session cookie), and that returns a 200 or 500 based on the result, would really be helpful.

**Comment by d00p** [comment]
Got you

**Comment by d00p** [comment]
It will be implemented in our API as all the other commands, so no you will need to have a valid API key and secret (and optionally bound to an IP address to restrict access). Here's a little patch that will enable the call `Froxlor.integrityCheck` via API. Please let me know whether this is something that works for you. 

```diff
diff --git a/lib/Froxlor/Api/Commands/Froxlor.php b/lib/Froxlor/Api/Commands/Froxlor.php
index 709cffe2..080676d6 100644
--- a/lib/Froxlor/Api/Commands/Froxlor.php
+++ b/lib/Froxlor/Api/Commands/Froxlor.php
@@ -243,6 +243,26 @@ class Froxlor extends \Froxlor\Api\ApiCommand
                return $this->response(200, "successfull", \Froxlor\System\Crypt::generatePassword());
        }
 
+       /**
+        * can be used to remotely run the integritiy checks froxlor implements
+        *
+        * @access admin
+        * @throws \Exception
+        * @return string
+        */
+       public function integrityCheck()
+       {
+               if ($this->isAdmin() && $this->getUserDetail('change_serversettings')) {
+                       $integrity = new \Froxlor\Database\IntegrityCheck();
+                       $result = $integrity->checkAll();
+                       if ($result) {
+                               return $this->response(200, "successfull", "OK");
+                       }
+                       throw new \Exception("Some checks failed.", 406);
+               }
+               throw new \Exception("Not allowed to execute given command.", 403);
+       }
+
        /**
         * returns a list of all available api functions
         *
```

**Comment by halfgaar** [comment]
Oh yeah, the new version already has this API infrastructure, so using a key is fine. That patch seems to be what I would like.

However, my upgrade from Froxlor 0.9 Debian 8 to Froxlor 0.10 Debian 10 went very wrong yesterday, and Froxlor wasn't too aware of it. In the end, I restored from backup (VM image).

It would be nice is the integrity check itself could be expanded. A start would be a better verification that the daemon config files are the way Froxlor wants them. Or at least that there is some check that all of them are configured to a working state. I know this may be hard, because user's config files will differ from the templates/initial version Froxlor proposes in the 'configuration' wizard, but in a case such as mine, where you want be up-to-date with Froxlor's wishes, survive a change from Courier to Dovecot, yet retain your own configuration, a good integrity check is very valuable.

Running with the correct PHP version may also be a check that is included. Or, perhaps that should be at the top level of any script. Debian left php5 enabled, all the way to Debian 10, and Froxlor didn't realize. Some parts of it just started malfunctioning. If this happens in the migration code, everything can be inconsistent and irrecoverable.

**Comment by d00p** [comment]
> However, my upgrade from Froxlor 0.9 Debian 8 to Froxlor 0.10 Debian 10 went very wrong 
> yesterday, and Froxlor wasn't too aware of it. In the end, I restored from backup (VM image).

I'm sorry to hear that you had these troubles, you might want to ask in the forum for further support if needed. Basically it's not really that hard and works just fine...

> Or at least that there is some check that all of them are configured to a working state.

There is no way of knowing that for sure ...we give the freedom to adjust the configs as needed, also the configuration is 99% ONE time-setup - you will never change anything froxlor-related in these configs. Makes no sense to monitor that regulary

> Running with the correct PHP version may also be a check that is included. 

There is no "correct" PHP version...if you use anything below php-7.0 it will just not work anyways - so also makes no sense to integrate a check via API if the API itself requires php-7.0+

> Debian left php5 enabled, all the way to Debian 10, and Froxlor didn't realize.

Well that's why all projects release announcements with important information...read, understand, know what to change before upgrading your whole Operating System or froxlor....sorry, also nothing one could "monitor".
