### ISSUE TITLE
Listing email addresses via webinterface results in error if domains are hidden from customers

### ISSUE THREAD

**Issue by d00p** [Froxlor/Froxlor#803]
# Summary

Please provide a concise summary of the problem you're experiencing...

Listing email addresses via webinterface results in error if domains are hidden from customers. This is because the frontend uses `SubDomains.listing()` to get all the customers available email-domains to show/hide the 'add new address' link. If the `domains` section is hidden via settings this results in an `You cannot access this resource` Exception.

# System information
* Froxlor version: 0.10+

# Steps to reproduce

1. Check "Domains" in Settings -> Panel-Settings -> Hide menu items and traffic charts in customer panel
2. Login or switch to customer with email resources
3. Click on "Emails"

# Expected behavior

1. List of email addresses already added or empty list

# Actual behavior

1. `You cannot access this resource` Exception

**Comment by kartoffelheinz** [comment]
The same error still occurs in 0.10.16 if you try to add a new email address while domains are hidden from the customer. Would be nice to see this fixed, too (and every other possible part where this could be a problem as well). Many Thanks!

**Comment by d00p** [comment]
I tested that on two of my systems and it worked fine. And just now tested again with current 0.10.16 and cannot reproduce the error. can you please specify exact steps to reproduce, screenshots, and possible (if log is set to paranoid) the log output?

**Comment by kartoffelheinz** [comment]
Cannot produce Screenshots right now, but these are the steps to reproduce in current 0.10.16 (just installed 3 days ago):

**Steps to reproduce**

- Check "Domains" in Settings -> Panel-Settings -> Hide menu items and traffic charts in customer panel
- Switch to customer with email resources
- Click on "Emails" (Note: All current addresses are visible and can be edited just fine)
- Click "Add E-Mail-Adress"
- Fill in localpart and chose any domain (if not pre-selected)
- Hit green Submit-Button
- Error Message shows "You cannot access this resource"

Could you try to reproduce if following these steps?

**Comment by d00p** [comment]
Yes I can, thanks, last time it was only the view of the page that resulted in the error.

**Comment by d00p** [comment]
Okay, I have a working solution, will take a while as this issue might apply to other situations too
