### ISSUE TITLE
feature request - duplicate domain

### ISSUE THREAD

**Issue by ghost** [Froxlor/Froxlor#807]
# Summary

would be nice to be able to duplicate domains so that the configurations could be copied.

**Comment by d00p** [comment]
Basically, that could make sense for various entities ;) let's see what we can do

**Comment by d00p** [comment]
Small feedback required: for example for a domain, we could copy almost everything except the domain name itself, so this would have to be passed as parameter. Now, should does it make sense to also let a duplicate function specify the customer? That would lead to way more adjustments in the duplicate process (especially for domains) like e.g. php-fpm is used, the source domain uses a fpm config that client a is allowed to use but target client b not - so this would need adjustment to. Just asking what is useful, needed, what are the use-cases so we can assess the scope better

**Comment by jucajuca** [comment]
Hi, in my case I would only need to duplicate the configuration for the same customer. 

I run similar applications that use very similar settings, so duplicating the settings would be very helpful.

**Comment by heavygale** [comment]
Is this meant to be added to the API or as a "Create domain" view in the Froxlor ui that's simply prefilled with the data of a the domain that's meant to copied?

**Comment by d00p** [comment]
Well, of course this would be a new API call and this can be implemented in the UI

**Comment by jucajuca** [comment]
is this feature being implemented?

**Comment by d00p** [comment]
It's on the to-do yes, that's why this is still open. Most of likely in 0.11.x but there are many other things to be done so this is not fixed for a specific release
