### ISSUE TITLE
Email-templates add missing variables

### ISSUE THREAD

**Issue by mr-manuel** [Froxlor/Froxlor#808]
# Feature request

# Summary

Add missing available variables from the available variable table in some Email-templates: {FIRSTNAME}, {NAME}, {COMPANY} and {SALUTATION}.

It would also be nice to have the Customer ID and Title as a variable.

![grafik](https://user-images.githubusercontent.com/12592765/74975339-3356b680-5427-11ea-8bbb-e8cdd5ee1e32.png)

![grafik](https://user-images.githubusercontent.com/12592765/74975408-4a95a400-5427-11ea-909f-72d92780b6c9.png)

# System information
* Froxlor version: 0.10.12

# Steps to reproduce

1. Create new Email template

# Expected behavior

1. See all available variables

**Comment by d00p** [comment]
jfyi: `{FIRSTNAME}, {NAME}, {COMPANY}` is combined in `{SALUTATION}`.

**Comment by d00p** [comment]
> It would also be nice to have the Customer ID and Title as a variable.

`ID` makes almost no sense, i don't know where this info would be helpful for a customer. I've added the `customernumber` field though. There is no `title` field.
