### ISSUE TITLE
Ubuntu 19.10 install is not supported

### ISSUE THREAD

**Issue by noraj** [Froxlor/Froxlor#812]
# Summary

Ubuntu 19.10 is not supported.

![image](https://user-images.githubusercontent.com/16578570/75899825-54160780-5e3c-11ea-9f6a-e3bec74731e4.png)

# System information

* OS/Version: ubuntu server 19.10

**Comment by d00p** [comment]
Because there aren't any configuration templates for it yet as I did not have the time

**Comment by Dessa** [comment]
we never supported non-lts tho
