### ISSUE TITLE
Storage engine MEMORY is disabled (Table creation is disallowed).

### ISSUE THREAD

**Issue by juhenriquez** [Froxlor/Froxlor#813]
# Summary

Please provide a concise summary of the problem you're experiencing...
While installing Froxlor using Mysql 8.0 with Digital Ocean Managed Database, get the following error.
![2020-03-05 12_43_35-Froxlor Server Management Panel - Installation](https://user-images.githubusercontent.com/8250019/76003881-13bb9580-5edf-11ea-82d0-ad9779d02a66.png)

From what I've read most cloud managed database providers don't allow ENGINE_MEMORY.

https://magento.stackexchange.com/questions/236316/install-fails-storage-engine-memory-is-disabled-table-creation-is-disallowed

# System information
* Froxlor version: latest
* Web server: nginx
*Mysql: 8.0.18 (Managed Digital Ocean)

**Comment by d00p** [comment]
We don't even use `ENGINE=MEMORY`....could you try giving us more information about the SQL command being executed that generates that error?

**Comment by juhenriquez** [comment]
How might I be able to see this, this happens during the Froxlor install.

**Comment by d00p** [comment]
[mysql] logs...?

**Comment by d00p** [comment]
no feedback
