### ISSUE TITLE
[feature request] - check DNS record before requesting/refreshing LE certificate

### ISSUE THREAD

**Issue by rseffner** [Froxlor/Froxlor#817]
# Summary
LE refresh is not checking if domain is on the server anymore. In my case a customer enables LE for an domain which he changed to another IP-address a few months later via DSN-editor - so LE can't find the acme-challenge in FROXLORs host because damian was already redirectet to  another machine via DNS.
As result my whole server was blocket from LE because of a lot of faulty requests.

# System information
* Froxlor version: 0.10.15
* Web server: apache2
* DNS server: Bind
* OS/Version: Debian 10

# Steps to reproduce
1. enable LE for an (sub-)domain (e.g. www.example.com)
2. change A-record of these (sub-)domain (e.g. www.example.com) to another server
3. wait for or try to refresh the LE certificate for this (sub-)domain

# Expected behavior
Don't run LE refresehs (and also requests?) for domains where DNS points to another IP-address.

# Actual behavior
LE refresehs (and also requests?) were startet every cron run.

**Comment by d00p** [comment]
Good idea, we should check whether the domain resolves to at least one of the assigned IP addresses, although it should be possible to disable this check, might not suite every setup (cloudflare ips, internal, etc.)

**Comment by dphi** [comment]
How about not just checking for DNS, but whether a http get is successful? This would help in more cases.

**Comment by d00p** [comment]
http can be answered by another server as well...doesn't necessarily help

**Comment by dphi** [comment]
a "get /" would of course not make much sense. Instead:

froxlor can put a random filename in the acme-challenge folder and test for it.

**Comment by d00p** [comment]
And how would that be equal or better to checking DNS?

**Comment by dphi** [comment]
A http get uses the same code paths as letsencrypt- which includes, but is more than, DNS.

**Comment by d00p** [comment]
If DNS is correct and froxlor is setup correctly then the DNS check will be sufficient because the rest surely works. Of course we can also create a random file to the acme-challenge directory, effect is the same imho
