### ISSUE TITLE
Two "Undefined index" errors

### ISSUE THREAD

**Issue by PHPGangsta** [Froxlor/Froxlor#818]
# Summary

In very rare cases I'm getting two "Undefined index" errors on the SSL-certificates page
froxlor/admin_domains.php?page=sslcertificates

Undefined index: letsencrypt
Undefined index: domain

![grafik](https://user-images.githubusercontent.com/608408/76255959-65ea1700-624f-11ea-8fa7-ca2b4903e0ca.png)

After a refresh the errors are gone.

Maybe it only happens after deleting a customer? I deleted 2 customers today, and a few minutes after that I got the errors.

# System information
* Froxlor version: 0.10.14
* Web server: apache2

**Comment by d00p** [comment]
From what I can see, when deleting a customer and all its resources, the ssl-certificates seem to be missing, so that should most likely be the cause

**Comment by PHPGangsta** [comment]
Thanks! I will test the next version as soon as it is available. :+1:
