### ISSUE TITLE
[Feedback] LetsEncrypt ipv6

### ISSUE THREAD

**Issue by ternes3** [Froxlor/Froxlor#823]
Hello dear Froxlor development community,
i have started to work with ipv6 recently, so far i have avoided it like most people. 

I have created a Debian 10.3 installation with only one ipv6 interface. 

I installed froxlor, the repo is already available for ipv6. This is great, because the standard Debian repos are not. 

Everything works so far, really very well and better than I would have expected. 

But now the following observation, letsencrypt does not work immediately. This is because the acme.sh is loaded from github, but github doesn't support ipv6. 

I was able to fix this relatively quickly by manually putting the acme.sh in the right place and adjusting the permissions (/root/.acme/acme.sh). 

It might be a good idea to install a fallback at this point, or to post a notice where the user is informed about the error, as long as github does not support ipv6.

# System information
* Froxlor version: 0.10.15-1
* Web server: apache2
* DNS server: Bind/
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian 10.3

**Comment by snoopotic** [comment]
Well, 
Besides this issue I’d recommend you a dual stack environment. The Internet is sadly not yet full IPv6 ready.

**Comment by d00p** [comment]
> Well,
> Besides this issue I’d recommend you a dual stack environment. The Internet is sadly not yet full IPv6 ready.

Eh...sorry, but we do not control github's server environment...froxlor is dual-stack ready for ages but this is not about froxlor if you read the issues correctly
