### ISSUE TITLE
Gentoo Repository down?

### ISSUE THREAD

**Issue by kakra** [Froxlor/Froxlor#824]
It seems git://git.froxlor.org/froxlor-gentoo.git is down or not accessible.

Maybe it should be mirrored or moved to Github?

```
# emaint sync -r froxlor
>>> Syncing repository 'froxlor' into '/var/db/repos/froxlor'...
/usr/bin/git clone --depth 1 git://git.froxlor.org/froxlor-gentoo.git .
Cloning into '.'...
fatal: unable to connect to git.froxlor.org:
git.froxlor.org[0: 2a01:440:1:12:dead:beef:3d2d:815]: errno=Connection timed out
git.froxlor.org[1: 46.253.127.142]: errno=Connection timed out

!!! git clone error in /var/db/repos/froxlor
!!! Repository 'froxlor' is missing masters attribute in '/var/db/repos/froxlor/metadata/layout.conf'
!!! Set 'masters = gentoo' in this file for future compatibility
```

**Comment by realkinetix** [comment]
Hi there... I started looking in to froxlor in the past week, and have got to the point to wanting to install on gentoo.  I see this bug's been open for a year - is there any plan to resolve this?  Is there any way to get what was in that repo that we can't access at this time?

Thanks very much in advance.

**Comment by d00p** [comment]
Dessa seems kind of busy, I'll remind him. Time to move that to github too I guess and it also needs a bit of refactoring - the ebuild was never adapted to 0.10.x at all

**Comment by Dessa** [comment]
truthfully, i forgot about this again, stupid real life stuff

we could move it to github since i'd not have to mess with certificates for git.froxlor.org this way.

im not sure what kind of refactoring is needed since i never needed to adapt it, but its been a while.

**Comment by kakra** [comment]
Given the security breach that hit PHP with their self-hosted Git repositories lately, it probably makes sense to move it to Github anyways. The PHP project did the same. One hassle less to bother with. So I'm all in for this idea.

**Comment by Dessa** [comment]
my gitea instance isn't going away, so it doesn't really change anything; keeping it up to date was never a problem for me.

**Comment by kakra** [comment]
Well, I mirrored it to our own Gitea instance back when it was still available but I no longer depend on the ebuild because it pulls too many dependencies in while OTOH I'm in the process of locking it up inside an isolated container putting all the other attack surfaces (web server, PHP, mail server etc) into separate and isolated containers, too. Only unix sockets are shared so each container can access the services of the other containers privately, with a frontend nginx proxy to guard access.

Containers are designed to be throw-away deployments (aka update an isolated clean clone of the container, swap, throw the old away), configuration files and storage is mapped externally. Froxlor doesn't integrate too well with it, so I already have some git patches floating around to work around UID mapping issues and using pam-extrausers correctly (and some `systemctl -H` wrappers to control external services). After porting it to 0.10.x, I could create a pull request if this is of interest. But as of now, the separation is not done yet, the container still has its own local PHP (not so easy to remove, I probably stick with it) and Apache (easy to remove) installation.

So for me, the ebuild is currently only left as more or less a meta-ebuild to pull in some dependencies.

In the end, this is like dockerizing Froxlor and making it container-aware to call into external containers for service management. I think this could be a nice future feature of Froxlor.

**Comment by d00p** [comment]
The repository is now located there https://github.com/Froxlor/Gentoo-Ebuild - I will have to put some work into it for everything to work as intended
