### ISSUE TITLE
[feature request] logfolder per customer like for mail, tmp, webs

### ISSUE THREAD

**Issue by mr-manuel** [Froxlor/Froxlor#825]
# Feature request

I would like to have a log folder per customer (`/var/customers/logs/{CUSTOMERLOGIN}/`), like there are subolders in `/var/customers/mail`, `/var/customers/tmp` and `/var/customers/webs`. Now all logs from all customers are in one folder. This causes the problem for me that every customer can see and view all logs from other customers. This folder can be accessed trough SSH/SFTP, which can be enabled by the user itself.

**Comment by d00p** [comment]
Since when can a customer with enabled ssh/sftp access anything outside of his homedir? It's not like they can access /var/customers/ ....
For the feature itself: sure, this should be no problem

**Comment by mr-manuel** [comment]
Strange. I installed Froxlor 2 months ago, created a customer, enabled SSH and then I can access even `/etc/apache` and view configuration files. But I cannot access other customer folders in `/var/customers/(webs|tmp)/`, which is correct. 

With FTP or FTPS I can only access the homedir. But the customer can enable the Shell by itself (FTP -> Accounts -> Account -> Shell -> /bin/bash. Then he can login with SSH and set cronjobs for example.

Maybe I missed something during installatio to set the permissions by myself in order to limit the users created by Froxlor?
Anyways, it would be very comfortable to have the logs in separated folders per customers with access only for the customer :)

**Comment by d00p** [comment]
Well, we do not have any chroot setup, that's something you should do - that's why enabling ssh access shows such a big warning. Viewing of various files even outside of the homedir is not forbidden by default.

**Comment by mr-manuel** [comment]
Would it be possible to also include a chroot setup in Froxlor installation script or is it to complex? If it's not possible, maybe a notification before installing and telling that the setup would be more secure with a chroot setup, would also help? If in your opinion everyone should know that already, then nevermind :)

**Comment by d00p** [comment]
This has nothing to do with the "default setup" - that is something ssh related if you actively enable ssh for customers which is disabled by default for many many reasons. This feature only exists if you really need that and you know why you need it and how to secure it.

Which again, has nothing to do with you current feature request. Which for me makes not too much sense - it compicates the logrotate snippet and from personal usage experience is not needed as the logs start with the username anyway. As discussed this doesn't change whether ssh users can access files/folders, a subfolder doesnt change that :)

**Comment by mr-manuel** [comment]
Ok, thank you for explanation
