### ISSUE TITLE
[feature request] file template add variable {DOMAIN}

### ISSUE THREAD

**Issue by mr-manuel** [Froxlor/Froxlor#826]
# Feature request
It would be great if a variable with the domain name would be available in the file template `index file for newly created customer directories`. So it's possible to write for example that the domain domain.tld is not available yet or something else.

**Comment by d00p** [comment]
When adding a customer, there is no domain yet for the customer, except when `stdsubdomain` is activated. So this makes little sense as there is no domain we can replace the placeholder with.

This is how it is currently possible and way more practical:

- Set `Settings -> System-System -> File extension for index file in newly created customer directories`to `php`
- use something like `<?php echo $_SERVER['SERVER_NAME']; ?> not available yet` or something else
