### ISSUE TITLE
Remove dependencies in bionic repository

### ISSUE THREAD

**Issue by kallookoo** [Froxlor/Froxlor#827]
Hi,
After install the ondrej repository for php, and install the 7.4 with the froxlor requeriments the froxlor packages install the php7.3-common and php7.3-mysql.
Thanks

**Comment by d00p** [comment]
that's because we build for and require the distros defaults and no external possible repositories.

**Comment by kallookoo** [comment]
I understand what you are saying, but instead of specifically using that version I think it would be solved using the generic name and that the system select the default version.
What is that I understand what happens, I have not looked at the source of the package.
In my case using that repo right now is 7.4.

**Comment by d00p** [comment]
There is no specific version string in the control-file of the deb package:

`Depends: apache2 | lighttpd | nginx, php | php-cgi | php-fpm, php-cli, php-bcmath, php-curl, php-json, php-mbstring, php-mysqlnd | php-mysql, php-xml, php-zip [...]`

**Comment by kallookoo** [comment]
Hi, 
After uninstalling and installing the necessary packages I realized that php7.4-mysql did not select it or so I think and I would say that is why I selected php7.3-mysql.
I close the issue, and thanks
