### ISSUE TITLE
Cannot create email account

### ISSUE THREAD

**Issue by tczaude** [Froxlor/Froxlor#829]
Cannot create email account. I always recive 

Error
Email-address contains invalid characters or is incomplete
Back

# System information
* Froxlor version: 0.10.15
* Web server: nginx

# Steps to reproduce

1. Customer account 
2. Create email-address
3. i try with test and chose domain
4. Create account
5. And recive error

I dont recive any error.

If i make by hand in database records. All works fine i can update passwords etc.
This look like validation problem i email name

**Comment by d00p** [comment]
Ensure the sender email address in the settings and for the admin/reseller are set and valid.

**Comment by tczaude** [comment]
Yes adress is set and valid. No have any bad spaces etc

**Comment by d00p** [comment]
So adding the email __address__ works but you get the error when creating the __account__ correct?
If you have the setting *Use alternative email-address* enabled in the mailserver setting, the customer will receive the account details of the freshly added account via email which needs to be given in the corresponding from when adding the account.

**Comment by pol5533** [comment]
Hello, we work together with @tczaude on this bug. After setting up alternative mail everything works fine, there is any option to remove this validation?

**Comment by d00p** [comment]
There is an option to disable sending account-details to alternative emails in *settings* -> *mailserversettings* -> *Use alternative email-address* (default is OFF).

But the correct behaviour would be to not fail validation of no address is given when *Use alternative email-address* is enabled systemwide

**Comment by pol5533** [comment]
By the way, after setting up alternative mail for user, We receive mail on totally different email for example we set up alternative email (alternative I set up my email account for this new user) for new created user but we recive mail with all credentionals for new users at admins goup admins@example.com

**Comment by tczaude** [comment]
Ok this option fix it.
Error should be more precise 
Thx

**Comment by d00p** [comment]
> By the way, after setting up alternative mail for user, We receive mail on totally different email for example we set up alternative email (alternative I set up my email account for this new user) for new created user but we recive mail with all credentionals for new users at admins goup [admins@example.com](mailto:admins@example.com)

sorry, i don't really understand what you mean. When activating "Send alternative email" you can specify an email address to send the account details of the email address to. The 'From'-field will be set to the customer's **admin**.

**Comment by pol5533** [comment]
> sorry, i don't really understand what you mean. When activating "Send alternative email" you can specify an email address to send the account details of the email address to. The 'From'-field will be set to the customer's admin.

Sorry, that was my mistake, so I deleted my answer. I noticed this after creating the message.
