### ISSUE TITLE
letsencrypt ecc certificate problem

### ISSUE THREAD

**Issue by lordrasmus** [Froxlor/Froxlor#830]
letsencrypt ecc certificate can't be renewed

in the cronjob output of froxlor_master_cronjob.php --letsencrypt --debug i see this message

The domain '...' seems to have a ECC cert already, please add '--ecc' parameter if you want to use that cert.

when the  enable ECC / ECDSA ssl setting is disabled the certificate renewal works

# System information
* Froxlor version: 0.10.12
* Web server: apache2
* OS/Version: Debian 10

# Steps to reproduce

1. create domain with ssl enabled
2. enable ECC / ECDSA in ssl settings

# Expected behavior

1. certificate is renewed

# Actual behavior

1. Error Message in cron log and certificate is not renewed

# Log files/log entries
syslog:
<pre>
The domain '...' seems to have a ECC cert already, please add '--ecc' parameter if you want to use that cert.
</pre>

**Comment by d00p** [comment]
Please update to 0.10.15 as renewing is now passed to acme.sh's cronjob and no longer done by froxlor itself
