### ISSUE TITLE
[feature request] File Manager like most panels do

### ISSUE THREAD

**Issue by kotakomputer** [Froxlor/Froxlor#831]
File Manager is the must have feature for User Hosting Panel. This feature was available on top panel like:
- CPanel
- Plesk
- Virtualmin from the creator of Webmin
- Webuzo from the creator of Softaculous

But I see Froxlor admin rejected this feature rather than accept as feature request based on security issue? Hope this must have feature to replace cPanel available on your plan :) 

Rgds, Wendy

**Comment by d00p** [comment]
You are free to install any filemanager available and provide the URL as link in the customer-menu.

**Comment by kotakomputer** [comment]
From user point of view, this is Hosting Panel job.
I have 3,000 users which satisfy with CPanel even I must buy tens CPanel and Webuzo license each month.

I leave Virtualmin because this developer reject to include PHPMyadmin because he says user can install by themself.

So, I hope Froxflor release a paid version like Webuzo for $2/mo is very interested price, which support Ready to Use features like File Manager.

I will explore Froxlor more, and will see if this Hosting Panel can replace CPanel completly, while this time only Webuzo near to CPanel (but Webuzo can only has 1 username).

Rgds, Wendy

**Comment by d00p** [comment]
> I leave Virtualmin because this developer reject to include PHPMyadmin because he says user can install by themself.

Same for froxlor. And now transfer that to a file manager...exactly. from an end user point of view, I agree. But you are an admin, you can install these tools according to your requirements and provide links in froxlor.

If you are interested in "Pro", maybe froxlor.com will be of interest for you later.

**Comment by kotakomputer** [comment]
I just visit froxlor.com, hope you can provide a paid version soon. Thanks.
