### ISSUE TITLE
[bug]ReportsCron.php failure

### ISSUE THREAD

**Issue by serecords** [Froxlor/Froxlor#833]
# Bug report 
# Summary
Cron: 
/usr/bin/nice -n 5 /usr/bin/php5 -q /var/www/programme/froxlor/scripts/froxlor_master_cronjob.php --usage_report 1> /dev/null

failed with Error:

PHP Parse error:  syntax error, unexpected '?' in /var/www/programme/froxlor/lib/Froxlor/Cron/Traffic/ReportsCron.php on line 397

# System information
* Froxlor version: 0.10.16 (DB: 202004140)
* Web server: apache2
* DNS server: PowerDNS (standalone)
* POP/IMAP server: Courier
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian jessie

# Steps to reproduce

1. php /var/www/programme/froxlor/scripts/froxlor_master_cronjob.php --usage_report --debug

ReportsCron.php on line 397:

new version with failure 
`$langfile = $lngfile['file'] ?? 'lng/english.lng.php';`

old version without failure
`$langfile = $lngfile['file'];`

**Comment by d00p** [comment]
Well, be sure that you php cli is on php-7 too...that's an Null-Coalescing-Operator which is perfectly fine in php-7

**Comment by TinoM** [comment]
Just to leave a note: I ran into the same problem after updating to 0.10.16-1.
On my system (although everything was already running with php 7.3) the cron job settings of froxlor specified explicitely php5, just remove the 5 from the cli call :
![image](https://user-images.githubusercontent.com/3512161/81381747-7dd5fe00-910d-11ea-9fe6-864b42ba0af8.png)

**Comment by d00p** [comment]
This is a __setting__ - of course you need to adjust that to fit your system. The default has been updated a few versions ago, it used to show php5 yes

**Comment by TinoM** [comment]
Yes, i am with you. But my system has been seen only upgrades of debian and froxlor and of course "as-long-as-it-works"™ nobody checks this config.
I've now removed php5 from my system. And: I've have just overread the "php5" in the error mail my system was sending me for a few days.
And seeing this bug just shows @serecords was as blind as me ;).

**Comment by d00p** [comment]
I know what you mean, when we updated the defaults there was no chance we can update the setting as users might have customized it (as we do with all settings of this kind). I think the best solution would be to check for the correct php version from within the cron and notify the admin. Just need to be sure not to send every 5 minutes when the cron runs :)
