### ISSUE TITLE
Is it possible to use just the email feature?

### ISSUE THREAD

**Issue by rubo77** [Froxlor/Froxlor#835]
I used to use syscp on my old server with a lot of emails managed by the tool. After some upgrades Apache was not correctly managed by syscp any more, so I started managing ahe apache config myself.

How would it be possible to just manage emails with Froxlor, while leaving the apache config to manual configuration?

**Comment by d00p** [comment]
Yes, you can set customer domains to `email only` (at the bottom of the add/edit form) and no Webserver configs will be created.

**Comment by rubo77** [comment]
> you can set customer domains to email only (at the bottom of the add/edit form)

I have hundreds of domains in my database. How could you change this setting in the database directly with a mysql command?

**Comment by d00p** [comment]
That should do yes
