### ISSUE TITLE
Undefined variable: lng

### ISSUE THREAD

**Issue by PHPGangsta** [Froxlor/Froxlor#836]
I'm getting the following Notices in the daily cronjob:

/usr/bin/nice -n 5 /usr/bin/php -q /var/www/html/froxlor/scripts/froxlor_master_cronjob.php --usage_report 1> /dev/null

PHP Notice:  Undefined variable: lng in /var/www/html/froxlor/lib/Froxlor/Cron/Traffic/ReportsCron.php on line 418
PHP Notice:  Undefined variable: lng in /var/www/html/froxlor/lib/Froxlor/Cron/Traffic/ReportsCron.php on line 422

I'm using Froxlor 0.10.15, but as far as I can see in the code, it should still happen in the newest version 0.10.16:

Search for 
$lng[
in the file lib/Froxlor/Cron/Traffic/ReportsCron.php, there are 8 occurrences where $lng is not defined.

**Comment by d00p** [comment]
it actually is defined by the language file which is being included a few lines earlier in that file. And as english is always included first there as fallback I'm kinda curious how it's not being defined.

I am also not able to reproduce this. Both reports, traffic and webspace are being generated and sent without any notices or anything (error_reporting set to E_ALL).

Can you please first try with 0.10.16 - most preferable before I'm pushing 0.10.17 today :)

**Comment by PHPGangsta** [comment]
Maybe the "include_once()" is skipped, because the file has been included in another function somewhere else in that file? Then $lng would not be defined at that position where it's missing...

I will update to 0.10.16. I guess I can run the cronjob manually during the day "out of order"?

**Comment by d00p** [comment]
yes you can test that easily by adjusting the __reportsent__ flag in *panel_customers* - just set it to 0 to send the reports again. This way you can sent only to one customer instead of all (affected) again

**Comment by d00p** [comment]
Okay, got it reproduced. I see if I can fix that up :)

**Comment by PHPGangsta** [comment]
All rows in "panel_customers" have "reportsent=0".

I just run
`/usr/bin/php -q /var/www/html/froxlor/scripts/froxlor_master_cronjob.php --usage_report`
manually as root: No output, and no error in syslog (where my PHP-errors should go to).
