### ISSUE TITLE
FTP is not connecting through filezilla 

### ISSUE THREAD

**Issue by softnwords** [Froxlor/Froxlor#837]
# Bug report vs. support request
If you're unsure of whether your problem is a bug or a configuration error
* contact us via IRC in #froxlor on freenode
* or post a thread in our forum at https://forum.froxlor.org

As a rule of thumb: before reporting an issue
* see if it hasn't been [reported](https://github.com/Froxlor/froxlor/issues) (and possibly already been [fixed](https://github.com/Froxlor/froxlor/issues?utf8=✓&q=is:issue%20is:closed)) first
* try with the git master

# Summary

Please provide a concise summary of the problem you're experiencing...

# System information
* Froxlor version: $version/$gitSHA1
* Web server: apache2/nginx/lighttpd
* DNS server: Bind/PowerDNS (standalone)/PowerDNS (Bind-backend)
* POP/IMAP server: Courier/Dovecot
* SMTP server: postfix/exim
* FTP server: proftpd/pureftpd
* OS/Version: ...

# Steps to reproduce

1.
2.
3.

# Expected behavior

1.
2.
3.

# Actual behavior

1.
2.
3.

# Log files/log entries
syslog:
<pre>
example
</pre>

**Comment by d00p** [comment]
absolutely no content or anything that's mentioned in the issue template. Did you even __read__ the template content? Please follow it accordingly. If you have issues connecting to a daemon please consider using our forum for support as it most like is *not* a bug in froxlor itself
