### ISSUE TITLE
Adding unique key on domainid field in domain ssl table fails

### ISSUE THREAD

**Issue by syssi** [Froxlor/Froxlor#840]
# Summary

I tried to update from 0.10.16 to 0.10.17. The update step (browser) is unable to apply the unique key constraint for column "domainid" of the `domain_ssl_settings` table (https://github.com/Froxlor/Froxlor/commit/eb3590dc340bf4336e9cf9677906d569a344ccfa). I've multiple records (duplicates) at the `domain_ssl_settings` table sharing the same domainid. 

# System information
* Froxlor version: 0.10.17
* Web server: apache2
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian

# Steps to reproduce

1. Make sure you've two records at the `domain_ssl_settings` table sharing the same domainid. ;-)
2. Update to 0.10.17

# Log files/log entries
syslog:
<pre>
Adding unique key on domainid field in domain ssl table
</pre>

**Comment by d00p** [comment]
The updater shoud've removed possible duplicates, dang.

Can you run the following query and check whether the duplicate entries are shown?

```sql
SELECT a.* FROM domain_ssl_settings AS a
LEFT JOIN domain_ssl_settings AS b ON UNIX_TIMESTAMP(b.`expirationdate`) > UNIX_TIMESTAMP(a.`expirationdate`)
AND (b.`domainid`=a.`domainid` OR (UNIX_TIMESTAMP(b.`expirationdate`) = UNIX_TIMESTAMP(a.`expirationdate`) AND b.`id`>a.`id`))
WHERE b.`id` IS NOT NULL
GROUP BY a.`id`
```

**Comment by syssi** [comment]
The query of the updater 

```
                DELETE a.* FROM domain_ssl_settings AS a
                LEFT JOIN domain_ssl_settings AS b ON UNIX_TIMESTAMP(b.`expirationdate`) > UNIX_TIMESTAMP(a.`expirationdate`)
                AND (b.`domainid`=a.`domainid` OR (UNIX_TIMESTAMP(b.`expirationdate`) = UNIX_TIMESTAMP(a.`expirationdate`) AND b.`id`>a.`id`))
                WHERE b.`id` IS NOT NULL
```
doesn't match. I will try your suggestion!

**Comment by d00p** [comment]
I just want you to CHECK for results first before deleteing right away to see if there might be any issues in the query

**Comment by syssi** [comment]
Your query returns an empty result, too. Does this example help?

```
id domainid expirationdate
51 164 2020-07-26 14:03:18
52 164 2020-07-26 14:03:18
```

**Comment by d00p** [comment]
are these all entries for domainid=164? Or just the duplicates?

I think the same date is the problem which I thought I've taken care of in the OR part of the query but looking at it now makes no sense because it only joins if the date differs.

Can you try whether this outputs duplicates?

```sql
SELECT a.* FROM domain_ssl_settings AS a
LEFT JOIN domain_ssl_settings AS b ON 
((b.`domainid`=a.`domainid` AND UNIX_TIMESTAMP(b.`expirationdate`) > UNIX_TIMESTAMP(a.`expirationdate`))
OR (UNIX_TIMESTAMP(b.`expirationdate`) = UNIX_TIMESTAMP(a.`expirationdate`) AND b.`id`>a.`id`))
WHERE b.`id` IS NOT NULL
```

**Comment by syssi** [comment]
This query returns the duplicates which needs to be deleted!

```
id domainid expirationdate
29 85 2020-07-26 13:47:16
30 94 2020-07-26 13:47:40
31 159 2020-07-26 14:35:16
32 88 2020-07-26 13:48:52
33 99 2020-07-26 14:35:34
34 130 2020-07-26 14:01:47
35 157 2020-07-26 14:02:08
36 139 2020-07-26 14:02:48
37 142 2020-07-26 14:00:15
44 143 2020-07-26 14:02:02
49 163 2020-07-26 14:03:03
51 164 2020-07-26 14:03:18
```

Thanks for your support!
