### ISSUE TITLE
Update from 0.10.16 to 0.10.17 does not work

### ISSUE THREAD

**Issue by l1f** [Froxlor/Froxlor#848]
# Summary
After the update from 0.10.16 to 0.10.17 we keep the following error: 

```
Adding unique key on domainid field in domain ssl tablefroxlor[14837]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '35' for key 'domainid'
froxlor[14837]: --- DEBUG: #0 [internal function]: PDO->query('ALTER TABLE `do...') #1 /var/www/froxlor/lib/Froxlor/Database/Database.php(218): call_user_func_array(Array, Array) #2 /var/www/froxlor/install/updates/froxlor/0.10/update_0.10.inc.php(631): Froxlor\Database\Database::__callStatic('query', Array) #3 /var/www/froxlor/install/updatesql.php(44): include_once('/var/www/froxlo...') #4 /var/www/froxlor/lib/Froxlor/Cron/MasterCron.php(325): include_once('/var/www/froxlo...') #5 /var/www/froxlor/lib/Froxlor/Cron/MasterCron.php(34): Froxlor\Cron\MasterCron::init() #6 /var/www/froxlor/scripts/froxlor_master_cronjob.php(26): Froxlor\Cron\MasterCron::run() #7 {main}
```

# System information
* Froxlor version: 0.10.16
* Web server: apache2
* DNS server: PowerDNS (standalone)
* POP/IMAP server: /Dovecot
* SMTP server: postfix/
* FTP server: proftpd/
* OS/Version: Debian 9

# Steps to reproduce

1. Update from 0.10.16 to 0.10.17 
2. Press update in the Froxlor interface

# Expected behavior

1. No stack trace I think

# Actual behavior

1. The stack trace inserted above

# Note
**On a test server where I did the following:**
In the update.php, I simply commented out the `alter table` there, because exactly the key already exists. After that the update worked. - But I don't know if this is the best solution.

**Comment by d00p** [comment]
Yes, known and fixes for next version, sorry, see https://github.com/Froxlor/Froxlor/issues/840

**Comment by l1f** [comment]
Oh, I'm sorry. I had flown over the issues before. I'll just close this one then ^^
