### ISSUE TITLE
Upgrade fails because of duplicate domain id

### ISSUE THREAD

**Issue by Linutux** [Froxlor/Froxlor#859]
# Summary

I have my froxlor install in an inconsistent state. I made an upgrade via Web gui, now I need to login as admin. When I try to proceed the upgrade from 0.10.16 to 0.10.17 it fails with

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4' for key 'domainid'

 

# System information
* Froxlor version: 0.10.16/0.10.17
* Web server: apache2
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS: Ubuntu 18.04

# Steps to reproduce

1. Upgrade from 0.10.16 to 0.10.17
2. Try tk finish the upgrade 
3.

# Expected behavior

1. Upgrade as normal 
2.
3.

# Actual behavior

1. Upgrade fails permanently
2. Froxlor gui unusable
3.

**Comment by d00p** [comment]
See #848  and #840
