### ISSUE TITLE
Api command Domains.update

### ISSUE THREAD

**Issue by andlinger** [Froxlor/Froxlor#861]
If the command "Domains.update" is executed successfully, the whole domain object should be returned, as with "Customers.update", "SubDomains.update", etc.

In the case of "Domains.update", for example, "domain" and "domain_ace" are missing

**Comment by d00p** [comment]
Yes you are right, in this case only the updated data is being returned instead of the result of the corresponding `get()` function as we do it generally. thanks for the hint
