### ISSUE TITLE
Error in API command SubDomains.delete

### ISSUE THREAD

**Issue by andlinger** [Froxlor/Froxlor#862]
The command "SubDomains.delete" requires either an "id" or the "domainname" according to the documentation. However, when executing the command against the Froxlor API interface, the following confusing error message is returned:
`Requested parameter "loginname" is empty where it should not be for "Customers:get"`

**Comment by d00p** [comment]
This is not an error, it's just a missing parameter description in the docs. If called as admin you need to specify the customer, see `SubDomains.add()` and `SubDomains.update()`
