### ISSUE TITLE
Acme.sh cronjob is missing until a new certificate is issues

### ISSUE THREAD

**Issue by halfgaar** [Froxlor/Froxlor#863]
## Abstract

Froxlor version 0.10.18-1 has the new refactored Let's Encrypt, which uses acme.sh to renew the certificates, and Frloxlor loads them in the DB. There's a bug in it, that the `acme.sh --install-cronjob` is only run on certificate issue. The expected result is that when you upgrade to a newer Froxlor and don't request new certificates, the cronjob also gets installed.

## Background

`acme.sh --install-cronjob` is done in [checkUpgrade()](https://github.com/Froxlor/Froxlor/blob/490704f8e12c174d012a78cf213e100659e1b26d/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php#L599), which is done in [runAcmeSh()](https://github.com/Froxlor/Froxlor/blob/490704f8e12c174d012a78cf213e100659e1b26d/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php#L290). That in turn, is only called in [runIssueFor()](https://github.com/Froxlor/Froxlor/blob/490704f8e12c174d012a78cf213e100659e1b26d/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php#L188).

## Affected versions

Froxlor 0.10.18-1 at least. It started with the commit [restructure acmesh implementation and let acme.sh take care of renewing the certificates itself](https://github.com/Froxlor/Froxlor/commit/0d35f5cb29e6b609d6eb64ed12d23bd8c504a469).

**Comment by d00p** [comment]
fixed as of d653f68 - thanks for the hint
