### ISSUE TITLE
CNAME not possible for www subdomain

### ISSUE THREAD

**Issue by Linutux** [Froxlor/Froxlor#864]
# Summary

I created a CNAME for the www subdomain in the DNS editor. It is created, but the A entries for IPv4 and IPv6 are not deleted. Both then exist, which is a bug.

# System information
* Froxlor version: 0.10.18
* Web server: apache2
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Ubuntu 18.04

# Steps to reproduce

1. Create a domain
2. go to the dns editor of that domain
3. try to create a CNAME for the www subdomain

# Expected behavior

1. CNAME of www subdomain exists
2. not A (IP) entries exist for the www subdomain
3.

# Actual behavior

1. The CNAME for www is created
2. The A entry for www ist not deleted, neither for IPv4 nor IPv6
3.

# Log files/log entries
syslog:
<pre>
example
</pre>

**Comment by d00p** [comment]
Does it work if you edit the domain and set the serveralias to "no alias"?
