### ISSUE TITLE
LE Cert doesn´t get renewed although expired

### ISSUE THREAD

**Issue by Af0x** [Froxlor/Froxlor#866]
Hello,

my certificate doesen´t get renewed although it is expired. Using
`php /path/to/froxlor/scripts/froxlor_master_cronjob.php --force --debug`
does not trigger the renewal process.

Regards,

Af0x

**Comment by d00p** [comment]
Fixed in #865

**Comment by d00p** [comment]
- check whether acme.sh cronjob is installed correctly (as root, type `crontab -e` you should see a line calling acme.sh with --cron et.

- check the certificates in /root/.acme.sh/[domain] whether they are renewed, froxlor only syncs these with its own database

**Comment by d00p** [comment]
Then please also follow the second part of my message...

**Comment by Af0x** [comment]
This was covered by the second part of my message. The certs at this location do not change.

**Comment by d00p** [comment]
Well it has nothing to do with the froxlor-cronjob. That's what the acme.sh cronjob is for. Whats the output of `/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh"`?

**Comment by Af0x** [comment]
This works. So the master_cronjob does not trigger the acme.sh-cron and I have to wait until it gets called by crontab?

**Comment by d00p** [comment]
Exactly, the renewal of the certificates is purely handled by acme.sh itself

**Comment by Af0x** [comment]
Would it be possible to include running acme.sh-cronjob with the master_cronjob?

**Comment by d00p** [comment]
Makes no sense, that's the whole point of having that as a cronjob, it runs automatically just as acme.sh needs it to. Froxlor just SYNCHRONIZES the files from acme.sh with its own database.

To continue any discussion, please use the forum.
