### ISSUE TITLE
Quick-Search results incomplete and paging navigation missing if $resultcount > $panel_paging

### ISSUE THREAD

**Issue by kartoffelheinz** [Froxlor/Froxlor#869]
# Summary

When using the quick search panel on top of lists, the results are incomplete, because they will be capped to the configured value of $panel_paging but no paging navigation ever gets shown at the bottom of the list. 

In addition to this, the total count at the top of the page does not reflect the actual result count from the search, but always shows the total count for all entries. This makes it impossible to know how many results the search actually returned.

# System information
* Froxlor version: 0.10.19 (DB: 202005150)
* Web server: apache2
* DNS server: none
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian 10

# Steps to reproduce

1. Populate a Froxlor Database Table with more than $panel_paging items (e.g. domains or email accounts)
2. Navigate to this list and enter a search term (tha would fin more than $panel_paging items) in the quick search input field at the top of the page
3. Hit Enter / Go

# Expected behavior

1. Panel will list $panel_paging items and offers a paging navigation at the bottom of the list
2. Panel shows "Listtype ($totalcount / $searchresultcount)" at the top

# Actual behavior

1. Panel will list $panel_paging items
2. Panel does not show a paging navigation
3. Panel Shows "Listtype ($totalcount)" at the top, no indication of how many results the search returned

**Comment by d00p** [comment]
Generally the intention was not to limit resultsets for search-procedures, the following patch restores this intended behaviour:

```diff
diff --git a/lib/Froxlor/UI/Pagination.php b/lib/Froxlor/UI/Pagination.php
index 107d38d6..91a1699d 100644
--- a/lib/Froxlor/UI/Pagination.php
+++ b/lib/Froxlor/UI/Pagination.php
@@ -164,6 +164,9 @@ class Pagination
                // if a search is performed, the result-entries-count is irrelevant
                // we do not want pagination
                $this->is_search = true;
+               // unset any limit as we do not have pagination when showing search-results
+               unset($this->data['sql_limit']);
+               unset($this->data['sql_offset']);
                return $this;
        }
```

**Comment by kartoffelheinz** [comment]
Thank you, will try the patch.

Any chance to display the item count of the searchresult someplace, maybe as suggested at the top of the list?

**Comment by d00p** [comment]
This is basically also no problem, as the number of results is always sent with the API result; this may take a bit longer as this is used in all listing-templates and partly other options there depend on the total-count (iirc)

**Comment by kartoffelheinz** [comment]
Well, if there is a dependency of some sorts to the total count, you do not have to replace it with the number of results, just put the latter next to it (or close to the search panel).
