### ISSUE TITLE
SSL cert of panel being offered as 2nd cert for non-panel vhosts

### ISSUE THREAD

**Issue by Lantizia** [Froxlor/Froxlor#873]
So I spotted an odd issue where a 2nd certificate was being offered up when doing a "Qualys SSL Labs" test against one of the websites we host.  Thinking perhaps it was just the way that our server was configured... we thought we'd try testing another website that we don't host, but that is also hosted using the Froxlor panel... the froxlor.org website itself.

[https://www.ssllabs.com/ssltest/analyze.html?d=froxlor.org&s=185.123.52.110](https://www.ssllabs.com/ssltest/analyze.html?d=froxlor.org&s=185.123.52.110)

![image](https://user-images.githubusercontent.com/10448369/88686950-8a0b9f00-d0ef-11ea-8ab5-4e290c7c91a9.png)

Although it gets an A+ rating overall, you can clearly see the certificate (that is meant only for use by the Froxlor panel -- on admin.froxlor.org) is also being offered when connecting to froxlor.org itself.

I suspect the issue (at least when I look at our own server) is that the Apache vhost conf file (e.g. **/etc/apache2/sites-enabled/10_froxlor_ipandport_<INSERT IP HERE>.443.conf**) also mentions an SSLCertificateFile and SSLCertificateKeyFile... and as this vhost is based on IP (not hostname) -- effectively both this vhost and the proper vhost (for whichever particular website) are processed combined... which could result in all kinds of other strange issues too.

Suffice to say it would be nice to have an option in the Froxlor panel... so that when it generates it's own panel vhost, it does so using the server hostname (as seen in Settings | System settings | Hostname) and not by IP.

I haven't seen such an option when looking in Settings | Froxlor VirtualHost settings

We've had the "Access Froxlor directly via the hostname" setting enabled from day one of this servers creation, maybe this is supposed to do that - but it is broken?

**Comment by d00p** [comment]
I'll take a closer look at this later, currently on vacation with the family ;) thx for finding this.

**Comment by d00p** [comment]
So, this has to do with SNI basically. Froxlor does nothing wrong in that case. If you want that to be gone you need one IP per domain :) See here: https://community.letsencrypt.org/t/second-certificate-in-ssl-test-and-no-sni-support/115552

**Comment by Lantizia** [comment]
Ah OK then, at least it's not because it's reading two vhost configurations then (if that was even possible)... that would be really odd.

For anyone else reading... I get now that the test is basically testing **with SNI** and **without SNI**... and **without SNI** it'll return whatever domain that Apache read **first** in the config(s) which _**happen**_ to have SSL on that particular IP... which _**happens**_ to be the panel as it's got a **10_** as it's filename prefix, rather than **35_**.

I may instead investigate if there is a way in Apache of disabling non-SNI TLS connections instead (perhaps this can be done on a per IP basis?)... which in theory should mean that part of the test returns nothing.

**Comment by d00p** [comment]
There is: https://httpd.apache.org/docs/current/mod/mod_ssl.html#sslstrictsnivhostcheck

**Comment by Lantizia** [comment]
OK so assuming I understand it's usage correctly...

How would you feel about adding a checkbox for this option under the "Webserver SSL settings" part of the per-domain configuration in the panel?

If it was as **on** by default (when a domain is created on the panel)... then this would mean the user can manually which domain (if any) to manually set this to **off**... and in doing so, they've nominated which IP (of those IPs they can pick on the same page) should respond to older non-SNI capable clients.

This allows for a single IP to be used in both SNI and non-SNI situations... at the moment you've got no control over which domain should appear for non-SNI capable clients.  This likely often leads to a website appearing which the certificate offered doesn't match the domain that the browser was trying to access.

It would additionally need a configuration option in the "Froxlor VirtualHost settings" section too as that's not treated like a regular domain on the panel.

**Comment by d00p** [comment]
You can set this option yourself in the custom vhost content if needed, Apache sets this to off by default for a Reason ;)

**Comment by Lantizia** [comment]
Right but... a good reason?

This graph (from a major CDN) is now 3 years old... I'm sure this figure **today in July 2020** would be very near 100% ?

[https://blogs.akamai.com/2017/03/reaching-toward-universal-tls-sni.html](https://blogs.akamai.com/2017/03/reaching-toward-universal-tls-sni.html)

![image](https://user-images.githubusercontent.com/10448369/88717484-86404280-d118-11ea-9fed-906ad41b896f.png)

Ultimately don't we want the best default values for shared hosting environments?  Today that means SNI is the presumption (not the other way around) and you want to enable (by strangely turning a setting **off**) legacy support for something specific.

Also I can't see anyway of adding custom vhost content for the Froxlor vhost itself?

**Comment by d00p** [comment]
You can do this in IP/port settings and on a per domain basis. 

If Apache sets a default they have their reasons and way more capacity than I do. Why not ask them why they don't turn this on by default? You are free to set it if wanted - froxlor does not deny you that...don't understand the problem here...

**Comment by Lantizia** [comment]
Wait, I thought you didn't see the need on this one?  If it's assigned to you and added to milestones - shouldn't this be open? :D

**Comment by d00p** [comment]
No i was just organizing. You have the answers in my previous answers
