### ISSUE TITLE
Domain import: Option for overwrite TLS settings and version

### ISSUE THREAD

**Issue by Af0x** [Froxlor/Froxlor#874]
Hello,

I discovered that the domain import does not cover the overwrite TLS settings and individual setting of the TLS protocol version.

Maybe it´s already present but the wiki doesn´t list it to date.

Regards,

Af0x

**Comment by d00p** [comment]
Basically, if parameter name is specified in the CSVs header the field will be used. the importer just calls Domains.add() and should pass parameters as stated in the header of the CSV file but yes, the docs should be updated

**Comment by d00p** [comment]
The wiki linked hard to version 0.10.0 api docs, it should be correct now.
