### ISSUE TITLE
warnings with php 7.4.9

### ISSUE THREAD

**Issue by df8oe** [Froxlor/Froxlor#876]
Using latest Froxlor 0.10.20 I got warnings about:

`Array and string offset access syntax with curly braces is deprecated`
vendor/algo26-matthias/idna-convert/src/UnicodeTranscoder.php:85
vendor/algo26-matthias/idna-convert/src/UnicodeTranscoder.php:206
vendor/algo26-matthias/idna-convert/src/UnicodeTranscoder.php:228
vendor/algo26-matthias/idna-convert/src/UnicodeTranscoder.php:231
vendor/algo26-matthias/idna-convert/src/UnicodeTranscoder.php:339

**Comment by d00p** [comment]
We do not use algo26-matthias/idna-converter anymore for a few releases now. Seems like you are using git directly, so you should run `conposer install --no-dev` and it should be replaced and fixed.

**Comment by df8oe** [comment]
Yes, so it is. For my distribution (Arch Linux) there is no other way than using git directly :) I will remove it - and I think it must be removed at git, too. Thanks for your lightning-fast reaction.
