### ISSUE TITLE
[Feature request]: Database memory limit

### ISSUE THREAD

**Issue by mr-manuel** [Froxlor/Froxlor#877]
# Feature request

Would it be possible to set a per database memory limit to the customer?

For example:
I set a database memory limit of 64 MB for customer A and 256 MB for customer B.

* Customer A has 3 databases. Every database can use 64 MB, so the customer uses max. 192 MB of RAM.

* Customer B has 2 databases. Every database can use 265 MB, so the customer uses max. 512 MB of RAM.

**Comment by d00p** [comment]
I am not aware of any configuration or setting in mysql that would make this possible
