### ISSUE TITLE
API Example not working

### ISSUE THREAD

**Issue by samuelweirer** [Froxlor/Froxlor#879]
Hi,
for a project i have to use the API, so i copied the example, but i'm not able to get it work.
Here are my errors form the apache log:
`[Fri Sep 04 08:41:32.037192 2020] [fcgid:warn] [pid 12903] [client *ip*:14653] mod_fcgid: stderr: PHP Notice:  Trying to access array offset on value of type null in *domain*/FroxlorAPI.php on line 118
[Fri Sep 04 08:41:32.037268 2020] [fcgid:warn] [pid 12903] [client *ip*:14653] mod_fcgid: stderr: PHP Notice:  Trying to access array offset on value of type null in *domain*/FroxlorAPI.php on line 121
[Fri Sep 04 08:41:32.037292 2020] [fcgid:warn] [pid 12903] [client *ip*:14653] mod_fcgid: stderr: PHP Notice:  Trying to access array offset on value of type null in *domain*/FroxlorAPI.php on line 124
[Fri Sep 04 08:41:32.037313 2020] [fcgid:warn] [pid 12903] [client *ip*:14653] mod_fcgid: stderr: PHP Notice:  Trying to access array offset on value of type null in *domain*/FroxlorAPI.php on line 125
[Fri Sep 04 08:41:32.037334 2020] [fcgid:warn] [pid 12903] [client *ip*:14653] mod_fcgid: stderr: PHP Fatal error:  Uncaught TypeError: Return value of FroxlorAPI::getLastResponse() must be of the type array, null returned in *domain*/FroxlorAPI.php:159
[Fri Sep 04 08:41:32.037354 2020] [fcgid:warn] [pid 12903] [client *ip*:14653] mod_fcgid: stderr: Stack trace:
[Fri Sep 04 08:41:32.037373 2020] [fcgid:warn] [pid 12903] [client *ip*:14653] mod_fcgid: stderr: #0 *domain*/froxlor.php(16): FroxlorAPI->getLastResponse()
[Fri Sep 04 08:41:32.037402 2020] [fcgid:warn] [pid 12903] [client *ip*:14653] mod_fcgid: stderr: #1 {main}
[Fri Sep 04 08:41:32.037423 2020] [fcgid:warn] [pid 12903] [client *ip*:14653] mod_fcgid: stderr:   thrown in *domain*/FroxlorAPI.php on line 159
`
I just copied the example and added my API-Key and Secret.

# System information
* Froxlor version: 0.10.20
* Web server: apache2
* PHP-Version: 7.4

**Comment by d00p** [comment]
1. have you enabled API in the settings?
2. which of the test-scripts did you use, `create_customer.php` or `list_functions.php`?
3. if none of the above, please show your `froxlor.php` file (which you seem to have called)

For now, I'm calling the `list_functions.php` with my api key on php-7.4.9 just fine without any notices or errors

**Comment by samuelweirer** [comment]
Hi,
yes i've enabled API in settings (otherwise i won't be able to create an API-Key ;))
froxlor.php = list_functions.php
but i tried create_customer.php too - same issues.

**Comment by d00p** [comment]
did you adjust the api-credentials in froxlor.php (the FroxlorAPI-constructor) or in FroxlorAPI.php itself? the latter would be wrong...
Possibly, try to check what the content of the curl result is (https://github.com/Froxlor/Froxlor/blob/master/doc/example/FroxlorAPI.php#L113).
As said, I'm unable to reproduce so please provide more details

**Comment by samuelweirer** [comment]
Hi,
i set the credentials via constructor.
if i just execute the request() method an dunp the output it seems to work.
`object(FroxlorAPI)#1 (6) { ["host":"FroxlorAPI":private]=> string(31) "API_URL" ["api_key":"FroxlorAPI":private]=> string(64) "API_KEY" ["api_secret":"FroxlorAPI":private]=> string(128) "API_SECRET" ["last_error":"FroxlorAPI":private]=> string(0) "" ["last_header":"FroxlorAPI":private]=> array(2) { ["status"]=> NULL ["status_message"]=> NULL } ["last_body":"FroxlorAPI":private]=> NULL }`

If i can tast anything else, please let me know.

**Comment by d00p** [comment]
You're calling `request()` without any parameters???
I don't really get what you do there, the `list_functions.php` example is a perfect test and it works perfectly fine even on php-7.4 so please just give EXACT steps to reproduce, show your code, show what exactly you do.
Also for support please rather use the forum

**Comment by samuelweirer** [comment]
Here's my froxlor.php:
`    require_once ( "config.php" );
    require __DIR__ . '/FroxlorAPI.php';

    $fapi = new FroxlorAPI ( $froxlorhost, $froxlorkey, $froxlorsecret );
    // send request
    $fapi->request('Froxlor.listFunctions');

    // check for error
    if (! empty($fapi->getLastError())) {
    	echo "Error: " . $fapi->getLastError();
    	exit();
    }

    // get response of request
    $request = $fapi->getLastResponse();

    // view response data
    var_dump($request);`
as written, i'm using list_functions.php ....
in config.php the credentials are set as expected.

**Comment by d00p** [comment]
I'm doing exactly the same thing and it works just fine - no notices, nothing. You sure your `$froxlorhost` includes the `/api.php` at the end?

**Comment by samuelweirer** [comment]
Yes of course. https://FROXLOR-ADDRESS/api.php
Can I provide any other logs / informations for solving the problem?

**Comment by d00p** [comment]
If you openb `https://FROXLOR-ADDRESS/api.php` in a browser is the output like this one?

```json
{
    "status": 400,
    "status_message": "Invalid request",
    "data": null
}
```

**Comment by samuelweirer** [comment]
yes - exactly.

Michael Kaufmann <notifications@github.com> schrieb am Fr. 4. Sep. 2020 um
10:45:

**Comment by d00p** [comment]
No idea then sorry. You can email me to d00p@froxlor.org and if you want i can login to your server and check that for myself

**Comment by samuelweirer** [comment]
thanks, i've sent you an email with details.

**Comment by d00p** [comment]
As it turns out, the used froxlor-domain was added to the `/etc/hosts` file and pointing to `127.0.1.1` which on the CLI resulted in a 404 because the webserver did not have a vhost-configuration for that ip.
