### ISSUE TITLE
Api customer identification should be uniform

### ISSUE THREAD

**Issue by andlinger** [Froxlor/Froxlor#883]
The interfaces should be uniform with regard to the identification of the respective customer. For most requests you can specify "customerid" or "loginname". Unfortunately, for the following requests you can only specify "customerid". If you work with the "loginname" as identification, you have to load the customer first to get the mapping between "loginname" and "customerid".

 - Domains.update, Domains.add
 - Ftps.add, Ftps.update
 - SubDomains.add, SubDomains.delete, SubDomains.update

**Comment by d00p** [comment]
`Domains.add` and `Domains.update` = true,

`Ftps.add` and `Ftps.update` as well as `SubDomains.add`, `SubDomains.update` and `SubDomains.delete` use `ApiCommand::getCustomerData()` which, when called as admin accepts **customerid** as well as **loginname** for the customer

**Comment by andlinger** [comment]
Ahh, I didn't know that. Then the documentation is wrong.

**Comment by d00p** [comment]
i wouldn't say wrong, it's just missing the alternative `loginname` ;)

**Comment by andlinger** [comment]
Haha, you can also call it like that :)
