### ISSUE TITLE
PHP Notice: Trying to access array offset on value of type bool in lib/Froxlor/Cron/Http/Php/Fpm.php

### ISSUE THREAD

**Issue by knox** [Froxlor/Froxlor#886]
# Summary

There is a bug in Fpm.php which is triggered by the fact that the original admin user does not exist anymore.

# System information
* Froxlor version: 0.10.21-1
* PHP: 7.4

# Steps to reproduce

1.  Add one or more new admin user
2. Delete original admin user
3. Run cron script

# Expected behavior

1. Cron script does not throw errors

# Actual behavior

1. Cron script throws errors (see below)

# Log files/log entries
<pre>
root@srv:~# /usr/bin/php -q /var/www/froxlor/scripts/froxlor_master_cronjob.php --force
PHP Notice:  Trying to access array offset on value of type bool in /var/www/froxlor/lib/Froxlor/Cron/Http/Php/Fpm.php on line 230
PHP Notice:  Trying to access array offset on value of type bool in /var/www/froxlor/lib/Froxlor/Cron/Http/Php/Fpm.php on line 233
</pre>

# Cheap workaround
After every Froxlor update i apply this patch to calm the problem:
<pre>--- Fpm.php	2020-10-02 18:06:43.000000000 +0200
+++ Fpm.php.bak	2020-08-26 13:20:34.767672832 +0200
@@ -227,10 +227,10 @@
 				'PEAR_DIR' => Settings::Get('phpfpm.peardir'),
 				'TMP_DIR' => $this->getTempDir(),
 				'CUSTOMER_EMAIL' => $this->domain['email'],
-				'ADMIN_EMAIL' => $admin['email'],
+				'ADMIN_EMAIL' => $admin['email'] ?? 'root@srv.example.org',
 				'DOMAIN' => $this->domain['domain'],
 				'CUSTOMER' => $this->domain['loginname'],
-				'ADMIN' => $admin['loginname'],
+				'ADMIN' => $admin['loginname'] ?? 'admin',
 				'OPEN_BASEDIR' => $openbasedir,
 				'OPEN_BASEDIR_C' => '',
 				'OPEN_BASEDIR_GLOBAL' => Settings::Get('system.phpappendopenbasedir'),</pre>

**Comment by discordier** [comment]
You must never use a domain you don't own. Therefore, you must not use `srv.mydomain.com` but use a designated domain for documentation purposes, eg. `srv.example.org`.

PS: I am assuming you don't own `mydomain.com` and therefore may not grant the right to the Froxlor project to use it, sorry if I should be wrong on this.

**Comment by d00p** [comment]
So, did you delete the old admin using the new one? All the resources should be assigned to the new admin then. Can you tell what domain exactly that is? Is it the froxlor hostname or a customer domain? This is not really Fpm.php bug...that's just where an error occured due to a domain that is connected to a nonexisting admin via adminid

**Comment by d00p** [comment]
> You must never use a domain you don't own. Therefore, you must not use `srv.mydomain.com` but use a designated domain for documentation purposes, eg. `srv.example.org`.
> 
> PS: I am assuming you don't own `mydomain.com` and therefore may not grant the right to the Froxlor project to use it, sorry if I should be wrong on this.

This has nothing to do with the issue

**Comment by d00p** [comment]
I'm guessing it's the froxlor hostname because here in fcgid/fpm we used adminid #1 (fixed) for the super-user because it's not really intended or wise to remove it.

**Comment by discordier** [comment]
> This has nothing to do with the issue

I was only referring to his solution to use a domain of a random entity `'ADMIN_EMAIL' => $admin['email'] ?? 'root@srv.mydomain.com',` which is considered harmful.

**Comment by knox** [comment]
Thanks @d00p for taking this issue seriously.

> So, did you delete the old admin using the new one? 

Yes, i think so.

> All  the resources should be assigned to the new admin then.

In my database there is no record in panel_domains with adminid 1. Where else should i look? As far as i can remember the creation of the new admin users and deletion of the first one where done before any domains where added.

> Can you tell what domain exactly that is? Is it the froxlor hostname or a customer domain? 
I believe it occurs when the cron script is processing the froxlor vhost but i am not sure about this.

> This is not really Fpm.php bug...that's just where an error occured due to a domain that is connected to a nonexisting admin via adminid

I still belive this is a bug since there is no domain connected to adminid 1. And i think the fpm cron script should handle handle the situation gracefully.

@discordier

> You must never use a domain you don't own. Therefore, you must not use srv.mydomain.com

You must never comment on an _example_ that you don't understand. 🙄

**Comment by discordier** [comment]
> > You must never use a domain you don't own. Therefore, you must not use srv.mydomain.com
> 
> You must never comment on an _example_ that you don't understand.

Then you should maybe refreign from marking your examples as:

> Cheap **workaround**
> After every Froxlor update i apply this **patch to calm the problem:**

As stating them as "workaround" and "patch" might encourage other users to simply apply the "workaround" to their installations and then we have a problem, that's what "example.org" is for, examples and documentation. See [iana.org](https://www.iana.org/domains/reserved) for details.

**Comment by d00p** [comment]
> I still belive this is a bug since there is no domain connected to adminid 1. 

yes and no...technically, for froxlor its own hostname is owned by (super)admin with id = 1 - that's why it is hardcoded at some points.

> Well then it should not be possible at least with the GUI.

totally agree.

**Comment by knox** [comment]
Instead of hard-tying the froxlor vhost to any `adminid` wouldn't it be sufficient to use the first record from table `panel_admins` instead?

Do you think it's a good idea for me to create another record in `panel_admin` with `adminid` 1 to get rid of the lousy patching?

**Comment by d00p** [comment]
> wouldn't it be sufficient to use the first record from table panel_admins instead?

no. imagine you as (first) admin add a reseller with alsmost no permissions for anything. then "somehow" delete the superadmin...you won't be able to use froxlor 

> Do you think it's a good idea for me to create another record in panel_admins with adminid 1 to get rid of the lousy patching?

to "repair" the issue, you could add a new "default" admin (best directly into `panel_admins`). See https://github.com/Froxlor/Froxlor/blob/master/install/lib/class.FroxlorInstall.php#L411 for the defaults that the installation uses. You could then set the id to 1.

The long-term fix will be (as we do it for php-ini configs for example) to not allow deletion of the first/superuser admin
