### ISSUE TITLE
Unable to get Awstats to work with Nginx without patching lib/Froxlor/Cron/Http/Nginx.php

### ISSUE THREAD

**Issue by dvandal** [Froxlor/Froxlor#888]
Hi,

Awstats configuration is not generated in nginx config without removing _AND path LIKE CONCAT(b.documentroot, '%')_ from SQL query.

Also the awstats path is not accessible (404 error) without changing _location /awstats_ to location _^~ /awstats_

After doing theses small changes it works fine on my server.

**System information:**
Froxlor version: 0.10.22
PHP: 7.4
Nginx: 1.18.0

**Changes:**
```
--- froxlor/lib/Froxlor/Cron/Http/Nginx.php-ORG 2020-10-13 11:18:31.211909031 -0400
+++ froxlor/lib/Froxlor/Cron/Http/Nginx.php-PATCHED     2020-10-13 11:19:27.000448484 -0400
@@ -902,7 +902,6 @@
                        FROM `" . TABLE_PANEL_HTPASSWDS . "` AS a
                        JOIN `" . TABLE_PANEL_DOMAINS . "` AS b USING (`customerid`)
                        WHERE b.customerid = :customerid AND b.domain = :domain
-                       AND path LIKE CONCAT(b.documentroot, '%')
                ");
                Database::pexecute($result_stmt, array(
                        'customerid' => $domain['customerid'],
@@ -1042,10 +1041,10 @@

                if (Settings::Get('system.awstats_enabled') == '1') {
                        // awstats
-                       $stats_text .= "\t" . 'location /awstats {' . "\n";
+                       $stats_text .= "\t" . 'location ^~ /awstats {' . "\n";
                } else {
                        // webalizer
-                       $stats_text .= "\t" . 'location /webalizer {' . "\n";
+                       $stats_text .= "\t" . 'location ^~ /webalizer {' . "\n";
                }

                $stats_text .= "\t\t" . 'alias ' . $alias_dir . ';' . "\n";

```

**Comment by dvandal** [comment]
As shown in the SQL data, there is no domain in path value: /srv/customers/files/pls/awstats/

**Comment by d00p** [comment]
Hm, Well usually, there is by default a htpasswd lock for the webalizer/awstats data (so it's not open in the wild). Did you possibly just remove that dir protection entry?

**Comment by dvandal** [comment]
No, all my customers account have the default configuration automatically created under Directory protection with 

Username = Customer username
Path = /awstats/

**Comment by dvandal** [comment]
```
MariaDB [froxlor]> SELECT id,customerid,path,username,authname FROM panel_htpasswds WHERE customerid=8;
+----+------------+-----------------------------------+----------+-----------------+
| id | customerid | path                              | username | authname        |
+----+------------+-----------------------------------+----------+-----------------+
|  8 |          8 | /srv/customers/files/pls/awstats/ | pls      | Restricted Area |
+----+------------+-----------------------------------+----------+-----------------+
1 row in set (0.000 sec)

```

**Comment by d00p** [comment]
Okay, got you. thanks for the detailed infos, appreciated. If i remember correctly, this (`documentroot% like path`) was added because the documentroot of the domain in your case is `/srv/customers/files/pls/productionslynesarrazin.com/` so the vhost would not be responsible for protecting `/srv/customers/files/pls/awstats` and thus no htpasswd entry for it. My guess would be that this originated from times before the `per-domain-docroot-setting` maybe and /awstats is an alias now anyways so (at least for nginx) I think you are right and there should be a htpasswd protection added for the alias (because the domain can open domain.tld/awstats/).
Is the  directory protection working for you with your adjustments?

**Comment by dvandal** [comment]
With my adjustement it works fine without any issues, same Directory protection user for all customer domains which is fine for me.
