### ISSUE TITLE
API: Updating domain documentroot

### ISSUE THREAD

**Issue by andlinger** [Froxlor/Froxlor#892]
For updating the documentroot of a domain, the documentation says: "specify homedir of domain by specifying a directory (relative to customer-docroot), be aware, if path starts with / it it considered a full path, not relative to customer-docroot"

But for example, if I send the parameter "documentroot" with the value "web", "/web/" is saved as document root.

**Comment by d00p** [comment]
API directly as admin/reseller?

**Comment by andlinger** [comment]
Yes.
