### ISSUE TITLE
[Feature request] Honor template depenencies

### ISSUE THREAD

**Issue by dtugend** [Froxlor/Froxlor#896]
This will either be inefficient or not easy, so I can understand if it has to be rejected.

Let me give an _example_:
E.g. by default `{CUSTOMER_EMAIL}` is used in PHP config template for sendmail options.
Currently changing the customer email of in the customer settings will not cause the files to be updated accordingly (at least for PHP-FPM).

Not sure if it's still solvable without a dependency tree / graph.
(Everything that has variables that can change and has the output cached has that problem.)

**Comment by d00p** [comment]
Yes, this is correct. Changing user properties does not trigger a rebuild of config-files. It should be no problem to add a trigger there but I'd rather take a deeper look on the dependencies (so we do not trigger rebuild more than necessary) so i postpone this to 0.10.23 as 0.10.22 is due for tomorrow :)
