### ISSUE TITLE
Froxlor Let's Encrypt protection don't work if subdomain is only ipv6

### ISSUE THREAD

**Issue by Dryusdan** [Froxlor/Froxlor#898]
Hello o/

# Summary

I want generate a certificate for a subdomain only set with ipv6.
But when froxlor run task it return this message : 

```
[warning] Skipping Let's Encrypt generation for ipv6.dryusdan.net due to no system known IP address via DNS check
```

But the service is only on ipv6 : 

```
dig +short AAAA ipv6.dryusdan.fr
2a01:4f8:161:2269:8000:0:1337:c0de
dig +short A ipv6.dryusdan.fr
```

# System information
* Froxlor version: 0.10.21-1 (DB: 202009070)
* Web server: apache2
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: ...

# Steps to reproduce

1. Create a domain who listen only on ipv6 
2. Run task 1

# Expected behavior

1. Create a domain who listen only on ipv6 
2. Run task 1
3. Generate certificate

# Actual behavior

1. Create a domain who listen only on ipv6 
2. Run task 1
3. Protection block certificate generation

# Log files/log entries
stdout:
<pre>
[warning] Skipping Let's Encrypt generation for ipv6.dryusdan.net due to no system known IP address via DNS check
</pre>

Have a nice day

**Comment by d00p** [comment]
Is the IP added in froxlor under "ips and ports"?

**Comment by Dryusdan** [comment]
Yes, the ip is set.
![Capture d’écran 2020-11-06 à 13 21 41](https://user-images.githubusercontent.com/4410431/98365661-0721ab00-2033-11eb-8ae5-0cd439e513d1.png)

**Comment by Dryusdan** [comment]
(I actually disable protection to permit certificate generation)

**Comment by d00p** [comment]
Most likely this https://github.com/Froxlor/Froxlor/commit/6bf5eccc2477257b6c1760a3c3784ae7e0554ce0#diff-12127d7f8ff98985a34ecb92e3d0d51b29f96b24ebe1691245a32d4f60b23e44

you could patch the changes from `public static function gethostbynamel6()` or wait for the release this afternoon :)

**Comment by d00p** [comment]
> Yes, the ip is set.
> ![Capture d’écran 2020-11-06 à 13 21 41](https://user-images.githubusercontent.com/4410431/98365661-0721ab00-2033-11eb-8ae5-0cd439e513d1.png)

the ip in this image is not the same IP as the domain resolves to...

**Comment by Dryusdan** [comment]
I can wait afternoon :p 

Curieux, a dig return the good IP : 

```
root@froxlor-1 ~ # dig @127.0.0.1 AAAA ipv6.dryusdan.net

; <<>> DiG 9.11.5-P4-5.1+deb10u2-Debian <<>> @127.0.0.1 AAAA ipv6.dryusdan.net
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13485
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 5, ADDITIONAL: 3

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 1b8eb0621c762f36e89629dc5fa54f711965c4f57027c0cb (good)
;; QUESTION SECTION:
;ipv6.dryusdan.net.		IN	AAAA

;; ANSWER SECTION:
ipv6.dryusdan.net.	3600	IN	AAAA	2a01:4f8:192:25a:8000:0:1337:c0de

;; AUTHORITY SECTION:
dryusdan.net.		3600	IN	NS	ns3.dryusdan.fr.
dryusdan.net.		3600	IN	NS	blackpearl.dryusdan.fr.
dryusdan.net.		3600	IN	NS	ns.drycat.net.
dryusdan.net.		3600	IN	NS	ns2.dryusdan.fr.
dryusdan.net.		3600	IN	NS	ns1.dryusdan.fr.

;; ADDITIONAL SECTION:
ns.drycat.net.		3600	IN	A	144.76.89.4
ns.drycat.net.		3600	IN	AAAA	2a01:4f8:192:25a:8000:0:1337:c0de

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Nov 06 14:28:17 CET 2020
;; MSG SIZE  rcvd: 260
```

```
ansible@Mul:~$ dig AAAA ipv6.dryusdan.net

; <<>> DiG 9.11.5-P4-5.1+deb10u2-Debian <<>> AAAA ipv6.dryusdan.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10256
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ipv6.dryusdan.net.		IN	AAAA

;; ANSWER SECTION:
ipv6.dryusdan.net.	2447	IN	AAAA	2a01:4f8:192:25a:8000:0:1337:c0de

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: ven. nov. 06 14:29:14 CET 2020
;; MSG SIZE  rcvd: 74
```

Ho, I see another "problem", when I add an IP on config, it automaticaly add on ip of ns (the 10.10.11.2 is resolved from ns.drycat.fr
```
;; ADDITIONAL SECTION:
ns.drycat.net.		3600	IN	A	10.10.11.2
ns.drycat.net.		3600	IN	A	144.76.89.4
ns.drycat.net.		3600	IN	AAAA	2a01:4f8:192:25a:8000:0:1337:c0de
```

🤔

**Comment by d00p** [comment]
Well looks like 10.10.11.2 is one of your froxlor ip's and assigned to that domain? So of course it's added.

**Comment by Dryusdan** [comment]
It add on ip setting ( admin_ipsandports.php ) but not on this ip for ns.

**Comment by Dryusdan** [comment]
Thank for new version :)

**Comment by d00p** [comment]
So, I'm not able to reproduce that. IPv6/AAAA record is check before even v4 is checked so there must be an issue with resolving the domain correctly

**Comment by Dryusdan** [comment]
Resolver work (I have not problem with there).
But maybe a missconfig.
Problem is solved for me anyway 👍 
Thank for your help
