### ISSUE TITLE
IDN domains are not working

### ISSUE THREAD

**Issue by shantanoo** [Froxlor/Froxlor#899]
# Summary

When I try to add IDN domain (typed in Unicode), it fails with

Wrong Input in Field 'Domain'

URL of the server: https://demo.froxlor.org/

# System information
* Froxlor version: 0.10.22 (DB: 202009070)
* Web server: nginx

# Steps to reproduce

1. Login as admin on https://demo.froxlor.org/admin_domains.php
2. Create domain (https://demo.froxlor.org/admin_domains.php)
3. Add domain 'उदाहरण.भारत

# Expected behavior

1. Domain should be successfully added and should be visible in https://demo.froxlor.org/admin_domains.php

# Actual behavior

1. Unable to add domain. Failing with "Wrong Input in Field 'Domain'" message

**Comment by d00p** [comment]
when I copy exactly the domain-string you have posted i get `NAMEPREP: Prohibited input U+00000027`

**Comment by shantanoo** [comment]
Try the one written in bold. There might be extra single quote which is not required.

**उदाहरण.भारत**

**Comment by d00p** [comment]
it's fixed already :)

**Comment by shantanoo** [comment]
Oh, thanks. Missed the commit while reading.
