### ISSUE TITLE
Email validation bug

### ISSUE THREAD

**Issue by bloodhunterd** [Froxlor/Froxlor#904]
_Froxlor version_: **master**/**0.10.23.1**

I encountered an error on the panel setting page when I try to change the sender email address.

![image](https://user-images.githubusercontent.com/43681086/104047286-b456a200-51e1-11eb-8dc1-91da35fdbc1c.png)

The reason is that the **validateEmail** function uses **filter_var** that returns the filtered data on success. So in this case the email address as string.

![image](https://user-images.githubusercontent.com/43681086/104048566-b6b9fb80-51e3-11eb-8f89-daf5a8bddcf9.png)

The validateEmail function is called via detours by the **validateFormField** function.

![image](https://user-images.githubusercontent.com/43681086/104048946-5e372e00-51e4-11eb-9a20-73d747c23c9e.png)

The **standard_error** will be called, because the email address string isn't _identical_ to the required boolean **TRUE**.

I fixed this error already in my fork and I can provide a PR if you want.

**Comment by d00p** [comment]
Weird, return-value if `validateEmail()` hasnt changed since forever.

> I fixed this error already in my fork and I can provide a PR if you want.

Sure, thanks
