### ISSUE TITLE
PHP 8 login as admin fails

### ISSUE THREAD

**Issue by daboss84** [Froxlor/Froxlor#908]
# Summary

Using PHP 8 and trying to login as an admin presets the following error:
<pre>A database error occurred

SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
</pre>
# System information
* Froxlor version: 0.10.23.1 stable release
* Web server: apache2
* DNS server: Bind
* OS/Version: Debian Buster
* PHP 8.0.1 (via sury.org)

# Steps to reproduce

1. Switch the Froxlor Version from PHP 7.3 to PHP 8.0
2. Login as user/customer: works
3. Login as admin: the above error occures

# Expected behavior

1. Login works also as admin

# Actual behavior

1. See above
2. 
# Log files/log entries
syslog:
<pre>
Jan 21 18:49:17 v22019078708093018 froxlor[14548]: froxlor.NOTICE: viewed admin_index {"source":"admin","action":"30","user":"admin"} []
Jan 21 18:49:17 v22019078708093018 froxlor[14548]: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
Jan 21 18:49:17 v22019078708093018 froxlor[14548]: --- DEBUG: #0 /var/www/html/froxlor/lib/Froxlor/Database/Database.php(83): PDOStatement->execute() #1 /var/www/html/froxlor/lib/Froxlor/Database/Database.php(104): Froxlor\Database\Database::pexecute() #2 /var/www/html/froxlor/admin_index.php(72): Froxlor\Database\Database::pexecute_first() #3 {main}
</pre>

# How to solve

Adjust the params for the prepared statements exactly as required, for example (the file/line from the log)
<pre>
 $overview_stmt = Database::prepare("SELECT COUNT(*) AS `number_customers`,
                                SUM(`diskspace_used`) AS `diskspace_used`,
                                SUM(`mysqls_used`) AS `mysqls_used`,
                                SUM(`emails_used`) AS `emails_used`,
                                SUM(`email_accounts_used`) AS `email_accounts_used`,
                                SUM(`email_forwarders_used`) AS `email_forwarders_used`,
                                SUM(`email_quota_used`) AS `email_quota_used`,
                                SUM(`ftps_used`) AS `ftps_used`,
                                SUM(`subdomains_used`) AS `subdomains_used`,
                                SUM(`traffic_used`) AS `traffic_used`
                                FROM `" . TABLE_PANEL_CUSTOMERS . "`" . ($userinfo['customers_see_all'] ? '' : " WHERE `adminid` = :adminid "));
        $stmtParams = array();
        if($userinfo['customers_see_all'] != 1) {
                $stmtParams = [ 'adminid' => $userinfo['adminid'] ];
        }
        $overview = Database::pexecute_first($overview_stmt, $stmtParams); //array(
//              'adminid' => $userinfo['adminid']
//      ));
</pre>

But obviously there are many more similar lines of code :/

**Comment by d00p** [comment]
This should already be fixed with https://github.com/Froxlor/Froxlor/commit/9f13aa9a120f84eb0d4647af3285220d548b2e24 which will be in 0.10.24
