### ISSUE TITLE
Can't install Froxlor (Broken Pipe Error)

### ISSUE THREAD

**Issue by Animo16** [Froxlor/Froxlor#909]
# Summary

`
--2021-01-25 13:44:25--  https://deb.froxlor.org/froxlor.gpg
Resolving deb.froxlor.org (deb.froxlor.org)... 185.123.52.110, 2a10:ec2::185:123:52:110
Connecting to deb.froxlor.org (deb.froxlor.org)|185.123.52.110|:443... connected.
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
HTTP request sent, awaiting response... 200 OK
Length: 2018 (2.0K)
Saving to: 'STDOUT'

-                               0%[                                                  ]       0  --.-KB/s    in 0s

Cannot write to '-' (Broken pipe).
`

# System information
* Froxlor version: ---
* Web server: apache2
* DNS server: Bind
* POP/IMAP server: ---
* SMTP server: ---
* FTP server: ---
* OS/Version: Debian 10.7 Minimal

**Comment by d00p** [comment]
See error message: 
**E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation**
