### ISSUE TITLE
[Feature request] API Search IN Operator / #mail_virtual & #panel_domains.description Field

### ISSUE THREAD

**Issue by GittyLover** [Froxlor/Froxlor#910]
Dear d00p,

i would like to have a **new database-field** in table #mail_virtual like "**userid**" (int11) and get/set/search it via API Parameter (like Emails.listing -> param[sql_search=>userid=X] and Emails.add -> param[userid=>X]) please.

So i can build a **API based web-tool** with the possibility, to read a "**individual**" adress-list and add/del adresses for every user from the "**same customer**". The userid would be defined by my web-tool.

Example:

User "Tony Test" (my userid = 1) can view/edit/add/etc only his adresses, like...
- tony.test@customer-xxx.net
- tony.xxx@customer-xxx.net
- tonys@customer-xxx.net

User "Eric Example" (my userid = 2) only like...
- eric.example@customer-xxx.net
- ericz@customer-xxx.net
- exampler@customer-xxx.net

This would be great! :)

And that would be great too: New description fields with API access in...

#mail_virtual.description
#panel_domains.description

Thousand thanks and best regards!

**Comment by d00p** [comment]
I aggree on the description fields even if (currently) not used in the frontend. but a `userid` field which is not part of froxlor? **If** we were to add some foreign-key/custom field we would need to do that for all the entities but it still dont see this as part of froxlor.

It sounds to me like you have some customers outside of froxlor who are mapped to some email addresses but share the same domain? Depending on the amount why not just add another table that maps your users to froxlor email addresses. Then read that in for your user and use `Emails.get()` for each of the entries

**Comment by GittyLover** [comment]
Hi d00p,

thanks for you fast responce!

> you have some customers outside of froxlor who are mapped to some email addresses but share the same domain?

Thats right and yes, the usage of an extra table is an option.

In this case it would be very nice, if i can use the API-Function `Emails.listing()` **sql_search** parameter with a **commaspaced-list of email-address-id's** ala [op=>'in',value=>'2,6,8'] ...  _like: WHERE id IN (2,6,8)_.

Is that possible?

Best regards

**Comment by d00p** [comment]
If you like, you could test the following patch which should enable you to do SQL IN-clause.

One tiny note: the value-parameter needs to be an array, not a comma-separated list of values, e.g.

```
[
    op => 'in',
    value => [
        2,
        6,
        8
    ]
]
```

```diff
diff --git a/lib/Froxlor/Api/ApiCommand.php b/lib/Froxlor/Api/ApiCommand.php
index 77fc415e..f561ccf8 100644
--- a/lib/Froxlor/Api/ApiCommand.php
+++ b/lib/Froxlor/Api/ApiCommand.php
@@ -310,6 +310,13 @@ abstract class ApiCommand extends ApiParameter
                                } elseif (in_array($valoper['op'], $ops)) {
                                        $condition .= $field . ' ' . $valoper['op'] . ':' . $cleanfield;
                                        $query_fields[':' . $cleanfield] = $valoper['value'] ?? '';
+                               } elseif (strtolower($valoper['op']) == 'in' && is_array($valoper['value']) && count($valoper['value']) > 0) {
+                                       $condition .= $field . ' ' . $valoper['op'] . ' (';
+                                       foreach ($valoper['value'] as $incnt => $invalue) {
+                                               $condition .= ":" . $cleanfield . $incnt . ", ";
+                                               $query_fields[':' . $cleanfield . $incnt] = $invalue ?? '';
+                                       }
+                                       $condition = substr($condition, 0, - 2) . ')';
                                } else {
                                        continue;
                                }
```

**Comment by GittyLover** [comment]
Hi d00p,

cool, thanks! :) 

My test with `Emails.listing()` returns this error status_message...

> SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous

Best regards

**Comment by d00p** [comment]
there are joins with other tables, use `m.id`

**Comment by GittyLover** [comment]
Hi d00p,

wonderful, it works. :)

Will the in-operator (and perhaps the description fields) be implemented in version 0.10.25?

Best regards

**Comment by d00p** [comment]
Code has been written - it will be in the next release :) I'll see what we can do about the description fields

**Comment by GittyLover** [comment]
Hi d00p,

any news for #mail_virtual.description #panel_domains.description in 0.10.25?

#mail_virtual.description would be very nice to describe what the e-mail address is for.

Best regards

**Comment by d00p** [comment]
Might be able to add the fields for the next release yes, frontend/gui not (yet).
