### ISSUE TITLE
PHP-Konfigurationen Domains anpassen

### ISSUE THREAD

**Issue by awshowo** [Froxlor/Froxlor#911]
Hallo,

bei mir werden Domain in der PHP Default Config gelistet obwohl PHP für diesen User und für die Domain deaktiviert ist.
Wäre super wenn da noch überprüft wird ob die Domain überhaupt PHP benutzt.

Danke

**Comment by d00p** [comment]
well it's bascially just a listing which domain is set to which php-fpm config  - nothing really regarding whether php is enabled or not.
I get your point, it's a bit of pointless showing domains in that listing that are not using php
