### ISSUE TITLE
[Feature request] API Customers.listing with cumulate mboxsize_used

### ISSUE THREAD

**Issue by GittyLover** [Froxlor/Froxlor#912]
Dear d00p,

is it possible to extent API `Customers.listing` with **mboxsize_used**?

It contains a cumulate mailspace usage (like `Emails.listing` > mboxsize) from each customer.

This would be nice, to display this in fast way in a table sheet like...

![screen](https://user-images.githubusercontent.com/28319729/107875146-7e7e9a80-6ebe-11eb-9d1c-6b09481d38f5.png)

Thanks and best regards!

**Comment by d00p** [comment]
That should be possible, nice idea :)
