### ISSUE TITLE
Froxlor lost compatibile with openrc

### ISSUE THREAD

**Issue by tczaude** [Froxlor/Froxlor#914]
As a rule of thumb: before reporting an issue

In last version in Funtoo.

i change all services when i found changed options for systemd service / systemctl change to /etc./init.d/....

and when i run 

`/usr/bin/php -q /var/www/froxlor/scripts/froxlor_master_cronjob.php --force --debug`

i recive:

```
[information] nginx::writeConfigs: rebuilding /etc/httpd/conf.d/
[information] Froxlor\Cron\Http\NginxFcgi::reload: running service php7.3-fpm restart
sh: service: command not found
[information] Froxlor\Cron\Http\NginxFcgi::reload: reloading Froxlor\Cron\Http\NginxFcgi
[notice] Checking system's last guid
```

i cannot determine where stay service command

**Comment by d00p** [comment]
Sign in as admin -> PHP-FPM versions -> edit entries, adjust `php-fpm restart command` as needed

**Comment by tczaude** [comment]
Thanks. I resolve this.
