### ISSUE TITLE
[Issue?] API Customers.update - why is company required?

### ISSUE THREAD

**Issue by GittyLover** [Froxlor/Froxlor#915]
Dear d00p,

if i de/activate a customer via API `Customers.update` + **customer-id**, why is the delivery of the "**company**" name **required**?...

> Requested parameter "company" could not be found for "Customers:update"

Make this sense? I dont want to change the "company" name, only set deactivated=1 ;)

Thanks and best regards!

ps. i use froxlor 0.10.22

**Comment by d00p** [comment]
`name` and `firstname` OR `company` must be set for the customer - just to check for potential bug there, which of these fields are filled for the customer you want to update?

**Comment by d00p** [comment]
If so, please test the following patch:

```diff
diff --git a/lib/Froxlor/Api/Commands/Customers.php b/lib/Froxlor/Api/Commands/Customers.php
index 1d9cad29..4c1772d8 100644
--- a/lib/Froxlor/Api/Commands/Customers.php
+++ b/lib/Froxlor/Api/Commands/Customers.php
@@ -873,7 +873,7 @@ class Customers extends \Froxlor\Api\ApiCommand implements \Froxlor\Api\Resource
                        $email = $this->getParam('email', true, $idna_convert->decode($result['email']));
                        $name = $this->getParam('name', true, $result['name']);
                        $firstname = $this->getParam('firstname', true, $result['firstname']);
-                       $company_required = (! empty($name) && empty($firstname)) || (empty($name) && ! empty($firstname)) || (empty($name) && empty($firstname));
+                       $company_required = empty($result['company']) && (! empty($name) && empty($firstname)) || (empty($name) && ! empty($firstname)) || (empty($name) && empty($firstname));
                        $company = $this->getParam('company', ($company_required ? false : true), $result['company']);
                        $street = $this->getParam('street', true, $result['street']);
                        $zipcode = $this->getParam('zipcode', true, $result['zipcode']);
```

ps: you should upgrade to 0.10.24 :)

**Comment by GittyLover** [comment]
Dear d00p,

> name and firstname OR company must be set for the customer

hmm, also when i want to **update** an existing customer?

I would like only change the deactivated parameter only with customer-id, nothing else.

Thanks and best regards!

ps. i waiting for 0.10.25 first, because i must order that and can't do updates by myself.

**Comment by d00p** [comment]
> hmm, also when i want to update an existing customer?

no that's why I was asking the questions and provided a patch

> ps. i waiting for 0.10.25 first, because i must order that and can't do updates by myself.

There is a release once a month...

**Comment by GittyLover** [comment]
Dear d00p,

ahh ok, i have change the code (see at the bottom) and the responce is still...

> Requested parameter "company" could not be found for "Customers:update"

Thanks for your info and best regards!

![screen](https://user-images.githubusercontent.com/28319729/107991168-55e9c400-6fd6-11eb-8762-2300a56ecbb2.png)

**Comment by d00p** [comment]
Please answer the question from https://github.com/Froxlor/Froxlor/issues/915#issuecomment-779409198

**Comment by GittyLover** [comment]
ups, sry: `company` is filled (name and firstname is empty)

**Comment by d00p** [comment]
> ups, sry: `company` is filled (name and firstname is empty)

well then `empty($result['company'])` should be `false` and `empty($name) && empty($firstname)` is `true` which leads to
`$company_required = false && true` which then translates to `false` at the end and therefore the field should not be required anymore

**Comment by GittyLover** [comment]
now it works, after added the brackets in my bottom screen. :)
do you add this in a coming release?

thank you for your help! 

![screen](https://user-images.githubusercontent.com/28319729/107998011-76b91600-6fe4-11eb-9630-cab0560d8d04.png)

**Comment by d00p** [comment]
> do you add this in a coming release?

yes
