### ISSUE TITLE
Error with php8.0 (In index.php:117 and lib/Froxlor/UI/Response.php:55)

### ISSUE THREAD

**Issue by cscholz** [Froxlor/Froxlor#916]
# Summary

I've replaced all php7.4 packages by php8.0 packages.

- PHP-FPM configuration in froxlor have been changed to php8.0
- Configuration files have been rebuild (forced by cron)

- Login page of froxlor is loaded.
- Login as normal user is working
- Login as **admin** failes

# System information
* Froxlor version: 0.10.24
* Web server: nginx 1.14.2-2+deb10u3
* OS/Version: Debian GNU/Linux 10 (buster)
* php8.0-fpm 8.0.2-2+0~20210212.11+debian10~1.gbpc6d49a (sury.org)

# Expected behavior

1. login as admin should work

# Actual behavior

After entering admin credentials following error is shown

<pre>PHP warning/error
#2 Trying to access array offset on value of type bool

index.php:117

PHP warning/error
#2 Cannot modify header information - headers already sent by (output started at
/.../froxlor/lib/Froxlor/PhpHelper.php:138)

lib/Froxlor/UI/Response.php:55</pre>

# Log files/log entries
syslog:
<pre>
no specific entry logged
</pre>

**Comment by d00p** [comment]
I cannot reproduce this (demo.froxlor.org runs on latest 8.0.2). Following the error the following patch should do the trick, would you be so kind to check whether it does or not?

```diff
d00p@adc-e15:~/SynologyDrive/Projekte/Froxlor_2013/Master$ git diff
diff --git a/index.php b/index.php
index 8f5b4c8b..a8c33ea3 100644
--- a/index.php
+++ b/index.php
@@ -114,7 +114,7 @@ if ($action == '2fa_entercode') {
                ));
                $row = $stmt->fetch(PDO::FETCH_ASSOC);
 
-               if ($row['customer'] == $loginname) {
+               if ($row && $row['customer'] == $loginname) {
                        $table = "`" . TABLE_PANEL_CUSTOMERS . "`";
                        $uid = 'customerid';
                        $adminsession = '0';
```

**Comment by cscholz** [comment]
Yes, the fix is working!
Paypal donation transaction code: 20532613456044318

**Comment by d00p** [comment]
Perfect, thanks a lot :)
