### ISSUE TITLE
[Feature request] API Access to #mail_user.imap

### ISSUE THREAD

**Issue by GittyLover** [Froxlor/Froxlor#921]
Dear d00p,

is it possible to extent API `Emails.listing` and `EmailAccounts.update` with **#mail_user.imap** access?

This would be nice to set a mailbox in-/active.

Thanks and best regards!

**Comment by d00p** [comment]
"Problem" is, the imap/pop3 flag is set on a per customer base and should not be editable by the customer itself (duh). As there is currently no admin-listing for all email accounts to edit them seperatly this is a challenge.

We could add it to the API method and maybe later enhance the interface for the admin/reseller to make it possible to edit this on a per-email-account base from within the panel

**Comment by d00p** [comment]
Smaller problem: if you disable a customer as admin and later re-enable him, all its email accounts will be activated again so account-specific settings will be overridden by this action
