### ISSUE TITLE
"No new certificates" obwohl expirationdate < Now() 

### ISSUE THREAD

**Issue by drexlma** [Froxlor/Froxlor#922]
Dieses Problem hab ich öfter auf mehreren (min. 3 Server, min 7 Mal aufgetreten.)  Froxlor-Hosting-Servern. In der Vergangenheit hab ich die Zertifikate, nach dem die Kunden wütend angerufen haben, einfach ausm Backend gelöscht. Ein anderer hatte hier schonmal so n Bug gemeldet jedoch wurde das nur abgetan. 

Problem: 
SSL Zertifikate werden nicht aktualisiert obwohl sie abgelaufen sind 

Hier das die Datenbank
<img width="242" alt="Bildschirmfoto 2021-03-02 um 08 28 27" src="https://user-images.githubusercontent.com/7121202/109613512-8c285700-7b31-11eb-863c-b84be6f69aeb.png">

Hier die Ansicht in der GUI
<img width="723" alt="Bildschirmfoto 2021-03-02 um 08 31 06" src="https://user-images.githubusercontent.com/7121202/109613610-ac581600-7b31-11eb-8bc5-b6ee23492c4e.png">

Hier auch wirklich das es abgelaufen ist
<img width="667" alt="Bildschirmfoto 2021-03-02 um 08 36 38" src="https://user-images.githubusercontent.com/7121202/109614155-8bdc8b80-7b32-11eb-8535-06575f828245.png">

Ja Server ist komplett neugestartet, Cache geleert, etc, aber selbst dann hätte es auch ohne funktionieren müssen. 
Naja Cronjob läuft aber es geht trotzdem nichts. 

Und ja wir haben heute den 2. März gegen 8 Uhr :) und meine PC Zeit ist auch korrekt  und meine Serverzeit ist auch korrekt
Shell: _Tue 02 Mar 2021 08:40:29 AM CET_ 
PHP: _02.03.2021 08:40:54_

Bei Manuellen Ausführen kommt folgendes:
(kein Force, damit funktioniert es leider auch ab und an nicht) 
php /var/www/froxlor/scripts/froxlor_master_cronjob.php --letsencrypt --debug

(Alte Froxlor Version)
<pre>
[information] No new certificates or certificate updates found
[notice] Checking system's last guid
You have new mail in /var/mail/root
</pre>

(aktuelle Froxlor Version)
<pre>
[information] Checking for LetsEncrypt client upgrades before renewing certificates:
[Tue Mar  2 08:19:21 CET 2021] Already uptodate!
[Tue Mar  2 08:19:21 CET 2021] Upgrade success!
[Tue Mar  2 08:19:21 CET 2021] Installing cron job
15 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
[information] No new certificates or certificate updates found
[notice] Creating passwd file
[notice] Writing 15 entries to passwd file
[notice] Succesfully wrote passwd file
[notice] Creating group file
[notice] Writing 4 entries to group file
[notice] Succesfully wrote group file
[notice] Creating shadow file
[notice] Writing 15 entries to shadow file
[notice] Succesfully wrote shadow file
[notice] Checking system's last guid
</pre>

So also,... woran kann das liegen?

**Comment by drexlma** [comment]
Bitte irgend ein Notfall Mechanismus einbauen. Hab nun die Zertifikate in der Froxlor GUI gelöscht  ... nun klappt es direkt.

**Comment by d00p** [comment]
Support bitte im Forum. Funktioniert bei mir seit Ewigkeiten wunderbar und alle Zertifikate werden normal rechzeitig erneuert.

**Comment by drexlma** [comment]
läuft bei dir ;)
