### ISSUE TITLE
SSL vhost config empty

### ISSUE THREAD

**Issue by Af0x** [Froxlor/Froxlor#924]
Hello,
adding a domain like so
```
DocumentRoot: https://some.domain.tld
Enable usage of SSL: Yes
SSL redirect: No
Use Let's Encrypt: Yes
HTTP2 support: Yes
Include non-SSL vHost-settings in SSL-vHost: No
```
results in Apache ssl_vhost-config being empty.

Best regards,
Af0x

**Comment by d00p** [comment]
Does the cronjob output anything when called with `--force --debug`?

**Comment by d00p** [comment]
Also, Domain (as admin) or SubDomain (as customer)?

**Comment by Af0x** [comment]
It seems the cert wasn´t present although that domain existed for ages. After I ran the cron, the config got updated.

**Comment by d00p** [comment]
I just did exactly what you've wrote (as admin) and the vhost was being generated just fine (of course it uses fallback ssl certificates as long as lets encrypt did not generate its own) but it's not empty

**Comment by Af0x** [comment]
I think I added it as admin but as said it´s long ago. I really don´t know why the cert and config wasn´t created by cron.
