### ISSUE TITLE
[Feature request] API: Use of #panel_domains.deactivated

### ISSUE THREAD

**Issue by GittyLover** [Froxlor/Froxlor#925]
Dear d00p,

what is the DB Table-Field **#panel_domains.deactivated** for?

It is possible to de/activate via API a domain and within its all addresses?

Thanks and best regards!

_ps. thanks for the new 25er release! :)_

**Comment by d00p** [comment]
There is not panel_domain.deactivated... do you mean the new description field? See corresponding issue #910 

PS: please dont use the issue tracker for questions like that, that's what the forum is for

**Comment by GittyLover** [comment]
Dear d00p,

i mean the panel_domain.deactivated from here...
/Froxlor/Froxlor/blob/master/install/froxlor.sql
...see Screen....

<img width="495" alt="screen" src="https://user-images.githubusercontent.com/28319729/110208003-dfc6d780-7e86-11eb-851f-e7492fba96e8.png">

best regards

**Comment by d00p** [comment]
Ah, didn't even see it when checking ;) This is not in use anywhere, couldn't find anything regarding this in froxlor history, so this must originate from syscp...

**Comment by GittyLover** [comment]
ok :)

> It is possible to de/activate via API a domain and within its all addresses?

Would this be possible in principle?

**Comment by d00p** [comment]
Yes, might be useful to be able to deactivate/activate single domains (as admin/reseller).

**Comment by GittyLover** [comment]
Dear d00p,

OK, the this issue is now a feature request please.

Because i have users they would to try sometimes a other external mailserver and want to easy switch back if the test fails. This would be great. :)

Thanks and best regards

**Comment by d00p** [comment]
You know you can disable mail abilities for specific domains already right? ;)either via Webinterface as admin or via API `isemaildomain` parameters

**Comment by GittyLover** [comment]
Dear d00p,

i have test it:
if i set isemaildomain=0, then all addresses of the domain will be deleted and lost.

But this is exactly what I would like to prevent, in order to switch back again.

Thanks and best regards

**Comment by d00p** [comment]
Oh sorry, yes, you're totally right, this is not what you wanted - one more reason to make panel_domains.deactivated count :)

**Comment by GittyLover** [comment]
:) then this is now a feature request. thanks in advise!

**Comment by jucajuca** [comment]
I would also like to deactivate domains. Thanks for the feature request.

**Comment by d00p** [comment]
postponing to 0.10.29 - this has a lot of impact on many different parts

**Comment by d00p** [comment]
Ran into a view issues as e.g. in Domains.listing() we already use the `deactivated` field from `panel_customers` - even more adjustments are necessary
