### ISSUE TITLE
origin CNAME and other RR check

### ISSUE THREAD

**Issue by rseffner** [Froxlor/Froxlor#927]
# Summary # Steps to reproduce # Expected behavior # Actual behavior
If there is an origin MX (@ IN MX 10 x.y.z) I'm not able to set up an origin CNAME (@ IN CNAME x.y.z) - what's correct.
But If there is an origin CNAME, I'm able to add an origin MX an bind nameserver fails to reload this zone.
CNAMEs should only be used for subdomains (instead of breaking other RR or SOA).

# System information
* Froxlor version: 0.10.24
* DNS server: Bind
* OS/Version: Debian 10

# Log files/log entries
15-Mar-2021 12:20:26.198 general: error: dns_master_load: /etc/bind/domains/s***.zone:11: .de: CNAME and other data
15-Mar-2021 12:20:26.198 general: error: zone solarenergie.de/IN: loading from master file /etc/bind/domains/s***.de.zone failed: CNAME and other data
15-Mar-2021 12:20:26.198 general: error: zone s***.de/IN: not loaded due to errors.

**Comment by d00p** [comment]
> CNAMEs should only be used for subdomains (instead of breaking other RR or SOA).

should yes, but still it's allowed. So froxlor needs to fix the validation.
