### ISSUE TITLE
Don't try to chown /dev/null

### ISSUE THREAD

**Issue by quthla** [Froxlor/Froxlor#934]
When logfiles for domain are disabled, Froxlor will try to chown /dev/null which fails and prints warnings like

PHP Warning:  chgrp(): Operation not permitted in... 

https://github.com/Froxlor/Froxlor/blob/master/lib/Froxlor/Cron/Http/Apache.php#L791

**Comment by nachtgeist** [comment]
This is a wrong fix.

Now, logs don't get created/chown'd/chgrp'd at all in case logging is enabled and not piped.

Instead, an additional check for equality of $error_log/$access_log against "/dev/null" must be implemented.
