### ISSUE TITLE
Trying to access array offset on value of type bool in .../lib/Froxlor/Dns/Dns.php on line 56

### ISSUE THREAD

**Issue by rseffner** [Froxlor/Froxlor#936]
# Summary
Unfortunately, the phenomenon cannot be reproduced. I suspect there is a lack of validation of data that humans can enter into the DNS editor. 

# System information
* Froxlor version: 0.10.25
* Web server: apache2
* DNS server: Bind
* OS/Version: debian 10

# Steps to reproduce
Sorry, I got only ONE mail by the cron Job and don't know wicht user changes which value using the froxlor ui.

# Expected behavior
No PHP-errors

# Actual behavior
ONE TIME this error. Not sure if user changes his value again or if error occurs only one time.

# Log files/log entries
nothing found in binds logfiles about broken zones.

**Comment by d00p** [comment]
So, on this line the `isbindomain` field of the domain is checked, which is always true for froxlorvhost so it must come from a customer-domain for which all fields from the tables are selected so it's definetly there, only time the array can be a boolean-type is when the SQL-select returned nothing.
Possibly a very random state where the cron tries to use the domain but it had been removed from the database after the cronjob was being started
