### ISSUE TITLE
Force database update

### ISSUE THREAD

**Issue by tczaude** [Froxlor/Froxlor#937]
Hi 
I have strange problem 
I Clic update in froxlor panel and files show mi new version but database not updated 
How i can force update database ?

I have this problem when i update from version 21 to version 25

**Comment by d00p** [comment]
Well what exactly happens when you proceed with update via webinterface? Empty page? error message? Success message but still not updated? How exactly have you updated your files? debian package? archive? git?

Also, generally, please use our forum for support

**Comment by tczaude** [comment]
Ok i close this and move to forum.
