### ISSUE TITLE
Installation problem: "Access denied for user 'root'@'localhost'"

### ISSUE THREAD

**Issue by dpauli** [Froxlor/Froxlor#939]
Hi guys,

while installing the latest version with running MySQL 8 there is a problem giving the root MySQL user to Froxlor.

Its not possible to connect remotly via outer SSH scope to MySQL root user, its a security feature.

How can I fix this?

Best regards,
David

**Comment by d00p** [comment]
https://forum.froxlor.org/index.php?/topic/13916-setup-proccess-failed-access-denied-for-user-rootlocalhost/#comment-35113

**Comment by dpauli** [comment]
That does not fully work with MySQL 8 and is MySQL 5.x standard. In MySQL 8 you should do this:

```mysql
> UPDATE mysql.user SET plugin = 'mysql_native_password' WHERE User = 'root';
> SET PASSWORD FOR 'root'@'localhost' = '<YOUR ROOT PASSWORD>';
> FLUSH PRIVILEGES;
```

**Comment by dpauli** [comment]
That does not fully work with MySQL 8 and is MySQL 5.x standard. In MySQL 8 you should do this:

```mysql
> ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '<PASSWORD>';
> FLUSH PRIVILEGES;
```
