### ISSUE TITLE
access control for awstats

### ISSUE THREAD

**Issue by sebastian-schmid** [Froxlor/Froxlor#942]
# Feature Request

In the latest version of froxlor (0.10.26) if awstats is configured the awstats for a website will be accessible to everyone by accessing domain.xyz/awstats

I think it should be not accessible to everyone by default. I would prefer to only display the domains awstats within froxlor panel or at least it should require a user/password via .htaccess.

Any other ideas to achieve that?

# Expected behavior

1. awstats not public accessible by default
2. best case only accessible within froxlor panel (so secured by froxlor login)
3. at least hidden behind user/password via .htaccess

# Actual behavior

1. awstats are public accessible domain.xyz/awstats
2. did not find a way to configure it in a way that all awstats for all domains are not public and only accessible for the domain customer

**Comment by d00p** [comment]
By default, when a new customer is added, the access for /webalizer or /awstats (regarding what is used) is restricted via "Directory protection"  with the customers login credentials, see https://github.com/Froxlor/Froxlor/blob/master/lib/Froxlor/Api/Commands/Customers.php#L653

There were absolutely no changes in this area from 0.10.25 to 0.10.26 - did you maybe switch from webalizer to awstats or vice-versa with already existing customers/domains?

**Comment by d00p** [comment]
Ah, yes, this change is not yet handled (because the old folder still exists and should still be protected) and froxlor cannot know whether a customer just named a folder "awstats" for his own use and thus cannot simply create a protection for it after a change.

You might be able to use the API to loop through all customers and create a directory protection for /awstats for them automatically calling `DirProtections.add()`.

**Comment by sebastian-schmid** [comment]
Ok, I will try that, but it's not possible to set it to the users password that way or do I miss something?

**Comment by d00p** [comment]
No, the passwords are hashed. And the hashes for htpasswd differ from the hashes from panel_customers. What could be possible is copying the password-hash from panel_htpasswds for the _old_ entries (protecting /webalizer) and replace the newly added entries that protect /awstats with the old hash

**Comment by sebastian-schmid** [comment]
I cloned the database entries and set the path to /user/path/awstats/ and recreated all configs, did the job, thank you :+1:
