### ISSUE TITLE
override default rrecords (ftp,www,pop,imap,mail) with other types than A rrecord

### ISSUE THREAD

**Issue by rseffner** [Froxlor/Froxlor#944]
# Summary # Steps to reproduce # Actual behavior
If you use froxlors DNS abilities an rrset of subdomains like www,ftp,mail and so on is created for each domain pointing as A record to the froxlor server.
Admin is able to override thes by adding A records using the DNS-editor for this domains.

If you add e.g an CNAME record for such an subdomian this will be additionally created instead of overriding froxlors default.
This results in bind warnings and not updating/loading the zone file.

# System information
* Froxlor version: 0.10.26
* Web server: apache2
* DNS server: Bind
* OS/Version: Debian 10

# Expected behavior

Adding an A, or CNAME record for one of the froxlor default subdomains should override the default A record. Some more logic is needed to cover IPv6 too.
- if Server is IPv6-only default should be also an AAAA, so setting manually an AAAA or CNAME should also override
- dual-stack-servers may ask admin overriding only by AAAA or A if the other IP-protocol should also be set

# Log files/log entries
26-May-2021 15:00:33.138 general: error: dns_master_load: /etc/bind/domains/****.de.zone:8: imap.****.de: CNAME and other data
26-May-2021 15:00:33.138 general: error: zone ****.de/IN: loading from master file /etc/bind/domains/****.zone failed: CNAME and other data
26-May-2021 15:00:33.138 general: error: zone ****.de/IN: not loaded due to errors.

**Comment by rseffner** [comment]
Maybe in /lib/Froxlor/Dns/Dns.php add an "isemaildomain"-case and add imap,pop3,mail,smtp into the "foreach"-loop.

**Comment by d00p** [comment]
aside that, you know you can disable the creation of these "mail-related" entreies in `Settings -> Nameserver -> Create mail-, imap-, pop3- and smtp-"A record" also with MX-Servers set`

**Comment by rseffner** [comment]
But thats a global setting an not per Domain. Usually I like the auto-generated subdomains but sometimes I need to override this.

**Comment by d00p** [comment]
understandable - just wanted to point out that this option exists :)

**Comment by d00p** [comment]
Can you verify that the following patch solves the issue?

```diff
diff --git a/lib/Froxlor/Dns/Dns.php b/lib/Froxlor/Dns/Dns.php
index fa95586e..02bc7fb3 100644
--- a/lib/Froxlor/Dns/Dns.php
+++ b/lib/Froxlor/Dns/Dns.php
@@ -190,12 +190,26 @@ class Dns
                                '@',
                                'www',
                                '*'
-                       ] as $crceord) {
-                               if ($entry['type'] == 'CNAME' && $entry['record'] == '@' && (array_key_exists(md5($crceord), $required_entries['A']) || array_key_exists(md5($crceord), $required_entries['AAAA']))) {
-                                       unset($required_entries['A'][md5($crceord)]);
-                                       unset($required_entries['AAAA'][md5($crceord)]);
+                       ] as $crecord) {
+                               if ($entry['type'] == 'CNAME' && $entry['record'] == '@' && (array_key_exists(md5($crecord), $required_entries['A']) || array_key_exists(md5($crecord), $required_entries['AAAA']))) {
+                                       unset($required_entries['A'][md5($crecord)]);
+                                       unset($required_entries['AAAA'][md5($crecord)]);
                                }
                        }
+                       // also allow overriding of auto-generated values (imap,pop3,mail,smtp) if enabled in the settings
+                       if (Settings::Get('system.dns_createmailentry')) {
+                           foreach (array(
+                               'imap',
+                               'pop3',
+                               'mail',
+                               'smtp'
+                           ) as $crecord) {
+                               if ($entry['type'] == 'CNAME' && $entry['record'] == $crecord && (array_key_exists(md5($crecord), $required_entries['A']) || array_key_exists(md5($crecord), $required_entries['AAAA']))) {
+                                   unset($required_entries['A'][md5($crecord)]);
+                                   unset($required_entries['AAAA'][md5($crecord)]);
+                               }
+                           }
+                       }
                        $zonerecords[] = new DnsEntry($entry['record'], $entry['type'], $entry['content'], $entry['prio'], $entry['ttl']);
                }
```

**Comment by d00p** [comment]
ah darn it, wrong issue referenced :p
