### ISSUE TITLE
acme.sh changes default CA to ZeroSSL

### ISSUE THREAD

**Issue by RipClaw2971** [Froxlor/Froxlor#946]
Starting from August-1st 2021, acme.sh will release v3.0, in which the default CA will use ZeroSSL. To use letsencrypt you have to use either the option "--server letsencrypt" or set the default CA to letsencrypt with the command: acme.sh --set-default-ca  --server letsencrypt

https://github.com/acmesh-official/acme.sh/wiki/Change-default-CA-to-ZeroSSL

**Comment by Dessa** [comment]
this has more context as to the why: https://community.letsencrypt.org/t/the-acme-sh-will-change-default-ca-to-zerossl-on-august-1st-2021/144052/7

**Comment by d00p** [comment]
As froxlor explicitly sets the server option (for production and staging server option, see https://github.com/Froxlor/Froxlor/blob/master/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php#L297) I see no big impact on our side.

**Comment by d00p** [comment]
Froxlor keeps the "Let's Encrypt" endpoint as default but 73991e8 enables to switch to zerossl if wanted, thanks for the report
