### ISSUE TITLE
Configurable system groups for Froxlor system users using libnss-extrausers

### ISSUE THREAD

**Issue by kartoffelheinz** [Froxlor/Froxlor#953]
For many security-related configuration options in system services, it is desirable to have some concise matching mechanism to "catch" all Froxlor system users. This would normally be achived by selecting their distinctive group (e.g. in sshd_config via AllowGroups and the likes). Many other administrative tasks also profit from a selectors like this.

While in earlier versions when libnss-mysql was still supported this used to be a minor, straightforward addition to some sql queries, I do not see any similar way to configure this with libnss-extrausers. 

So my wish is to introduce an additional preference setting under the system group (simple text filed should suffice) to allow for (multiple, comma seperated) groups that will get automatically assigned as additional sysstem groups of all users when the extrausers file is being build. Note that I do not believe these groups should be extragroups at all, so Froxlor should assume they exist already in the system. If the admin enters non-existing groups, it is his burden to fix the resulting malfunction.

**Comment by d00p** [comment]
Should also be only be added to users where `ssh` is allowed and a shell executable is selected

**Comment by kartoffelheinz** [comment]
I disagree :)

Even if no logins are possible, there are still many other tasks that use group selectors for system users. I do not see why the additional groups should only be inserted if ssh usage is allowed for this user.

**Comment by d00p** [comment]
Well this is a crutial security related thing. Adding all users to specific groups. What would a use-case be that makes this necessary?

**Comment by kartoffelheinz** [comment]
Simple things, like killing all running Processes from Froxlor users only. Or giving Froxlor users access to specific sockets (e.g. redis).

**Comment by d00p** [comment]
The processes that froxlor-users run are only php-fpm or fcgid ...so you could either stop/restart php-fpm or just the webserver if you want to "kill" running processes of froxlor users.

Granting access to sockets...why not just do that user-specific and use the corresponding user-group that exists already?
Don't get me wrong, I can understand i'm just trying to understand why the generalization "all froxlor users" is useful

**Comment by kartoffelheinz** [comment]
That first assumption is only true if everything works as expected - granted, that is no always the case. There will be Zombie processes or processes split from parents. The "killing of processes" was just an example. There are other tasks like monitoring, cronjobs-allowance etc. that make the systemadmins life easier if he or she could distinguish between froxlor and non-froxlor users. There could also be other PHP or other FCGID processes on the same system, which were manually configured.

Granting or denying (via ACLs) access to files/sockets to many users is simply not possible (apart from granting world-access) if these users do not share a common group. So having all froxlor users in one group makes it possible to allow/deny specific files/sockets which would otherwise impossible to achieve. Hardening the server is so much easier this way.

Next up: Process-Limits. Most folks do not want to hard limit ALL users to e.g. 128 processes or 10min CPU time, but only froxlor users. That together with AllowGroups and Match Group (for froxlor user specific settings) in sshd_config are probably the most important use cases.

**Comment by d00p** [comment]
Problem with existing group is: froxlor would need to manage the group-members system-based which we always tried to avoid (hence libnss-mysql/extrausers). It would be a lot easier specifying a desired "froxlor-customers"-group name and then create that using libnss-extrausers and automatically add all froxlor customer users as members to it

**Comment by kartoffelheinz** [comment]
I understand what you're saying. What about implementing this in 2 steps / versions?
1. Simple Version: Checkbox "activate Froxlor Group for extrausers" somewhere in System-Settings with a short info that the this special group (e.g. "froxlor-customers") needs to be created manually as a system group. We can expect a system administrator who activates this to able to do a simple task like that.
2. Advanced Version: Implement this via a custom froxlor group via libnss-extrausers and make the name of the group customizable.

**Comment by d00p** [comment]
I think the best solution would be to make this a complete froxlor-handled thing via libnss-extrausers...no need to get the system involved :p

This way, you can just enter a groupname (check if exists of course) and then throw out permissions as you like :)
