### ISSUE TITLE
Unable to set session.save_path when using FPM

### ISSUE THREAD

**Issue by touchstone364** [Froxlor/Froxlor#954]
# Summary

When using FPM, the save_path is hardcoded to the temp directory of the user:
https://github.com/Froxlor/Froxlor/blob/master/lib/Froxlor/Cron/Http/Php/Fpm.php#L221

This is a very sensible default for session files, but for other session save handlers (like php-memcached) it is necessary to change the value to something like `session.save_path = localhost:11211`. This is for example used by Shopware. Unfortunately, because of the "php_admin_value", this is not possible. Also, it is not possible to override with other config (like FPM custom php.ini settings) because the php_admin_value takes precedence. 

I propose changing line 221 in Fpm.php to php_value, so it is possible to override this value in a php application:

`$fpm_config .= 'php_value[session.save_path] = ' ...`

While there are some security considerations, i do not think this change would cause any risk in the real world. As of now, an attacker could easily install his own session handler (because session.save_handler can be changed) and ignore the save_path. But as it is impossible to use any PHP application with memcached i would very much welcome this change. I tested it with Shopware 5.6.10 and after this change it works as expected.

Kind regards,
Touchstone

# System information
* Froxlor version: 0.10.26
* Web server: apache2
* DNS server: -
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian GNU/Linux 10 (buster)

# Steps to reproduce

1. Install Shopware
2. Change configuration to use memcached

# Expected behavior

1. Shopware now uses memcached

# Actual behavior

1. Fatal error

# Log files/log entries
php log:
<pre>
PHP Fatal error:  Uncaught Zend_Session_Exception: Zend_Session::start() - /srv/froxlor/webs/username/domainname.com/engine/Library/Zend/Session.php(Line:468): Error #2 session_start(): Failed to read session data: memcached (path: /srv/froxlor/tmp/username/) 
</pre>

Notice the temp path of the user in the error message, this should be "localhost:11211" but it could not be set by Shopware.

**Comment by d00p** [comment]
Ehm...you can just adjust the php-config in froxlor directly? Or create a a special config for only some domains that require this special save_path.

As admin -> PHP Configurations -> add new or edit existing -> adjust "php.ini settings"

```diff
- session.save_path = "{TMP_DIR}"
+ session.save_path = "whateveryouwant"
```

**Comment by d00p** [comment]
Got ya, yes, just saw that for fpm the ini setting isn't used and replaced with the `TMP_DIR` replacer. I thought it did it (after initially setting it to a 'safe' value in your mentioned line).

**Comment by d00p** [comment]
okay, two steps.

1) Patch `lib/Froxlor/Cron/Http/Php/Fpm.php`

```diff
diff --git a/lib/Froxlor/Cron/Http/Php/Fpm.php b/lib/Froxlor/Cron/Http/Php/Fpm.php
index c74cace8..c220232d 100644
--- a/lib/Froxlor/Cron/Http/Php/Fpm.php
+++ b/lib/Froxlor/Cron/Http/Php/Fpm.php
@@ -218,7 +218,7 @@ class Fpm
                                        $openbasedir .= $_phpappendopenbasedir;
                                }
                        }
-                       $fpm_config .= 'php_admin_value[session.save_path] = ' . \Froxlor\FileDir::makeCorrectDir(Settings::Get('phpfpm.tmpdir') . '/' . $this->domain['loginname'] . '/') . "\n";
+
                        $fpm_config .= 'php_admin_value[upload_tmp_dir] = ' . \Froxlor\FileDir::makeCorrectDir(Settings::Get('phpfpm.tmpdir') . '/' . $this->domain['loginname'] . '/') . "\n";
 
                        $admin = $this->getAdminData($this->domain['adminid']);
@@ -261,6 +261,11 @@ class Fpm
                                $fpm_config .= 'php_admin_value[sendmail_path] = /usr/sbin/sendmail -t -i -f ' . $this->domain['email'] . "\n";
                        }
 
+                       // check for session.save_path, whether it has been specified by the user, if not, set a default
+                       if (strpos($fpm_config, 'php_admin_value[session.save_path]') === false) {
+                               $fpm_config .= 'php_admin_value[session.save_path] = ' . $this->getTempDir() . "\n";
+                       }
+
                        // append custom phpfpm configuration
                        if (! empty($fpm_custom_config)) {
                                $fpm_config .= "\n; Custom Configuration\n";
```

2) You need to add `session.save_path` to the list of allowed php.ini directives in `Settings -> PHP-FPM -> Enter possible php_admin_values for php.ini. One entry per line` then you should be able to adjust the settings as described in my initial answer.

Let me know whether it works as intended then I'll push the changes to the repository for the next release

**Comment by touchstone364** [comment]
Thank you for your quick response.

I would really like to set this value in the application, so I would prefer php_value instead of php_admin_value. Maybe extend the check for already set values for both variants:

```
// check for session.save_path, whether it has been specified by the user, if not, set a default
if ((strpos($fpm_config, 'php_admin_value[session.save_path]') === false) &&
	(strpos($fpm_config, 'php_value[session.save_path]') === false)) {
        $fpm_config .= 'php_admin_value[session.save_path] = ' . $this->getTempDir() . "\n";
}
```

Then I can insert `session.save_path` in  PHP-FPM -> Enter possible **php_values** for php.ini, use a PHP configuration with a dummy value, and let Shopware set the real value. I tested it and it works for me. For other users there should not be any change in the generated FPM config.
