### ISSUE TITLE
AcmeSh.php syntax error

### ISSUE THREAD

**Issue by monster010** [Froxlor/Froxlor#957]
Since I receive e-mails when a cronjob fails, I noticed that there is a syntax error in AcmeSh.php, for more information see log files.

**System information**
* Froxlor version: 0.10.27
* Web server: apache2
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Debian 10

**Logfiles**
`PHP Parse error:  syntax error, unexpected end of file in /var/www/froxlor/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php on line 619`

**Comment by d00p** [comment]
Weird the lining tests did not mention anything:
`     [lint] No syntax errors detected in /home/runner/work/Froxlor/Froxlor/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php`

Need to check, thanks for the hint

**Comment by d00p** [comment]
Cannot reproduce this on three updated machines, do you have anymore information? Updated or fresh install? Debian package or tar.gz? or git clone? issue or renew? Did you compare you AcmeSh.php to the 0.10.27 tag from here https://github.com/Froxlor/Froxlor/blob/0.10.27/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php?

**Comment by monster010** [comment]
Is an updated tar.gz installation, renew the certificate and Absolutely the same.

I found the error: PHP version 7.1 was selected as the standard, there the error exists. The bug has been fixed in PHP 8.0.

**Comment by d00p** [comment]
ah, too simple. intendation of HEREDOC, autoformat must've destroyed it

**Comment by agentur2c** [comment]
same error occurs with php7.2 (deb.sury.org) on Debian 9.13 (Stretch)

**Comment by d00p** [comment]
> same error occurs with php7.2 (deb.sury.org) on Debian 9.13 (Stretch)

With the current commit?? Please only test with current master

**Comment by agentur2c** [comment]
After normal tar.gz update from 0.10.25 to 0.10.27 and php7.2 - with 7.3 no problems

**Comment by monster010** [comment]
Works for me with PHP version 7.1, 7.3, 7.4 and 8.0.
