### ISSUE TITLE
Wrong / no logo if no database connection

### ISSUE THREAD

**Issue by agentur2c** [Froxlor/Froxlor#958]
The new custom logo solution has design failures.
It is no longer possible to use different themes with different logos because the image will be saved and if no database connection exists the wrong logo (fallback) is shown.

Possible solutions:

- Only use filename from database with theme directory and without upload functionality (ugly solution ;-) )
- Use logo_custom.png and logo_custom_login.png from the theme directory, If not exists use logos from the db or fallback to the distributed froxlor logo.

**Comment by d00p** [comment]
My solution (for now):

Have two new settings, 1. **override theme-logo** and 2. **overide custom-theme-logo**

Default will be the theme's defined logo.png and if exist, the logo_custom* ones.

When uploading a logo, you can then check, whether this image will overwrite the theme's logo and whether it should also override the custom ones.
