### ISSUE TITLE
[Feature Request]: Option to disable creation of default subdomain

### ISSUE THREAD

**Issue by tinyoverflow** [Froxlor/Froxlor#960]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm creating a new customer that I have to manually disable the creation of the default subdomain by hand, as it might be forgotten.

**Describe the solution you'd like**
I'd like an option in the system settings to disable that checkbox by default, just like there is an option to select a default domain alias.

**Describe alternatives you've considered**
Not having it, but it's quite frustrating.

**Comment by d00p** [comment]
There are many many many settings that could have a setting for a system-default...but i feel you on this one :)

**Comment by tinyoverflow** [comment]
Haha, thanks!
I tried to understand the code base, especially the PR which adds the option for the preselected domain alias to be able to PR this one. While I cannot promise anything, I'll try to find some time to get into it and to create a PR :)
