### ISSUE TITLE
Use GitHub Pages for documentation

### ISSUE THREAD

**Issue by tinyoverflow** [Froxlor/Froxlor#964]
Hello,

once up and running, Froxlor is an awesome piece of software, but unfortunately it has a flat learning curve. This combined with the current wiki, which doesn't provide many informations regarding the configuration, can make it very hard for Froxlor newbies to get it up and running.

I would like to suggest and to contribute to a proper Froxlor documentation. Unfortunately, the GitHub Wiki itself is not very dynamic nor well suited for OSS projects with many collaborators which don't have the collaborator role.

Therefore using GitHub pages, which is backed by Jekyll, would be an appropiate alternative in my opinion. This also has some advantages:
- The documentation is properly versioned
- Anyone can contribute to it by using PRs

I'd like to hear your opinion about that.

**Comment by d00p** [comment]
I'm with you on this one. To be honest regarding GitHub pages, I don't really want to dive into Jekyll. Also there is a user and admin documentation on my to-do, just not enough time as always. Help would be appreciated a lot

**Comment by tinyoverflow** [comment]
Understandable. While Jekyll is pretty easy to use, in my opinion, it takes some time to get into it. If wanted, I could try to find some spare time to setup a Jekyll page with some basic pages, which can then be extended by all collaborators from time to time, and then do a PR.

**Comment by d00p** [comment]
Sounds very nice. I think with a good base layout I can add content here and there more easily

**Comment by d00p** [comment]
Setup repo for this, see https://github.com/Froxlor/Froxlor.github.io

**Comment by envoyr** [comment]
See https://github.com/Froxlor/Froxlor.github.io/pull/1

**Comment by d00p** [comment]
Completely moved to https://github.com/Froxlor/Documentation
