### ISSUE TITLE
Acme.sh le_domain_dnscheck with zero's in ipv6 address

### ISSUE THREAD

**Issue by genofire** [Froxlor/Froxlor#965]
**Describe the bug**
`Skipping Let's Encrypt generation for domain due to no system known IP address via DNS check`
for Domains which are binded on a IPv6-Adress with zero's in Address

**System information**
* Froxlor version: 156846a845cab8af35c09c14397c5c63f9d3ec06
* Web server: nginx
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: debian buster

**To Reproduce**
1. Go to IP and Ports
2. Enter a IP with `:0000:` inside
3. Use it on a single domain on this IP-Adress

**Expected behavior**
It works ;) - Check run as okay

**Additional context**
https://github.com/Froxlor/Froxlor/blob/156846a845cab8af35c09c14397c5c63f9d3ec06/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php#L290-L294

Use more complex validation then: ` count(array_intersect($our_ips, $domain_ips))`- it will not regonise IPv6-Addresses with zeros

**Comment by d00p** [comment]
This indeed goes a bit deeper :) I am now compressing all ipv6 addresses froxlor-wide so comparisons are no problem and everything is in an equal format
