### ISSUE TITLE
Caddyserver support

### ISSUE THREAD

**Issue by genofire** [Froxlor/Froxlor#966]
It would be nice to have Caddy-Server support, it handels:
- ACME
- Proxy
- FCGI for php-fpm

It has an internal API and config-file management.
Maybe a live editing per API is cool.

**Comment by d00p** [comment]
Well it doesn't matter as it handles acme etc., as we always have to check for all cases (in this case, the other supported webservers). So basically it comes down to supporting a new Webserver.

**Comment by genofire** [comment]
The feature list I just announce, because:
- it would be nice to use the internal service instatt of acme.sh as example
- php should be used on the fpm way

**Comment by d00p** [comment]
Acme service would be caddy only, and you can do fpm with froxlor no problem
