### ISSUE TITLE
Rewrite vHost to "Disabled Account"-Page for disabled accounts

### ISSUE THREAD

**Issue by tinyoverflow** [Froxlor/Froxlor#967]
**Is your feature request related to a problem? Please describe.**
When I deactivate a customer account, the website just redirects to the Froxlor login page and will generate a SSL warning in the browser in most cases. This won't explain anything to the customer itself.

**Describe the solution you'd like**
I'd like to be able to create a file in the admin area (optionally with placeholders), which will be shown when a webspace is deactivated. This could be done by rewriting all incoming requests on the affected vhosts to that specific HTML file.

In the best case, it would also be possible to just disable single domains (specific vhosts). I think this might be related to #925.

**Describe alternatives you've considered**
I'm not exactly sure about what deactivating a user does in particular, but it could be possible to setup a default vhost which doesn't care about domains and just set that to a more generalized "here's nothing"-page. Though I couldn't test this one yet. Also, this wouldn't solve the SSL warning issue.

**Additional context**
What _exactly_ does Froxlor do when an admin deactivates a customer?

**Comment by d00p** [comment]
1) Settings -> Webserver settings -> Docroot for deactivated users
When a user is deactivated this path is used as his docroot. Leave empty for not creating a vHost at all.

2) What exactly does Froxlor do when an admin deactivates a customer?

- no access to froxlor account
- no access to email accounts
- no access to ftp
- domains do not point to the customer-docroot (see _1)_ too)
- no access to mysql databases
- no access via API

**Comment by tinyoverflow** [comment]
I never felt that stupid before. Thank you really much for clarifying all of this :)
