### ISSUE TITLE
[Feature Request] login with OTP Token / Google Authenticator and others

### ISSUE THREAD

**Issue by mr-manuel** [Froxlor/Froxlor#972]
**Is your feature request related to a problem? Please describe.**
Nowadays nearly all logins are also protected by a MFA solutions. I would love to see a MFA login option also in Froxlor.

A simple solution would be a E-Mail OTP (One Time Password), Google Authenticator or others (see [Google Authenticator PHP class](https://github.com/PHPGangsta/GoogleAuthenticator))

**Describe the solution you'd like**
Request additionally to username and password a OTP token.

**Additional context**
With the PHP class it should not be a big effort to implement this. What do you think about this idea?

**Comment by d00p** [comment]
Already implemented. Login to your account -> options -> 2fa options

**Comment by mr-manuel** [comment]
Sorry and thanks!
