### ISSUE TITLE
How to Install in Centos 8.

### ISSUE THREAD

**Issue by Wotan6891** [Froxlor/Froxlor#975]
Hello, congratulations on your management in this software.

1. Would you like to know how to install Centos 8?

2. Do I have to keep my computer on 24 hours a day?

I have a 4GB memory and 2000 GB of storage.

I want to host my web pages. I am not interested in offering the hosting service.

I work with wordpress.

Greetings

Thanks

**Comment by d00p** [comment]
Please use the forum for questions like that.
