### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by LogoJK** [Froxlor/Froxlor#977]
Idk if this is alwready a thing but i would like that customers can create Domains by them selv.

You can der a Nummer of Domains a customer can have when creating bis Account (Also an unlimited option)

Best regards

**Comment by d00p** [comment]
There are a lot of settings to be set for a main-domain which should not be of any customers concern (and the wrong changes may lead to the webserver not working for all customers).

**Comment by LogoJK** [comment]
Well male customer only edit the Main things and the other things only for admins

**Comment by d00p** [comment]
duplicate of #729
