### ISSUE TITLE
Froxlor and Google Workplace/Office 365

### ISSUE THREAD

**Issue by realrellek** [Froxlor/Froxlor#978]
Hi,

I'd like to propose a setting so that Froxlor can be set up to work with Google Workplace (former G Suite).

Like right now, Froxlor is sort of meant to manage mails on its own, but when Google is involved (or Office 365 for that matter), you would not want that because some huge cloud does the email.

However. Neither do I know how I would set this up (i guess it does not exist yet) nor would it help to use a Google SMTP to handle the server's mails (such as notifications from WordPress). This is due to Google's (and I guess also Microsoft's) rate limitation for mails via SMTP. Which would render it unusable if you have, say, a newsletter in a forum or something.

So the easy solution would be to disable local lookup in postfix config to ensure every mail goes through the internet (hence the email provider). Because default behaviour is to ask the local server and if domain matches, such email would not leave the server.

So what I did (if memory serves) to skip all POP3/IMAP configuration and adjust a little bit in /etc/postfix/main.cf

`inet_interfaces = loopback-only`
because nobody needs to connect to the server when it would not accept mails anyway

and i removed this line (well, in fact, I commented it)

`virtual_mailbox_domains = mysql:/etc/postfix/mysql-virtual_mailbox_domains.cf`
Making virtual mailboxes unknown to postfix makes it look up every domain

So when WordPress installed on example.com sends a mail now to info@example.com, it does not try to deliver it locally but goes the long route, asking the DNS, DNS says Google is in charge, gives Google the mail, Google delivers the mail.

So, and what I want to propose is a switch that I can flip that would make the change for me for the configuration.

(Yes I am aware that that won't sign my mails and I am aware that I have to allow my IP in SPF because otherwise it'll get spammed)

I have no idea if that would be "best practise" to achieve it, but it does work for me :)

**Comment by d00p** [comment]
Why don't you just disable mail for the domains you want to use external mail services for?

**Comment by realrellek** [comment]
Excellent question. Would that do exactly what I need in this case? Was a little afraid to be unable to send mails at all then with PHP mail(). 🤔

**Comment by d00p** [comment]
You can still call mail() or send mail from within code. It just disables that domain for postfix
