### ISSUE TITLE
PowerDNS Native Mode: Do not include allow-axfr-ips in config

### ISSUE THREAD

**Issue by Af0x** [Froxlor/Froxlor#990]
Hello,

when the PowerDNS operation mode is set to "Native", the generated config still contains the `allow-axfr-ips` setting.

Regards,

Af0x

**Comment by d00p** [comment]
Question is, is it just not necessary or is it bad? :)

**Comment by Af0x** [comment]
If Master is set and you want Native Mode then it´s unwanted I guess.
