### ISSUE TITLE
PowerDNS: Do not remove the domain completely (keep ID)

### ISSUE THREAD

**Issue by Af0x** [Froxlor/Froxlor#993]
Hello,

everytime the master-cron is running the id of a domain in the pdns-database is changed.

I´m not completely sure if this is a bug but if possible a domain should always keep its id.

Regards,

Af0x

**Comment by Af0x** [comment]
the reason why this is pretty important is for example the use of DNSSEC with PowerDNS. The generated key is tied to the id and if that id changes all DNSSEC functionality is broken (and probably more).

**Comment by d00p** [comment]
Do you have the possibility to test the following patch?

[PowerDNS.php.patch.zip](https://github.com/Froxlor/Froxlor/files/7580321/PowerDNS.php.patch.zip)

**Comment by Af0x** [comment]
Unfortunately I moved to managing PowerDNS manually.

**Comment by d00p** [comment]
This was over 2 years ago, never received feedback as you said you now manage this manually and no other issues were reported. So in order to concentrate on current 2.0.x versions this was closed
