### ISSUE TITLE
APCu Info page throws division by zero when there is no hits yet

### ISSUE THREAD

**Issue by heaven73** [Froxlor/Froxlor#995]
**Describe the bug**
After fresh installing froxlor the apcuinfo page gave error 500 
in the apache log appears: 

AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught DivisionByZeroError: Division by zero in /var/www/html/froxlor/admin_apcuinfo.php:87\nStack trace:\n#0 {main}\n  thrown in /var/www/html/froxlor/
admin_apcuinfo.php on line 87',

The line 87 = 
$hits = $cache['num_hits'] . @sprintf(" (%.1f%%)", $cache['num_hits'] * 100 / ($cache['num_hits'] + $cache['num_misses']));

so i guess the num_hits variable is still 0 because having a fresh install it had no hits yet.
i never coded in php but i suppose this line should have a verification first if num_hits = 0 and if its 0 hits should be assigned 0 avoiding the division by zero

Hope i gave enough details.

**System information**
* Froxlor version:  0.10.29.1 (DB: 202109040)
* Web server: apache2
* DNS server: none
* POP/IMAP server: none
* SMTP server: none
* FTP server: non
* OS/Version: debian 10
* PHP Version v8.0.12

**To Reproduce**
1. install apt-get install php8.0-apcu
2. in the froxlor menu after the fresh installation click the apcu-info
3. Error 500 appears

**Expected behavior**
see above

**Logfiles**
If applicable, add log-entries to help explain your problem.
AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught DivisionByZeroError: Division by zero in /var/www/html/froxlor/admin_apcuinfo.php:87\nStack trace:\n#0 {main}\n  thrown in /var/www/html/froxlor/
admin_apcuinfo.php on line 87'

**Comment by d00p** [comment]
Can you check whether the following patch resolves the issue?

```diff
diff --git a/admin_apcuinfo.php b/admin_apcuinfo.php
index d7854d65..b616b0a5 100644
--- a/admin_apcuinfo.php
+++ b/admin_apcuinfo.php
@@ -67,6 +67,9 @@ if ($page == 'showinfo') {
        $uptime_duration = duration($cache['start_time']);
        $size_vars = bsize($cache['mem_size']);
 
+       $num_hits_and_misses = $cache['num_hits'] + $cache['num_misses'];
+       $num_hits_and_misses = 0 >= $num_hits_and_misses ? 1 : $num_hits_and_misses;
+
        // check for possible empty values that are used in the templates
        if (! isset($cache['file_upload_progress'])) {
                $cache['file_upload_progress'] = $lng['logger']['unknown'];
@@ -84,8 +87,8 @@ if ($page == 'showinfo') {
 
        $freemem = bsize($mem_avail) . sprintf(" (%.1f%%)", $mem_avail * 100 / $mem_size);
        $usedmem = bsize($mem_used) . sprintf(" (%.1f%%)", $mem_used * 100 / $mem_size);
-       $hits = $cache['num_hits'] . @sprintf(" (%.1f%%)", $cache['num_hits'] * 100 / ($cache['num_hits'] + $cache['num_misses']));
-       $misses = $cache['num_misses'] . @sprintf(" (%.1f%%)", $cache['num_misses'] * 100 / ($cache['num_hits'] + $cache['num_misses']));
+       $hits = $cache['num_hits'] . @sprintf(" (%.1f%%)", $cache['num_hits'] * 100 / $num_hits_and_misses);
+       $misses = $cache['num_misses'] . @sprintf(" (%.1f%%)", $cache['num_misses'] * 100 / $num_hits_and_misses);
 
        // Fragmentation: (freeseg - 1) / total_seg
        $nseg = $freeseg = $fragsize = $freetotal = 0;
```

**Comment by heaven73** [comment]
works like a charm.
