### ISSUE TITLE
Add a keyserver for froxlor installation on ubuntu!

### ISSUE THREAD

**Issue by lukasdoerr** [Froxlor/Froxlor#996]
When you want to install Froxlor, the tutorial only tells you something about the key but there has to be the command to receive the key to complete the installation.

**Describe the solution you'd like**
Add the command

apt-key adv --keyserver pgp.mit.edu --recv-key FD88018B6F2D5390D051343FF6B4A8704F9E9BBC

I tried to follow this tutorial, but without my command before you can't get the repository:
https://github.com/Froxlor/Froxlor/wiki/Install-froxlor-on-ubuntu

**Comment by d00p** [comment]
We use apt-key add for that, it's the second command there:

`wget -O - https://deb.froxlor.org/froxlor.gpg | apt-key add -`
