### ISSUE TITLE
The default subdomain is deleted when the user is updated via the api

### ISSUE THREAD

**Issue by envoyr** [Froxlor/Froxlor#998]
**Describe the bug**
When I 'deactivated' the user via the API I always have to explicitly submit the value of 'createstdsubdomain', otherwise the default subdomain is deleted.

This is also the case when Settings > Account settings > "Preselected value for "Create standard subdomain" when creating a customer" is set to Yes or No.

**System information**
* Froxlor version: 0.10.30-1 (DB: 202109040)
* Web server: apache2
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Ubuntu 20.04 LTS

**To Reproduce**
A API request with "Customers.update", "loginname" = "example", "deactivated" = "1" will disable the  "standardsubdomain"

This will also be deleted if only the 'custom_notes' is customized via the API.

**Expected behavior**
"createstdsubdomain" has the value as it was set before the "Customers.update" request, e.g. by modification in the customer interface

**Logfiles**
None

**Additional context**
None

**Comment by d00p** [comment]
I think the issue here is that `createstdsubdomain` is not a _value_ field from the database-table but rather a one-time-function indicator, whether to create a standard-subdomain or not.

If I'm not mistaken, the default value must be changed to whether the customer has a std-subdomain (db-field `standardsubdomain != 0`) or not.

Can you verify that the following patch resolves this issue?

```diff
diff --git a/lib/Froxlor/Api/Commands/Customers.php b/lib/Froxlor/Api/Commands/Customers.php
index 05749ca1..90bc4dfd 100644
--- a/lib/Froxlor/Api/Commands/Customers.php
+++ b/lib/Froxlor/Api/Commands/Customers.php
@@ -915,7 +915,7 @@ class Customers extends \Froxlor\Api\ApiCommand implements \Froxlor\Api\Resource
         * @param bool $mysqls_ul
         *              optional, whether customer should have unlimited mysql-databases, default 0 (false)
         * @param bool $createstdsubdomain
-        *              optional, whether to create a standard-subdomain ([loginname].froxlor-hostname.tld), default 0 (false)
+        *              optional, whether to create a standard-subdomain ([loginname].froxlor-hostname.tld), default 1 (if customer has std-subdomain) else 0 (false)
         * @param bool $phpenabled
         *              optional, whether to allow usage of PHP, default 0 (false)
         * @param array $allowed_phpconfigs
@@ -979,7 +979,7 @@ class Customers extends \Froxlor\Api\ApiCommand implements \Froxlor\Api\Resource
                        $email_pop3 = $this->getParam('email_pop3', true, $result['pop3']);
                        $ftps = $this->getUlParam('ftps', 'ftps_ul', true, $result['ftps']);
                        $mysqls = $this->getUlParam('mysqls', 'mysqls_ul', true, $result['mysqls']);
-                       $createstdsubdomain = $this->getBoolParam('createstdsubdomain', true, 0);
+                       $createstdsubdomain = $this->getBoolParam('createstdsubdomain', true, ($result['standardsubdomain'] != 0 ? 1 : 0));
                        $password = $this->getParam('new_customer_password', true, '');
                        $phpenabled = $this->getBoolParam('phpenabled', true, $result['phpenabled']);
                        $allowed_phpconfigs = $this->getParam('allowed_phpconfigs', true, json_decode($result['allowed_phpconfigs'], true));
```

**Comment by envoyr** [comment]
Have just tested it and it works like a charm 😊
